const CONTENT_DATA = {
  vocabulary: {
    salam: [
      { ru: 'Привет', id: 'Halo', note: 'informal' },
      { ru: 'Здравствуйте', id: 'Selamat siang', note: 'formal' },
      { ru: 'Доброе утро', id: 'Selamat pagi' },
      { ru: 'Добрый день', id: 'Selamat siang' },
      { ru: 'Добрый вечер', id: 'Selamat sore' },
      { ru: 'Спокойной ночи', id: 'Selamat malam' },
      { ru: 'До свидания', id: 'Sampai jumpa' },
      { ru: 'Пока', id: 'Dadah', note: 'informal' },
      { ru: 'До завтра', id: 'Sampai besok' },
      { ru: 'Добро пожаловать', id: 'Selamat datang' },
      { ru: 'Приятно познакомиться', id: 'Senang berkenalan' },
      { ru: 'Как дела?', id: 'Apa kabar?' },
      { ru: 'Хорошо', id: 'Baik' },
      { ru: 'Плохо', id: 'Buruk' },
      { ru: 'Спасибо', id: 'Terima kasih' },
      { ru: 'Пожалуйста', id: 'Tolong/Sama-sama' },
      { ru: 'Извините', id: 'Maaf' },
      { ru: 'Простите', id: 'Permisi' },
      { ru: 'Да', id: 'Ya' },
      { ru: 'Нет', id: 'Tidak' },
      { ru: 'Меня зовут...', id: 'Nama saya...' },
      { ru: 'Как вас зовут?', id: 'Siapa nama Anda?' },
      { ru: 'Очень приятно', id: 'Senang bertemu Anda' },
      { ru: 'Давно не виделись', id: 'Lama tidak bertemu' },
      { ru: 'Удачи!', id: 'Semoga beruntung!' },
      { ru: 'Всего хорошего', id: 'Semoga yang terbaik' },
      { ru: 'Берегите себя', id: 'Jaga diri' },
      { ru: 'С праздником!', id: 'Selamat hari raya!' },
      { ru: 'С днём рождения!', id: 'Selamat ulang tahun!' },
      { ru: 'С Новым годом!', id: 'Selamat tahun baru!' }
    ],
    angka: [
      { ru: 'ноль', id: 'Nol' },
      { ru: 'один', id: 'Satu' },
      { ru: 'два', id: 'Dua' },
      { ru: 'три', id: 'Tiga' },
      { ru: 'четыре', id: 'Empat' },
      { ru: 'пять', id: 'Lima' },
      { ru: 'шесть', id: 'Enam' },
      { ru: 'семь', id: 'Tujuh' },
      { ru: 'восемь', id: 'Delapan' },
      { ru: 'девять', id: 'Sembilan' },
      { ru: 'десять', id: 'Sepuluh' },
      { ru: 'одиннадцать', id: 'Sebelas' },
      { ru: 'двенадцать', id: 'Dua belas' },
      { ru: 'тринадцать', id: 'Tiga belas' },
      { ru: 'двадцать', id: 'Dua puluh' },
      { ru: 'тридцать', id: 'Tiga puluh' },
      { ru: 'сорок', id: 'Empat puluh' },
      { ru: 'пятьдесят', id: 'Lima puluh' },
      { ru: 'сто', id: 'Seratus' },
      { ru: 'тысяча', id: 'Seribu' },
      { ru: 'первый', id: 'Pertama' },
      { ru: 'второй', id: 'Kedua' },
      { ru: 'третий', id: 'Ketiga' },
      { ru: 'десятый', id: 'Kesepuluh' },
      { ru: 'последний', id: 'Terakhir' },
      { ru: 'четный', id: 'Genap' },
      { ru: 'нечётный', id: 'Ganjil' },
      { ru: 'число', id: 'Angka/Bilangan' }
    ],
    hari: [
      { ru: 'понедельник', id: 'Senin' },
      { ru: 'вторник', id: 'Selasa' },
      { ru: 'среда', id: 'Rabu' },
      { ru: 'четверг', id: 'Kamis' },
      { ru: 'пятница', id: 'Jumat' },
      { ru: 'суббота', id: 'Sabtu' },
      { ru: 'воскресенье', id: 'Minggu' },
      { ru: 'будний день', id: 'Hari kerja' },
      { ru: 'выходной', id: 'Hari libur' },
      { ru: 'сегодня', id: 'Hari ini' },
      { ru: 'вчера', id: 'Kemarin' },
      { ru: 'завтра', id: 'Besok' },
      { ru: 'неделя', id: 'Minggu (satuan waktu)' },
      { ru: 'месяц', id: 'Bulan' },
      { ru: 'год', id: 'Tahun' },
      { ru: 'январь', id: 'Januari' },
      { ru: 'февраль', id: 'Februari' },
      { ru: 'март', id: 'Maret' },
      { ru: 'апрель', id: 'April' },
      { ru: 'май', id: 'Mei' },
      { ru: 'июнь', id: 'Juni' },
      { ru: 'июль', id: 'Juli' },
      { ru: 'август', id: 'Agustus' },
      { ru: 'сентябрь', id: 'September' },
      { ru: 'октябрь', id: 'Oktober' },
      { ru: 'ноябрь', id: 'November' },
      { ru: 'декабрь', id: 'Desember' },
      { ru: 'сезон', id: 'Musim' },
      { ru: 'весна', id: 'Musim semi' },
      { ru: 'лето', id: 'Musim panas' },
      { ru: 'осень', id: 'Musim gugur' },
      { ru: 'зима', id: 'Musim dingin' }
    ],
    warna: [
      { ru: 'красный', id: 'Merah' },
      { ru: 'синий', id: 'Biru' },
      { ru: 'зелёный', id: 'Hijau' },
      { ru: 'жёлтый', id: 'Kuning' },
      { ru: 'оранжевый', id: 'Oranye' },
      { ru: 'фиолетовый', id: 'Ungu' },
      { ru: 'розовый', id: 'Merah muda' },
      { ru: 'чёрный', id: 'Hitam' },
      { ru: 'белый', id: 'Putih' },
      { ru: 'серый', id: 'Abu-abu' },
      { ru: 'коричневый', id: 'Cokelat' },
      { ru: 'золотой', id: 'Emas' },
      { ru: 'серебряный', id: 'Perak' },
      { ru: 'бежевый', id: 'Krem' },
      { ru: 'голубой', id: 'Biru muda' }
    ],
    ganti: [
      { ru: 'я', id: 'Saya', note: 'nominatif' },
      { ru: 'ты', id: 'Kamu', note: 'nominatif informal' },
      { ru: 'он', id: 'Dia (laki-laki)', note: 'maskulin' },
      { ru: 'она', id: 'Dia (perempuan)', note: 'feminin' },
      { ru: 'оно', id: 'Dia (netral)', note: 'netral' },
      { ru: 'мы', id: 'Kami/Kita' },
      { ru: 'вы', id: 'Anda/Kalian', note: 'formal' },
      { ru: 'они', id: 'Mereka' },
      { ru: 'мой', id: 'Saya (milik)', note: 'maskulin' },
      { ru: 'моя', id: 'Saya (milik)', note: 'feminin' },
      { ru: 'твой', id: 'Kamu (milik)', note: 'maskulin' },
      { ru: 'его', id: 'Dia (milik laki-laki)' },
      { ru: 'её', id: 'Dia (milik perempuan)' },
      { ru: 'наш', id: 'Kita (milik)', note: 'maskulin' },
      { ru: 'ваш', id: 'Anda (milik)', note: 'maskulin' },
      { ru: 'их', id: 'Mereka (milik)' },
      { ru: 'этот', id: 'Ini', note: 'maskulin' },
      { ru: 'эта', id: 'Ini', note: 'feminin' },
      { ru: 'тот', id: 'Itu', note: 'maskulin' },
      { ru: 'кто', id: 'Siapa' },
      { ru: 'что', id: 'Apa' },
      { ru: 'где', id: 'Di mana' },
      { ru: 'когда', id: 'Kapan' },
      { ru: 'почему', id: 'Mengapa' },
      { ru: 'как', id: 'Bagaimana' },
      { ru: 'сколько', id: 'Berapa' }
    ],
    keluarga: [
      { ru: 'мать', id: 'Ibu', note: 'feminin' },
      { ru: 'отец', id: 'Ayah', note: 'maskulin' },
      { ru: 'бабушка', id: 'Nenek', note: 'feminin' },
      { ru: 'дедушка', id: 'Kakek', note: 'maskulin' },
      { ru: 'сестра', id: 'Saudara perempuan', note: 'feminin' },
      { ru: 'брат', id: 'Saudara laki-laki', note: 'maskulin' },
      { ru: 'дочь', id: 'Anak perempuan', note: 'feminin' },
      { ru: 'сын', id: 'Anak laki-laki', note: 'maskulin' },
      { ru: 'тётя', id: 'Bibi', note: 'feminin' },
      { ru: 'дядя', id: 'Paman', note: 'maskulin' },
      { ru: 'двоюродная сестра', id: 'Sepupu (wanita)', note: 'feminin' },
      { ru: 'двоюродный брат', id: 'Sepupu (pria)', note: 'maskulin' },
      { ru: 'внучка', id: 'Cucu perempuan', note: 'feminin' },
      { ru: 'внук', id: 'Cucu laki-laki', note: 'maskulin' },
      { ru: 'семья', id: 'Keluarga', note: 'feminin' },
      { ru: 'жена', id: 'Istri', note: 'feminin' },
      { ru: 'муж', id: 'Suami', note: 'maskulin' },
      { ru: 'родители', id: 'Orang tua' },
      { ru: 'дети', id: 'Anak-anak' },
      { ru: 'племянница', id: 'Keponakan (wanita)', note: 'feminin' },
      { ru: 'племянник', id: 'Keponakan (pria)', note: 'maskulin' },
      { ru: 'свекровь', id: 'Mertua (wanita)', note: 'feminin' },
      { ru: 'свёкор', id: 'Mertua (pria)', note: 'maskulin' },
      { ru: 'зять', id: 'Menantu laki-laki', note: 'maskulin' },
      { ru: 'невестка', id: 'Menantu perempuan', note: 'feminin' }
    ],
    makanan: [
      { ru: 'завтрак', id: 'Sarapan' },
      { ru: 'обед', id: 'Makan siang' },
      { ru: 'ужин', id: 'Makan malam' },
      { ru: 'хлеб', id: 'Roti', note: 'maskulin' },
      { ru: 'масло', id: 'Mentega', note: 'netral' },
      { ru: 'сыр', id: 'Keju', note: 'maskulin' },
      { ru: 'колбаса', id: 'Sosis', note: 'feminin' },
      { ru: 'яйцо', id: 'Telur', note: 'netral' },
      { ru: 'рис', id: 'Nasi', note: 'maskulin' },
      { ru: 'картофель', id: 'Kentang', note: 'maskulin' },
      { ru: 'суп', id: 'Sup', note: 'maskulin' },
      { ru: 'салат', id: 'Salad', note: 'maskulin' },
      { ru: 'мясо', id: 'Daging', note: 'netral' },
      { ru: 'рыба', id: 'Ikan', note: 'feminin' },
      { ru: 'молоко', id: 'Susu', note: 'netral' },
      { ru: 'кофе', id: 'Kopi', note: 'maskulin' },
      { ru: 'чай', id: 'Teh', note: 'maskulin' },
      { ru: 'сок', id: 'Jus', note: 'maskulin' },
      { ru: 'вода', id: 'Air', note: 'feminin' },
      { ru: 'пиво', id: 'Bir', note: 'netral' },
      { ru: 'вино', id: 'Anggur', note: 'netral' },
      { ru: 'сахар', id: 'Gula', note: 'maskulin' },
      { ru: 'соль', id: 'Garam', note: 'feminin' },
      { ru: 'перец', id: 'Merica', note: 'maskulin' },
      { ru: 'масло растительное', id: 'Minyak goreng', note: 'netral' },
      { ru: 'мука', id: 'Tepung', note: 'feminin' },
      { ru: 'торт', id: 'Kue tart', note: 'maskulin' },
      { ru: 'мороженое', id: 'Es krim', note: 'netral' },
      { ru: 'шоколад', id: 'Cokelat', note: 'maskulin' },
      { ru: 'конфеты', id: 'Permen' },
      { ru: 'пицца', id: 'Pizza', note: 'feminin' },
      { ru: 'сэндвич', id: 'Roti lapis', note: 'maskulin' },
      { ru: 'лапша', id: 'Mie', note: 'feminin' },
      { ru: 'бутерброд', id: 'Roti isi', note: 'maskulin' },
      { ru: 'йогурт', id: 'Yogurt', note: 'maskulin' }
    ],
    tempat: [
      { ru: 'школа', id: 'Sekolah', note: 'feminin' },
      { ru: 'университет', id: 'Universitas', note: 'maskulin' },
      { ru: 'больница', id: 'Rumah sakit', note: 'feminin' },
      { ru: 'церковь', id: 'Gereja', note: 'feminin' },
      { ru: 'музей', id: 'Museum', note: 'maskulin' },
      { ru: 'отель', id: 'Hotel', note: 'maskulin' },
      { ru: 'ресторан', id: 'Restoran', note: 'maskulin' },
      { ru: 'почта', id: 'Kantor pos', note: 'feminin' },
      { ru: 'банк', id: 'Bank', note: 'maskulin' },
      { ru: 'супермаркет', id: 'Supermarket', note: 'maskulin' },
      { ru: 'библиотека', id: 'Perpustakaan', note: 'feminin' },
      { ru: 'кинотеатр', id: 'Bioskop', note: 'maskulin' },
      { ru: 'театр', id: 'Teater', note: 'maskulin' },
      { ru: 'опера', id: 'Opera', note: 'feminin' },
      { ru: 'парк', id: 'Taman', note: 'maskulin' },
      { ru: 'вокзал', id: 'Stasiun kereta', note: 'maskulin' },
      { ru: 'аэропорт', id: 'Bandara', note: 'maskulin' },
      { ru: 'аптека', id: 'Apotek', note: 'feminin' },
      { ru: 'кладбище', id: 'Kuburan', note: 'netral' },
      { ru: 'завод', id: 'Pabrik', note: 'maskulin' },
      { ru: 'ратуша', id: 'Balai kota', note: 'netral' },
      { ru: 'полицейский участок', id: 'Kantor polisi', note: 'maskulin' },
      { ru: 'пожарная часть', id: 'Kantor pemadam', note: 'feminin' },
      { ru: 'рынок', id: 'Pasar', note: 'maskulin' },
      { ru: 'торговый центр', id: 'Pusat perbelanjaan', note: 'maskulin' },
      { ru: 'стадион', id: 'Stadion', note: 'maskulin' },
      { ru: 'зоопарк', id: 'Kebun binatang', note: 'maskulin' },
      { ru: 'аквариум', id: 'Akuarium', note: 'maskulin' },
      { ru: 'кафе', id: 'Kafe', note: 'netral' },
      { ru: 'бар', id: 'Bar', note: 'maskulin' },
      { ru: 'спортзал', id: 'Gym', note: 'maskulin' }
    ],
    profesi: [
      { ru: 'врач', id: 'Dokter', note: 'maskulin' },
      { ru: 'учитель', id: 'Guru', note: 'maskulin' },
      { ru: 'инженер', id: 'Insinyur', note: 'maskulin' },
      { ru: 'адвокат', id: 'Pengacara', note: 'maskulin' },
      { ru: 'полицейский', id: 'Polisi', note: 'maskulin' },
      { ru: 'пожарный', id: 'Pemadam kebakaran', note: 'maskulin' },
      { ru: 'медсестра', id: 'Perawat', note: 'feminin' },
      { ru: 'повар', id: 'Koki', note: 'maskulin' },
      { ru: 'пекарь', id: 'Tukang roti', note: 'maskulin' },
      { ru: 'мясник', id: 'Tukang daging', note: 'maskulin' },
      { ru: 'парикмахер', id: 'Tukang cukur', note: 'maskulin' },
      { ru: 'продавец', id: 'Penjual', note: 'maskulin' },
      { ru: 'официант', id: 'Pelayan', note: 'maskulin' },
      { ru: 'пилот', id: 'Pilot', note: 'maskulin' },
      { ru: 'архитектор', id: 'Arsitek', note: 'maskulin' },
      { ru: 'журналист', id: 'Jurnalis', note: 'maskulin' },
      { ru: 'писатель', id: 'Penulis', note: 'maskulin' },
      { ru: 'художник', id: 'Seniman', note: 'maskulin' },
      { ru: 'музыкант', id: 'Musisi', note: 'maskulin' },
      { ru: 'актёр', id: 'Aktor', note: 'maskulin' },
      { ru: 'актриса', id: 'Aktris', note: 'feminin' },
      { ru: 'режиссёр', id: 'Sutradara', note: 'maskulin' },
      { ru: 'программист', id: 'Programmer', note: 'maskulin' },
      { ru: 'водитель', id: 'Sopir', note: 'maskulin' },
      { ru: 'фермер', id: 'Petani', note: 'maskulin' }
    ],
    emosi: [
      { ru: 'счастливый', id: 'Bahagia' },
      { ru: 'грустный', id: 'Sedih' },
      { ru: 'злой', id: 'Marah' },
      { ru: 'раздражённый', id: 'Jengkel' },
      { ru: 'удивлённый', id: 'Terkejut' },
      { ru: 'разочарованный', id: 'Kecewa' },
      { ru: 'гордый', id: 'Bangga' },
      { ru: 'застенчивый', id: 'Malu' },
      { ru: 'любопытный', id: 'Penasaran' },
      { ru: 'довольный', id: 'Puas' },
      { ru: 'обеспокоенный', id: 'Khawatir' },
      { ru: 'взволнованный', id: 'Gugup' },
      { ru: 'растерянный', id: 'Bingung' },
      { ru: 'смелый', id: 'Pemberani' },
      { ru: 'трусливый', id: 'Penakut' },
      { ru: 'ревнивый', id: 'Cemburu' },
      { ru: 'виноватый', id: 'Bersalah' },
      { ru: 'одинокий', id: 'Kesepian' },
      { ru: 'спокойный', id: 'Tenang' },
      { ru: 'нервный', id: 'Gelisah' },
      { ru: 'усталый', id: 'Lelah' },
      { ru: 'скучающий', id: 'Bosan' },
      { ru: 'благодарный', id: 'Bersyukur' },
      { ru: 'завистливый', id: 'Iri' },
      { ru: 'влюбленный', id: 'Jatuh cinta' },
      { ru: 'сердитый', id: 'Kesal' },
      { ru: 'восторженный', id: 'Antusias' },
      { ru: 'паникующий', id: 'Panik' },
      { ru: 'раздосадованный', id: 'Jengkel' },
      { ru: 'уверенный', id: 'Percaya diri' }
    ],
    verbes: [
      { ru: 'быть', id: 'Adalah' },
      { ru: 'иметь', id: 'Memiliki' },
      { ru: 'мочь', id: 'Bisa' },
      { ru: 'хотеть', id: 'Mau' },
      { ru: 'долженствовать', id: 'Harus' },
      { ru: 'идти', id: 'Pergi' },
      { ru: 'приходить', id: 'Datang' },
      { ru: 'делать', id: 'Membuat' },
      { ru: 'говорить', id: 'Berbicara' },
      { ru: 'давать', id: 'Memberi' },
      { ru: 'брать', id: 'Mengambil' },
      { ru: 'видеть', id: 'Melihat' },
      { ru: 'знать', id: 'Tahu' },
      { ru: 'понимать', id: 'Mengerti' },
      { ru: 'думать', id: 'Berpikir' },
      { ru: 'верить', id: 'Percaya' },
      { ru: 'любить', id: 'Mencintai' },
      { ru: 'ненавидеть', id: 'Membenci' },
      { ru: 'покупать', id: 'Membeli' },
      { ru: 'продавать', id: 'Menjual' },
      { ru: 'работать', id: 'Bekerja' },
      { ru: 'учиться', id: 'Belajar' },
      { ru: 'читать', id: 'Membaca' },
      { ru: 'писать', id: 'Menulis' },
      { ru: 'слушать', id: 'Mendengarkan' },
      { ru: 'отвечать', id: 'Menjawab' },
      { ru: 'спрашивать', id: 'Bertanya' },
      { ru: 'объяснять', id: 'Menjelaskan' },
      { ru: 'показывать', id: 'Menunjukkan' },
      { ru: 'искать', id: 'Mencari' },
      { ru: 'находить', id: 'Menemukan' },
      { ru: 'терять', id: 'Kehilangan' },
      { ru: 'выигрывать', id: 'Menang' },
      { ru: 'открывать', id: 'Membuka' },
      { ru: 'закрывать', id: 'Menutup' },
      { ru: 'начинать', id: 'Memulai' },
      { ru: 'заканчивать', id: 'Mengakhiri' },
      { ru: 'есть', id: 'Makan' },
      { ru: 'пить', id: 'Minum' },
      { ru: 'спать', id: 'Tidur' },
      { ru: 'жить', id: 'Hidup' },
      { ru: 'умирать', id: 'Mati' },
      { ru: 'рождаться', id: 'Lahir' },
      { ru: 'помогать', id: 'Membantu' },
      { ru: 'ждать', id: 'Menunggu' },
      { ru: 'нести', id: 'Membawa' },
      { ru: 'получать', id: 'Menerima' },
      { ru: 'отправлять', id: 'Mengirim' },
      { ru: 'платить', id: 'Membayar' },
      { ru: 'гулять', id: 'Berjalan-jalan' }
    ],
    bodyParts: [
      { ru: 'голова', id: 'Kepala', note: 'feminin' },
      { ru: 'лицо', id: 'Wajah', note: 'netral' },
      { ru: 'лоб', id: 'Dahi', note: 'maskulin' },
      { ru: 'бровь', id: 'Alis', note: 'feminin' },
      { ru: 'глаз', id: 'Mata', note: 'maskulin' },
      { ru: 'ресницы', id: 'Bulu mata' },
      { ru: 'нос', id: 'Hidung', note: 'maskulin' },
      { ru: 'щека', id: 'Pipi', note: 'feminin' },
      { ru: 'рот', id: 'Mulut', note: 'maskulin' },
      { ru: 'губа', id: 'Bibir', note: 'feminin' },
      { ru: 'зуб', id: 'Gigi', note: 'maskulin' },
      { ru: 'язык', id: 'Lidah', note: 'maskulin' },
      { ru: 'подбородок', id: 'Dagu', note: 'maskulin' },
      { ru: 'челюсть', id: 'Rahang', note: 'feminin' },
      { ru: 'ухо', id: 'Telinga', note: 'netral' },
      { ru: 'шея', id: 'Leher', note: 'feminin' },
      { ru: 'плечо', id: 'Bahu', note: 'netral' },
      { ru: 'плечевой сустав', id: 'Sendi bahu', note: 'maskulin' },
      { ru: 'локоть', id: 'Siku', note: 'maskulin' },
      { ru: 'предплечье', id: 'Lengan bawah', note: 'netral' },
      { ru: 'рука', id: 'Tangan', note: 'feminin' },
      { ru: 'палец', id: 'Jari', note: 'maskulin' },
      { ru: 'большой палец', id: 'Ibu jari', note: 'maskulin' },
      { ru: 'ладонь', id: 'Telapak tangan', note: 'feminin' },
      { ru: 'грудь', id: 'Dada', note: 'feminin' },
      { ru: 'рёбра', id: 'Tulang rusuk' },
      { ru: 'живот', id: 'Perut', note: 'maskulin' },
      { ru: 'спина', id: 'Punggung', note: 'feminin' },
      { ru: 'талия', id: 'Pinggang', note: 'feminin' },
      { ru: 'бедро', id: 'Paha', note: 'netral' },
      { ru: 'колено', id: 'Lutut', note: 'netral' },
      { ru: 'голень', id: 'Tungkai bawah', note: 'feminin' },
      { ru: 'икра', id: 'Betis', note: 'feminin' },
      { ru: 'лодыжка', id: 'Pergelangan kaki', note: 'feminin' },
      { ru: 'ступня', id: 'Telapak kaki', note: 'feminin' },
      { ru: 'носок (ноги)', id: 'Jari kaki', note: 'maskulin' },
      { ru: 'кожа', id: 'Kulit', note: 'feminin' },
      { ru: 'волосы', id: 'Rambut' },
      { ru: 'борода', id: 'Janggut', note: 'feminin' },
      { ru: 'сердце', id: 'Jantung', note: 'netral' },
      { ru: 'лёгкое', id: 'Paru-paru', note: 'netral' },
      { ru: 'печень', id: 'Hati', note: 'feminin' },
      { ru: 'почка', id: 'Ginjal', note: 'feminin' },
      { ru: 'желудок', id: 'Lambung', note: 'maskulin' },
      { ru: 'кишечник', id: 'Usus', note: 'maskulin' },
      { ru: 'мозг', id: 'Otak', note: 'maskulin' },
      { ru: 'кровь', id: 'Darah', note: 'feminin' },
      { ru: 'кость', id: 'Tulang', note: 'feminin' },
      { ru: 'сустав', id: 'Sendi', note: 'maskulin' },
      { ru: 'мышца', id: 'Otot', note: 'feminin' },
      { ru: 'нерв', id: 'Saraf', note: 'maskulin' }
    ],
    clothing: [
      { ru: 'платье', id: 'Gaun', note: 'netral' },
      { ru: 'юбка', id: 'Rok', note: 'feminin' },
      { ru: 'брюки', id: 'Celana' },
      { ru: 'джинсы', id: 'Jeans' },
      { ru: 'футболка', id: 'Kaos', note: 'feminin' },
      { ru: 'блузка', id: 'Blus', note: 'feminin' },
      { ru: 'свитер', id: 'Sweter', note: 'maskulin' },
      { ru: 'куртка', id: 'Jaket', note: 'feminin' },
      { ru: 'пальто', id: 'Mantel', note: 'netral' },
      { ru: 'костюм', id: 'Jas', note: 'maskulin' },
      { ru: 'рубашка', id: 'Kemeja', note: 'feminin' },
      { ru: 'галстук', id: 'Dasi', note: 'maskulin' },
      { ru: 'ремень', id: 'Ikat pinggang', note: 'maskulin' },
      { ru: 'обувь', id: 'Sepatu', note: 'feminin' },
      { ru: 'сапоги', id: 'Bot' },
      { ru: 'носки', id: 'Kaus kaki' },
      { ru: 'шляпа', id: 'Topi', note: 'feminin' },
      { ru: 'шапка', id: 'Topi hangat', note: 'feminin' },
      { ru: 'шарф', id: 'Syal', note: 'maskulin' },
      { ru: 'перчатки', id: 'Sarung tangan' },
      { ru: 'очки', id: 'Kacamata' },
      { ru: 'украшения', id: 'Perhiasan' },
      { ru: 'ожерелье', id: 'Kalung', note: 'netral' },
      { ru: 'кольцо', id: 'Cincin', note: 'netral' },
      { ru: 'браслет', id: 'Gelang', note: 'maskulin' },
      { ru: 'серьги', id: 'Anting' },
      { ru: 'купальник', id: 'Baju renang', note: 'maskulin' },
      { ru: 'пижама', id: 'Baju tidur', note: 'feminin' },
      { ru: 'нижнее бельё', id: 'Pakaian dalam', note: 'netral' },
      { ru: 'колготки', id: 'Stoking' },
      { ru: 'спортивный костюм', id: 'Pakaian olahraga', note: 'maskulin' },
      { ru: 'форма', id: 'Seragam', note: 'feminin' },
      { ru: 'лабораторный халат', id: 'Jas lab', note: 'maskulin' },
      { ru: 'комбинезон', id: 'Wangsu', note: 'maskulin' },
      { ru: 'берет', id: 'Baret', note: 'maskulin' }
    ],
    house: [
      { ru: 'дом', id: 'Rumah', note: 'maskulin' },
      { ru: 'квартира', id: 'Apartemen', note: 'feminin' },
      { ru: 'комната', id: 'Kamar', note: 'feminin' },
      { ru: 'спальня', id: 'Kamar tidur', note: 'feminin' },
      { ru: 'гостиная', id: 'Ruang tamu', note: 'feminin' },
      { ru: 'кухня', id: 'Dapur', note: 'feminin' },
      { ru: 'ванная', id: 'Kamar mandi', note: 'feminin' },
      { ru: 'столовая', id: 'Ruang makan', note: 'feminin' },
      { ru: 'кабинет', id: 'Ruang kerja', note: 'maskulin' },
      { ru: 'детская', id: 'Kamar anak', note: 'feminin' },
      { ru: 'коридор', id: 'Koridor', note: 'maskulin' },
      { ru: 'прихожая', id: 'Ruang depan', note: 'feminin' },
      { ru: 'балкон', id: 'Balkon', note: 'maskulin' },
      { ru: 'терраса', id: 'Teras', note: 'feminin' },
      { ru: 'сад', id: 'Kebun', note: 'maskulin' },
      { ru: 'подвал', id: 'Gudang bawah tanah', note: 'maskulin' },
      { ru: 'чердак', id: 'Loteng', note: 'maskulin' },
      { ru: 'гараж', id: 'Garasi', note: 'maskulin' },
      { ru: 'крыша', id: 'Atap', note: 'feminin' },
      { ru: 'труба', id: 'Cerobong asap', note: 'feminin' },
      { ru: 'окно', id: 'Jendela', note: 'netral' },
      { ru: 'дверь', id: 'Pintu', note: 'feminin' },
      { ru: 'ворота', id: 'Gerbang' },
      { ru: 'стена', id: 'Tembok/Dinding', note: 'feminin' },
      { ru: 'пол', id: 'Lantai', note: 'maskulin' },
      { ru: 'потолок', id: 'Langit-langit', note: 'maskulin' },
      { ru: 'лестница', id: 'Tangga', note: 'feminin' },
      { ru: 'перила', id: 'Pegangan' },
      { ru: 'ключ', id: 'Kunci', note: 'maskulin' },
      { ru: 'замок', id: 'Kunci pintu', note: 'maskulin' },
      { ru: 'дверная ручка', id: 'Gagang pintu', note: 'feminin' },
      { ru: 'дверной звонок', id: 'Bel pintu', note: 'maskulin' },
      { ru: 'отопление', id: 'Pemanas', note: 'netral' },
      { ru: 'кондиционер', id: 'AC', note: 'maskulin' },
      { ru: 'розетка', id: 'Stop kontak', note: 'feminin' },
      { ru: 'выключатель', id: 'Sakelar', note: 'maskulin' },
      { ru: 'стиральная машина', id: 'Mesin cuci', note: 'feminin' },
      { ru: 'холодильник', id: 'Kulkas', note: 'maskulin' },
      { ru: 'духовка', id: 'Oven', note: 'feminin' },
      { ru: 'плита', id: 'Kompor', note: 'feminin' },
      { ru: 'посудомоечная машина', id: 'Mesin pencuci piring', note: 'feminin' },
      { ru: 'пылесос', id: 'Penyedot debu', note: 'maskulin' },
      { ru: 'мусорное ведро', id: 'Tempat sampah', note: 'netral' },
      { ru: 'зеркало', id: 'Cermin', note: 'netral' },
      { ru: 'диван', id: 'Sofa', note: 'maskulin' },
      { ru: 'шкаф', id: 'Lemari', note: 'maskulin' },
      { ru: 'полка', id: 'Rak', note: 'feminin' },
      { ru: 'стол', id: 'Meja', note: 'maskulin' },
      { ru: 'стул', id: 'Kursi', note: 'maskulin' },
      { ru: 'кровать', id: 'Tempat tidur', note: 'feminin' },
      { ru: 'матрас', id: 'Kasur', note: 'maskulin' },
      { ru: 'подушка', id: 'Bantal', note: 'feminin' },
      { ru: 'одеяло', id: 'Selimut', note: 'netral' },
      { ru: 'простыня', id: 'Sprei', note: 'feminin' },
      { ru: 'лампа', id: 'Lampu', note: 'feminin' },
      { ru: 'ковёр', id: 'Karpet', note: 'maskulin' },
      { ru: 'занавеска', id: 'Gorden', note: 'feminin' },
      { ru: 'картина', id: 'Lukisan', note: 'feminin' },
      { ru: 'часы', id: 'Jam' },
      { ru: 'ваза', id: 'Vas', note: 'feminin' }
    ],
    nature: [
      { ru: 'солнце', id: 'Matahari', note: 'netral' },
      { ru: 'луна', id: 'Bulan', note: 'feminin' },
      { ru: 'звезда', id: 'Bintang', note: 'feminin' },
      { ru: 'небо', id: 'Langit', note: 'netral' },
      { ru: 'море', id: 'Laut', note: 'netral' },
      { ru: 'океан', id: 'Samudra', note: 'maskulin' },
      { ru: 'река', id: 'Sungai', note: 'feminin' },
      { ru: 'озеро', id: 'Danau', note: 'netral' },
      { ru: 'гора', id: 'Gunung', note: 'feminin' },
      { ru: 'холм', id: 'Bukit', note: 'maskulin' },
      { ru: 'лес', id: 'Hutan', note: 'maskulin' },
      { ru: 'дерево', id: 'Pohon', note: 'netral' },
      { ru: 'цветок', id: 'Bunga', note: 'maskulin' },
      { ru: 'трава', id: 'Rumput', note: 'feminin' },
      { ru: 'камень', id: 'Batu', note: 'maskulin' },
      { ru: 'песок', id: 'Pasir', note: 'maskulin' },
      { ru: 'облако', id: 'Awan', note: 'netral' },
      { ru: 'дождь', id: 'Hujan', note: 'maskulin' },
      { ru: 'снег', id: 'Salju', note: 'maskulin' },
      { ru: 'ветер', id: 'Angin', note: 'maskulin' },
      { ru: 'воздух', id: 'Udara', note: 'maskulin' },
      { ru: 'земля', id: 'Tanah/Bumi', note: 'feminin' },
      { ru: 'вода', id: 'Air', note: 'feminin' },
      { ru: 'огонь', id: 'Api', note: 'maskulin' },
      { ru: 'радуга', id: 'Pelangi', note: 'feminin' },
      { ru: 'молния', id: 'Petir', note: 'feminin' },
      { ru: 'гром', id: 'Guntur', note: 'maskulin' },
      { ru: 'рассвет', id: 'Fajar', note: 'maskulin' },
      { ru: 'закат', id: 'Senja', note: 'maskulin' },
      { ru: 'остров', id: 'Pulau', note: 'maskulin' },
      { ru: 'пляж', id: 'Pantai', note: 'maskulin' },
      { ru: 'пустыня', id: 'Gurun', note: 'feminin' },
      { ru: 'долина', id: 'Lembah', note: 'feminin' },
      { ru: 'водопад', id: 'Air terjun', note: 'maskulin' },
      { ru: 'пещера', id: 'Gua', note: 'feminin' },
      { ru: 'вулкан', id: 'Gunung berapi', note: 'maskulin' },
      { ru: 'землетрясение', id: 'Gempa bumi', note: 'netral' },
      { ru: 'наводнение', id: 'Banjir', note: 'netral' },
      { ru: 'засуха', id: 'Kekeringan', note: 'feminin' }
    ],
    animalsDomestic: [
      { ru: 'собака', id: 'Anjing', note: 'feminin' },
      { ru: 'кошка', id: 'Kucing', note: 'feminin' },
      { ru: 'кролик', id: 'Kelinci', note: 'maskulin' },
      { ru: 'птица', id: 'Burung', note: 'feminin' },
      { ru: 'золотая рыбка', id: 'Ikan mas', note: 'feminin' },
      { ru: 'хомяк', id: 'Hamster', note: 'maskulin' },
      { ru: 'черепаха', id: 'Kura-kura', note: 'feminin' },
      { ru: 'лошадь', id: 'Kuda', note: 'feminin' },
      { ru: 'курица', id: 'Ayam betina', note: 'feminin' },
      { ru: 'петух', id: 'Ayam jantan', note: 'maskulin' },
      { ru: 'утка', id: 'Bebek', note: 'feminin' },
      { ru: 'коза', id: 'Kambing', note: 'feminin' },
      { ru: 'овца', id: 'Domba', note: 'feminin' },
      { ru: 'свинья', id: 'Babi', note: 'feminin' },
      { ru: 'осёл', id: 'Keledai', note: 'maskulin' },
      { ru: 'корова', id: 'Sapi', note: 'feminin' },
      { ru: 'бык', id: 'Banteng', note: 'maskulin' },
      { ru: 'индюк', id: 'Kalkun', note: 'maskulin' },
      { ru: 'голубь', id: 'Merpati', note: 'maskulin' },
      { ru: 'попугай', id: 'Burung beo', note: 'maskulin' }
    ],
    animalsWild: [
      { ru: 'лев', id: 'Singa', note: 'maskulin' },
      { ru: 'тигр', id: 'Harimau', note: 'maskulin' },
      { ru: 'слон', id: 'Gajah', note: 'maskulin' },
      { ru: 'жираф', id: 'Jerapah', note: 'maskulin' },
      { ru: 'зебра', id: 'Zebra', note: 'feminin' },
      { ru: 'горилла', id: 'Gorila', note: 'feminin' },
      { ru: 'медведь', id: 'Beruang', note: 'maskulin' },
      { ru: 'волк', id: 'Serigala', note: 'maskulin' },
      { ru: 'лиса', id: 'Rubah', note: 'feminin' },
      { ru: 'олень', id: 'Rusa', note: 'maskulin' },
      { ru: 'змея', id: 'Ular', note: 'feminin' },
      { ru: 'крокодил', id: 'Buaya', note: 'maskulin' },
      { ru: 'бегемот', id: 'Kuda nil', note: 'maskulin' },
      { ru: 'носорог', id: 'Badak', note: 'maskulin' },
      { ru: 'обезьяна', id: 'Monyet', note: 'feminin' },
      { ru: 'кенгуру', id: 'Kanguru', note: 'maskulin' },
      { ru: 'коала', id: 'Koala', note: 'maskulin' },
      { ru: 'гиена', id: 'Hiena', note: 'feminin' },
      { ru: 'леопард', id: 'Macan tutul', note: 'maskulin' },
      { ru: 'гепард', id: 'Cheetah', note: 'maskulin' },
      { ru: 'шакал', id: 'Jakal', note: 'maskulin' },
      { ru: 'гриф', id: 'Burung nasar', note: 'maskulin' },
      { ru: 'кабан', id: 'Babi hutan', note: 'maskulin' },
      { ru: 'енот', id: 'Rakun', note: 'maskulin' },
      { ru: 'ёж', id: 'Landak', note: 'maskulin' },
      { ru: 'бобр', id: 'Berang-berang', note: 'maskulin' },
      { ru: 'белка', id: 'Tupai', note: 'feminin' },
      { ru: 'крот', id: 'Tikus tanah', note: 'maskulin' },
      { ru: 'летучая мышь', id: 'Kelelawar', note: 'feminin' }
    ],
    animalsSea: [
      { ru: 'кит', id: 'Paus', note: 'maskulin' },
      { ru: 'дельфин', id: 'Lumba-lumba', note: 'maskulin' },
      { ru: 'акула', id: 'Hiu', note: 'feminin' },
      { ru: 'морская черепаха', id: 'Penyu', note: 'feminin' },
      { ru: 'тюлень', id: 'Anjing laut', note: 'maskulin' },
      { ru: 'морской котик', id: 'Singa laut', note: 'maskulin' },
      { ru: 'краб', id: 'Kepiting', note: 'maskulin' },
      { ru: 'креветка', id: 'Udang', note: 'feminin' },
      { ru: 'устрица', id: 'Tiram', note: 'feminin' },
      { ru: 'моллюск', id: 'Kerang', note: 'maskulin' },
      { ru: 'осьминог', id: 'Gurita', note: 'maskulin' },
      { ru: 'кальмар', id: 'Cumi-cumi', note: 'maskulin' },
      { ru: 'медуза', id: 'Ubur-ubur', note: 'feminin' },
      { ru: 'морская звезда', id: 'Bintang laut', note: 'feminin' },
      { ru: 'конёк (рыба)', id: 'Kuda laut', note: 'maskulin' }
    ],
    insects: [
      { ru: 'пчела', id: 'Lebah', note: 'feminin' },
      { ru: 'муравей', id: 'Semut', note: 'maskulin' },
      { ru: 'бабочка', id: 'Kupu-kupu', note: 'feminin' },
      { ru: 'гусеница', id: 'Ulat', note: 'feminin' },
      { ru: 'божья коровка', id: 'Kepik', note: 'feminin' },
      { ru: 'жук', id: 'Kumbang', note: 'maskulin' },
      { ru: 'муха', id: 'Lalat', note: 'feminin' },
      { ru: 'комар', id: 'Nyamuk', note: 'maskulin' },
      { ru: 'мотылёк', id: 'Ngengat', note: 'maskulin' },
      { ru: 'кузнечик', id: 'Belalang', note: 'maskulin' },
      { ru: 'сверчок', id: 'Jangkrik', note: 'maskulin' },
      { ru: 'паук', id: 'Laba-laba', note: 'maskulin' },
      { ru: 'скорпион', id: 'Kalajengking', note: 'maskulin' },
      { ru: 'клоп', id: 'Kutu busuk', note: 'maskulin' },
      { ru: 'стрекоза', id: 'Capung', note: 'feminin' },
      { ru: 'богомол', id: 'Belalang sembah', note: 'maskulin' },
      { ru: 'таракан', id: 'Kecoa', note: 'maskulin' },
      { ru: 'мокрица', id: 'Kutu babi', note: 'feminin' }
    ],
    foodExtended: [
      { ru: 'круассан', id: 'Croissant', note: 'maskulin' },
      { ru: 'крендель', id: 'Pretzel', note: 'maskulin' },
      { ru: 'торт', id: 'Kue', note: 'maskulin' },
      { ru: 'блин', id: 'Kue dadar', note: 'maskulin' },
      { ru: 'вафля', id: 'Waffle', note: 'feminin' },
      { ru: 'киш', id: 'Kue pai asin', note: 'maskulin' },
      { ru: 'козий сыр', id: 'Keju kambing', note: 'maskulin' },
      { ru: 'камамбер', id: 'Keju Camembert', note: 'maskulin' },
      { ru: 'колбаса жареная', id: 'Sosis panggang', note: 'feminin' },
      { ru: 'квашеная капуста', id: 'Kubis asam', note: 'feminin' },
      { ru: 'картофельный салат', id: 'Salad kentang', note: 'maskulin' },
      { ru: 'шницель', id: 'Schnitzel', note: 'maskulin' },
      { ru: 'яблочный штрудель', id: 'Strudel apel', note: 'maskulin' },
      { ru: 'хлеб', id: 'Roti', note: 'maskulin' },
      { ru: 'булочка', id: 'Roti kecil', note: 'feminin' },
      { ru: 'лапша', id: 'Mie/Pasta', note: 'feminin' },
      { ru: 'томатный суп', id: 'Sup tomat', note: 'maskulin' },
      { ru: 'фруктовый салат', id: 'Salad buah', note: 'maskulin' },
      { ru: 'овощной салат', id: 'Salad sayuran', note: 'maskulin' },
      { ru: 'яблоко', id: 'Apel', note: 'netral' },
      { ru: 'груша', id: 'Pir', note: 'feminin' },
      { ru: 'персик', id: 'Persik', note: 'maskulin' },
      { ru: 'вишня', id: 'Ceri', note: 'feminin' },
      { ru: 'клубника', id: 'Stroberi', note: 'feminin' },
      { ru: 'черника', id: 'Blueberry', note: 'feminin' },
      { ru: 'малина', id: 'Raspberry', note: 'feminin' },
      { ru: 'виноград', id: 'Anggur buah', note: 'maskulin' },
      { ru: 'дыня', id: 'Melon', note: 'feminin' },
      { ru: 'апельсин', id: 'Jeruk', note: 'maskulin' },
      { ru: 'лимон', id: 'Lemon', note: 'maskulin' },
      { ru: 'ананас', id: 'Nanas', note: 'maskulin' },
      { ru: 'манго', id: 'Mangga', note: 'netral' },
      { ru: 'киви', id: 'Kiwi', note: 'netral' },
      { ru: 'слива', id: 'Plum', note: 'feminin' },
      { ru: 'миндаль', id: 'Almond', note: 'maskulin' },
      { ru: 'грецкий орех', id: 'Kenari', note: 'maskulin' },
      { ru: 'фундук', id: 'Hazelnut', note: 'maskulin' },
      { ru: 'арахис', id: 'Kacang tanah', note: 'maskulin' },
      { ru: 'фисташки', id: 'Kacang pistachio' },
      { ru: 'кешью', id: 'Kacang mete' },
      { ru: 'варенье', id: 'Selai', note: 'netral' },
      { ru: 'мёд', id: 'Madu', note: 'maskulin' },
      { ru: 'масло сливочное', id: 'Mentega', note: 'netral' },
      { ru: 'мука', id: 'Tepung', note: 'feminin' },
      { ru: 'оливковое масло', id: 'Minyak zaitun', note: 'netral' },
      { ru: 'уксус', id: 'Cuka', note: 'maskulin' },
      { ru: 'горчица', id: 'Mustard', note: 'feminin' },
      { ru: 'кетчуп', id: 'Kecap', note: 'maskulin' },
      { ru: 'майонез', id: 'Mayones', note: 'maskulin' },
      { ru: 'сливки', id: 'Krim' },
      { ru: 'йогурт', id: 'Yogurt', note: 'maskulin' },
      { ru: 'творог', id: 'Keju cottage', note: 'maskulin' },
      { ru: 'сметана', id: 'Krim asam', note: 'feminin' }
    ],
    transportation: [
      { ru: 'автомобиль', id: 'Mobil', note: 'maskulin' },
      { ru: 'грузовик', id: 'Truk', note: 'maskulin' },
      { ru: 'автобус', id: 'Bus', note: 'maskulin' },
      { ru: 'метро', id: 'Kereta bawah tanah', note: 'netral' },
      { ru: 'поезд', id: 'Kereta api', note: 'maskulin' },
      { ru: 'трамвай', id: 'Trem', note: 'maskulin' },
      { ru: 'такси', id: 'Taksi', note: 'netral' },
      { ru: 'самолёт', id: 'Pesawat', note: 'maskulin' },
      { ru: 'корабль', id: 'Kapal', note: 'maskulin' },
      { ru: 'велосипед', id: 'Sepeda', note: 'maskulin' },
      { ru: 'мотоцикл', id: 'Motor', note: 'maskulin' },
      { ru: 'скутер', id: 'Skuter', note: 'maskulin' },
      { ru: 'паром', id: 'Kapal feri', note: 'maskulin' },
      { ru: 'яхта', id: 'Kapal pesiar', note: 'feminin' },
      { ru: 'канатная дорога', id: 'Kereta gantung', note: 'feminin' },
      { ru: 'скоростной поезд', id: 'Kereta cepat', note: 'maskulin' },
      { ru: 'вертолёт', id: 'Helikopter', note: 'maskulin' },
      { ru: 'воздушный шар', id: 'Balon udara', note: 'maskulin' },
      { ru: 'подводная лодка', id: 'Kapal selam', note: 'feminin' },
      { ru: 'грузовой корабль', id: 'Kapal kargo', note: 'maskulin' },
      { ru: 'скорая помощь', id: 'Ambulans', note: 'feminin' },
      { ru: 'пожарная машина', id: 'Truk pemadam', note: 'feminin' },
      { ru: 'мусоровоз', id: 'Truk sampah', note: 'maskulin' },
      { ru: 'трактор', id: 'Traktor', note: 'maskulin' },
      { ru: 'транспорт', id: 'Kendaraan', note: 'maskulin' },
      { ru: 'шоссе', id: 'Jalan tol', note: 'netral' },
      { ru: 'дорога', id: 'Jalan raya', note: 'feminin' },
      { ru: 'перекрёсток', id: 'Perempatan', note: 'maskulin' },
      { ru: 'круговое движение', id: 'Bundaran', note: 'netral' },
      { ru: 'стоянка', id: 'Parkir', note: 'feminin' },
      { ru: 'пешеходный переход', id: 'Penyeberangan', note: 'maskulin' },
      { ru: 'светофор', id: 'Lampu lalu lintas', note: 'maskulin' },
      { ru: 'знак дорожный', id: 'Rambu lalu lintas', note: 'maskulin' },
      { ru: 'ремень безопасности', id: 'Sabuk pengaman', note: 'maskulin' },
      { ru: 'водительское удостоверение', id: 'SIM', note: 'netral' },
      { ru: 'бензин', id: 'Bensin', note: 'maskulin' },
      { ru: 'бак', id: 'Tangki', note: 'maskulin' },
      { ru: 'двигатель', id: 'Mesin', note: 'maskulin' },
      { ru: 'колесо', id: 'Roda', note: 'netral' }
    ],
    technology: [
      { ru: 'компьютер', id: 'Komputer', note: 'maskulin' },
      { ru: 'экран', id: 'Layar', note: 'maskulin' },
      { ru: 'клавиатура', id: 'Keyboard', note: 'feminin' },
      { ru: 'мышь', id: 'Mouse', note: 'feminin' },
      { ru: 'принтер', id: 'Printer', note: 'maskulin' },
      { ru: 'телефон', id: 'Telepon', note: 'maskulin' },
      { ru: 'мобильный телефон', id: 'HP', note: 'maskulin' },
      { ru: 'планшет', id: 'Tablet', note: 'maskulin' },
      { ru: 'интернет', id: 'Internet', note: 'maskulin' },
      { ru: 'сеть', id: 'Jaringan', note: 'feminin' },
      { ru: 'соединение', id: 'Koneksi', note: 'netral' },
      { ru: 'Wi-Fi', id: 'Wifi', note: 'maskulin' },
      { ru: 'приложение', id: 'Aplikasi', note: 'netral' },
      { ru: 'программное обеспечение', id: 'Perangkat lunak', note: 'netral' },
      { ru: 'оборудование', id: 'Perangkat keras', note: 'netral' },
      { ru: 'сенсорный экран', id: 'Layar sentuh', note: 'maskulin' },
      { ru: 'процессор', id: 'Prosesor', note: 'maskulin' },
      { ru: 'память', id: 'Memori', note: 'feminin' },
      { ru: 'жёсткий диск', id: 'Hard disk', note: 'maskulin' },
      { ru: 'флешка', id: 'Flashdisk', note: 'feminin' },
      { ru: 'камера', id: 'Kamera', note: 'feminin' },
      { ru: 'видео', id: 'Video', note: 'netral' },
      { ru: 'фото', id: 'Foto', note: 'netral' },
      { ru: 'наушники', id: 'Headset' },
      { ru: 'колонки', id: 'Speaker' },
      { ru: 'зарядное устройство', id: 'Charger', note: 'netral' },
      { ru: 'аккумулятор', id: 'Baterai', note: 'maskulin' },
      { ru: 'домашний экран', id: 'Home screen', note: 'maskulin' },
      { ru: 'пароль', id: 'Password', note: 'maskulin' },
      { ru: 'электронная почта', id: 'Email', note: 'feminin' },
      { ru: 'браузер', id: 'Browser', note: 'maskulin' },
      { ru: 'веб-страница', id: 'Halaman web', note: 'feminin' },
      { ru: 'веб-сайт', id: 'Situs web', note: 'maskulin' },
      { ru: 'блог', id: 'Blog', note: 'maskulin' },
      { ru: 'социальная сеть', id: 'Jejaring sosial', note: 'feminin' },
      { ru: 'сообщение', id: 'Pesan', note: 'netral' },
      { ru: 'вложение', id: 'Lampiran', note: 'netral' },
      { ru: 'скачать', id: 'Mengunduh' },
      { ru: 'обновить', id: 'Memperbarui' },
      { ru: 'сохранить', id: 'Menyimpan' },
      { ru: 'отправить', id: 'Mengirim' },
      { ru: 'удалить', id: 'Menghapus' },
      { ru: 'напечатать', id: 'Mencetak' },
      { ru: 'заряжать', id: 'Mengisi daya' }
    ],
    schoolEducation: [
      { ru: 'школа', id: 'Sekolah', note: 'feminin' },
      { ru: 'университет', id: 'Universitas', note: 'maskulin' },
      { ru: 'класс', id: 'Kelas', note: 'maskulin' },
      { ru: 'доска', id: 'Papan tulis', note: 'feminin' },
      { ru: 'учительский стол', id: 'Meja guru', note: 'maskulin' },
      { ru: 'книга', id: 'Buku', note: 'feminin' },
      { ru: 'тетрадь', id: 'Buku tulis', note: 'feminin' },
      { ru: 'ручка', id: 'Pena', note: 'feminin' },
      { ru: 'карандаш', id: 'Pensil', note: 'maskulin' },
      { ru: 'ластик', id: 'Penghapus', note: 'maskulin' },
      { ru: 'линейка', id: 'Penggaris', note: 'feminin' },
      { ru: 'рюкзак', id: 'Tas punggung', note: 'maskulin' },
      { ru: 'авторучка', id: 'Pulpen', note: 'feminin' },
      { ru: 'маркер', id: 'Spidol', note: 'maskulin' },
      { ru: 'мел', id: 'Kapur tulis', note: 'maskulin' },
      { ru: 'уравнение', id: 'Persamaan', note: 'netral' },
      { ru: 'дробь', id: 'Pecahan', note: 'feminin' },
      { ru: 'результат', id: 'Hasil', note: 'maskulin' },
      { ru: 'средний балл', id: 'Nilai rata-rata', note: 'maskulin' },
      { ru: 'оценка', id: 'Nilai', note: 'feminin' },
      { ru: 'домашнее задание', id: 'PR', note: 'netral' },
      { ru: 'экзамен', id: 'Ujian', note: 'maskulin' },
      { ru: 'курс', id: 'Kursus', note: 'maskulin' },
      { ru: 'предмет', id: 'Mata pelajaran', note: 'maskulin' },
      { ru: 'русский язык', id: 'Bahasa Rusia', note: 'maskulin' },
      { ru: 'математика', id: 'Matematika', note: 'feminin' },
      { ru: 'физика', id: 'Fisika', note: 'feminin' },
      { ru: 'химия', id: 'Kimia', note: 'feminin' },
      { ru: 'биология', id: 'Biologi', note: 'feminin' },
      { ru: 'история', id: 'Sejarah', note: 'feminin' },
      { ru: 'география', id: 'Geografi', note: 'feminin' },
      { ru: 'английский язык', id: 'Bahasa Inggris', note: 'maskulin' },
      { ru: 'искусство', id: 'Seni', note: 'netral' },
      { ru: 'музыка', id: 'Musik', note: 'feminin' },
      { ru: 'физкультура', id: 'Olahraga', note: 'feminin' },
      { ru: 'философия', id: 'Filsafat', note: 'feminin' },
      { ru: 'экономика', id: 'Ekonomi', note: 'feminin' },
      { ru: 'семестр', id: 'Semester', note: 'maskulin' },
      { ru: 'кампус', id: 'Kampus', note: 'maskulin' },
      { ru: 'библиотека', id: 'Perpustakaan', note: 'feminin' },
      { ru: 'столовая', id: 'Kantin', note: 'feminin' },
      { ru: 'зачисление', id: 'Pendaftaran', note: 'netral' },
      { ru: 'диплом', id: 'Gelar', note: 'maskulin' },
      { ru: 'дипломная работа', id: 'Tesis', note: 'feminin' },
      { ru: 'стажировка', id: 'Magang', note: 'feminin' },
      { ru: 'профессор', id: 'Profesor', note: 'maskulin' },
      { ru: 'ректор', id: 'Rektor', note: 'maskulin' },
      { ru: 'ученик', id: 'Siswa', note: 'maskulin' },
      { ru: 'одноклассник', id: 'Teman sekelas', note: 'maskulin' }
    ],
    workOffice: [
      { ru: 'офис', id: 'Kantor', note: 'maskulin' },
      { ru: 'совещание', id: 'Rapat', note: 'netral' },
      { ru: 'начальник', id: 'Atasan', note: 'maskulin' },
      { ru: 'коллега', id: 'Rekan kerja', note: 'maskulin' },
      { ru: 'зарплата', id: 'Gaji', note: 'feminin' },
      { ru: 'работа', id: 'Pekerjaan', note: 'feminin' },
      { ru: 'договор', id: 'Kontrak', note: 'maskulin' },
      { ru: 'отпуск', id: 'Liburan', note: 'maskulin' },
      { ru: 'перерыв', id: 'Istirahat', note: 'maskulin' },
      { ru: 'конец рабочего дня', id: 'Akhir hari kerja', note: 'maskulin' },
      { ru: 'собеседование', id: 'Wawancara kerja', note: 'netral' },
      { ru: 'заявление о приёме', id: 'Lamaran kerja', note: 'netral' },
      { ru: 'резюме', id: 'CV', note: 'netral' },
      { ru: 'сопроводительное письмо', id: 'Surat motivasi', note: 'netral' },
      { ru: 'повышение', id: 'Promosi', note: 'netral' },
      { ru: 'увольнение', id: 'PHK', note: 'netral' },
      { ru: 'пенсия', id: 'Pensiun', note: 'feminin' },
      { ru: 'отдел', id: 'Departemen', note: 'maskulin' },
      { ru: 'проект', id: 'Proyek', note: 'maskulin' },
      { ru: 'успех', id: 'Keberhasilan', note: 'maskulin' },
      { ru: 'достижение', id: 'Pencapaian', note: 'netral' },
      { ru: 'амбиция', id: 'Ambisi', note: 'feminin' },
      { ru: 'оценка работы', id: 'Penilaian', note: 'feminin' },
      { ru: 'бонус', id: 'Bonus', note: 'maskulin' },
      { ru: 'налог', id: 'Pajak', note: 'maskulin' },
      { ru: 'касса', id: 'Kasir', note: 'feminin' },
      { ru: 'шкаф для документов', id: 'Lemari arsip', note: 'maskulin' },
      { ru: 'папка', id: 'Map', note: 'feminin' }
    ],
    sportsActivities: [
      { ru: 'футбол', id: 'Sepak bola', note: 'maskulin' },
      { ru: 'баскетбол', id: 'Basket', note: 'maskulin' },
      { ru: 'теннис', id: 'Tenis', note: 'maskulin' },
      { ru: 'волейбол', id: 'Voli', note: 'maskulin' },
      { ru: 'лёгкая атлетика', id: 'Atletik', note: 'feminin' },
      { ru: 'плавание', id: 'Renang', note: 'netral' },
      { ru: 'регби', id: 'Ragbi', note: 'netral' },
      { ru: 'гандбол', id: 'Bola tangan', note: 'maskulin' },
      { ru: 'фехтование', id: 'Anggar', note: 'netral' },
      { ru: 'верховая езда', id: 'Berkuda', note: 'feminin' },
      { ru: 'гольф', id: 'Golf', note: 'maskulin' },
      { ru: 'лыжный спорт', id: 'Ski', note: 'maskulin' },
      { ru: 'сноубординг', id: 'Snowboard', note: 'maskulin' },
      { ru: 'сёрфинг', id: 'Selancar', note: 'maskulin' },
      { ru: 'дзюдо', id: 'Judo', note: 'netral' },
      { ru: 'карате', id: 'Karate', note: 'netral' },
      { ru: 'бокс', id: 'Tinju', note: 'maskulin' },
      { ru: 'борьба', id: 'Gulat', note: 'feminin' },
      { ru: 'гимнастика', id: 'Senam', note: 'feminin' },
      { ru: 'йога', id: 'Yoga', note: 'feminin' },
      { ru: 'езда на велосипеде', id: 'Bersepeda', note: 'feminin' },
      { ru: 'тяжёлая атлетика', id: 'Angkat besi', note: 'feminin' },
      { ru: 'бег', id: 'Lari', note: 'maskulin' },
      { ru: 'пешая прогулка', id: 'Jalan kaki', note: 'feminin' },
      { ru: 'скалолазание', id: 'Panjat tebing', note: 'netral' },
      { ru: 'дайвинг', id: 'Selam', note: 'maskulin' },
      { ru: 'парусный спорт', id: 'Layar', note: 'maskulin' },
      { ru: 'гребля', id: 'Mendayung', note: 'feminin' },
      { ru: 'каякинг', id: 'Kajak', note: 'maskulin' },
      { ru: 'стрельба из лука', id: 'Panahan', note: 'feminin' },
      { ru: 'стрельба', id: 'Menembak', note: 'feminin' },
      { ru: 'фигурное катание', id: 'Seluncur indah', note: 'netral' },
      { ru: 'хоккей', id: 'Hoki es', note: 'maskulin' },
      { ru: 'бейсбол', id: 'Baseball', note: 'maskulin' },
      { ru: 'крикет', id: 'Kriket', note: 'maskulin' },
      { ru: 'бадминтон', id: 'Bulutangkis', note: 'maskulin' },
      { ru: 'настольный теннис', id: 'Pingpong', note: 'maskulin' },
      { ru: 'боулинг', id: 'Boling', note: 'maskulin' },
      { ru: 'танцы', id: 'Tari' },
      { ru: 'скейтбординг', id: 'Skateboard', note: 'maskulin' },
      { ru: 'роликовые коньки', id: 'Inline skate' }
    ],
    hobbiesLeisure: [
      { ru: 'чтение', id: 'Membaca', note: 'netral' },
      { ru: 'письмо', id: 'Menulis', note: 'netral' },
      { ru: 'живопись', id: 'Melukis', note: 'feminin' },
      { ru: 'рисование', id: 'Menggambar', note: 'netral' },
      { ru: 'кино', id: 'Nonton film', note: 'netral' },
      { ru: 'музыка', id: 'Dengar musik', note: 'feminin' },
      { ru: 'видеоигры', id: 'Main game' },
      { ru: 'фотография', id: 'Fotografi', note: 'feminin' },
      { ru: 'садоводство', id: 'Berkebun', note: 'netral' },
      { ru: 'шитьё', id: 'Menjahit', note: 'netral' },
      { ru: 'вязание', id: 'Merajut', note: 'netral' },
      { ru: 'вышивание', id: 'Menyulam', note: 'netral' },
      { ru: 'ремонт', id: 'DIY/perbaikan', note: 'maskulin' },
      { ru: 'коллекционирование', id: 'Koleksi', note: 'netral' },
      { ru: 'моделизм', id: 'Model kit', note: 'maskulin' },
      { ru: 'филателия', id: 'Filateli', note: 'feminin' },
      { ru: 'аквариумистика', id: 'Hobi ikan', note: 'feminin' },
      { ru: 'петанк', id: 'Petanque', note: 'maskulin' },
      { ru: 'шахматы', id: 'Catur' },
      { ru: 'карточные игры', id: 'Main kartu' },
      { ru: 'медитация', id: 'Meditasi', note: 'feminin' },
      { ru: 'природа', id: 'Alam terbuka', note: 'feminin' },
      { ru: 'поход', id: 'Hiking', note: 'maskulin' },
      { ru: 'пикник', id: 'Piknik', note: 'maskulin' },
      { ru: 'кемпинг', id: 'Berkemah', note: 'maskulin' },
      { ru: 'рыбалка', id: 'Memancing', note: 'feminin' },
      { ru: 'охота', id: 'Berburu', note: 'feminin' },
      { ru: 'танцы', id: 'Menari' },
      { ru: 'керамика', id: 'Keramik', note: 'feminin' }
    ],
    healthMedical: [
      { ru: 'здоровье', id: 'Kesehatan', note: 'netral' },
      { ru: 'болезнь', id: 'Penyakit', note: 'feminin' },
      { ru: 'простуда', id: 'Pilek', note: 'feminin' },
      { ru: 'грипп', id: 'Flu', note: 'maskulin' },
      { ru: 'жар', id: 'Demam', note: 'maskulin' },
      { ru: 'кашель', id: 'Batuk', note: 'maskulin' },
      { ru: 'головная боль', id: 'Sakit kepala', note: 'feminin' },
      { ru: 'боль в спине', id: 'Sakit punggung', note: 'feminin' },
      { ru: 'боль в животе', id: 'Sakit perut', note: 'feminin' },
      { ru: 'тошнота', id: 'Mual', note: 'feminin' },
      { ru: 'рвота', id: 'Muntah', note: 'feminin' },
      { ru: 'диарея', id: 'Diare', note: 'feminin' },
      { ru: 'запор', id: 'Sembelit', note: 'maskulin' },
      { ru: 'аллергия', id: 'Alergi', note: 'feminin' },
      { ru: 'астма', id: 'Asma', note: 'feminin' },
      { ru: 'диабет', id: 'Diabetes', note: 'maskulin' },
      { ru: 'гипертония', id: 'Hipertensi', note: 'feminin' },
      { ru: 'инфекция', id: 'Infeksi', note: 'feminin' },
      { ru: 'рана', id: 'Luka', note: 'feminin' },
      { ru: 'шрам', id: 'Bekas luka', note: 'maskulin' },
      { ru: 'ссадина', id: 'Luka lecet', note: 'feminin' },
      { ru: 'порез', id: 'Goresan', note: 'maskulin' },
      { ru: 'синяк', id: 'Memar', note: 'maskulin' },
      { ru: 'отёк', id: 'Bengkak', note: 'maskulin' },
      { ru: 'головокружение', id: 'Pusing', note: 'netral' },
      { ru: 'бессонница', id: 'Insomnia', note: 'feminin' },
      { ru: 'усталость', id: 'Kelelahan', note: 'feminin' },
      { ru: 'стресс', id: 'Stres', note: 'maskulin' },
      { ru: 'депрессия', id: 'Depresi', note: 'feminin' },
      { ru: 'тревога', id: 'Kecemasan', note: 'feminin' },
      { ru: 'лечение', id: 'Perawatan', note: 'netral' },
      { ru: 'рецепт', id: 'Resep', note: 'maskulin' },
      { ru: 'антибиотик', id: 'Antibiotik', note: 'maskulin' },
      { ru: 'аспирин', id: 'Aspirin', note: 'maskulin' },
      { ru: 'мазь', id: 'Salep', note: 'feminin' },
      { ru: 'повязка', id: 'Perban', note: 'feminin' },
      { ru: 'укол', id: 'Suntikan', note: 'maskulin' },
      { ru: 'обследование', id: 'Pemeriksaan', note: 'netral' },
      { ru: 'рентген', id: 'Rontgen', note: 'maskulin' },
      { ru: 'операция', id: 'Operasi', note: 'feminin' },
      { ru: 'наркоз', id: 'Anestesi', note: 'maskulin' },
      { ru: 'выздоровление', id: 'Penyembuhan', note: 'netral' },
      { ru: 'прививка', id: 'Vaksin', note: 'feminin' }
    ],
    professionsExtended: [
      { ru: 'врач', id: 'Dokter', note: 'maskulin' },
      { ru: 'врач (женщина)', id: 'Dokter (wanita)', note: 'feminin' },
      { ru: 'адвокат', id: 'Pengacara', note: 'maskulin' },
      { ru: 'адвокат (женщина)', id: 'Pengacara (wanita)', note: 'feminin' },
      { ru: 'инженер', id: 'Insinyur', note: 'maskulin' },
      { ru: 'инженер (женщина)', id: 'Insinyur (wanita)', note: 'feminin' },
      { ru: 'архитектор', id: 'Arsitek', note: 'maskulin' },
      { ru: 'архитектор (женщина)', id: 'Arsitek (wanita)', note: 'feminin' },
      { ru: 'учитель', id: 'Guru', note: 'maskulin' },
      { ru: 'учительница', id: 'Guru (wanita)', note: 'feminin' },
      { ru: 'профессор', id: 'Profesor', note: 'maskulin' },
      { ru: 'профессор (женщина)', id: 'Profesor (wanita)', note: 'feminin' },
      { ru: 'пилот', id: 'Pilot', note: 'maskulin' },
      { ru: 'пилот (женщина)', id: 'Pilot (wanita)', note: 'feminin' },
      { ru: 'полицейский', id: 'Polisi', note: 'maskulin' },
      { ru: 'полицейская', id: 'Polisi (wanita)', note: 'feminin' },
      { ru: 'пожарный', id: 'Pemadam kebakaran', note: 'maskulin' },
      { ru: 'пожарная', id: 'Pemadam (wanita)', note: 'feminin' },
      { ru: 'медбрат', id: 'Perawat (pria)', note: 'maskulin' },
      { ru: 'медсестра', id: 'Perawat', note: 'feminin' },
      { ru: 'зубной врач', id: 'Dokter gigi', note: 'maskulin' },
      { ru: 'зубной врач (женщина)', id: 'Dokter gigi (wanita)', note: 'feminin' },
      { ru: 'аптекарь', id: 'Apoteker', note: 'maskulin' },
      { ru: 'аптекарь (женщина)', id: 'Apoteker (wanita)', note: 'feminin' },
      { ru: 'журналист', id: 'Jurnalis', note: 'maskulin' },
      { ru: 'журналистка', id: 'Jurnalis (wanita)', note: 'feminin' },
      { ru: 'писатель', id: 'Penulis', note: 'maskulin' },
      { ru: 'писательница', id: 'Penulis (wanita)', note: 'feminin' },
      { ru: 'художник', id: 'Seniman', note: 'maskulin' },
      { ru: 'художница', id: 'Seniwati', note: 'feminin' },
      { ru: 'музыкант', id: 'Musisi', note: 'maskulin' },
      { ru: 'музыкант (женщина)', id: 'Musisi (wanita)', note: 'feminin' },
      { ru: 'актёр', id: 'Aktor', note: 'maskulin' },
      { ru: 'актриса', id: 'Aktris', note: 'feminin' },
      { ru: 'режиссёр', id: 'Sutradara', note: 'maskulin' },
      { ru: 'режиссёр (женщина)', id: 'Sutradara (wanita)', note: 'feminin' },
      { ru: 'повар', id: 'Koki', note: 'maskulin' },
      { ru: 'повар (женщина)', id: 'Koki (wanita)', note: 'feminin' },
      { ru: 'пекарь', id: 'Tukang roti', note: 'maskulin' },
      { ru: 'пекарь (женщина)', id: 'Tukang roti (wanita)', note: 'feminin' },
      { ru: 'мясник', id: 'Tukang daging', note: 'maskulin' },
      { ru: 'мясник (женщина)', id: 'Tukang daging (wanita)', note: 'feminin' },
      { ru: 'парикмахер', id: 'Tukang cukur', note: 'maskulin' },
      { ru: 'парикмахер (женщина)', id: 'Tukang cukur (wanita)', note: 'feminin' },
      { ru: 'продавец', id: 'Penjual', note: 'maskulin' },
      { ru: 'продавщица', id: 'Penjual (wanita)', note: 'feminin' },
      { ru: 'официант', id: 'Pelayan', note: 'maskulin' },
      { ru: 'официантка', id: 'Pelayan (wanita)', note: 'feminin' },
      { ru: 'менеджер', id: 'Manajer', note: 'maskulin' },
      { ru: 'менеджер (женщина)', id: 'Manajer (wanita)', note: 'feminin' },
      { ru: 'секретарь', id: 'Sekretaris', note: 'maskulin' },
      { ru: 'секретарь (женщина)', id: 'Sekretaris (wanita)', note: 'feminin' },
      { ru: 'программист', id: 'Programmer', note: 'maskulin' },
      { ru: 'программист (женщина)', id: 'Programmer (wanita)', note: 'feminin' }
    ],
    cityPlaces: [
      { ru: 'город', id: 'Kota', note: 'maskulin' },
      { ru: 'столица', id: 'Ibukota', note: 'feminin' },
      { ru: 'деревня', id: 'Desa', note: 'feminin' },
      { ru: 'пригород', id: 'Pinggiran kota', note: 'maskulin' },
      { ru: 'район', id: 'Distrik kota', note: 'maskulin' },
      { ru: 'ратуша', id: 'Balai kota', note: 'feminin' },
      { ru: 'церковь', id: 'Gereja', note: 'feminin' },
      { ru: 'собор', id: 'Katedral', note: 'maskulin' },
      { ru: 'часовня', id: 'Kapel', note: 'feminin' },
      { ru: 'музей', id: 'Museum', note: 'maskulin' },
      { ru: 'галерея', id: 'Galeri', note: 'feminin' },
      { ru: 'дворец', id: 'Istana', note: 'maskulin' },
      { ru: 'крепость', id: 'Benteng', note: 'feminin' },
      { ru: 'парк', id: 'Taman', note: 'maskulin' },
      { ru: 'сад', id: 'Kebun', note: 'maskulin' },
      { ru: 'детская площадка', id: 'Taman bermain', note: 'feminin' },
      { ru: 'школа', id: 'Sekolah', note: 'feminin' },
      { ru: 'больница', id: 'Rumah sakit', note: 'feminin' },
      { ru: 'аптека', id: 'Apotek', note: 'feminin' },
      { ru: 'почта', id: 'Kantor pos', note: 'feminin' },
      { ru: 'банк', id: 'Bank', note: 'maskulin' },
      { ru: 'отель', id: 'Hotel', note: 'maskulin' },
      { ru: 'ресторан', id: 'Restoran', note: 'maskulin' },
      { ru: 'бар', id: 'Bar', note: 'maskulin' },
      { ru: 'кафе', id: 'Kafe', note: 'netral' },
      { ru: 'пекарня', id: 'Toko roti', note: 'feminin' },
      { ru: 'кондитерская', id: 'Toko kue', note: 'feminin' },
      { ru: 'мясная лавка', id: 'Toko daging', note: 'feminin' },
      { ru: 'супермаркет', id: 'Supermarket', note: 'maskulin' },
      { ru: 'рынок', id: 'Pasar', note: 'maskulin' },
      { ru: 'универмаг', id: 'Toko serba ada', note: 'maskulin' },
      { ru: 'библиотека', id: 'Perpustakaan', note: 'feminin' },
      { ru: 'театр', id: 'Teater', note: 'maskulin' },
      { ru: 'опера', id: 'Opera', note: 'feminin' },
      { ru: 'кинотеатр', id: 'Bioskop', note: 'maskulin' },
      { ru: 'вокзал', id: 'Stasiun kereta', note: 'maskulin' },
      { ru: 'остановка', id: 'Halte bus', note: 'feminin' },
      { ru: 'аэропорт', id: 'Bandara', note: 'maskulin' },
      { ru: 'мост', id: 'Jembatan', note: 'maskulin' },
      { ru: 'башня', id: 'Menara', note: 'feminin' },
      { ru: 'памятник', id: 'Monumen', note: 'maskulin' },
      { ru: 'фонтан', id: 'Air mancur', note: 'maskulin' },
      { ru: 'колодец', id: 'Sumur', note: 'maskulin' },
      { ru: 'лестница', id: 'Tangga', note: 'feminin' },
      { ru: 'лифт', id: 'Lift', note: 'maskulin' },
      { ru: 'улица', id: 'Jalan', note: 'feminin' },
      { ru: 'дорога', id: 'Jalur', note: 'feminin' },
      { ru: 'знак', id: 'Rambu', note: 'maskulin' },
      { ru: 'реклама', id: 'Reklame', note: 'feminin' },
      { ru: 'завод', id: 'Pabrik', note: 'maskulin' }
    ],
    weatherClimate: [
      { ru: 'погода', id: 'Cuaca', note: 'feminin' },
      { ru: 'климат', id: 'Iklim', note: 'maskulin' },
      { ru: 'солнце', id: 'Matahari', note: 'netral' },
      { ru: 'дождь', id: 'Hujan', note: 'maskulin' },
      { ru: 'снег', id: 'Salju', note: 'maskulin' },
      { ru: 'ветер', id: 'Angin', note: 'maskulin' },
      { ru: 'облако', id: 'Awan', note: 'netral' },
      { ru: 'туман', id: 'Kabut', note: 'maskulin' },
      { ru: 'гроза', id: 'Badai petir', note: 'feminin' },
      { ru: 'молния', id: 'Petir', note: 'feminin' },
      { ru: 'гром', id: 'Guntur', note: 'maskulin' },
      { ru: 'радуга', id: 'Pelangi', note: 'feminin' },
      { ru: 'иней', id: 'Embun beku', note: 'maskulin' },
      { ru: 'лёд', id: 'Es', note: 'maskulin' },
      { ru: 'жара', id: 'Panas', note: 'feminin' },
      { ru: 'холод', id: 'Dingin', note: 'maskulin' },
      { ru: 'засуха', id: 'Kekeringan', note: 'feminin' },
      { ru: 'влажность', id: 'Kelembapan', note: 'feminin' },
      { ru: 'шторм', id: 'Badai', note: 'maskulin' },
      { ru: 'наводнение', id: 'Banjir', note: 'netral' },
      { ru: 'засуха', id: 'Kekeringan', note: 'feminin' },
      { ru: 'солнечный свет', id: 'Sinar matahari', note: 'maskulin' },
      { ru: 'температура', id: 'Suhu', note: 'feminin' },
      { ru: 'градус', id: 'Derajat', note: 'maskulin' },
      { ru: 'лето', id: 'Musim panas', note: 'netral' },
      { ru: 'зима', id: 'Musim dingin', note: 'feminin' },
      { ru: 'весна', id: 'Musim semi', note: 'feminin' },
      { ru: 'осень', id: 'Musim gugur', note: 'feminin' }
    ],
    timeExtended: [
      { ru: 'время', id: 'Waktu', note: 'netral' },
      { ru: 'секунда', id: 'Detik', note: 'feminin' },
      { ru: 'минута', id: 'Menit', note: 'feminin' },
      { ru: 'час', id: 'Jam', note: 'maskulin' },
      { ru: 'утро', id: 'Pagi', note: 'netral' },
      { ru: 'день', id: 'Siang/Hari', note: 'maskulin' },
      { ru: 'вечер', id: 'Sore/Malam', note: 'maskulin' },
      { ru: 'ночь', id: 'Malam', note: 'feminin' },
      { ru: 'день (сутки)', id: 'Hari (24 jam)', note: 'maskulin' },
      { ru: 'неделя', id: 'Minggu', note: 'feminin' },
      { ru: 'месяц', id: 'Bulan', note: 'maskulin' },
      { ru: 'год', id: 'Tahun', note: 'maskulin' },
      { ru: 'десятилетие', id: 'Dekade', note: 'netral' },
      { ru: 'век', id: 'Abad', note: 'maskulin' },
      { ru: 'тысячелетие', id: 'Milenium', note: 'netral' },
      { ru: 'прошлое', id: 'Masa lalu', note: 'netral' },
      { ru: 'настоящее', id: 'Masa kini', note: 'netral' },
      { ru: 'будущее', id: 'Masa depan', note: 'netral' },
      { ru: 'рассвет', id: 'Subuh', note: 'maskulin' },
      { ru: 'спешка', id: 'Terburu-buru', note: 'feminin' },
      { ru: 'терпение', id: 'Kesabaran', note: 'netral' },
      { ru: 'тишина', id: 'Keheningan', note: 'feminin' },
      { ru: 'покой', id: 'Ketenangan', note: 'maskulin' },
      { ru: 'возраст', id: 'Usia', note: 'maskulin' },
      { ru: 'молодость', id: 'Masa muda', note: 'feminin' },
      { ru: 'детство', id: 'Masa kecil', note: 'netral' },
      { ru: 'начало', id: 'Awal', note: 'netral' },
      { ru: 'конец', id: 'Akhir', note: 'maskulin' },
      { ru: 'пауза', id: 'Jeda', note: 'feminin' },
      { ru: 'праздник', id: 'Pesta', note: 'maskulin' },
      { ru: 'каникулы', id: 'Liburan' },
      { ru: 'будни', id: 'Hari biasa' }
    ],
    directionsPositions: [
      { ru: 'влево', id: 'Kiri' },
      { ru: 'вправо', id: 'Kanan' },
      { ru: 'прямо', id: 'Lurus' },
      { ru: 'вверх', id: 'Atas' },
      { ru: 'вниз', id: 'Bawah' },
      { ru: 'вперёд', id: 'Depan' },
      { ru: 'назад', id: 'Belakang' },
      { ru: 'рядом', id: 'Di sebelah' },
      { ru: 'напротив', id: 'Seberang' },
      { ru: 'между', id: 'Di antara' },
      { ru: 'близко', id: 'Dekat' },
      { ru: 'далеко', id: 'Jauh' },
      { ru: 'внутри', id: 'Di dalam' },
      { ru: 'снаружи', id: 'Di luar' },
      { ru: 'над', id: 'Di atas' },
      { ru: 'под', id: 'Di bawah' },
      { ru: 'перед', id: 'Di depan' },
      { ru: 'за', id: 'Di belakang' },
      { ru: 'у', id: 'Di samping' },
      { ru: 'на', id: 'Di atas (permukaan)' },
      { ru: 'из', id: 'Dari dalam' },
      { ru: 'в', id: 'Ke/Di' },
      { ru: 'от', id: 'Dari' },
      { ru: 'к', id: 'Ke' },
      { ru: 'с', id: 'Bersama' },
      { ru: 'без', id: 'Tanpa' },
      { ru: 'против', id: 'Melawan' },
      { ru: 'для', id: 'Untuk' },
      { ru: 'вокруг', id: 'Di sekitar' },
      { ru: 'через', id: 'Melalui' }
    ],
    quantitiesMeasurements: [
      { ru: 'метр', id: 'Meter', note: 'maskulin' },
      { ru: 'километр', id: 'Kilometer', note: 'maskulin' },
      { ru: 'сантиметр', id: 'Sentimeter', note: 'maskulin' },
      { ru: 'килограмм', id: 'Kilogram', note: 'maskulin' },
      { ru: 'грамм', id: 'Gram', note: 'maskulin' },
      { ru: 'тонна', id: 'Ton', note: 'feminin' },
      { ru: 'литр', id: 'Liter', note: 'maskulin' },
      { ru: 'бутылка', id: 'Botol', note: 'feminin' },
      { ru: 'стакан', id: 'Gelas', note: 'maskulin' },
      { ru: 'чашка', id: 'Cangkir', note: 'feminin' },
      { ru: 'ложка', id: 'Sendok', note: 'feminin' },
      { ru: 'вилка', id: 'Garpu', note: 'feminin' },
      { ru: 'нож', id: 'Pisau', note: 'maskulin' },
      { ru: 'миска', id: 'Mangkuk', note: 'feminin' },
      { ru: 'тарелка', id: 'Piring', note: 'feminin' },
      { ru: 'поднос', id: 'Nampan', note: 'maskulin' },
      { ru: 'кастрюля', id: 'Panci', note: 'feminin' },
      { ru: 'сковорода', id: 'Wajan', note: 'feminin' },
      { ru: 'чайник', id: 'Ketel', note: 'maskulin' },
      { ru: 'ведро', id: 'Ember', note: 'netral' },
      { ru: 'лопата', id: 'Cangkul', note: 'feminin' },
      { ru: 'метла', id: 'Sapu', note: 'feminin' },
      { ru: 'корзина', id: 'Keranjang', note: 'feminin' },
      { ru: 'коробка', id: 'Kotak', note: 'feminin' },
      { ru: 'картон', id: 'Kardus', note: 'maskulin' },
      { ru: 'банка', id: 'Kaleng', note: 'feminin' },
      { ru: 'крышка', id: 'Tutup', note: 'feminin' },
      { ru: 'пакет', id: 'Tas belanja', note: 'maskulin' },
      { ru: 'упаковка', id: 'Kemasan', note: 'feminin' },
      { ru: 'цена', id: 'Harga', note: 'feminin' },
      { ru: 'счёт', id: 'Tagihan', note: 'maskulin' },
      { ru: 'скидка', id: 'Diskon', note: 'feminin' },
      { ru: 'НДС', id: 'PPN', note: 'maskulin' },
      { ru: 'чаевые', id: 'Tip' },
      { ru: 'общая цена', id: 'Total harga', note: 'feminin' },
      { ru: 'цена за штуку', id: 'Harga satuan', note: 'feminin' }
    ],
    adjectivesDescriptions: [
      { ru: 'большой', id: 'Besar' },
      { ru: 'маленький', id: 'Kecil' },
      { ru: 'длинный', id: 'Panjang' },
      { ru: 'короткий', id: 'Pendek' },
      { ru: 'широкий', id: 'Lebar' },
      { ru: 'узкий', id: 'Sempit' },
      { ru: 'толстый', id: 'Tebal' },
      { ru: 'тонкий', id: 'Tipis' },
      { ru: 'тяжёлый', id: 'Berat' },
      { ru: 'лёгкий', id: 'Ringan' },
      { ru: 'сильный', id: 'Kuat' },
      { ru: 'слабый', id: 'Lemah' },
      { ru: 'быстрый', id: 'Cepat' },
      { ru: 'медленный', id: 'Lambat' },
      { ru: 'старый', id: 'Tua/Lama' },
      { ru: 'молодой', id: 'Muda' },
      { ru: 'новый', id: 'Baru' },
      { ru: 'хороший', id: 'Baik' },
      { ru: 'плохой', id: 'Buruk' },
      { ru: 'красивый', id: 'Cantik/Indah' },
      { ru: 'уродливый', id: 'Jelek' },
      { ru: 'чистый', id: 'Bersih' },
      { ru: 'грязный', id: 'Kotor' },
      { ru: 'сухой', id: 'Kering' },
      { ru: 'мокрый', id: 'Basah' },
      { ru: 'холодный', id: 'Dingin' },
      { ru: 'тёплый', id: 'Hangat' },
      { ru: 'горячий', id: 'Panas' },
      { ru: 'свежий', id: 'Segar' },
      { ru: 'усталый', id: 'Lelah' },
      { ru: 'голодный', id: 'Lapar' },
      { ru: 'жаждущий', id: 'Haus' },
      { ru: 'больной', id: 'Sakit' },
      { ru: 'здоровый', id: 'Sehat' },
      { ru: 'весёлый', id: 'Bahagia' },
      { ru: 'грустный', id: 'Sedih' },
      { ru: 'смешной', id: 'Lucu' },
      { ru: 'серьёзный', id: 'Serius' },
      { ru: 'дружелюбный', id: 'Ramah' },
      { ru: 'злой', id: 'Jahat' },
      { ru: 'приятный', id: 'Menyenangkan' },
      { ru: 'удобный', id: 'Nyaman' },
      { ru: 'простой', id: 'Sederhana' },
      { ru: 'сложный', id: 'Sulit' },
      { ru: 'готовый', id: 'Siap' },
      { ru: 'правильный', id: 'Benar' },
      { ru: 'неправильный', id: 'Salah' },
      { ru: 'важный', id: 'Penting' },
      { ru: 'интересный', id: 'Menarik' },
      { ru: 'скучный', id: 'Membosankan' },
      { ru: 'известный', id: 'Terkenal' },
      { ru: 'особенный', id: 'Istimewa' },
      { ru: 'нормальный', id: 'Normal' },
      { ru: 'типичный', id: 'Tipikal' },
      { ru: 'современный', id: 'Modern' },
      { ru: 'старомодный', id: 'Ketinggalan zaman' },
      { ru: 'классический', id: 'Klasik' },
      { ru: 'международный', id: 'Internasional' },
      { ru: 'национальный', id: 'Nasional' },
      { ru: 'местный', id: 'Lokal' },
      { ru: 'глобальный', id: 'Global' },
      { ru: 'личный', id: 'Pribadi' },
      { ru: 'частный', id: 'Privat' },
      { ru: 'публичный', id: 'Publik' },
      { ru: 'дорогой', id: 'Mahal' },
      { ru: 'дешёвый', id: 'Murah' },
      { ru: 'богатый', id: 'Kaya' },
      { ru: 'бедный', id: 'Miskin' }
    ],
    verbsExtended: [
      { ru: 'спать', id: 'Tidur' },
      { ru: 'просыпаться', id: 'Bangun' },
      { ru: 'завтракать', id: 'Makan pagi' },
      { ru: 'принимать душ', id: 'Mandi' },
      { ru: 'одеваться', id: 'Berpakaian' },
      { ru: 'раздеваться', id: 'Membuka pakaian' },
      { ru: 'готовить', id: 'Memasak' },
      { ru: 'печь', id: 'Memanggang' },
      { ru: 'жарить', id: 'Menggoreng' },
      { ru: 'мыть', id: 'Mencuci' },
      { ru: 'убирать', id: 'Membersihkan' },
      { ru: 'пылесосить', id: 'Menyedot debu' },
      { ru: 'гладить', id: 'Menggosok' },
      { ru: 'подметать', id: 'Menyapu' },
      { ru: 'мыть пол', id: 'Mengepel' },
      { ru: 'покупать', id: 'Berbelanja' },
      { ru: 'платить', id: 'Membayar' },
      { ru: 'копить', id: 'Menabung' },
      { ru: 'тратить', id: 'Menghabiskan' },
      { ru: 'зарабатывать', id: 'Menghasilkan' },
      { ru: 'работать', id: 'Bekerja' },
      { ru: 'учиться', id: 'Belajar' },
      { ru: 'изучать', id: 'Belajar (mendalam)' },
      { ru: 'читать', id: 'Membaca' },
      { ru: 'писать', id: 'Menulis' },
      { ru: 'говорить', id: 'Berbicara' },
      { ru: 'разговаривать', id: 'Bicara' },
      { ru: 'слушать', id: 'Mendengarkan' },
      { ru: 'отвечать', id: 'Menjawab' },
      { ru: 'спрашивать', id: 'Bertanya' },
      { ru: 'рассказывать', id: 'Menceritakan' },
      { ru: 'объяснять', id: 'Menjelaskan' },
      { ru: 'показывать', id: 'Menunjukkan' },
      { ru: 'искать', id: 'Mencari' },
      { ru: 'находить', id: 'Menemukan' },
      { ru: 'терять', id: 'Kehilangan' },
      { ru: 'выигрывать', id: 'Menang' },
      { ru: 'покупать', id: 'Membeli' },
      { ru: 'продавать', id: 'Menjual' },
      { ru: 'менять', id: 'Menukar' },
      { ru: 'доставлять', id: 'Mengirim' },
      { ru: 'прибывать', id: 'Tiba' },
      { ru: 'уезжать', id: 'Berangkat' },
      { ru: 'возвращаться', id: 'Kembali' },
      { ru: 'путешествовать', id: 'Bepergian' },
      { ru: 'летать', id: 'Terbang' },
      { ru: 'ехать', id: 'Mengendarai' },
      { ru: 'бежать', id: 'Berlari' },
      { ru: 'идти', id: 'Berjalan' },
      { ru: 'приходить', id: 'Datang' },
      { ru: 'приносить', id: 'Membawa' },
      { ru: 'брать', id: 'Mengambil' },
      { ru: 'давать', id: 'Memberi' },
      { ru: 'держать', id: 'Memegang' },
      { ru: 'класть', id: 'Meletakkan' },
      { ru: 'ставить', id: 'Menempatkan' },
      { ru: 'бросать', id: 'Melempar' },
      { ru: 'ловить', id: 'Menangkap' },
      { ru: 'открывать', id: 'Membuka' },
      { ru: 'закрывать', id: 'Menutup' },
      { ru: 'начинать', id: 'Memulai' },
      { ru: 'заканчивать', id: 'Mengakhiri' },
      { ru: 'пить', id: 'Minum' },
      { ru: 'есть (кушать)', id: 'Makan' },
      { ru: 'чувствовать', id: 'Merasa' },
      { ru: 'думать', id: 'Berpikir' },
      { ru: 'верить', id: 'Percaya' },
      { ru: 'знать', id: 'Tahu' },
      { ru: 'понимать', id: 'Mengerti' },
      { ru: 'забывать', id: 'Lupa' },
      { ru: 'помнить', id: 'Ingat' },
      { ru: 'мечтать', id: 'Bermimpi' },
      { ru: 'надеяться', id: 'Berharap' },
      { ru: 'хотеть', id: 'Menginginkan' },
      { ru: 'любить', id: 'Mencintai' },
      { ru: 'ненавидеть', id: 'Membenci' },
      { ru: 'уважать', id: 'Menghormati' },
      { ru: 'помогать', id: 'Membantu' },
      { ru: 'поддерживать', id: 'Mendukung' },
      { ru: 'нуждаться', id: 'Membutuhkan' },
      { ru: 'использовать', id: 'Menggunakan' },
      { ru: 'запрещать', id: 'Melarang' },
      { ru: 'разрешать', id: 'Memperbolehkan' },
      { ru: 'решать', id: 'Memutuskan' },
      { ru: 'выбирать', id: 'Memilih' },
      { ru: 'менять', id: 'Mengubah' },
      { ru: 'развивать', id: 'Mengembangkan' },
      { ru: 'улучшать', id: 'Memperbaiki' },
      { ru: 'ухудшать', id: 'Memperburuk' },
      { ru: 'сравнивать', id: 'Membandingkan' },
      { ru: 'отличать', id: 'Membedakan' },
      { ru: 'измерять', id: 'Mengukur' },
      { ru: 'считать', id: 'Menghitung' },
      { ru: 'проверять', id: 'Memeriksa' },
      { ru: 'контролировать', id: 'Mengontrol' },
      { ru: 'тестировать', id: 'Menguji' },
      { ru: 'смешивать', id: 'Mencampur' },
      { ru: 'разделять', id: 'Memisahkan' },
      { ru: 'соединять', id: 'Menyambungkan' },
      { ru: 'разрушать', id: 'Menghancurkan' },
      { ru: 'чинить', id: 'Memperbaiki' },
      { ru: 'строить', id: 'Membangun' },
      { ru: 'рисовать', id: 'Menggambar' },
      { ru: 'фотографировать', id: 'Memotret' },
      { ru: 'снимать на видео', id: 'Merekam' },
      { ru: 'резать', id: 'Memotong' },
      { ru: 'звенеть', id: 'Berdering' },
      { ru: 'шептать', id: 'Berbisik' },
      { ru: 'кричать', id: 'Berteriak' },
      { ru: 'плакать', id: 'Menangis' },
      { ru: 'смеяться', id: 'Tertawa' },
      { ru: 'улыбаться', id: 'Senyum' },
      { ru: 'чихать', id: 'Bersin' },
      { ru: 'кашлять', id: 'Batuk' },
      { ru: 'глотать', id: 'Menelan' },
      { ru: 'жевать', id: 'Mengunyah' },
      { ru: 'храпеть', id: 'Mendengkur' },
      { ru: 'дышать', id: 'Bernapas' }
    ],
    abstractConcepts: [
      { ru: 'жизнь', id: 'Kehidupan', note: 'feminin' },
      { ru: 'смерть', id: 'Kematian', note: 'feminin' },
      { ru: 'любовь', id: 'Cinta', note: 'feminin' },
      { ru: 'ненависть', id: 'Kebencian', note: 'feminin' },
      { ru: 'дружба', id: 'Persahabatan', note: 'feminin' },
      { ru: 'семья', id: 'Keluarga', note: 'feminin' },
      { ru: 'общество', id: 'Masyarakat', note: 'netral' },
      { ru: 'политика', id: 'Politik', note: 'feminin' },
      { ru: 'экономика', id: 'Ekonomi', note: 'feminin' },
      { ru: 'культура', id: 'Budaya', note: 'feminin' },
      { ru: 'искусство', id: 'Seni', note: 'netral' },
      { ru: 'музыка', id: 'Musik', note: 'feminin' },
      { ru: 'религия', id: 'Agama', note: 'feminin' },
      { ru: 'вера', id: 'Keyakinan', note: 'feminin' },
      { ru: 'надежда', id: 'Harapan', note: 'feminin' },
      { ru: 'мечта', id: 'Mimpi', note: 'feminin' },
      { ru: 'страх', id: 'Ketakutan', note: 'maskulin' },
      { ru: 'свобода', id: 'Kebebasan', note: 'feminin' },
      { ru: 'справедливость', id: 'Keadilan', note: 'feminin' },
      { ru: 'истина', id: 'Kebenaran', note: 'feminin' },
      { ru: 'ложь', id: 'Kebohongan', note: 'feminin' },
      { ru: 'счастье', id: 'Kebahagiaan', note: 'netral' },
      { ru: 'страдание', id: 'Penderitaan', note: 'netral' },
      { ru: 'успех', id: 'Keberhasilan', note: 'maskulin' },
      { ru: 'неудача', id: 'Kegagalan', note: 'feminin' },
      { ru: 'разочарование', id: 'Kekecewaan', note: 'netral' },
      { ru: 'удивление', id: 'Keterkejutan', note: 'netral' },
      { ru: 'энтузиазм', id: 'Antusiasme', note: 'maskulin' },
      { ru: 'скука', id: 'Kebosanan', note: 'feminin' },
      { ru: 'любопытство', id: 'Keingintahuan', note: 'netral' },
      { ru: 'сомнение', id: 'Keraguan', note: 'netral' },
      { ru: 'безопасность', id: 'Keamanan', note: 'feminin' },
      { ru: 'опасность', id: 'Bahaya', note: 'feminin' },
      { ru: 'риск', id: 'Risiko', note: 'maskulin' },
      { ru: 'вызов', id: 'Tantangan', note: 'maskulin' },
      { ru: 'возможность', id: 'Kesempatan', note: 'feminin' },
      { ru: 'вероятность', id: 'Kemungkinan', note: 'feminin' },
      { ru: 'необходимость', id: 'Kebutuhan', note: 'feminin' },
      { ru: 'обязанность', id: 'Kewajiban', note: 'feminin' },
      { ru: 'ответственность', id: 'Tanggung jawab', note: 'feminin' },
      { ru: 'решение', id: 'Keputusan', note: 'netral' },
      { ru: 'мнение', id: 'Pendapat', note: 'netral' },
      { ru: 'идея', id: 'Ide', note: 'feminin' },
      { ru: 'план', id: 'Rencana', note: 'maskulin' },
      { ru: 'цель', id: 'Tujuan', note: 'feminin' },
      { ru: 'значение', id: 'Arti', note: 'netral' },
      { ru: 'воспоминание', id: 'Kenangan', note: 'netral' },
      { ru: 'опыт', id: 'Pengalaman', note: 'maskulin' },
      { ru: 'традиция', id: 'Tradisi', note: 'feminin' },
      { ru: 'история', id: 'Sejarah', note: 'feminin' },
      { ru: 'природа', id: 'Alam', note: 'feminin' },
      { ru: 'окружающая среда', id: 'Lingkungan', note: 'netral' },
      { ru: 'земля', id: 'Bumi', note: 'feminin' },
      { ru: 'небо', id: 'Langit', note: 'netral' },
      { ru: 'солнце', id: 'Matahari', note: 'netral' },
      { ru: 'луна', id: 'Bulan', note: 'feminin' },
      { ru: 'звезда', id: 'Bintang', note: 'feminin' },
      { ru: 'море', id: 'Laut', note: 'netral' },
      { ru: 'река', id: 'Sungai', note: 'feminin' },
      { ru: 'озеро', id: 'Danau', note: 'netral' },
      { ru: 'гора', id: 'Gunung', note: 'feminin' },
      { ru: 'долина', id: 'Lembah', note: 'feminin' },
      { ru: 'остров', id: 'Pulau', note: 'maskulin' },
      { ru: 'лес', id: 'Hutan', note: 'maskulin' },
      { ru: 'пустыня', id: 'Gurun', note: 'feminin' },
      { ru: 'язык', id: 'Bahasa', note: 'maskulin' },
      { ru: 'слово', id: 'Kata', note: 'netral' },
      { ru: 'предложение', id: 'Kalimat', note: 'netral' },
      { ru: 'грамматика', id: 'Tata bahasa', note: 'feminin' },
      { ru: 'перевод', id: 'Terjemahan', note: 'maskulin' },
      { ru: 'произношение', id: 'Pengucapan', note: 'netral' },
      { ru: 'акцент', id: 'Aksen', note: 'maskulin' },
      { ru: 'письмо', id: 'Tulisan', note: 'netral' },
      { ru: 'алфавит', id: 'Alfabet', note: 'maskulin' }
    ]
    },
    quizzes: {
      colors: {
        title: 'Warna', icon: '🎨',
        vocab: [
          { ru: 'красный', id: 'Merah' }, { ru: 'синий', id: 'Biru' }, { ru: 'зелёный', id: 'Hijau' },
          { ru: 'жёлтый', id: 'Kuning' }, { ru: 'фиолетовый', id: 'Ungu' }, { ru: 'розовый', id: 'Merah muda' },
          { ru: 'чёрный', id: 'Hitam' }, { ru: 'белый', id: 'Putih' }, { ru: 'серый', id: 'Abu-abu' },
          { ru: 'коричневый', id: 'Cokelat' }, { ru: 'золотой', id: 'Emas' }, { ru: 'серебряный', id: 'Perak' }
        ]
      },
      numbers: {
        title: 'Angka', icon: '🔢',
        vocab: [
          { ru: 'ноль', id: 'Nol' }, { ru: 'один', id: 'Satu' }, { ru: 'два', id: 'Dua' },
          { ru: 'три', id: 'Tiga' }, { ru: 'четыре', id: 'Empat' }, { ru: 'пять', id: 'Lima' },
          { ru: 'шесть', id: 'Enam' }, { ru: 'семь', id: 'Tujuh' }, { ru: 'восемь', id: 'Delapan' },
          { ru: 'девять', id: 'Sembilan' }, { ru: 'десять', id: 'Sepuluh' }, { ru: 'двадцать', id: 'Dua puluh' },
          { ru: 'сто', id: 'Seratus' }, { ru: 'тысяча', id: 'Seribu' }
        ]
      },
      greetings: {
        title: 'Salam', icon: '👋',
        vocab: [
          { ru: 'Привет', id: 'Halo' }, { ru: 'Доброе утро', id: 'Selamat pagi' },
          { ru: 'Добрый день', id: 'Selamat siang' }, { ru: 'Добрый вечер', id: 'Selamat sore' },
          { ru: 'Спокойной ночи', id: 'Selamat malam' }, { ru: 'До свидания', id: 'Sampai jumpa' },
          { ru: 'Пока', id: 'Dadah' }, { ru: 'Спасибо', id: 'Terima kasih' },
          { ru: 'Пожалуйста', id: 'Tolong/Sama-sama' }, { ru: 'Извините', id: 'Maaf' },
          { ru: 'Да', id: 'Ya' }, { ru: 'Нет', id: 'Tidak' }
        ]
      },
      family: {
        title: 'Keluarga', icon: '👨‍👩‍👧‍👦',
        vocab: [
          { ru: 'мать', id: 'Ibu' }, { ru: 'отец', id: 'Ayah' },
          { ru: 'бабушка', id: 'Nenek' }, { ru: 'дедушка', id: 'Kakek' },
          { ru: 'сестра', id: 'Saudara perempuan' }, { ru: 'брат', id: 'Saudara laki-laki' },
          { ru: 'дочь', id: 'Anak perempuan' }, { ru: 'сын', id: 'Anak laki-laki' },
          { ru: 'семья', id: 'Keluarga' }, { ru: 'жена', id: 'Istri' },
          { ru: 'муж', id: 'Suami' }, { ru: 'ребёнок', id: 'Anak' }
        ]
      },
      food: {
        title: 'Makanan & Minuman', icon: '🍽️',
        vocab: [
          { ru: 'хлеб', id: 'Roti' }, { ru: 'масло', id: 'Mentega' },
          { ru: 'сыр', id: 'Keju' }, { ru: 'колбаса', id: 'Sosis' },
          { ru: 'яйцо', id: 'Telur' }, { ru: 'рис', id: 'Nasi' },
          { ru: 'картофель', id: 'Kentang' }, { ru: 'суп', id: 'Sup' },
          { ru: 'мясо', id: 'Daging' }, { ru: 'рыба', id: 'Ikan' },
          { ru: 'молоко', id: 'Susu' }, { ru: 'кофе', id: 'Kopi' },
          { ru: 'чай', id: 'Teh' }, { ru: 'вода', id: 'Air' },
          { ru: 'сахар', id: 'Gula' }, { ru: 'соль', id: 'Garam' },
          { ru: 'торт', id: 'Kue' }, { ru: 'лапша', id: 'Pasta' }
        ]
      },
      places: {
        title: 'Tempat', icon: '📍',
        vocab: [
          { ru: 'школа', id: 'Sekolah' }, { ru: 'университет', id: 'Universitas' },
          { ru: 'больница', id: 'Rumah sakit' }, { ru: 'церковь', id: 'Gereja' },
          { ru: 'музей', id: 'Museum' }, { ru: 'отель', id: 'Hotel' },
          { ru: 'ресторан', id: 'Restoran' }, { ru: 'банк', id: 'Bank' },
          { ru: 'супермаркет', id: 'Supermarket' }, { ru: 'библиотека', id: 'Perpustakaan' },
          { ru: 'кинотеатр', id: 'Bioskop' }, { ru: 'парк', id: 'Taman' },
          { ru: 'вокзал', id: 'Stasiun kereta' }, { ru: 'аэропорт', id: 'Bandara' }
        ]
      },
      professions: {
        title: 'Profesi', icon: '💼',
        vocab: [
          { ru: 'врач', id: 'Dokter' }, { ru: 'врач (женщина)', id: 'Dokter (wanita)' },
          { ru: 'учитель', id: 'Guru' }, { ru: 'учительница', id: 'Guru (wanita)' },
          { ru: 'инженер', id: 'Insinyur' }, { ru: 'инженер (женщина)', id: 'Insinyur (wanita)' },
          { ru: 'адвокат', id: 'Pengacara' }, { ru: 'полицейский', id: 'Polisi' },
          { ru: 'полицейская', id: 'Polisi (wanita)' }, { ru: 'повар', id: 'Koki' },
          { ru: 'повар (женщина)', id: 'Koki (wanita)' }, { ru: 'пилот', id: 'Pilot' },
          { ru: 'пилот (женщина)', id: 'Pilot (wanita)' }, { ru: 'журналист', id: 'Jurnalis' },
          { ru: 'медсестра', id: 'Perawat' }, { ru: 'архитектор', id: 'Arsitek' }
        ]
      },
      emotions: {
        title: 'Emosi', icon: '😊',
        vocab: [
          { ru: 'счастливый', id: 'Bahagia' }, { ru: 'грустный', id: 'Sedih' },
          { ru: 'злой', id: 'Marah' }, { ru: 'удивлённый', id: 'Terkejut' },
          { ru: 'разочарованный', id: 'Kecewa' }, { ru: 'гордый', id: 'Bangga' },
          { ru: 'любопытный', id: 'Penasaran' }, { ru: 'довольный', id: 'Puas' },
          { ru: 'обеспокоенный', id: 'Khawatir' }, { ru: 'взволнованный', id: 'Gugup' },
          { ru: 'растерянный', id: 'Bingung' }, { ru: 'смелый', id: 'Pemberani' },
          { ru: 'трусливый', id: 'Penakut' }, { ru: 'влюблённый', id: 'Jatuh cinta' },
          { ru: 'ревнивый', id: 'Cemburu' }, { ru: 'виноватый', id: 'Bersalah' }
        ]
      },
      verbConjugations: {
        title: 'Konjugasi Verba', icon: '📝',
        vocab: [
          { ru: 'я есть', id: 'Saya adalah' }, { ru: 'ты есть', id: 'Kamu adalah' },
          { ru: 'он/она есть', id: 'Dia adalah' }, { ru: 'мы есть', id: 'Kami adalah' },
          { ru: 'я имею', id: 'Saya memiliki' }, { ru: 'ты имеешь', id: 'Kamu memiliki' },
          { ru: 'он/она имеет', id: 'Dia memiliki' }, { ru: 'я буду', id: 'Saya akan' },
          { ru: 'я могу', id: 'Saya bisa' }, { ru: 'ты можешь', id: 'Kamu bisa' },
          { ru: 'я должен', id: 'Saya harus' }, { ru: 'я хочу', id: 'Saya mau' },
          { ru: 'я иду', id: 'Saya pergi' }, { ru: 'ты идёшь', id: 'Kamu pergi' },
          { ru: 'я прихожу', id: 'Saya datang' }, { ru: 'я делаю', id: 'Saya membuat' },
          { ru: 'я говорю', id: 'Saya berkata' }, { ru: 'я даю', id: 'Saya memberi' },
          { ru: 'я беру', id: 'Saya mengambil' }, { ru: 'я вижу', id: 'Saya melihat' },
          { ru: 'я знаю', id: 'Saya tahu' }, { ru: 'я верю', id: 'Saya percaya' },
          { ru: 'я работаю', id: 'Saya bekerja' }, { ru: 'я учусь', id: 'Saya belajar' },
          { ru: 'я играю', id: 'Saya bermain' }, { ru: 'я помогаю', id: 'Saya membantu' }
        ]
      },
      bodyParts: {
        title: 'Bagian Tubuh', icon: '🫁',
        vocab: [
          { ru: 'голова', id: 'Kepala' }, { ru: 'лицо', id: 'Wajah' },
          { ru: 'глаз', id: 'Mata' }, { ru: 'нос', id: 'Hidung' },
          { ru: 'рот', id: 'Mulut' }, { ru: 'губа', id: 'Bibir' },
          { ru: 'зуб', id: 'Gigi' }, { ru: 'язык', id: 'Lidah' },
          { ru: 'ухо', id: 'Telinga' }, { ru: 'шея', id: 'Leher' },
          { ru: 'плечо', id: 'Bahu' }, { ru: 'рука', id: 'Tangan' },
          { ru: 'палец', id: 'Jari' }, { ru: 'грудь', id: 'Dada' },
          { ru: 'живот', id: 'Perut' }, { ru: 'спина', id: 'Punggung' },
          { ru: 'колено', id: 'Lutut' }, { ru: 'ступня', id: 'Kaki' },
          { ru: 'сердце', id: 'Jantung' }, { ru: 'мозг', id: 'Otak' }
        ]
      },
      clothing: {
        title: 'Pakaian', icon: '👕',
        vocab: [
          { ru: 'платье', id: 'Gaun' }, { ru: 'брюки', id: 'Celana' },
          { ru: 'рубашка', id: 'Kemeja' }, { ru: 'куртка', id: 'Jaket' },
          { ru: 'обувь', id: 'Sepatu' }, { ru: 'носки', id: 'Kaus kaki' },
          { ru: 'шляпа', id: 'Topi' }, { ru: 'очки', id: 'Kacamata' },
          { ru: 'ремень', id: 'Ikat pinggang' }, { ru: 'галстук', id: 'Dasi' },
          { ru: 'свитер', id: 'Sweter' }, { ru: 'пальто', id: 'Mantel' },
          { ru: 'перчатки', id: 'Sarung tangan' }, { ru: 'шарф', id: 'Syal' }
        ]
      },
      house: {
        title: 'Rumah', icon: '🏠',
        vocab: [
          { ru: 'дом', id: 'Rumah' }, { ru: 'комната', id: 'Kamar' },
          { ru: 'кухня', id: 'Dapur' }, { ru: 'ванная', id: 'Kamar mandi' },
          { ru: 'дверь', id: 'Pintu' }, { ru: 'окно', id: 'Jendela' },
          { ru: 'стол', id: 'Meja' }, { ru: 'стул', id: 'Kursi' },
          { ru: 'кровать', id: 'Tempat tidur' }, { ru: 'диван', id: 'Sofa' },
          { ru: 'шкаф', id: 'Lemari' }, { ru: 'полка', id: 'Rak' },
          { ru: 'ключ', id: 'Kunci' }, { ru: 'зеркало', id: 'Cermin' },
          { ru: 'лестница', id: 'Tangga' }, { ru: 'сад', id: 'Kebun' }
        ]
      },
      foodExtended: {
        title: 'Makanan Lanjutan', icon: '🍷',
        vocab: [
          { ru: 'яблоко', id: 'Apel' }, { ru: 'груша', id: 'Pir' },
          { ru: 'вишня', id: 'Ceri' }, { ru: 'клубника', id: 'Stroberi' },
          { ru: 'виноград', id: 'Anggur' }, { ru: 'апельсин', id: 'Jeruk' },
          { ru: 'лимон', id: 'Lemon' }, { ru: 'ананас', id: 'Nanas' },
          { ru: 'манго', id: 'Mangga' }, { ru: 'мёд', id: 'Madu' },
          { ru: 'варенье', id: 'Selai' }, { ru: 'горчица', id: 'Mustard' },
          { ru: 'уксус', id: 'Cuka' }, { ru: 'мука', id: 'Tepung' },
          { ru: 'оливковое масло', id: 'Minyak zaitun' }, { ru: 'сливки', id: 'Krim' }
        ]
      },
      technology: {
        title: 'Teknologi', icon: '💻',
        vocab: [
          { ru: 'компьютер', id: 'Komputer' }, { ru: 'мобильный телефон', id: 'HP' },
          { ru: 'планшет', id: 'Tablet' }, { ru: 'интернет', id: 'Internet' },
          { ru: 'Wi-Fi', id: 'Wifi' }, { ru: 'программное обеспечение', id: 'Perangkat lunak' },
          { ru: 'оборудование', id: 'Perangkat keras' }, { ru: 'экран', id: 'Layar' },
          { ru: 'клавиатура', id: 'Keyboard' }, { ru: 'мышь', id: 'Mouse' },
          { ru: 'принтер', id: 'Printer' }, { ru: 'камера', id: 'Kamera' },
          { ru: 'пароль', id: 'Password' }, { ru: 'браузер', id: 'Browser' },
          { ru: 'электронная почта', id: 'Email' }, { ru: 'приложение', id: 'Aplikasi' }
        ]
      },
      transportation: {
        title: 'Transportasi', icon: '🚗',
        vocab: [
          { ru: 'автомобиль', id: 'Mobil' }, { ru: 'автобус', id: 'Bus' },
          { ru: 'поезд', id: 'Kereta api' }, { ru: 'такси', id: 'Taksi' },
          { ru: 'самолёт', id: 'Pesawat' }, { ru: 'корабль', id: 'Kapal' },
          { ru: 'велосипед', id: 'Sepeda' }, { ru: 'мотоцикл', id: 'Motor' },
          { ru: 'шоссе', id: 'Jalan tol' }, { ru: 'вокзал', id: 'Stasiun' },
          { ru: 'аэропорт', id: 'Bandara' }, { ru: 'светофор', id: 'Lampu lalu lintas' },
          { ru: 'водительское удостоверение', id: 'SIM' }, { ru: 'бензин', id: 'Bensin' }
        ]
      },
      travel: {
        title: 'Perjalanan', icon: '✈️',
        vocab: [
          { ru: 'отпуск', id: 'Liburan' }, { ru: 'путешествие', id: 'Perjalanan' },
          { ru: 'отель', id: 'Hotel' }, { ru: 'жильё', id: 'Akomodasi' },
          { ru: 'паспорт', id: 'Paspor' }, { ru: 'чемодан', id: 'Koper' },
          { ru: 'билет', id: 'Tiket' }, { ru: 'бронирование', id: 'Reservasi' },
          { ru: 'туристическая информация', id: 'Pariwisata' }, { ru: 'сувенир', id: 'Oleh-oleh' },
          { ru: 'достопримечательность', id: 'Tempat wisata' }, { ru: 'пляж', id: 'Pantai' },
          { ru: 'горы', id: 'Gunung' }, { ru: 'виза', id: 'Visa' }
        ]
      }
    },
    achievements: [
      { id: 'first_quiz', title: 'Kuis Pertama', description: 'Selesaikan kuis pertama', icon: '🎯', condition: (stats) => stats.quizzesCompleted >= 1 },
      { id: 'quiz_master', title: 'Ahli Kuis', description: 'Selesaikan 10 kuis', icon: '🏆', condition: (stats) => stats.quizzesCompleted >= 10 },
      { id: 'quiz_champion', title: 'Juara Kuis', description: 'Selesaikan 50 kuis', icon: '👑', condition: (stats) => stats.quizzesCompleted >= 50 },
      { id: 'perfect_score', title: 'Skor Sempurna', description: 'Dapat skor 100% dalam kuis', icon: '💯', condition: (stats) => stats.perfectScores >= 1 },
      { id: 'perfect_10', title: 'Sempurna 10x', description: 'Dapat skor 100% sebanyak 10 kali', icon: '⭐', condition: (stats) => stats.perfectScores >= 10 },
      { id: 'flashcard_beginner', title: 'Pemula Flashcard', description: 'Lihat 10 kartu flashcard', icon: '🃏', condition: (stats) => stats.flashcardsViewed >= 10 },
      { id: 'flashcard_master', title: 'Ahli Flashcard', description: 'Lihat 100 kartu flashcard', icon: '🎰', condition: (stats) => stats.flashcardsViewed >= 100 },
      { id: 'flashcard_expert', title: 'Pakar Flashcard', description: 'Lihat 500 kartu flashcard', icon: '📚', condition: (stats) => stats.flashcardsViewed >= 500 },
      { id: 'vocabulary_100', title: 'Kolektor Kata', description: 'Pelajari 100 kata', icon: '📝', condition: (stats) => stats.wordsLearned >= 100 },
      { id: 'vocabulary_500', title: 'Master Kosakata', description: 'Pelajari 500 kata', icon: '📖', condition: (stats) => stats.wordsLearned >= 500 },
      { id: 'vocabulary_1000', title: 'Koleksi Besar', description: 'Pelajari 1000 kata', icon: '🎓', condition: (stats) => stats.wordsLearned >= 1000 },
      { id: 'xp_100', title: 'Pengalaman 100', description: 'Kumpulkan 100 XP', icon: '✨', condition: (stats) => stats.totalXP >= 100 },
      { id: 'xp_500', title: 'Pengalaman 500', description: 'Kumpulkan 500 XP', icon: '🌟', condition: (stats) => stats.totalXP >= 500 },
      { id: 'xp_1000', title: 'Pengalaman 1000', description: 'Kumpulkan 1000 XP', icon: '💫', condition: (stats) => stats.totalXP >= 1000 },
      { id: 'xp_5000', title: 'Pengalaman 5000', description: 'Kumpulkan 5000 XP', icon: '🔥', condition: (stats) => stats.totalXP >= 5000 },
      { id: 'level_5', title: 'Level 5', description: 'Capai level 5', icon: '🏅', condition: (stats) => stats.level >= 5 },
      { id: 'level_10', title: 'Level 10', description: 'Capai level 10', icon: '🥇', condition: (stats) => stats.level >= 10 },
      { id: 'level_20', title: 'Level 20', description: 'Capai level 20', icon: '🎖️', condition: (stats) => stats.level >= 20 },
      { id: 'streak_3', title: 'Streak 3 Hari', description: 'Belajar 3 hari berturut-turut', icon: '📅', condition: (stats) => stats.streak >= 3 },
      { id: 'streak_7', title: 'Streak 7 Hari', description: 'Belajar 7 hari berturut-turut', icon: '📆', condition: (stats) => stats.streak >= 7 },
      { id: 'streak_30', title: 'Streak 30 Hari', description: 'Belajar 30 hari berturut-turut', icon: '🗓️', condition: (stats) => stats.streak >= 30 },
      { id: 'all_categories', title: 'Semua Kategori', description: 'Coba semua kategori kuis', icon: '🗂️', condition: (stats) => stats.categoriesTried >= 16 },
      { id: 'speed_demon', title: 'Iblis Kecepatan', description: 'Selesaikan kuis dalam waktu kurang dari 30 detik', icon: '⚡', condition: (stats) => stats.fastestQuiz <= 30 },
      { id: 'consistent', title: 'Konsisten', description: 'Selesaikan 10 kuis tanpa salah', icon: '🎯', condition: (stats) => stats.perfectStreak >= 10 },
      { id: 'night_owl', title: 'Burung Hantu', description: 'Belajar setelah jam 10 malam', icon: '🦉', condition: (stats) => stats.nightStudy >= 1 },
      { id: 'early_bird', title: 'Burung Pagi', description: 'Belajar sebelum jam 6 pagi', icon: '🐦', condition: (stats) => stats.earlyStudy >= 1 },
      { id: 'explorer', title: 'Penjelajah', description: 'Gunakan semua fitur aplikasi', icon: '🧭', condition: (stats) => stats.featuresUsed >= 8 },
      { id: 'social', title: 'Sosial', description: 'Ekspor data 1 kali', icon: '📤', condition: (stats) => stats.exports >= 1 },
      { id: 'collector', title: 'Kolektor', description: 'Impor data 1 kali', icon: '📥', condition: (stats) => stats.imports >= 1 },
      { id: 'perfectionist', title: 'Perfeksionis', description: 'Dapat 100% di 5 kuis berbeda', icon: '💎', condition: (stats) => stats.perfectScores >= 5 },
      { id: 'polyglot', title: 'Polyglot', description: 'Pelajari 3 bahasa berbeda', icon: '🌍', condition: (stats) => stats.languagesStudied >= 3 },
      { id: 'daily_quest', title: 'Kuis Harian', description: 'Selesaikan kuis harian', icon: '📋', condition: (stats) => stats.dailyQuests >= 1 },
      { id: 'weekend_warrior', title: 'Pejuang Akhir Pekan', description: 'Belajar di akhir pekan', icon: '⚔️', condition: (stats) => stats.weekendStudy >= 1 },
      { id: 'master_grammar', title: 'Pakar Tata Bahasa', description: 'Selesaikan kuis konjugasi 5 kali', icon: '📐', condition: (stats) => stats.grammarQuizzes >= 5 },
      { id: 'cyrillic_master', title: 'Master Aksara Kiril', description: 'Pelajari semua huruf Kiril', icon: '🔤', condition: (stats) => stats.cyrillicMastered >= 1 }
    ]
  };
