const CONTENT_DATA = {
  vocabulary: {
    salam: [
      { de: 'Hallo', id: 'Halo', note: 'informal' },
      { de: 'Guten Tag', id: 'Selamat siang', note: 'formal' },
      { de: 'Guten Morgen', id: 'Selamat pagi' },
      { de: 'Guten Abend', id: 'Selamat malam' },
      { de: 'Auf Wiedersehen', id: 'Sampai jumpa', note: 'formal' },
      { de: 'Tschüss', id: 'Dah/Bye', note: 'informal' },
      { de: 'Danke', id: 'Terima kasih' },
      { de: 'Bitte', id: 'Tolong/Sama-sama' },
      { de: 'Entschuldigung', id: 'Maaf/Permisi' },
      { de: 'Ja', id: 'Ya' },
      { de: 'Nein', id: 'Tidak' },
      { de: 'Wie geht es Ihnen?', id: 'Apa kabar? (formal)' },
      { de: 'Wie geht es dir?', id: 'Apa kabar? (informal)' },
      { de: 'Mir geht es gut', id: 'Saya baik-baik saja' },
      { de: 'Ich heiße...', id: 'Nama saya...' },
      { de: 'Freut mich', id: 'Senang bertemu Anda' },
      { de: 'Auf Wiederhören', id: 'Sampai jumpa (telepon)' },
      { de: 'Gute Nacht', id: 'Selamat tidur' },
      { de: 'Tschüssi', id: 'Bye (cute/informal)' },
      { de: 'Bis bald', id: 'Sampai nanti' },
      { de: 'Bis morgen', id: 'Sampai besok' },
      { de: 'Willkommen', id: 'Selamat datang' },
      { de: 'Herzlich willkommen', id: 'Selamat datang (hangat)' },
      { de: 'Schönen Tag noch', id: 'Selamat menikmati hari' },
      { de: 'Guten Appetit', id: 'Selamat menikmati makanan' },
      { de: 'Prost', id: 'Bersulang' },
      { de: 'Herzlichen Glückwunsch', id: 'Selamat' },
      { de: 'Alles Gute', id: 'Semoga yang terbaik' },
      { de: 'Viel Erfolg', id: 'Semoga sukses' },
      { de: 'Gute Besserung', id: 'Semoga cepat sembuh' }
    ],
    angka: [
      { de: 'eins', id: '1' }, { de: 'zwei', id: '2' }, { de: 'drei', id: '3' },
      { de: 'vier', id: '4' }, { de: 'fünf', id: '5' }, { de: 'sechs', id: '6' },
      { de: 'sieben', id: '7' }, { de: 'acht', id: '8' }, { de: 'neun', id: '9' },
      { de: 'zehn', id: '10' }, { de: 'elf', id: '11' }, { de: 'zwölf', id: '12' },
      { de: 'dreizehn', id: '13' }, { de: 'vierzehn', id: '14' }, { de: 'fünfzehn', id: '15' },
      { de: 'sechzehn', id: '16' }, { de: 'siebzehn', id: '17' },
      { de: 'achtzehn', id: '18' }, { de: 'neunzehn', id: '19' },
      { de: 'zwanzig', id: '20' }, { de: 'dreißig', id: '30' },
      { de: 'vierzig', id: '40' }, { de: 'fünfzig', id: '50' },
      { de: 'sechzig', id: '60' }, { de: 'siebzig', id: '70' },
      { de: 'achtzig', id: '80' }, { de: 'neunzig', id: '90' }, { de: 'hundert', id: '100' }
    ],
    hari: [
      { de: 'Montag', id: 'Senin' }, { de: 'Dienstag', id: 'Selasa' },
      { de: 'Mittwoch', id: 'Rabu' }, { de: 'Donnerstag', id: 'Kamis' },
      { de: 'Freitag', id: 'Jumat' }, { de: 'Samstag', id: 'Sabtu' },
      { de: 'Sonntag', id: 'Minggu' }
    ],
    warna: [
      { de: 'rot', id: 'Merah' }, { de: 'blau', id: 'Biru' },
      { de: 'grün', id: 'Hijau' }, { de: 'gelb', id: 'Kuning' },
      { de: 'schwarz', id: 'Hitam' }, { de: 'weiß', id: 'Putih' },
      { de: 'grau', id: 'Abu-abu' }, { de: 'orange', id: 'Oranye' },
      { de: 'rosa', id: 'Merah muda' }, { de: 'braun', id: 'Cokelat' },
      { de: 'lila', id: 'Ungu' }, { de: 'golden', id: 'Emas' },
      { de: 'silbern', id: 'Perak' }, { de: 'hellblau', id: 'Biru muda' },
      { de: 'dunkelblau', id: 'Biru tua' }
    ],
    ganti: [
      { de: 'ich', id: 'Saya' }, { de: 'du', id: 'Kamu (informal)' },
      { de: 'er', id: 'Dia (lk)' }, { de: 'sie', id: 'Dia (pr)' },
      { de: 'es', id: 'Dia (netral)' }, { de: 'wir', id: 'Kami/Kita' },
      { de: 'ihr', id: 'Kalian (informal)' }, { de: 'sie/Sie', id: 'Mereka/Anda (formal)' },
      { de: 'mich', id: 'Saya (objekt)' }, { de: 'dich', id: 'Kamu (objekt)' },
      { de: 'ihm', id: 'Dia (objek maskulin/netral)' }, { de: 'ihr', id: 'Dia (objek feminin)' },
      { de: 'uns', id: 'Kami (objekt)' }, { de: 'euch', id: 'Kalian (objekt)' },
      { de: 'mein', id: 'Milik saya' }, { de: 'dein', id: 'Milik kamu' },
      { de: 'sein', id: 'Milik dia (lk)' }, { de: 'ihr', id: 'Milik dia (pr)' },
      { de: 'unser', id: 'Milik kami' }, { de: 'euer', id: 'Milik kalian' }
    ],
    keluarga: [
      { de: 'die Mutter', id: 'Ibu', note: 'feminin' },
      { de: 'der Vater', id: 'Ayah', note: 'maskulin' },
      { de: 'die Schwester', id: 'Saudari', note: 'feminin' },
      { de: 'der Bruder', id: 'Saudara laki-laki', note: 'maskulin' },
      { de: 'die Tochter', id: 'Anak perempuan', note: 'feminin' },
      { de: 'der Sohn', id: 'Anak laki-laki', note: 'maskulin' },
      { de: 'die Großmutter', id: 'Nenek', note: 'feminin' },
      { de: 'der Großvater', id: 'Kakek', note: 'maskulin' },
      { de: 'die Eltern', id: 'Orang tua', note: 'jamak' },
      { de: 'die Familie', id: 'Keluarga', note: 'feminin' },
      { de: 'die Tante', id: 'Bibi', note: 'feminin' },
      { de: 'der Onkel', id: 'Paman', note: 'maskulin' },
      { de: 'die Cousine', id: 'Sepupu (pr)', note: 'feminin' },
      { de: 'der Cousin', id: 'Sepupu (lk)', note: 'maskulin' },
      { de: 'die Großeltern', id: 'Kakek & Nenek', note: 'jamak' }
    ],
    makanan: [
      { de: 'das Brot', id: 'Roti', note: 'netral' },
      { de: 'das Wasser', id: 'Air', note: 'netral' },
      { de: 'der Kaffee', id: 'Kopi', note: 'maskulin' },
      { de: 'die Milch', id: 'Susu', note: 'feminin' },
      { de: 'der Käse', id: 'Keju', note: 'maskulin' },
      { de: 'der Apfel', id: 'Apel', note: 'maskulin' },
      { de: 'das Fleisch', id: 'Daging', note: 'netral' },
      { de: 'der Fisch', id: 'Ikan', note: 'maskulin' },
      { de: 'der Reis', id: 'Nasi', note: 'maskulin' },
      { de: 'der Zucker', id: 'Gula', note: 'maskulin' },
      { de: 'das Salz', id: 'Garam', note: 'netral' },
      { de: 'der Wein', id: 'Anggur (minuman)', note: 'maskulin' },
      { de: 'das Bier', id: 'Bir', note: 'netral' },
      { de: 'der Tee', id: 'Teh', note: 'maskulin' },
      { de: 'die Suppe', id: 'Sup', note: 'feminin' },
      { de: 'der Kuchen', id: 'Kue', note: 'maskulin' },
      { de: 'die Butter', id: 'Mentega', note: 'feminin' },
      { de: 'das Ei', id: 'Telur', note: 'netral' },
      { de: 'die Kartoffel', id: 'Kentang', note: 'feminin' },
      { de: 'die Tomate', id: 'Tomat', note: 'feminin' }
    ],
    tempat: [
      { de: 'die Schule', id: 'Sekolah', note: 'feminin' },
      { de: 'das Haus', id: 'Rumah', note: 'netral' },
      { de: 'der Laden', id: 'Toko', note: 'maskulin' },
      { de: 'die Straße', id: 'Jalan', note: 'feminin' },
      { de: 'das Krankenhaus', id: 'Rumah sakit', note: 'netral' },
      { de: 'die Bibliothek', id: 'Perpustakaan', note: 'feminin' },
      { de: 'das Restaurant', id: 'Restoran', note: 'netral' },
      { de: 'der Bahnhof', id: 'Stasiun', note: 'maskulin' },
      { de: 'das Hotel', id: 'Hotel', note: 'netral' },
      { de: 'die Bank', id: 'Bank', note: 'feminin' },
      { de: 'der Park', id: 'Taman', note: 'maskulin' },
      { de: 'der Supermarkt', id: 'Supermarket', note: 'maskulin' },
      { de: 'die Apotheke', id: 'Apotek', note: 'feminin' },
      { de: 'das Postamt', id: 'Kantor pos', note: 'netral' },
      { de: 'die Kirche', id: 'Gereja', note: 'feminin' },
      { de: 'das Kino', id: 'Bioskop', note: 'netral' },
      { de: 'der Markt', id: 'Pasar', note: 'maskulin' },
      { de: 'die Universität', id: 'Universitas', note: 'feminin' },
      { de: 'das Museum', id: 'Museum', note: 'netral' },
      { de: 'die Tankstelle', id: 'Stasiun pengisian bahan bakar', note: 'feminin' }
    ],
    profesi: [
      { de: 'der Arzt', id: 'Dokter (lk)', note: 'maskulin' },
      { de: 'die Ärztin', id: 'Dokter (pr)', note: 'feminin' },
      { de: 'der Lehrer', id: 'Guru (lk)', note: 'maskulin' },
      { de: 'die Lehrerin', id: 'Guru (pr)', note: 'feminin' },
      { de: 'der Ingenieur', id: 'Insinyur', note: 'maskulin' },
      { de: 'der Student', id: 'Mahasiswa (lk)', note: 'maskulin' },
      { de: 'die Studentin', id: 'Mahasiswa (pr)', note: 'feminin' },
      { de: 'der Polizist', id: 'Polisi (lk)', note: 'maskulin' },
      { de: 'die Polizistin', id: 'Polisi (pr)', note: 'feminin' },
      { de: 'der Koch', id: 'Koki (lk)', note: 'maskulin' },
      { de: 'die Köchin', id: 'Koki (pr)', note: 'feminin' },
      { de: 'der Künstler', id: 'Seniman', note: 'maskulin' },
      { de: 'der Journalist', id: 'Jurnalis', note: 'maskulin' },
      { de: 'der Fahrer', id: 'Sopir', note: 'maskulin' },
      { de: 'der Verkäufer', id: 'Penjual (lk)', note: 'maskulin' },
      { de: 'der Kellner', id: 'Pelayan (lk)', note: 'maskulin' },
      { de: 'der Briefträger', id: 'Tukang pos', note: 'maskulin' },
      { de: 'der Soldat', id: 'Tentara', note: 'maskulin' },
      { de: 'der Feuerwehrmann', id: 'Pemadam kebakaran', note: 'maskulin' },
      { de: 'der Anwalt', id: 'Pengacara', note: 'maskulin' }
    ],
    emosi: [
      { de: 'glücklich', id: 'Senang' }, { de: 'traurig', id: 'Sedih' },
      { de: 'müde', id: 'Lelah' }, { de: 'wütend', id: 'Marah' },
      { de: 'ängstlich', id: 'Takut' }, { de: 'überrascht', id: 'Terkejut' },
      { de: 'ruhig', id: 'Tenang' }, { de: 'aufgeregt', id: 'Antusias' },
      { de: 'verliebt', id: 'Jatuh cinta' }, { de: 'eifersüchtig', id: 'Cemburu' },
      { de: 'stolz', id: 'Bangga' }, { de: 'schüchtern', id: 'Pemalu' },
      { de: 'verlegen', id: 'Memalukan' }, { de: 'selbstbewusst', id: 'Percaya diri' },
      { de: 'enttäuscht', id: 'Kecewa' }, { de: 'besorgt', id: 'Khawatir' },
      { de: 'einsam', id: 'Kesepian' }, { de: 'begeistert', id: 'Antusias' },
      { de: 'zufrieden', id: 'Puas' }, { de: 'nervös', id: 'Gugup' }
    ],
    verbes: [
      { de: 'sein', id: 'Adalah/menjadi' }, { de: 'haben', id: 'Memiliki' },
      { de: 'gehen', id: 'Pergi' }, { de: 'machen', id: 'Melakukan' },
      { de: 'können', id: 'Bisa' }, { de: 'wollen', id: 'Mau' },
      { de: 'müssen', id: 'Harus' }, { de: 'sagen', id: 'Berkata' },
      { de: 'sehen', id: 'Melihat' }, { de: 'kommen', id: 'Datang' },
      { de: 'fahren', id: 'Pergi (dengan kendaraan)' }, { de: 'ankommen', id: 'Tiba' },
      { de: 'eingehen', id: 'Masuk' }, { de: 'ausgehen', id: 'Keluar' },
      { de: 'steigen', id: 'Naik' }, { de: 'fallen', id: 'Turun/Jatuh' },
      { de: 'öffnen', id: 'Membuka' }, { de: 'schließen', id: 'Menutup' },
      { de: 'geben', id: 'Memberi' }, { de: 'nehmen', id: 'Mengambil' }
    ]
  },
    bodyParts: [
      { de: 'der Kopf', id: 'Kepala', note: 'maskulin' },
      { de: 'die Haare', id: 'Rambut', note: 'feminin' },
      { de: 'die Stirn', id: 'Dahi', note: 'feminin' },
      { de: 'die Augen', id: 'Mata', note: 'feminin' },
      { de: 'die Nase', id: 'Hidung', note: 'feminin' },
      { de: 'die Ohren', id: 'Telinga', note: 'feminin' },
      { de: 'der Mund', id: 'Mulut', note: 'maskulin' },
      { de: 'die Lippen', id: 'Bibir', note: 'feminin' },
      { de: 'die Zähne', id: 'Gigi', note: 'feminin' },
      { de: 'die Zunge', id: 'Lidah', note: 'feminin' },
      { de: 'das Kinn', id: 'Dagu', note: 'netral' },
      { de: 'die Wange', id: 'Pipi', note: 'feminin' },
      { de: 'der Hals', id: 'Leher', note: 'maskulin' },
      { de: 'die Schultern', id: 'Bahu', note: 'feminin' },
      { de: 'der Arm', id: 'Lengan', note: 'maskulin' },
      { de: 'der Ellbogen', id: 'Siku', note: 'maskulin' },
      { de: 'das Handgelenk', id: 'Pergelangan tangan', note: 'netral' },
      { de: 'die Hand', id: 'Tangan', note: 'feminin' },
      { de: 'die Finger', id: 'Jari-jari', note: 'maskulin' },
      { de: 'die Brust', id: 'Dada', note: 'feminin' },
      { de: 'der Bauch', id: 'Perut', note: 'maskulin' },
      { de: 'der Rücken', id: 'Punggung', note: 'maskulin' },
      { de: 'die Taille', id: 'Pinggang', note: 'feminin' },
      { de: 'die Hüften', id: 'Pinggul', note: 'feminin' },
      { de: 'der Oberschenkel', id: 'Paha', note: 'maskulin' },
      { de: 'das Knie', id: 'Lutut', note: 'netral' },
      { de: 'die Wade', id: 'Betis', note: 'feminin' },
      { de: 'der Knöchel', id: 'Pergelangan kaki', note: 'maskulin' },
      { de: 'der Fuß', id: 'Kaki', note: 'maskulin' },
      { de: 'die Füße', id: 'Kaki (jamak)', note: 'feminin' },
      { de: 'die Zehen', id: 'Jari kaki', note: 'feminin' },
      { de: 'das Herz', id: 'Jantung', note: 'netral' },
      { de: 'die Lungen', id: 'Paru-paru', note: 'feminin' },
      { de: 'die Leber', id: 'Hati', note: 'feminin' }
    ],
    clothing: [
      { de: 'die Hose', id: 'Celana panjang', note: 'feminin' },
      { de: 'der Rock', id: 'Rok', note: 'maskulin' },
      { de: 'das Hemd', id: 'Kemeja', note: 'netral' },
      { de: 'das Kleid', id: 'Gaun/Baju', note: 'netral' },
      { de: 'das T-Shirt', id: 'Kaos', note: 'netral' },
      { de: 'der Pullover', id: 'Sweater', note: 'maskulin' },
      { de: 'die Jacke', id: 'Jaket', note: 'feminin' },
      { de: 'der Mantel', id: 'Mantel', note: 'maskulin' },
      { de: 'der Anzug', id: 'Setelan', note: 'maskulin' },
      { de: 'die Krawatte', id: 'Dasi', note: 'feminin' },
      { de: 'der Gürtel', id: 'Ikat pinggang', note: 'maskulin' },
      { de: 'die Schuhe', id: 'Sepatu', note: 'feminin' },
      { de: 'die Stiefel', id: 'Boots', note: 'feminin' },
      { de: 'die Sandalen', id: 'Sandal', note: 'feminin' },
      { de: 'die Socken', id: 'Kaos kaki', note: 'feminin' },
      { de: 'der Hut', id: 'Topi', note: 'maskulin' },
      { de: 'die Brille', id: 'Kacamata', note: 'feminin' },
      { de: 'der Schal', id: 'Syal', note: 'maskulin' },
      { de: 'die Handschuhe', id: 'Sarung tangan', note: 'feminin' },
      { de: 'die Mütze', id: 'Topi hangat', note: 'feminin' },
      { de: 'die Jeans', id: 'Jeans', note: 'feminin' },
      { de: 'der Kragen', id: 'Kerah', note: 'maskulin' },
      { de: 'die Manschetten', id: 'Manset', note: 'feminin' },
      { de: 'die Tasche', id: 'Tas', note: 'feminin' },
      { de: 'der Rucksack', id: 'Tas punggung', note: 'maskulin' },
      { de: 'der Ring', id: 'Cincin', note: 'maskulin' },
      { de: 'die Kette', id: 'Kalung', note: 'feminin' },
      { de: 'die Armbanduhr', id: 'Jam tangan', note: 'feminin' },
      { de: 'der Anhänger', id: 'Gantungan', note: 'maskulin' },
      { de: 'die Ohrringe', id: 'Anting-anting', note: 'feminin' },
      { de: 'der Schmuck', id: 'Perhiasan', note: 'maskulin' },
      { de: 'der Schlafanzug', id: 'Piama', note: 'maskulin' },
      { de: 'die Unterwäsche', id: 'Pakaian dalam', note: 'feminin' },
      { de: 'der Badeanzug', id: 'Baju renang', note: 'maskulin' },
      { de: 'die Sportschuhe', id: 'Sneakers', note: 'feminin' }
    ],
    house: [
      { de: 'das Schlafzimmer', id: 'Kamar tidur', note: 'netral' },
      { de: 'das Badezimmer', id: 'Kamar mandi', note: 'netral' },
      { de: 'die Küche', id: 'Dapur', note: 'feminin' },
      { de: 'das Wohnzimmer', id: 'Ruang tamu', note: 'netral' },
      { de: 'der Flur', id: 'Koridor', note: 'maskulin' },
      { de: 'der Keller', id: 'Ruang bawah tanah', note: 'maskulin' },
      { de: 'der Dachboden', id: 'Loteng', note: 'maskulin' },
      { de: 'die Garage', id: 'Garasi', note: 'feminin' },
      { de: 'der Garten', id: 'Taman', note: 'maskulin' },
      { de: 'die Terrasse', id: 'Teras', note: 'feminin' },
      { de: 'der Balkon', id: 'Balkon', note: 'maskulin' },
      { de: 'die Tür', id: 'Pintu', note: 'feminin' },
      { de: 'das Fenster', id: 'Jendela', note: 'netral' },
      { de: 'die Wand', id: 'Dinding', note: 'feminin' },
      { de: 'die Decke', id: 'Langit-langit', note: 'feminin' },
      { de: 'der Boden', id: 'Lantai', note: 'maskulin' },
      { de: 'die Treppe', id: 'Tangga', note: 'feminin' },
      { de: 'das Geländer', id: 'Pegangan tangga', note: 'netral' },
      { de: 'der Ziegelstein', id: 'Bata', note: 'maskulin' },
      { de: 'das Dach', id: 'Atap', note: 'netral' },
      { de: 'der Kamin', id: 'Perapian', note: 'maskulin' },
      { de: 'der Zaun', id: 'Pagar', note: 'maskulin' },
      { de: 'das Gebäude', id: 'Gedung', note: 'netral' },
      { de: 'die Wohnung', id: 'Apartemen', note: 'feminin' },
      { de: 'die Einrichtung', id: 'Perabotan', note: 'feminin' },
      { de: 'der Schrank', id: 'Lemari', note: 'maskulin' },
      { de: 'das Sofa', id: 'Sofa', note: 'netral' },
      { de: 'der Tisch', id: 'Meja', note: 'maskulin' },
      { de: 'der Stuhl', id: 'Kursi', note: 'maskulin' },
      { de: 'das Bett', id: 'Tempat tidur', note: 'netral' },
      { de: 'die Matratze', id: 'Matras', note: 'feminin' },
      { de: 'das Kopfkissen', id: 'Bantal', note: 'netral' },
      { de: 'die Decke', id: 'Selimut', note: 'feminin' },
      { de: 'die Bettwäsche', id: 'Sprei', note: 'feminin' },
      { de: 'der Spiegel', id: 'Cermin', note: 'maskulin' },
      { de: 'das Regal', id: 'Rak', note: 'netral' },
      { de: 'die Schublade', id: 'Laci', note: 'feminin' },
      { de: 'der Teppich', id: 'Karpet', note: 'maskulin' },
      { de: 'die Gardine', id: 'Gorden', note: 'feminin' },
      { de: 'die Lampe', id: 'Lampu', note: 'feminin' }
    ],
    nature: [
      { de: 'die Sonne', id: 'Matahari', note: 'feminin' },
      { de: 'der Mond', id: 'Bulan', note: 'maskulin' },
      { de: 'die Sterne', id: 'Bintang', note: 'feminin' },
      { de: 'der Himmel', id: 'Langit', note: 'maskulin' },
      { de: 'das Meer', id: 'Laut', note: 'netral' },
      { de: 'der Ozean', id: 'Samudra', note: 'maskulin' },
      { de: 'der Fluss', id: 'Sungai', note: 'maskulin' },
      { de: 'der See', id: 'Danau', note: 'maskulin' },
      { de: 'der Berg', id: 'Gunung', note: 'maskulin' },
      { de: 'der Hügel', id: 'Bukit', note: 'maskulin' },
      { de: 'das Tal', id: 'Lembah', note: 'netral' },
      { de: 'die Wüste', id: 'Gurun', note: 'feminin' },
      { de: 'der Wald', id: 'Hutan', note: 'maskulin' },
      { de: 'die Ebene', id: 'Dataran', note: 'feminin' },
      { de: 'der Bach', id: 'Aliran sungai', note: 'maskulin' },
      { de: 'die Insel', id: 'Pulau', note: 'feminin' },
      { de: 'der Strand', id: 'Pantai', note: 'maskulin' },
      { de: 'die Wellen', id: 'Ombak', note: 'feminin' },
      { de: 'der Sand', id: 'Pasir', note: 'maskulin' },
      { de: 'die Felsen', id: 'Batu karang', note: 'feminin' },
      { de: 'der Wind', id: 'Angin', note: 'maskulin' },
      { de: 'der Regen', id: 'Hujan', note: 'maskulin' },
      { de: 'der Schnee', id: 'Salju', note: 'maskulin' },
      { de: 'der Hagel', id: 'Hujan es', note: 'maskulin' },
      { de: 'der Regenbogen', id: 'Pelangi', note: 'maskulin' },
      { de: 'die Wolke', id: 'Awan', note: 'feminin' },
      { de: 'das Gewitter', id: 'Badai petir', note: 'netral' },
      { de: 'der Nebel', id: 'Kabut', note: 'maskulin' },
      { de: 'der Frost', id: 'Embun beku', note: 'maskulin' },
      { de: 'das Eis', id: 'Es', note: 'netral' },
      { de: 'die Erde', id: 'Tanah/Bumi', note: 'feminin' },
      { de: 'der Staub', id: 'Debu', note: 'maskulin' },
      { de: 'das Gras', id: 'Rumput', note: 'netral' },
      { de: 'die Blätter', id: 'Daun', note: 'feminin' },
      { de: 'das Moos', id: 'Lumut', note: 'netral' }
    ],
    animalsDomestic: [
      { de: 'der Hund', id: 'Anjing', note: 'maskulin' },
      { de: 'die Katze', id: 'Kucing', note: 'feminin' },
      { de: 'das Kaninchen', id: 'Kelinci', note: 'netral' },
      { de: 'der Vogel', id: 'Burung', note: 'maskulin' },
      { de: 'der Goldfisch', id: 'Ikan mas', note: 'maskulin' },
      { de: 'der Hamster', id: 'Hamster', note: 'maskulin' },
      { de: 'die Schildkröte', id: 'Kura-kura', note: 'feminin' },
      { de: 'das Pferd', id: 'Kuda', note: 'netral' },
      { de: 'die Henne', id: 'Ayam betina', note: 'feminin' },
      { de: 'der Hahn', id: 'Ayam jantan', note: 'maskulin' },
      { de: 'die Ente', id: 'Bebek', note: 'feminin' },
      { de: 'die Ziege', id: 'Kambing', note: 'feminin' },
      { de: 'das Schaf', id: 'Domba', note: 'netral' },
      { de: 'das Schwein', id: 'Babi', note: 'netral' },
      { de: 'der Esel', id: 'Keledai', note: 'maskulin' }
    ],
    animalsWild: [
      { de: 'der Löwe', id: 'Singa', note: 'maskulin' },
      { de: 'der Tiger', id: 'Harimau', note: 'maskulin' },
      { de: 'der Elefant', id: 'Gajah', note: 'maskulin' },
      { de: 'die Giraffe', id: 'Jerapah', note: 'feminin' },
      { de: 'das Zebra', id: 'Zebra', note: 'netral' },
      { de: 'der Gorilla', id: 'Gorila', note: 'maskulin' },
      { de: 'der Bär', id: 'Beruang', note: 'maskulin' },
      { de: 'der Wolf', id: 'Serigala', note: 'maskulin' },
      { de: 'der Fuchs', id: 'Rubah', note: 'maskulin' },
      { de: 'der Hirsch', id: 'Rusa', note: 'maskulin' },
      { de: 'die Schlange', id: 'Ular', note: 'feminin' },
      { de: 'das Krokodil', id: 'Buaya', note: 'netral' },
      { de: 'das Nilpferd', id: 'Kudanil', note: 'netral' },
      { de: 'das Nashorn', id: 'Badak', note: 'netral' },
      { de: 'der Affe', id: 'Monyet', note: 'maskulin' },
      { de: 'das Känguru', id: 'Kanguru', note: 'netral' },
      { de: 'das Koala', id: 'Koala', note: 'netral' },
      { de: 'die Hyäne', id: 'Hiena', note: 'feminin' },
      { de: 'der Leopard', id: 'Macan tutul', note: 'maskulin' },
      { de: 'der Gepard', id: 'Cheetah', note: 'maskulin' },
      { de: 'der Schakal', id: 'Jakal', note: 'maskulin' },
      { de: 'der Geier', id: 'Burung nasar', note: 'maskulin' },
      { de: 'das Wildschwein', id: 'Babi hutan', note: 'netral' },
      { de: 'der Waschbär', id: 'Rakun', note: 'maskulin' },
      { de: 'der Igel', id: 'Landak', note: 'maskulin' }
    ],
    animalsSea: [
      { de: 'der Wal', id: 'Paus', note: 'maskulin' },
      { de: 'der Delfin', id: 'Lumba-lumba', note: 'maskulin' },
      { de: 'der Hai', id: 'Hiu', note: 'maskulin' },
      { de: 'die Meeresschildkröte', id: 'Penyu', note: 'feminin' },
      { de: 'der Seehund', id: 'Anjing laut', note: 'maskulin' },
      { de: 'der Seebär', id: 'Singa laut', note: 'maskulin' },
      { de: 'die Krabbe', id: 'Kepiting', note: 'feminin' },
      { de: 'die Garnele', id: 'Udang', note: 'feminin' },
      { de: 'die Auster', id: 'Tiram', note: 'feminin' },
      { de: 'die Muschel', id: 'Kerang', note: 'feminin' }
    ],
    insects: [
      { de: 'die Biene', id: 'Lebah', note: 'feminin' },
      { de: 'die Ameise', id: 'Semut', note: 'feminin' },
      { de: 'der Schmetterling', id: 'Kupu-kupu', note: 'maskulin' },
      { de: 'die Raupe', id: 'Ulat', note: 'feminin' },
      { de: 'der Marienkäfer', id: 'Kepik', note: 'maskulin' },
      { de: 'der Käfer', id: 'Kumbang', note: 'maskulin' },
      { de: 'die Fliege', id: 'Lalat', note: 'feminin' },
      { de: 'die Mücke', id: 'Nyamuk', note: 'feminin' },
      { de: 'die Motte', id: 'Ngengat', note: 'feminin' },
      { de: 'die Heuschrecke', id: 'Belalang', note: 'feminin' },
      { de: 'die Grille', id: 'Jangkrik', note: 'feminin' },
      { de: 'die Spinne', id: 'Laba-laba', note: 'feminin' },
      { de: 'der Skorpion', id: 'Kalajengking', note: 'maskulin' },
      { de: 'die Wanze', id: 'Kutu busuk', note: 'feminin' },
      { de: 'die Libelle', id: 'Capung', note: 'feminin' }
    ],
    foodExtended: [
      { de: 'das Croissant', id: 'Croissant', note: 'netral' },
      { de: 'die Brezel', id: 'Pretzel', note: 'feminin' },
      { de: 'der Kuchen', id: 'Kue', note: 'maskulin' },
      { de: 'die Crêpe', id: 'Kue dadar', note: 'feminin' },
      { de: 'der Waffel', id: 'Waffle', note: 'maskulin' },
      { de: 'die Quiche', id: 'Kue pai asin', note: 'feminin' },
      { de: 'der Ziegenkäse', id: 'Keju kambing', note: 'maskulin' },
      { de: 'der Camembert', id: 'Keju Camembert', note: 'maskulin' },
      { de: 'der Bratwurst', id: 'Sosis panggang', note: 'feminin' },
      { de: 'das Sauerkraut', id: 'Kubis asam', note: 'netral' },
      { de: 'die Kartoffelsalat', id: 'Salad kentang', note: 'feminin' },
      { de: 'das Schnitzel', id: 'Schnitzel', note: 'netral' },
      { de: 'die Brezeln', id: 'Pretzel', note: 'feminin' },
      { de: 'der Apfelstrudel', id: 'Strudel apel', note: 'maskulin' },
      { de: 'die Spätzle', id: 'Spätzle', note: 'feminin' },
      { de: 'der Käsespätzle', id: 'Spätzle keju', note: 'maskulin' },
      { de: 'die Wiener Schnitzel', id: 'Schnitzel Wina', note: 'feminin' },
      { de: 'das Brot', id: 'Roti', note: 'netral' },
      { de: 'der Brötchen', id: 'Roti kecil', note: 'maskulin' },
      { de: 'die Semmel', id: 'Roti gulung', note: 'feminin' },
      { de: 'der Reis', id: 'Nasi', note: 'maskulin' },
      { de: 'die Nudeln', id: 'Mie/Pasta', note: 'feminin' },
      { de: 'die Tomatensuppe', id: 'Sup tomat', note: 'feminin' },
      { de: 'der Obstsalat', id: 'Salad buah', note: 'maskulin' },
      { de: 'der Gemüsesalat', id: 'Salad sayuran', note: 'maskulin' },
      { de: 'der Apfel', id: 'Apel', note: 'maskulin' },
      { de: 'die Birne', id: 'Pir', note: 'feminin' },
      { de: 'die Pfirsich', id: 'Persik', note: 'feminin' },
      { de: 'die Kirsche', id: 'Ceri', note: 'feminin' },
      { de: 'die Erdbeere', id: 'Stroberi', note: 'feminin' },
      { de: 'die Blaubeere', id: 'Blueberry', note: 'feminin' },
      { de: 'die Himbeere', id: 'Raspberry', note: 'feminin' },
      { de: 'die Traube', id: 'Anggur buah', note: 'feminin' },
      { de: 'die Melone', id: 'Melon', note: 'feminin' },
      { de: 'die Orange', id: 'Jeruk', note: 'feminin' },
      { de: 'die Zitrone', id: 'Lemon', note: 'feminin' },
      { de: 'die Ananas', id: 'Nanas', note: 'feminin' },
      { de: 'die Mango', id: 'Mangga', note: 'feminin' },
      { de: 'die Kiwi', id: 'Kiwi', note: 'feminin' },
      { de: 'die Pflaume', id: 'Plum', note: 'feminin' },
      { de: 'die Mandel', id: 'Almond', note: 'feminin' },
      { de: 'die Walnuss', id: 'Kenari', note: 'feminin' },
      { de: 'die Haselnuss', id: 'Hazelnut', note: 'feminin' },
      { de: 'die Erdnuss', id: 'Kacang tanah', note: 'feminin' },
      { de: 'die Pistazie', id: 'Kacang pistachio', note: 'feminin' },
      { de: 'die Cashewnuss', id: 'Kacang mete', note: 'feminin' },
      { de: 'die Marmelade', id: 'Selai', note: 'feminin' },
      { de: 'der Honig', id: 'Madu', note: 'maskulin' },
      { de: 'die Butter', id: 'Mentega', note: 'feminin' },
      { de: 'das Mehl', id: 'Tepung', note: 'netral' },
      { de: 'das Olivenöl', id: 'Minyak zaitun', note: 'netral' },
      { de: 'der Essig', id: 'Cuka', note: 'maskulin' },
      { de: 'der Senf', id: 'Mustard', note: 'maskulin' },
      { de: 'die Ketchup', id: 'Kecap', note: 'feminin' },
      { de: 'die Mayonnaise', id: 'Mayones', note: 'feminin' },
      { de: 'die Sahne', id: 'Krim', note: 'feminin' }
    ],
    transportation: [
      { de: 'das Auto', id: 'Mobil', note: 'netral' },
      { de: 'der LKW', id: 'Truk', note: 'maskulin' },
      { de: 'der Bus', id: 'Bus', note: 'maskulin' },
      { de: 'die U-Bahn', id: 'Kereta bawah tanah', note: 'feminin' },
      { de: 'der Zug', id: 'Kereta api', note: 'maskulin' },
      { de: 'die Straßenbahn', id: 'Trem', note: 'feminin' },
      { de: 'das Taxi', id: 'Taksi', note: 'netral' },
      { de: 'das Flugzeug', id: 'Pesawat', note: 'netral' },
      { de: 'das Schiff', id: 'Kapal', note: 'netral' },
      { de: 'das Fahrrad', id: 'Sepeda', note: 'netral' },
      { de: 'das Motorrad', id: 'Motor', note: 'netral' },
      { de: 'der Roller', id: 'Skuter', note: 'maskulin' },
      { de: 'die Fähre', id: 'Kapal feri', note: 'feminin' },
      { de: 'die Yacht', id: 'Kapal pesiar', note: 'feminin' },
      { de: 'die Seilbahn', id: 'Kereta gantung', note: 'feminin' },
      { de: 'der Hochgeschwindigkeitszug', id: 'Kereta cepat', note: 'maskulin' },
      { de: 'der Hubschrauber', id: 'Helikopter', note: 'maskulin' },
      { de: 'der Luftschiff', id: 'Balon udara', note: 'netral' },
      { de: 'das U-Boot', id: 'Kapal selam', note: 'netral' },
      { de: 'der Frachter', id: 'Kapal kargo', note: 'maskulin' },
      { de: 'das Krankenwagen', id: 'Ambulans', note: 'netral' },
      { de: 'der Feuerwehrwagen', id: 'Truk pemadam', note: 'maskulin' },
      { de: 'der Müllwagen', id: 'Truk sampah', note: 'maskulin' },
      { de: 'der Traktor', id: 'Traktor', note: 'maskulin' },
      { de: 'das Fahrzeug', id: 'Kendaraan', note: 'netral' },
      { de: 'die Autobahn', id: 'Jalan tol', note: 'feminin' },
      { de: 'die Straße', id: 'Jalan raya', note: 'feminin' },
      { de: 'die Kreuzung', id: 'Perempatan', note: 'feminin' },
      { de: 'der Kreisverkehr', id: 'Bundaran', note: 'maskulin' },
      { de: 'der Parkplatz', id: 'Parkir', note: 'maskulin' },
      { de: 'der Fußgängerweg', id: 'Penyeberangan pejalan kaki', note: 'maskulin' },
      { de: 'die Ampel', id: 'Lampu lalu lintas', note: 'feminin' },
      { de: 'das Verkehrszeichen', id: 'Rambu lalu lintas', note: 'netral' },
      { de: 'der Sicherheitsgurt', id: 'Sabuk pengaman', note: 'maskulin' },
      { de: 'der Führerschein', id: 'Surat izin mengemudi', note: 'maskulin' },
      { de: 'das Benzin', id: 'Bensin', note: 'netral' },
      { de: 'der Tank', id: 'Tangki', note: 'maskulin' },
      { de: 'der Motor', id: 'Mesin', note: 'maskulin' },
      { de: 'das Rad', id: 'Roda', note: 'netral' }
    ],
    technology: [
      { de: 'der Computer', id: 'Komputer', note: 'maskulin' },
      { de: 'der Bildschirm', id: 'Layar', note: 'maskulin' },
      { de: 'die Tastatur', id: 'Keyboard', note: 'feminin' },
      { de: 'die Maus', id: 'Mouse', note: 'feminin' },
      { de: 'der Drucker', id: 'Printer', note: 'maskulin' },
      { de: 'das Telefon', id: 'Telepon', note: 'netral' },
      { de: 'das Handy', id: 'HP', note: 'netral' },
      { de: 'das Tablet', id: 'Tablet', note: 'netral' },
      { de: 'das Internet', id: 'Internet', note: 'netral' },
      { de: 'das Netzwerk', id: 'Jaringan', note: 'netral' },
      { de: 'die Verbindung', id: 'Koneksi', note: 'feminin' },
      { de: 'das WLAN', id: 'Wifi', note: 'netral' },
      { de: 'die Anwendung', id: 'Aplikasi', note: 'feminin' },
      { de: 'die Software', id: 'Perangkat lunak', note: 'feminin' },
      { de: 'die Hardware', id: 'Perangkat keras', note: 'feminin' },
      { de: 'der Touchscreen', id: 'Layar sentuh', note: 'maskulin' },
      { de: 'der Prozessor', id: 'Prosesor', note: 'maskulin' },
      { de: 'der Speicher', id: 'Memori', note: 'maskulin' },
      { de: 'die Festplatte', id: 'Hard disk', note: 'feminin' },
      { de: 'der USB-Stick', id: 'Flashdisk', note: 'maskulin' },
      { de: 'die Kamera', id: 'Kamera', note: 'feminin' },
      { de: 'das Video', id: 'Video', note: 'netral' },
      { de: 'das Foto', id: 'Foto', note: 'netral' },
      { de: 'die Kopfhörer', id: 'Headset', note: 'feminin' },
      { de: 'die Ohropax', id: 'Earphone', note: 'feminin' },
      { de: 'die Lautsprecher', id: 'Speaker', note: 'feminin' },
      { de: 'der Ladekabel', id: 'Charger', note: 'maskulin' },
      { de: 'der Akku', id: 'Baterai', note: 'maskulin' },
      { de: 'der Startbildschirm', id: 'Home screen', note: 'maskulin' },
      { de: 'das Passwort', id: 'Password', note: 'netral' },
      { de: 'die E-Mail-Adresse', id: 'Alamat email', note: 'feminin' },
      { de: 'der Browser', id: 'Browser', note: 'maskulin' },
      { de: 'die Webseite', id: 'Halaman web', note: 'feminin' },
      { de: 'die Website', id: 'Situs web', note: 'feminin' },
      { de: 'der Blog', id: 'Blog', note: 'maskulin' },
      { de: 'das soziale Netzwerk', id: 'Jejaring sosial', note: 'netral' },
      { de: 'die Nachricht', id: 'Pesan', note: 'feminin' },
      { de: 'die E-Mail', id: 'Email', note: 'feminin' },
      { de: 'der Anhang', id: 'Lampiran', note: 'maskulin' },
      { de: 'herunterladen', id: 'Mengunduh' },
      { de: 'aktualisieren', id: 'Memperbarui' },
      { de: 'speichern', id: 'Menyimpan' },
      { de: 'senden', id: 'Mengirim' },
      { de: 'löschen', id: 'Menghapus' },
      { de: 'drucken', id: 'Mencetak' }
    ],
    schoolEducation: [
      { de: 'die Schule', id: 'Sekolah', note: 'feminin' },
      { de: 'die Universität', id: 'Universitas', note: 'feminin' },
      { de: 'das Klassenzimmer', id: 'Kelas', note: 'netral' },
      { de: 'die Tafel', id: 'Papan tulis', note: 'feminin' },
      { de: 'der Schreibtisch', id: 'Meja guru', note: 'maskulin' },
      { de: 'das Buch', id: 'Buku', note: 'netral' },
      { de: 'das Heft', id: 'Buku tulis', note: 'netral' },
      { de: 'der Stift', id: 'Pena', note: 'maskulin' },
      { de: 'der Bleistift', id: 'Pensil', note: 'maskulin' },
      { de: 'der Radiergummi', id: 'Penghapus', note: 'maskulin' },
      { de: 'das Lineal', id: 'Penggaris', note: 'netral' },
      { de: 'der Rucksack', id: 'Tas punggung', note: 'maskulin' },
      { de: 'der Kugelschreiber', id: 'Pulpen', note: 'maskulin' },
      { de: 'der Marker', id: 'Spidol', note: 'maskulin' },
      { de: 'die Kreide', id: 'Kapur tulis', note: 'feminin' },
      { de: 'die Gleichung', id: 'Persamaan matematika', note: 'feminin' },
      { de: 'der Bruch', id: 'Pecahan', note: 'maskulin' },
      { de: 'das Ergebnis', id: 'Hasil', note: 'netral' },
      { de: 'der Durchschnitt', id: 'Nilai rata-rata', note: 'maskulin' },
      { de: 'die Note', id: 'Nilai', note: 'feminin' },
      { de: 'die Hausaufgabe', id: 'PR', note: 'feminin' },
      { de: 'die Prüfung', id: 'Ujian', note: 'feminin' },
      { de: 'der Kurs', id: 'Kursus', note: 'maskulin' },
      { de: 'das Fach', id: 'Mata pelajaran', note: 'netral' },
      { de: 'das Deutsch', id: 'Bahasa Jerman', note: 'netral' },
      { de: 'die Mathematik', id: 'Matematika', note: 'feminin' },
      { de: 'die Physik', id: 'Fisika', note: 'feminin' },
      { de: 'die Chemie', id: 'Kimia', note: 'feminin' },
      { de: 'die Biologie', id: 'Biologi', note: 'feminin' },
      { de: 'die Geschichte', id: 'Sejarah', note: 'feminin' },
      { de: 'die Geografie', id: 'Geografi', note: 'feminin' },
      { de: 'das Englisch', id: 'Bahasa Inggris', note: 'netral' },
      { de: 'die Kunst', id: 'Seni', note: 'feminin' },
      { de: 'die Musik', id: 'Musik', note: 'feminin' },
      { de: 'der Sport', id: 'Pendidikan jasmani', note: 'maskulin' },
      { de: 'die Philosophie', id: 'Filsafat', note: 'feminin' },
      { de: 'die Wirtschaft', id: 'Ekonomi', note: 'feminin' },
      { de: 'das Semester', id: 'Semester', note: 'netral' },
      { de: 'der Campus', id: 'Kampus', note: 'maskulin' },
      { de: 'die Bibliothek', id: 'Perpustakaan', note: 'feminin' },
      { de: 'die Mensa', id: 'Kantin', note: 'feminin' },
      { de: 'die Immatrikulation', id: 'Pendaftaran', note: 'feminin' },
      { de: 'der Abschluss', id: 'Gelar', note: 'maskulin' },
      { de: 'die Abschlussarbeit', id: 'Tesis', note: 'feminin' },
      { de: 'das Praktikum', id: 'Magang', note: 'netral' },
      { de: 'der Professor', id: 'Guru besar', note: 'maskulin' },
      { de: 'der Rektor', id: 'Rektor', note: 'maskulin' },
      { de: 'der Schüler', id: 'Siswa', note: 'maskulin' },
      { de: 'der Mitschüler', id: 'Teman sekelas', note: 'maskulin' }
    ],
    workOffice: [
      { de: 'das Büro', id: 'Kantor', note: 'netral' },
      { de: 'die Besprechung', id: 'Rapat', note: 'feminin' },
      { de: 'der Chef', id: 'Atasan', note: 'maskulin' },
      { de: 'der Kollege', id: 'Rekan kerja', note: 'maskulin' },
      { de: 'das Gehalt', id: 'Gaji', note: 'netral' },
      { de: 'die Arbeit', id: 'Pekerjaan', note: 'feminin' },
      { de: 'der Vertrag', id: 'Kontrak', note: 'maskulin' },
      { de: 'der Urlaub', id: 'Liburan', note: 'maskulin' },
      { de: 'die Pause', id: 'Istirahat', note: 'feminin' },
      { de: 'der Feierabend', id: 'Akhir hari kerja', note: 'maskulin' },
      { de: 'das Vorstellungsgespräch', id: 'Wawancara kerja', note: 'netral' },
      { de: 'die Bewerbung', id: 'Lamaran kerja', note: 'feminin' },
      { de: 'der Lebenslauf', id: 'Curriculum vitae', note: 'maskulin' },
      { de: 'das Anschreiben', id: 'Surat motivasi', note: 'netral' },
      { de: 'die Beförderung', id: 'Promosi', note: 'feminin' },
      { de: 'die Kündigung', id: 'PHK', note: 'feminin' },
      { de: 'der Ruhestand', id: 'Pensiun', note: 'maskulin' },
      { de: 'die Abteilung', id: 'Departemen', note: 'feminin' },
      { de: 'das Projekt', id: 'Proyek', note: 'netral' },
      { de: 'der Erfolg', id: 'Keberhasilan', note: 'maskulin' },
      { de: 'die Leistung', id: 'Pencapaian', note: 'feminin' },
      { de: 'der Ehrgeiz', id: 'Ambisi', note: 'maskulin' },
      { de: 'die Bewertung', id: 'Penilaian', note: 'feminin' },
      { de: 'der Bonus', id: 'Bonus', note: 'maskulin' },
      { de: 'die Steuer', id: 'Pajak', note: 'feminin' },
      { de: 'die Kasse', id: 'Meja kasir', note: 'feminin' },
      { de: 'der Aktenschrank', id: 'Lemari arsip', note: 'maskulin' },
      { de: 'die Mappe', id: 'Map', note: 'feminin' }
    ],
    sportsActivities: [
      { de: 'der Fußball', id: 'Sepak bola', note: 'maskulin' },
      { de: 'das Basketball', id: 'Basket', note: 'netral' },
      { de: 'das Tennis', id: 'Tenis', note: 'netral' },
      { de: 'das Volleyball', id: 'Voli', note: 'netral' },
      { de: 'die Leichtathletik', id: 'Atletik', note: 'feminin' },
      { de: 'das Schwimmen', id: 'Renang', note: 'netral' },
      { de: 'das Rugby', id: 'Ragbi', note: 'netral' },
      { de: 'das Handball', id: 'Bola tangan', note: 'netral' },
      { de: 'das Fechten', id: 'Anggar', note: 'netral' },
      { de: 'das Reiten', id: 'Berkuda', note: 'netral' },
      { de: 'das Golf', id: 'Golf', note: 'netral' },
      { de: 'das Skifahren', id: 'Ski', note: 'netral' },
      { de: 'das Snowboarden', id: 'Snowboard', note: 'netral' },
      { de: 'das Surfen', id: 'Selancar', note: 'netral' },
      { de: 'das Judo', id: 'Judo', note: 'netral' },
      { de: 'das Karate', id: 'Karate', note: 'netral' },
      { de: 'das Boxen', id: 'Tinju', note: 'netral' },
      { de: 'das Ringen', id: 'Gulat', note: 'netral' },
      { de: 'die Gymnastik', id: 'Senam', note: 'feminin' },
      { de: 'das Yoga', id: 'Yoga', note: 'netral' },
      { de: 'das Radfahren', id: 'Bersepeda', note: 'netral' },
      { de: 'das Gewichtheben', id: 'Angkat besi', note: 'netral' },
      { de: 'das Laufen', id: 'Lari', note: 'netral' },
      { de: 'das Wandern', id: 'Jalan kaki', note: 'netral' },
      { de: 'das Klettern', id: 'Panjat tebing', note: 'netral' },
      { de: 'das Tauchen', id: 'Selam', note: 'netral' },
      { de: 'das Segeln', id: 'Layar', note: 'netral' },
      { de: 'das Rudern', id: 'Mendayung', note: 'netral' },
      { de: 'das Kajakfahren', id: 'Kajak', note: 'netral' },
      { de: 'das Bogenschießen', id: 'Panahan', note: 'netral' },
      { de: 'das Schießen', id: 'Menembak', note: 'netral' },
      { de: 'das Eislaufen', id: 'Seluncur es', note: 'netral' },
      { de: 'das Eishockey', id: 'Hoki es', note: 'netral' },
      { de: 'das Baseball', id: 'Baseball', note: 'netral' },
      { de: 'das Cricket', id: 'Kriket', note: 'netral' },
      { de: 'das Badminton', id: 'Bulutangkis', note: 'netral' },
      { de: 'das Tischtennis', id: 'Pingpong', note: 'netral' },
      { de: 'das Bowling', id: 'Boling', note: 'netral' },
      { de: 'das Tanzen', id: 'Tari', note: 'netral' },
      { de: 'das Skateboardfahren', id: 'Skateboard', note: 'netral' },
      { de: 'das Inline-Skaten', id: 'Inline skate', note: 'netral' }
    ],
    hobbiesLeisure: [
      { de: 'das Lesen', id: 'Membaca', note: 'netral' },
      { de: 'das Schreiben', id: 'Menulis', note: 'netral' },
      { de: 'die Malerei', id: 'Melukis', note: 'feminin' },
      { de: 'das Zeichnen', id: 'Menggambar', note: 'netral' },
      { de: 'das Kino', id: 'Nonton film', note: 'netral' },
      { de: 'die Musik', id: 'Dengar musik', note: 'feminin' },
      { de: 'die Videospiele', id: 'Main game', note: 'feminin' },
      { de: 'die Fotografie', id: 'Fotografi', note: 'feminin' },
      { de: 'das Gärtnern', id: 'Berkebun', note: 'netral' },
      { de: 'das Nähen', id: 'Menjahit', note: 'netral' },
      { de: 'das Stricken', id: 'Merajut', note: 'netral' },
      { de: 'die Stickerei', id: 'Menyulam', note: 'feminin' },
      { de: 'das Heimwerken', id: 'DIY/perbaikan', note: 'netral' },
      { de: 'die Sammlung', id: 'Koleksi', note: 'feminin' },
      { de: 'das Modellbau', id: 'Model kit', note: 'maskulin' },
      { de: 'die Philatelie', id: 'Filateli (perangko)', note: 'feminin' },
      { de: 'die Aquaristik', id: 'Hobi ikan', note: 'feminin' },
      { de: 'das Boulespielen', id: 'Petanque', note: 'netral' },
      { de: 'das Schach', id: 'Catur', note: 'netral' },
      { de: 'die Kartenspiele', id: 'Main kartu', note: 'feminin' },
      { de: 'die Meditation', id: 'Meditasi', note: 'feminin' },
      { de: 'die Natur', id: 'Alam terbuka', note: 'feminin' },
      { de: 'die Wanderung', id: 'Hiking', note: 'feminin' },
      { de: 'das Picknick', id: 'Piknik', note: 'netral' },
      { de: 'das Campen', id: 'Berkemah', note: 'netral' },
      { de: 'das Angeln', id: 'Memancing', note: 'netral' },
      { de: 'die Jagd', id: 'Berburu', note: 'feminin' },
      { de: 'das Tanzen', id: 'Menari', note: 'netral' },
      { de: 'die Keramik', id: 'Keramik', note: 'feminin' }
    ],
    healthMedical: [
      { de: 'die Gesundheit', id: 'Kesehatan', note: 'feminin' },
      { de: 'die Krankheit', id: 'Penyakit', note: 'feminin' },
      { de: 'die Erkältung', id: 'Pilek', note: 'feminin' },
      { de: 'die Grippe', id: 'Flu', note: 'feminin' },
      { de: 'das Fieber', id: 'Demam', note: 'netral' },
      { de: 'der Husten', id: 'Batuk', note: 'maskulin' },
      { de: 'der Kopfschmerz', id: 'Sakit kepala', note: 'maskulin' },
      { de: 'der Rückenschmerz', id: 'Sakit punggung', note: 'maskulin' },
      { de: 'der Bauchschmerz', id: 'Sakit perut', note: 'maskulin' },
      { de: 'die Übelkeit', id: 'Mual', note: 'feminin' },
      { de: 'das Erbrechen', id: 'Muntah', note: 'netral' },
      { de: 'der Durchfall', id: 'Diare', note: 'maskulin' },
      { de: 'die Verstopfung', id: 'Sembelit', note: 'feminin' },
      { de: 'die Allergie', id: 'Alergi', note: 'feminin' },
      { de: 'das Asthma', id: 'Asma', note: 'netral' },
      { de: 'der Diabetes', id: 'Diabetes', note: 'maskulin' },
      { de: 'der Bluthochdruck', id: 'Hipertensi', note: 'maskulin' },
      { de: 'die Infektion', id: 'Infeksi', note: 'feminin' },
      { de: 'die Verletzung', id: 'Luka', note: 'feminin' },
      { de: 'die Narbe', id: 'Bekas luka', note: 'feminin' },
      { de: 'die Schürfwunde', id: 'Luka lecet', note: 'feminin' },
      { de: 'die Schnittwunde', id: 'Goresan', note: 'feminin' },
      { de: 'die Bluterguss', id: 'Memar', note: 'maskulin' },
      { de: 'die Schwellung', id: 'Bengkak', note: 'feminin' },
      { de: 'der Schwindel', id: 'Pusing', note: 'maskulin' },
      { de: 'die Schlaflosigkeit', id: 'Insomnia', note: 'feminin' },
      { de: 'die Müdigkeit', id: 'Kelelahan', note: 'feminin' },
      { de: 'der Stress', id: 'Stres', note: 'maskulin' },
      { de: 'die Depression', id: 'Depresi', note: 'feminin' },
      { de: 'die Angst', id: 'Kecemasan', note: 'feminin' },
      { de: 'die Behandlung', id: 'Perawatan', note: 'feminin' },
      { de: 'das Rezept', id: 'Resep', note: 'netral' },
      { de: 'das Antibiotikum', id: 'Antibiotik', note: 'netral' },
      { de: 'die Aspirin', id: 'Aspirin', note: 'feminin' },
      { de: 'die Salbe', id: 'Salep', note: 'feminin' },
      { de: 'der Verband', id: 'Perban', note: 'maskulin' },
      { de: 'die Spritze', id: 'Suntikan', note: 'feminin' },
      { de: 'die Untersuchung', id: 'Pemeriksaan', note: 'feminin' },
      { de: 'die Röntgenaufnahme', id: 'Rontgen', note: 'feminin' },
      { de: 'die Operation', id: 'Operasi', note: 'feminin' },
      { de: 'die Narkose', id: 'Anestesi', note: 'feminin' },
      { de: 'die Genesung', id: 'Penyembuhan', note: 'feminin' },
      { de: 'die Impfung', id: 'Vaksin', note: 'feminin' }
    ],
    professionsExtended: [
      { de: 'der Arzt', id: 'Dokter', note: 'maskulin' },
      { de: 'die Ärztin', id: 'Dokter (wanita)', note: 'feminin' },
      { de: 'der Anwalt', id: 'Pengacara', note: 'maskulin' },
      { de: 'die Anwältin', id: 'Pengacara (wanita)', note: 'feminin' },
      { de: 'der Ingenieur', id: 'Insinyur', note: 'maskulin' },
      { de: 'die Ingenieurin', id: 'Insinyur (wanita)', note: 'feminin' },
      { de: 'der Architekt', id: 'Arsitek', note: 'maskulin' },
      { de: 'die Architektin', id: 'Arsitek (wanita)', note: 'feminin' },
      { de: 'der Lehrer', id: 'Guru', note: 'maskulin' },
      { de: 'die Lehrerin', id: 'Guru (wanita)', note: 'feminin' },
      { de: 'der Professor', id: 'Profesor', note: 'maskulin' },
      { de: 'die Professorin', id: 'Profesor (wanita)', note: 'feminin' },
      { de: 'der Pilot', id: 'Pilot', note: 'maskulin' },
      { de: 'die Pilotin', id: 'Pilot (wanita)', note: 'feminin' },
      { de: 'der Polizist', id: 'Polisi', note: 'maskulin' },
      { de: 'die Polizistin', id: 'Polisi (wanita)', note: 'feminin' },
      { de: 'der Feuerwehrmann', id: 'Pemadam kebakaran', note: 'maskulin' },
      { de: 'die Feuerwehrfrau', id: 'Pemadam kebakaran (wanita)', note: 'feminin' },
      { de: 'der Krankenpfleger', id: 'Perawat', note: 'maskulin' },
      { de: 'die Krankenschwester', id: 'Perawat (wanita)', note: 'feminin' },
      { de: 'der Zahnarzt', id: 'Dokter gigi', note: 'maskulin' },
      { de: 'die Zahnärztin', id: 'Dokter gigi (wanita)', note: 'feminin' },
      { de: 'der Apotheker', id: 'Apoteker', note: 'maskulin' },
      { de: 'die Apothekerin', id: 'Apoteker (wanita)', note: 'feminin' },
      { de: 'der Journalist', id: 'Jurnalis', note: 'maskulin' },
      { de: 'die Journalistin', id: 'Jurnalis (wanita)', note: 'feminin' },
      { de: 'der Schriftsteller', id: 'Penulis', note: 'maskulin' },
      { de: 'die Schriftstellerin', id: 'Penulis (wanita)', note: 'feminin' },
      { de: 'der Künstler', id: 'Seniman', note: 'maskulin' },
      { de: 'die Künstlerin', id: 'Seniwati', note: 'feminin' },
      { de: 'der Musiker', id: 'Musisi', note: 'maskulin' },
      { de: 'die Musikerin', id: 'Musisi (wanita)', note: 'feminin' },
      { de: 'der Schauspieler', id: 'Aktor', note: 'maskulin' },
      { de: 'die Schauspielerin', id: 'Aktris', note: 'feminin' },
      { de: 'der Regisseur', id: 'Sutradara', note: 'maskulin' },
      { de: 'die Regisseurin', id: 'Sutradara (wanita)', note: 'feminin' },
      { de: 'der Koch', id: 'Koki', note: 'maskulin' },
      { de: 'die Köchin', id: 'Koki (wanita)', note: 'feminin' },
      { de: 'der Bäcker', id: 'Tukang roti', note: 'maskulin' },
      { de: 'die Bäckerin', id: 'Tukang roti (wanita)', note: 'feminin' },
      { de: 'der Metzger', id: 'Tukang daging', note: 'maskulin' },
      { de: 'die Metzgerin', id: 'Tukang daging (wanita)', note: 'feminin' },
      { de: 'der Friseur', id: 'Tukang cukur', note: 'maskulin' },
      { de: 'die Friseurin', id: 'Tukang cukur (wanita)', note: 'feminin' },
      { de: 'der Verkäufer', id: 'Penjual', note: 'maskulin' },
      { de: 'die Verkäuferin', id: 'Penjual (wanita)', note: 'feminin' },
      { de: 'der Kellner', id: 'Pelayan', note: 'maskulin' },
      { de: 'die Kellnerin', id: 'Pelayan (wanita)', note: 'feminin' },
      { de: 'der Bäcker', id: 'Tukang roti', note: 'maskulin' },
      { de: 'der Manager', id: 'Manajer', note: 'maskulin' },
      { de: 'die Managerin', id: 'Manajer (wanita)', note: 'feminin' },
      { de: 'der Sekretär', id: 'Sekretaris', note: 'maskulin' },
      { de: 'die Sekretärin', id: 'Sekretaris (wanita)', note: 'feminin' }
    ],
    cityPlaces: [
      { de: 'die Stadt', id: 'Kota', note: 'feminin' },
      { de: 'die Hauptstadt', id: 'Ibukota', note: 'feminin' },
      { de: 'das Dorf', id: 'Desa', note: 'netral' },
      { de: 'die Vorstadt', id: 'Pinggiran kota', note: 'feminin' },
      { de: 'der Stadtteil', id: 'Distrik kota', note: 'maskulin' },
      { de: 'das Rathaus', id: 'Balai kota', note: 'netral' },
      { de: 'die Kirche', id: 'Gereja', note: 'feminin' },
      { de: 'der Dom', id: 'Katedral', note: 'maskulin' },
      { de: 'die Kapelle', id: 'Kapel', note: 'feminin' },
      { de: 'das Museum', id: 'Museum', note: 'netral' },
      { de: 'die Galerie', id: 'Galeri', note: 'feminin' },
      { de: 'das Schloss', id: 'Istana', note: 'netral' },
      { de: 'die Burg', id: 'Benteng', note: 'feminin' },
      { de: 'der Park', id: 'Taman', note: 'maskulin' },
      { de: 'der Garten', id: 'Kebun', note: 'maskulin' },
      { de: 'der Spielplatz', id: 'Taman bermain', note: 'maskulin' },
      { de: 'die Schule', id: 'Sekolah', note: 'feminin' },
      { de: 'das Krankenhaus', id: 'Rumah sakit', note: 'netral' },
      { de: 'die Apotheke', id: 'Apotek', note: 'feminin' },
      { de: 'die Post', id: 'Kantor pos', note: 'feminin' },
      { de: 'die Bank', id: 'Bank', note: 'feminin' },
      { de: 'das Hotel', id: 'Hotel', note: 'netral' },
      { de: 'das Restaurant', id: 'Restoran', note: 'netral' },
      { de: 'die Bar', id: 'Bar', note: 'feminin' },
      { de: 'das Café', id: 'Kafe', note: 'netral' },
      { de: 'die Bäckerei', id: 'Toko roti', note: 'feminin' },
      { de: 'die Konditorei', id: 'Toko kue', note: 'feminin' },
      { de: 'die Metzgerei', id: 'Toko daging', note: 'feminin' },
      { de: 'der Supermarkt', id: 'Supermarket', note: 'maskulin' },
      { de: 'der Markt', id: 'Pasar', note: 'maskulin' },
      { de: 'das Kaufhaus', id: 'Toko serba ada', note: 'netral' },
      { de: 'die Bibliothek', id: 'Perpustakaan', note: 'feminin' },
      { de: 'das Theater', id: 'Teater', note: 'netral' },
      { de: 'die Oper', id: 'Opera', note: 'feminin' },
      { de: 'das Kino', id: 'Bioskop', note: 'netral' },
      { de: 'der Bahnhof', id: 'Stasiun kereta', note: 'maskulin' },
      { de: 'die Haltestelle', id: 'Halte bus', note: 'feminin' },
      { de: 'der Flughafen', id: 'Bandara', note: 'maskulin' },
      { de: 'die Brücke', id: 'Jembatan', note: 'feminin' },
      { de: 'der Turm', id: 'Menara', note: 'maskulin' },
      { de: 'das Denkmal', id: 'Monumen', note: 'netral' },
      { de: 'die Fontäne', id: 'Air mancur', note: 'feminin' },
      { de: 'der Brunnen', id: 'Sumur', note: 'maskulin' },
      { de: 'die Treppe', id: 'Tangga', note: 'feminin' },
      { de: 'der Aufzug', id: 'Lift', note: 'maskulin' },
      { de: 'die Straße', id: 'Jalan', note: 'feminin' },
      { de: 'der Weg', id: 'Jalan/Jalur', note: 'maskulin' },
      { de: 'das Schild', id: 'Rambu', note: 'netral' },
      { de: 'die Umnutzung', id: 'Reklame', note: 'feminin' },
      { de: 'die Fabrik', id: 'Pabrik', note: 'feminin' }
    ],
    weatherClimate: [
      { de: 'das Wetter', id: 'Cuaca', note: 'netral' },
      { de: 'das Klima', id: 'Iklim', note: 'netral' },
      { de: 'die Sonne', id: 'Matahari', note: 'feminin' },
      { de: 'der Regen', id: 'Hujan', note: 'maskulin' },
      { de: 'der Schnee', id: 'Salju', note: 'maskulin' },
      { de: 'der Wind', id: 'Angin', note: 'maskulin' },
      { de: 'die Wolke', id: 'Awan', note: 'feminin' },
      { de: 'der Nebel', id: 'Kabut', note: 'maskulin' },
      { de: 'das Gewitter', id: 'Badai', note: 'netral' },
      { de: 'der Blitz', id: 'Petir', note: 'maskulin' },
      { de: 'der Donner', id: 'Guntur', note: 'maskulin' },
      { de: 'der Regenbogen', id: 'Pelangi', note: 'maskulin' },
      { de: 'der Frost', id: 'Embun beku', note: 'maskulin' },
      { de: 'das Eis', id: 'Es', note: 'netral' },
      { de: 'die Hitze', id: 'Panas', note: 'feminin' },
      { de: 'die Kälte', id: 'Dingin', note: 'feminin' },
      { de: 'die Trockenheit', id: 'Kekeringan', note: 'feminin' },
      { de: 'die Feuchtigkeit', id: 'Kelembapan', note: 'feminin' },
      { de: 'der Sturm', id: 'Badai', note: 'maskulin' },
      { de: 'die Überschwemmung', id: 'Banjir', note: 'feminin' },
      { de: 'die Dürre', id: 'Kekeringan', note: 'feminin' },
      { de: 'der Sonnenschein', id: 'Sinar matahari', note: 'maskulin' },
      { de: 'die Temperatur', id: 'Suhu', note: 'feminin' },
      { de: 'der Grad', id: 'Derajat', note: 'maskulin' },
      { de: 'der Sommer', id: 'Musim panas', note: 'maskulin' },
      { de: 'der Winter', id: 'Musim dingin', note: 'maskulin' },
      { de: 'der Frühling', id: 'Musim semi', note: 'maskulin' },
      { de: 'der Herbst', id: 'Musim gugur', note: 'maskulin' }
    ],
    timeExtended: [
      { de: 'die Zeit', id: 'Waktu', note: 'feminin' },
      { de: 'die Sekunde', id: 'Detik', note: 'feminin' },
      { de: 'die Minute', id: 'Menit', note: 'feminin' },
      { de: 'die Stunde', id: 'Jam', note: 'feminin' },
      { de: 'der Morgen', id: 'Pagi', note: 'maskulin' },
      { de: 'der Vormittag', id: 'Sebelum siang', note: 'maskulin' },
      { de: 'das Mittag', id: 'Siang', note: 'netral' },
      { de: 'der Nachmittag', id: 'Setelah siang', note: 'maskulin' },
      { de: 'der Abend', id: 'Sore/Malam', note: 'maskulin' },
      { de: 'die Nacht', id: 'Malam', note: 'feminin' },
      { de: 'der Tag', id: 'Hari', note: 'maskulin' },
      { de: 'die Woche', id: 'Minggu', note: 'feminin' },
      { de: 'der Monat', id: 'Bulan', note: 'maskulin' },
      { de: 'das Jahr', id: 'Tahun', note: 'netral' },
      { de: 'das Jahrzehnt', id: 'Dekade', note: 'netral' },
      { de: 'das Jahrhundert', id: 'Abad', note: 'netral' },
      { de: 'das Jahrtausend', id: 'Milenium', note: 'netral' },
      { de: 'die Vergangenheit', id: 'Masa lalu', note: 'feminin' },
      { de: 'die Gegenwart', id: 'Masa kini', note: 'feminin' },
      { de: 'die Zukunft', id: 'Masa depan', note: 'feminin' },
      { de: 'der Frühanfang', id: 'Awal pagi', note: 'maskulin' },
      { de: 'die Eile', id: 'Terburu-buru', note: 'feminin' },
      { de: 'die Geduld', id: 'Kesabaran', note: 'feminin' },
      { de: 'die Stille', id: 'Keheningan', note: 'feminin' },
      { de: 'die Ruhe', id: 'Ketenangan', note: 'feminin' },
      { de: 'das Alter', id: 'Usia', note: 'netral' },
      { de: 'die Jugend', id: 'Masa muda', note: 'feminin' },
      { de: 'die Kindheit', id: 'Masa kecil', note: 'feminin' },
      { de: 'der Beginn', id: 'Awal', note: 'maskulin' },
      { de: 'das Ende', id: 'Akhir', note: 'netral' },
      { de: 'die Pause', id: 'Jeda', note: 'feminin' },
      { de: 'die Feier', id: 'Pesta', note: 'feminin' }
    ],
    directionsPositions: [
      { de: 'links', id: 'Kiri' },
      { de: 'rechts', id: 'Kanan' },
      { de: 'geradeaus', id: 'Lurus' },
      { de: 'oben', id: 'Atas' },
      { de: 'unten', id: 'Bawah' },
      { de: 'vorne', id: 'Depan' },
      { de: 'hinten', id: 'Belakang' },
      { de: 'neben', id: 'Di sebelah' },
      { de: 'gegenüber', id: 'Seberang' },
      { de: 'zwischen', id: 'Di antara' },
      { de: 'in der Nähe', id: 'Dekat' },
      { de: 'in der Ferne', id: 'Jauh' },
      { de: 'im Inneren', id: 'Di dalam' },
      { de: 'im Äußeren', id: 'Di luar' },
      { de: 'über', id: 'Di atas' },
      { de: 'unter', id: 'Di bawah' },
      { de: 'vor', id: 'Di depan' },
      { de: 'hinter', id: 'Di belakang' },
      { de: 'an', id: 'Di samping' },
      { de: 'auf', id: 'Di atas (permukaan)' },
      { de: 'aus', id: 'Dari dalam' },
      { de: 'nach', id: 'Ke arah' },
      { de: 'von', id: 'Dari' },
      { de: 'zu', id: 'Ke' },
      { de: 'mit', id: 'Bersama' },
      { de: 'ohne', id: 'Tanpa' },
      { de: 'gegen', id: 'Melawan' },
      { de: 'für', id: 'Untuk' },
      { de: 'um', id: 'Sekitar/Pada' },
      { de: 'um ... herum', id: 'Di sekitar' }
    ],
    quantitiesMeasurements: [
      { de: 'der Meter', id: 'Meter', note: 'maskulin' },
      { de: 'der Kilometer', id: 'Kilometer', note: 'maskulin' },
      { de: 'der Zentimeter', id: 'Sentimeter', note: 'maskulin' },
      { de: 'das Kilogramm', id: 'Kilogram', note: 'netral' },
      { de: 'das Gramm', id: 'Gram', note: 'netral' },
      { de: 'die Tonne', id: 'Ton', note: 'feminin' },
      { de: 'der Liter', id: 'Liter', note: 'maskulin' },
      { de: 'die Flasche', id: 'Botol', note: 'feminin' },
      { de: 'der Becher', id: 'Gelas', note: 'maskulin' },
      { de: 'das Glas', id: 'Gelas kaca', note: 'netral' },
      { de: 'die Tasse', id: 'Cangkir', note: 'feminin' },
      { de: 'der Löffel', id: 'Sendok', note: 'maskulin' },
      { de: 'die Gabel', id: 'Garpu', note: 'feminin' },
      { de: 'das Messer', id: 'Pisau', note: 'netral' },
      { de: 'die Schüssel', id: 'Mangkuk', note: 'feminin' },
      { de: 'der Teller', id: 'Piring', note: 'maskulin' },
      { de: 'das Tablett', id: 'Nampan', note: 'netral' },
      { de: 'der Topf', id: 'Panci', note: 'maskulin' },
      { de: 'die Pfanne', id: 'Wajan', note: 'feminin' },
      { de: 'der Kessel', id: 'Ketel', note: 'maskulin' },
      { de: 'die Mulde', id: 'Wadah', note: 'feminin' },
      { de: 'der Eimer', id: 'Ember', note: 'maskulin' },
      { de: 'der Eimer', id: 'Ember', note: 'maskulin' },
      { de: 'die Schaufel', id: 'Cangkul', note: 'feminin' },
      { de: 'der Besen', id: 'Sapu', note: 'maskulin' },
      { de: 'der Stiel', id: 'Tangkai', note: 'maskulin' },
      { de: 'der Korb', id: 'Keranjang', note: 'maskulin' },
      { de: 'die Box', id: 'Kotak', note: 'feminin' },
      { de: 'der Karton', id: 'Kardus', note: 'maskulin' },
      { de: 'die Dose', id: 'Kaleng', note: 'feminin' },
      { de: 'der Deckel', id: 'Tutup', note: 'maskulin' },
      { de: 'die Tüte', id: 'Tas belanja', note: 'feminin' },
      { de: 'die Verpackung', id: 'Kemasan', note: 'feminin' },
      { de: 'der Preis', id: 'Harga', note: 'maskulin' },
      { de: 'die Rechnung', id: 'Tagihan', note: 'feminin' },
      { de: 'der Rabatt', id: 'Diskon', note: 'maskulin' },
      { de: 'die MwSt.', id: 'PPN', note: 'feminin' },
      { de: 'die Trinkgeld', id: 'Tip', note: 'feminin' },
      { de: 'der Gesamtpreis', id: 'Total harga', note: 'maskulin' },
      { de: 'der Einzelpreis', id: 'Harga satuan', note: 'maskulin' }
    ],
    adjectivesDescriptions: [
      { de: 'groß', id: 'Besar/Tinggi' },
      { de: 'klein', id: 'Kecil' },
      { de: 'lang', id: 'Panjang' },
      { de: 'kurz', id: 'Pendek' },
      { de: 'breit', id: 'Lebar' },
      { de: 'schmal', id: 'Sempit' },
      { de: 'dick', id: 'Tebal' },
      { de: 'dünn', id: 'Tipis' },
      { de: 'schwer', id: 'Berat' },
      { de: 'leicht', id: 'Ringan' },
      { de: 'stark', id: 'Kuat' },
      { de: 'schwach', id: 'Lemah' },
      { de: 'schnell', id: 'Cepat' },
      { de: 'langsam', id: 'Lambat' },
      { de: 'alt', id: 'Tua/Lama' },
      { de: 'jung', id: 'Muda' },
      { de: 'neu', id: 'Baru' },
      { de: 'gut', id: 'Baik' },
      { de: 'schlecht', id: 'Buruk' },
      { de: 'schön', id: 'Cantik/Indah' },
      { de: 'hässlich', id: 'Jelek' },
      { de: 'sauber', id: 'Bersih' },
      { de: 'schmutzig', id: 'Kotor' },
      { de: 'trocken', id: 'Kering' },
      { de: 'nass', id: 'Basah' },
      { de: 'kalt', id: 'Dingin' },
      { de: 'warm', id: 'Hangat' },
      { de: 'heiß', id: 'Panas' },
      { de: 'frisch', id: 'Segar' },
      { de: 'müde', id: 'Lelah' },
      { de: 'wach', id: 'Sadar' },
      { de: 'satt', id: 'Kenyang' },
      { de: 'hungrig', id: 'Lapar' },
      { de: 'durstig', id: 'Haus' },
      { de: 'krank', id: 'Sakit' },
      { de: 'gesund', id: 'Sehat' },
      { de: 'glücklich', id: 'Bahagia' },
      { de: 'traurig', id: 'Sedih' },
      { de: 'lustig', id: 'Lucu' },
      { de: 'ernst', id: 'Serius' },
      { de: 'freundlich', id: 'Ramah' },
      { de: 'böse', id: 'Jahat' },
      { de: 'nett', id: 'Menyenangkan' },
      { de: 'bequem', id: 'Nyaman' },
      { de: 'bequem', id: 'Nyaman' },
      { de: 'praktisch', id: 'Praktis' },
      { de: 'einfach', id: 'Sederhana' },
      { de: 'schwierig', id: 'Sulit' },
      { de: 'kompliziert', id: 'Kompleks' },
      { de: 'fertig', id: 'Selesai' },
      { de: 'bereit', id: 'Siap' },
      { de: 'richtig', id: 'Benar' },
      { de: 'falsch', id: 'Salah' },
      { de: 'wichtig', id: 'Penting' },
      { de: 'wichtig', id: 'Penting' },
      { de: 'interessant', id: 'Menarik' },
      { de: 'langweilig', id: 'Membosankan' },
      { de: 'berühmt', id: 'Terkenal' },
      { de: 'besonders', id: 'Istimewa' },
      { de: 'normal', id: 'Normal' },
      { de: 'typisch', id: 'Tipikal' },
      { de: 'modern', id: 'Modern' },
      { de: 'altmodisch', id: 'Ketinggalan zaman' },
      { de: 'klassisch', id: 'Klasik' },
      { de: 'international', id: 'Internasional' },
      { de: 'nationale', id: 'Nasional' },
      { de: 'lokal', id: 'Lokal' },
      { de: 'global', id: 'Global' },
      { de: 'persönlich', id: 'Pribadi' },
      { de: 'privat', id: 'Privat' },
      { de: 'öffentlich', id: 'Publik' }
    ],
    verbsExtended: [
      { de: 'schlafen', id: 'Tidur' },
      { de: 'aufstehen', id: 'Bangun' },
      { de: 'frühstücken', id: 'Makan pagi' },
      { de: 'duschen', id: 'Mandi' },
      { de: 'sich anziehen', id: 'Berpakaian' },
      { de: 'sich ausziehen', id: 'Membuka pakaian' },
      { de: 'kochen', id: 'Memasak' },
      { de: 'backen', id: 'Memanggang' },
      { de: 'braten', id: 'Menggoreng' },
      { de: 'waschen', id: 'Mencuci' },
      { de: 'putzen', id: 'Membersihkan' },
      { de: 'staubsaugen', id: 'Menyedot debu' },
      { de: 'bügeln', id: 'Menggosok' },
      { de: 'fegen', id: 'Menyapu' },
      { de: 'wischen', id: 'Mengepel' },
      { de: 'einkaufen', id: 'Berbelanja' },
      { de: 'bezahlen', id: 'Membayar' },
      { de: 'sparen', id: 'Menabung' },
      { de: 'ausgeben', id: 'Menghabiskan' },
      { de: 'verdienen', id: 'Menghasilkan' },
      { de: 'arbeiten', id: 'Bekerja' },
      { de: 'lernen', id: 'Belajar' },
      { de: 'studieren', id: 'Belajar (kuliah)' },
      { de: 'lesen', id: 'Membaca' },
      { de: 'schreiben', id: 'Menulis' },
      { de: 'sprechen', id: 'Berbicara' },
      { de: 'reden', id: 'Bicara' },
      { de: 'zuhören', id: 'Mendengarkan' },
      { de: 'antworten', id: 'Menjawab' },
      { de: 'fragen', id: 'Bertanya' },
      { de: 'erzählen', id: 'Menceritakan' },
      { de: 'erklären', id: 'Menjelaskan' },
      { de: 'zeigen', id: 'Menunjukkan' },
      { de: 'suchen', id: 'Mencari' },
      { de: 'finden', id: 'Menemukan' },
      { de: 'verlieren', id: 'Kehilangan' },
      { de: 'gewinnen', id: 'Menang' },
      { de: 'kaufen', id: 'Membeli' },
      { de: 'verkaufen', id: 'Menjual' },
      { de: 'tauschen', id: 'Menukar' },
      { de: 'liefern', id: 'Mengirim' },
      { de: 'ankommen', id: 'Tiba' },
      { de: 'abfahren', id: 'Berangkat' },
      { de: 'zurückkehren', id: 'Kembali' },
      { de: 'reisen', id: 'Bepergian' },
      { de: 'fliegen', id: 'Terbang' },
      { de: 'fahren', id: 'Mengendarai' },
      { de: 'laufen', id: 'Berjalan/Lari' },
      { de: 'gehen', id: 'Berjalan' },
      { de: 'kommen', id: 'Datang' },
      { de: 'bringen', id: 'Membawa' },
      { de: 'nehmen', id: 'Mengambil' },
      { de: 'geben', id: 'Memberi' },
      { de: 'halten', id: 'Menahan/Memegang' },
      { de: 'legen', id: 'Meletakkan' },
      { de: 'stellen', id: 'Menempatkan' },
      { de: 'werfen', id: 'Melempar' },
      { de: 'fangen', id: 'Menangkap' },
      { de: 'öffnen', id: 'Membuka' },
      { de: 'schließen', id: 'Menutup' },
      { de: 'starten', id: 'Memulai' },
      { de: 'anfangen', id: 'Memulai' },
      { de: 'aufhören', id: 'Berhenti' },
      { de: 'endigen', id: 'Berakhir' },
      { de: 'trinken', id: 'Minum' },
      { de: 'essen', id: 'Makan' },
      { de: 'schmecken', id: 'Rasa' },
      { de: 'riechen', id: 'Bau' },
      { de: 'fühlen', id: 'Merasa' },
      { de: 'denken', id: 'Berpikir' },
      { de: 'glauben', id: 'Percaya' },
      { de: 'wissen', id: 'Tahu' },
      { de: 'kennen', id: 'Mengenal' },
      { de: 'verstehen', id: 'Mengerti' },
      { de: 'vergessen', id: 'Lupa' },
      { de: 'erinnern', id: 'Ingat' },
      { de: 'träumen', id: 'Bermimpi' },
      { de: 'hoffen', id: 'Berharap' },
      { de: 'wünschen', id: 'Menginginkan' },
      { de: 'mögen', id: 'Suka' },
      { de: 'lieben', id: 'Cinta' },
      { de: 'hassen', id: 'Benci' },
      { de: 'respektieren', id: 'Menghormati' },
      { de: 'helfen', id: 'Membantu' },
      { de: 'unterstützen', id: 'Mendukung' },
      { de: 'benötigen', id: 'Membutuhkan' },
      { de: 'verwenden', id: 'Menggunakan' },
      { de: 'benutzen', id: 'Memakai' },
      { de: 'verbieten', id: 'Melarang' },
      { de: 'erlauben', id: 'Memperbolehkan' },
      { de: 'entscheiden', id: 'Memutuskan' },
      { de: 'wählen', id: 'Memilih' },
      { de: 'ändern', id: 'Mengubah' },
      { de: 'entwickeln', id: 'Mengembangkan' },
      { de: 'verbessern', id: 'Memperbaiki' },
      { de: 'verschlechtern', id: 'Memperburuk' },
      { de: 'vergleichen', id: 'Membandingkan' },
      { de: 'unterscheiden', id: 'Membedakan' },
      { de: 'messen', id: 'Mengukur' },
      { de: 'zählen', id: 'Menghitung' },
      { de: 'rechnen', id: 'Menghitung' },
      { de: 'prüfen', id: 'Memeriksa' },
      { de: 'kontrollieren', id: 'Mengontrol' },
      { de: 'testen', id: 'Menguji' },
      { de: 'mischen', id: 'Mencampur' },
      { de: 'trennen', id: 'Memisahkan' },
      { de: 'verbinden', id: 'Menyambungkan' },
      { de: 'zerstören', id: 'Menghancurkan' },
      { de: 'reparieren', id: 'Memperbaiki' },
      { de: 'bauen', id: 'Membangun' },
      { de: 'konstruieren', id: 'Merekonstruksi' },
      { de: 'malen', id: 'Menggambar' },
      { de: 'zeichnen', id: 'Menggambar' },
      { de: 'fotografieren', id: 'Memotret' },
      { de: 'filmen', id: 'Merekam' },
      { de: 'aufnehmen', id: 'Merekam' },
      { de: 'abschneiden', id: 'Memotong' },
      { de: 'anschneiden', id: 'Memotong' },
      { de: 'schneiden', id: 'Memotong' },
      { de: 'klingen', id: 'Bunyi' },
      { de: 'klingeln', id: 'Berdering' },
      { de: 'läuten', id: 'Berbunyi' },
      { de: 'rauschen', id: 'Menderu' },
      { de: 'tosen', id: 'Menderu' },
      { de: 'flüstern', id: 'Berbisik' },
      { de: 'schreien', id: 'Berteriak' },
      { de: 'weinen', id: 'Menangis' },
      { de: 'lachen', id: 'Tertawa' },
      { de: 'lächeln', id: 'Senyum' },
      { de: 'grinsen', id: 'Meringis' },
      { de: 'lächeln', id: 'Senyum' },
      { de: 'stöhnen', id: 'Mengerang' },
      { de: 'niesen', id: 'Tersinflu' },
      { de: 'husten', id: 'Batuk' },
      { de: 'schlucken', id: 'Menelan' },
      { de: 'kauen', id: 'Mengunyah' },
      { de: 'schlürfen', id: 'Menyeruput' },
      { de: 'schmatzen', id: 'Mencicipi' },
      { de: 'schnarchen', id: 'Mendengkur' },
      { de: 'schniefen', id: 'Menghirup' },
      { de: 'atmen', id: 'Bernafas' }
    ],
    abstractConcepts: [
      { de: 'das Leben', id: 'Kehidupan', note: 'netral' },
      { de: 'der Tod', id: 'Kematian', note: 'maskulin' },
      { de: 'die Liebe', id: 'Cinta', note: 'feminin' },
      { de: 'der Hass', id: 'Kebencian', note: 'maskulin' },
      { de: 'die Freundschaft', id: 'Persahabatan', note: 'feminin' },
      { de: 'die Familie', id: 'Keluarga', note: 'feminin' },
      { de: 'die Gesellschaft', id: 'Masyarakat', note: 'feminin' },
      { de: 'die Politik', id: 'Politik', note: 'feminin' },
      { de: 'die Wirtschaft', id: 'Ekonomi', note: 'feminin' },
      { de: 'die Kultur', id: 'Budaya', note: 'feminin' },
      { de: 'die Kunst', id: 'Seni', note: 'feminin' },
      { de: 'die Musik', id: 'Musik', note: 'feminin' },
      { de: 'die Religion', id: 'Agama', note: 'feminin' },
      { de: 'der Glaube', id: 'Keyakinan', note: 'maskulin' },
      { de: 'die Hoffnung', id: 'Harapan', note: 'feminin' },
      { de: 'der Traum', id: 'Mimpi', note: 'maskulin' },
      { de: 'die Angst', id: 'Ketakutan', note: 'feminin' },
      { de: 'die Freiheit', id: 'Kebebasan', note: 'feminin' },
      { de: 'die Gerechtigkeit', id: 'Keadilan', note: 'feminin' },
      { de: 'die Wahrheit', id: 'Kebenaran', note: 'feminin' },
      { de: 'die Lüge', id: 'Kebohongan', note: 'feminin' },
      { de: 'das Glück', id: 'Kebahagiaan', note: 'netral' },
      { de: 'das Leid', id: 'Penderitaan', note: 'netral' },
      { de: 'der Erfolg', id: 'Keberhasilan', note: 'maskulin' },
      { de: 'das Scheitern', id: 'Kegagalan', note: 'netral' },
      { de: 'die Hoffnung', id: 'Harapan', note: 'feminin' },
      { de: 'die Enttäuschung', id: 'Kekecewaan', note: 'feminin' },
      { de: 'die Überraschung', id: 'Keterkejutan', note: 'feminin' },
      { de: 'die Begeisterung', id: 'Antusiasme', note: 'feminin' },
      { de: 'die Langeweile', id: 'Kebosanan', note: 'feminin' },
      { de: 'die Neugier', id: 'Keingintahuan', note: 'feminin' },
      { de: 'der Zweifel', id: 'Keraguan', note: 'maskulin' },
      { de: 'die Sicherheit', id: 'Keamanan', note: 'feminin' },
      { de: 'die Gefahr', id: 'Bahaya', note: 'feminin' },
      { de: 'das Risiko', id: 'Risiko', note: 'netral' },
      { de: 'die Herausforderung', id: 'Tantangan', note: 'feminin' },
      { de: 'die Gelegenheit', id: 'Kesempatan', note: 'feminin' },
      { de: 'die Möglichkeit', id: 'Kemungkinan', note: 'feminin' },
      { de: 'die Wahrscheinlichkeit', id: 'Kemungkinan besar', note: 'feminin' },
      { de: 'die Notwendigkeit', id: 'Kebutuhan', note: 'feminin' },
      { de: 'die Pflicht', id: 'Kewajiban', note: 'feminin' },
      { de: 'die Verantwortung', id: 'Tanggung jawab', note: 'feminin' },
      { de: 'die Entscheidung', id: 'Keputusan', note: 'feminin' },
      { de: 'die Meinung', id: 'Pendapat', note: 'feminin' },
      { de: 'die Idee', id: 'Ide', note: 'feminin' },
      { de: 'der Plan', id: 'Rencana', note: 'maskulin' },
      { de: 'das Ziel', id: 'Tujuan', note: 'netral' },
      { de: 'der Zweck', id: 'Tujuan', note: 'maskulin' },
      { de: 'die Bedeutung', id: 'Arti', note: 'feminin' },
      { de: 'die Erinnerung', id: 'Kenangan', note: 'feminin' },
      { de: 'die Erfahrung', id: 'Pengalaman', note: 'feminin' },
      { de: 'die Tradition', id: 'Tradisi', note: 'feminin' },
      { de: 'die Geschichte', id: 'Sejarah', note: 'feminin' },
      { de: 'die Natur', id: 'Alam', note: 'feminin' },
      { de: 'die Umwelt', id: 'Lingkungan', note: 'feminin' },
      { de: 'die Erde', id: 'Bumi', note: 'feminin' },
      { de: 'der Himmel', id: 'Langit', note: 'maskulin' },
      { de: 'die Sonne', id: 'Matahari', note: 'feminin' },
      { de: 'der Mond', id: 'Bulan', note: 'maskulin' },
      { de: 'der Stern', id: 'Bintang', note: 'maskulin' },
      { de: 'das Meer', id: 'Laut', note: 'netral' },
      { de: 'der Fluss', id: 'Sungai', note: 'maskulin' },
      { de: 'der See', id: 'Danau', note: 'maskulin' },
      { de: 'der Berg', id: 'Gunung', note: 'maskulin' },
      { de: 'das Tal', id: 'Lembah', note: 'netral' },
      { de: 'die Insel', id: 'Pulau', note: 'feminin' },
      { de: 'der Wald', id: 'Hutan', note: 'maskulin' },
      { de: 'die Wüste', id: 'Gurun', note: 'feminin' },
      { de: 'die Sprache', id: 'Bahasa', note: 'feminin' },
      { de: 'das Wort', id: 'Kata', note: 'netral' },
      { de: 'der Satz', id: 'Kalimat', note: 'maskulin' },
      { de: 'die Grammatik', id: 'Tata bahasa', note: 'feminin' },
      { de: 'die Übersetzung', id: 'Terjemahan', note: 'feminin' },
      { de: 'die Bedeutung', id: 'Arti', note: 'feminin' },
      { de: 'die Aussprache', id: 'Pengucapan', note: 'feminin' },
      { de: 'der Akzent', id: 'Aksen', note: 'maskulin' },
      { de: 'die Schrift', id: 'Tulisan', note: 'feminin' },
      { de: 'das Alphabet', id: 'Alfabet', note: 'netral' }
    ],
    quizzes: {
      colors: {
        title: 'Warna', icon: '🎨',
        vocab: [
          { de: 'rot', id: 'Merah' }, { de: 'blau', id: 'Biru' }, { de: 'grün', id: 'Hijau' },
          { de: 'gelb', id: 'Kuning' }, { de: 'lila', id: 'Ungu' }, { de: 'rosa', id: 'Merah muda' },
          { de: 'schwarz', id: 'Hitam' }, { de: 'weiß', id: 'Putih' }, { de: 'grau', id: 'Abu-abu' },
          { de: 'braun', id: 'Cokelat' }, { de: 'golden', id: 'Emas' }, { de: 'silber', id: 'Perak' }
        ]
      },
      numbers: {
        title: 'Angka', icon: '🔢',
        vocab: [
          { de: 'null', id: 'Nol' }, { de: 'eins', id: 'Satu' }, { de: 'zwei', id: 'Dua' },
          { de: 'drei', id: 'Tiga' }, { de: 'vier', id: 'Empat' }, { de: 'fünf', id: 'Lima' },
          { de: 'sechs', id: 'Enam' }, { de: 'sieben', id: 'Tujuh' }, { de: 'acht', id: 'Delapan' },
          { de: 'neun', id: 'Sembilan' }, { de: 'zehn', id: 'Sepuluh' }, { de: 'zwanzig', id: 'Dua puluh' },
          { de: 'hundert', id: 'Seratus' }, { de: 'tausend', id: 'Seribu' }
        ]
      },
      greetings: {
        title: 'Salam', icon: '👋',
        vocab: [
          { de: 'Hallo', id: 'Halo' }, { de: 'Guten Morgen', id: 'Selamat pagi' },
          { de: 'Guten Tag', id: 'Selamat siang' }, { de: 'Guten Abend', id: 'Selamat sore' },
          { de: 'Gute Nacht', id: 'Selamat malam' }, { de: 'Tschüss', id: 'Selamat tinggal' },
          { de: 'Auf Wiedersehen', id: 'Sampai jumpa' }, { de: 'Danke', id: 'Terima kasih' },
          { de: 'Bitte', id: 'Tolong/Sama-sama' }, { de: 'Entschuldigung', id: 'Maaf' },
          { de: 'Ja', id: 'Ya' }, { de: 'Nein', id: 'Tidak' }
        ]
      },
      family: {
        title: 'Keluarga', icon: '👨‍👩‍👧‍👦',
        vocab: [
          { de: 'die Mutter', id: 'Ibu' }, { de: 'der Vater', id: 'Ayah' },
          { de: 'die Großmutter', id: 'Nenek' }, { de: 'der Großvater', id: 'Kakek' },
          { de: 'die Schwester', id: 'Saudara perempuan' }, { de: 'der Bruder', id: 'Saudara laki-laki' },
          { de: 'die Tochter', id: 'Anak perempuan' }, { de: 'der Sohn', id: 'Anak laki-laki' },
          { de: 'die Familie', id: 'Keluarga' }, { de: 'die Ehefrau', id: 'Istri' },
          { de: 'der Ehemann', id: 'Suami' }, { de: 'das Kind', id: 'Anak' }
        ]
      },
      food: {
        title: 'Makanan & Minuman', icon: '🍽️',
        vocab: [
          { de: 'das Brot', id: 'Roti' }, { de: 'die Butter', id: 'Mentega' },
          { de: 'der Käse', id: 'Keju' }, { de: 'die Wurst', id: 'Sosis' },
          { de: 'das Ei', id: 'Telur' }, { de: 'der Reis', id: 'Nasi' },
          { de: 'die Kartoffel', id: 'Kentang' }, { de: 'die Suppe', id: 'Sup' },
          { de: 'das Obst', id: 'Buah' }, { de: 'das Gemüse', id: 'Sayuran' },
          { de: 'das Fleisch', id: 'Daging' }, { de: 'der Fisch', id: 'Ikan' },
          { de: 'die Milch', id: 'Susu' }, { de: 'der Kaffee', id: 'Kopi' },
          { de: 'der Tee', id: 'Teh' }, { de: 'das Wasser', id: 'Air' },
          { de: 'der Kuchen', id: 'Kue' }, { de: 'die Nudeln', id: 'Pasta' }
        ]
      },
      places: {
        title: 'Tempat', icon: '📍',
        vocab: [
          { de: 'die Schule', id: 'Sekolah' }, { de: 'die Universität', id: 'Universitas' },
          { de: 'das Krankenhaus', id: 'Rumah sakit' }, { de: 'die Kirche', id: 'Gereja' },
          { de: 'das Museum', id: 'Museum' }, { de: 'das Hotel', id: 'Hotel' },
          { de: 'das Restaurant', id: 'Restoran' }, { de: 'die Bank', id: 'Bank' },
          { de: 'der Supermarkt', id: 'Supermarket' }, { de: 'die Bibliothek', id: 'Perpustakaan' },
          { de: 'das Kino', id: 'Bioskop' }, { de: 'der Park', id: 'Taman' },
          { de: 'der Bahnhof', id: 'Stasiun kereta' }, { de: 'der Flughafen', id: 'Bandara' }
        ]
      },
      professions: {
        title: 'Profesi', icon: '💼',
        vocab: [
          { de: 'der Arzt', id: 'Dokter' }, { de: 'die Ärztin', id: 'Dokter (wanita)' },
          { de: 'der Lehrer', id: 'Guru' }, { de: 'die Lehrerin', id: 'Guru (wanita)' },
          { de: 'der Ingenieur', id: 'Insinyur' }, { de: 'die Ingenieurin', id: 'Insinyur (wanita)' },
          { de: 'der Anwalt', id: 'Pengacara' }, { de: 'der Polizist', id: 'Polisi' },
          { de: 'die Polizistin', id: 'Polisi (wanita)' }, { de: 'der Koch', id: 'Koki' },
          { de: 'die Köchin', id: 'Koki (wanita)' }, { de: 'der Pilot', id: 'Pilot' },
          { de: 'die Pilotin', id: 'Pilot (wanita)' }, { de: 'der Journalist', id: 'Jurnalis' },
          { de: 'die Krankenschwester', id: 'Perawat' }, { de: 'der Architekt', id: 'Arsitek' }
        ]
      },
      emotions: {
        title: 'Emosi', icon: '😊',
        vocab: [
          { de: 'glücklich', id: 'Bahagia' }, { de: 'traurig', id: 'Sedih' },
          { de: 'wütend', id: 'Marah' }, { de: 'überrascht', id: 'Terkejut' },
          { de: 'enttäuscht', id: 'Kecewa' }, { de: 'stolz', id: 'Bangga' },
          { de: 'neugierig', id: 'Penasaran' }, { de: 'zufrieden', id: 'Puas' },
          { de: 'besorgt', id: 'Khawatir' }, { de: 'aufgeregt', id: 'Gugup' },
          { de: 'verwirrt', id: 'Bingung' }, { de: 'mutig', id: 'Pemberani' },
          { de: 'ängstlich', id: 'Takut' }, { de: 'verliebt', id: 'Jatuh cinta' },
          { de: 'eifersüchtig', id: 'Cemburu' }, { de: 'schuldig', id: 'Bersalah' }
        ]
      },
      verbConjugations: {
        title: 'Konjugasi Verba', icon: '📝',
        vocab: [
          { de: 'ich bin', id: 'Saya adalah' }, { de: 'du bist', id: 'Kamu adalah' },
          { de: 'er/sie ist', id: 'Dia adalah' }, { de: 'wir sind', id: 'Kami adalah' },
          { de: 'ich habe', id: 'Saya memiliki' }, { de: 'du hast', id: 'Kamu memiliki' },
          { de: 'er/sie hat', id: 'Dia memiliki' }, { de: 'ich werde', id: 'Saya menjadi' },
          { de: 'ich kann', id: 'Saya bisa' }, { de: 'du kannst', id: 'Kamu bisa' },
          { de: 'ich muss', id: 'Saya harus' }, { de: 'ich will', id: 'Saya mau' },
          { de: 'ich darf', id: 'Saya boleh' }, { de: 'ich mag', id: 'Saya suka' },
          { de: 'ich gehe', id: 'Saya pergi' }, { de: 'ich komme', id: 'Saya datang' },
          { de: 'ich mache', id: 'Saya membuat' }, { de: 'ich sage', id: 'Saya berkata' },
          { de: 'ich gebe', id: 'Saya memberi' }, { de: 'ich nehme', id: 'Saya mengambil' },
          { de: 'ich sehe', id: 'Saya melihat' }, { de: 'ich weiß', id: 'Saya tahu' },
          { de: 'ich glaube', id: 'Saya percaya' }, { de: 'ich arbeite', id: 'Saya bekerja' },
          { de: 'ich lerne', id: 'Saya belajar' }, { de: 'ich helfe', id: 'Saya membantu' }
        ]
      },
      bodyParts: {
        title: 'Bagian Tubuh', icon: '🫁',
        vocab: [
          { de: 'der Kopf', id: 'Kepala' }, { de: 'das Gesicht', id: 'Wajah' },
          { de: 'das Auge', id: 'Mata' }, { de: 'die Nase', id: 'Hidung' },
          { de: 'der Mund', id: 'Mulut' }, { de: 'die Lippe', id: 'Bibir' },
          { de: 'die Zähne', id: 'Gigi' }, { de: 'die Zunge', id: 'Lidah' },
          { de: 'das Ohr', id: 'Telinga' }, { de: 'der Hals', id: 'Leher' },
          { de: 'die Schulter', id: 'Bahu' }, { de: 'die Hand', id: 'Tangan' },
          { de: 'die Finger', id: 'Jari-jari' }, { de: 'die Brust', id: 'Dada' },
          { de: 'der Bauch', id: 'Perut' }, { de: 'der Rücken', id: 'Punggung' },
          { de: 'das Knie', id: 'Lutut' }, { de: 'der Fuß', id: 'Kaki' },
          { de: 'das Herz', id: 'Jantung' }, { de: 'das Gehirn', id: 'Otak' }
        ]
      },
      clothing: {
        title: 'Pakaian', icon: '👕',
        vocab: [
          { de: 'das Kleid', id: 'Gaun' }, { de: 'die Hose', id: 'Celana' },
          { de: 'das Hemd', id: 'Kemeja' }, { de: 'die Jacke', id: 'Jaket' },
          { de: 'die Schuhe', id: 'Sepatu' }, { de: 'die Socken', id: 'Kaus kaki' },
          { de: 'der Hut', id: 'Topi' }, { de: 'die Brille', id: 'Kacamata' },
          { de: 'der Gürtel', id: 'Ikat pinggang' }, { de: 'die Krawatte', id: 'Dasi' },
          { de: 'der Pullover', id: 'Sweter' }, { de: 'der Mantel', id: 'Mantel' },
          { de: 'die Handschuhe', id: 'Sarung tangan' }, { de: 'der Schal', id: 'Syal' }
        ]
      },
      house: {
        title: 'Rumah', icon: '🏠',
        vocab: [
          { de: 'das Haus', id: 'Rumah' }, { de: 'das Zimmer', id: 'Kamar' },
          { de: 'die Küche', id: 'Dapur' }, { de: 'das Badezimmer', id: 'Kamar mandi' },
          { de: 'die Tür', id: 'Pintu' }, { de: 'das Fenster', id: 'Jendela' },
          { de: 'der Tisch', id: 'Meja' }, { de: 'der Stuhl', id: 'Kursi' },
          { de: 'das Bett', id: 'Tempat tidur' }, { de: 'das Sofa', id: 'Sofa' },
          { de: 'der Schrank', id: 'Lemari' }, { de: 'das Regal', id: 'Rak' },
          { de: 'der Schlüssel', id: 'Kunci' }, { de: 'der Spiegel', id: 'Cermin' },
          { de: 'die Treppe', id: 'Tangga' }, { de: 'der Garten', id: 'Kebun' }
        ]
      },
      foodExtended: {
        title: 'Makanan Lanjutan', icon: '🍷',
        vocab: [
          { de: 'der Apfel', id: 'Apel' }, { de: 'die Birne', id: 'Pir' },
          { de: 'die Kirsche', id: 'Ceri' }, { de: 'die Erdbeere', id: 'Stroberi' },
          { de: 'die Traube', id: 'Anggur' }, { de: 'die Orange', id: 'Jeruk' },
          { de: 'die Zitrone', id: 'Lemon' }, { de: 'die Ananas', id: 'Nanas' },
          { de: 'die Mango', id: 'Mangga' }, { de: 'der Honig', id: 'Madu' },
          { de: 'die Marmelade', id: 'Selai' }, { de: 'der Senf', id: 'Mustard' },
          { de: 'der Essig', id: 'Cuka' }, { de: 'das Mehl', id: 'Tepung' },
          { de: 'das Olivenöl', id: 'Minyak zaitun' }, { de: 'die Sahne', id: 'Krim' }
        ]
      },
      technology: {
        title: 'Teknologi', icon: '💻',
        vocab: [
          { de: 'der Computer', id: 'Komputer' }, { de: 'das Handy', id: 'HP' },
          { de: 'das Tablet', id: 'Tablet' }, { de: 'das Internet', id: 'Internet' },
          { de: 'das WLAN', id: 'Wifi' }, { de: 'die Software', id: 'Perangkat lunak' },
          { de: 'die Hardware', id: 'Perangkat keras' }, { de: 'der Bildschirm', id: 'Layar' },
          { de: 'die Tastatur', id: 'Keyboard' }, { de: 'die Maus', id: 'Mouse' },
          { de: 'der Drucker', id: 'Printer' }, { de: 'die Kamera', id: 'Kamera' },
          { de: 'das Passwort', id: 'Password' }, { de: 'der Browser', id: 'Browser' },
          { de: 'die E-Mail', id: 'Email' }, { de: 'die App', id: 'Aplikasi' }
        ]
      },
      transportation: {
        title: 'Transportasi', icon: '🚗',
        vocab: [
          { de: 'das Auto', id: 'Mobil' }, { de: 'der Bus', id: 'Bus' },
          { de: 'der Zug', id: 'Kereta api' }, { de: 'das Taxi', id: 'Taksi' },
          { de: 'das Flugzeug', id: 'Pesawat' }, { de: 'das Schiff', id: 'Kapal' },
          { de: 'das Fahrrad', id: 'Sepeda' }, { de: 'das Motorrad', id: 'Motor' },
          { de: 'die Autobahn', id: 'Jalan tol' }, { de: 'der Bahnhof', id: 'Stasiun' },
          { de: 'der Flughafen', id: 'Bandara' }, { de: 'die Ampel', id: 'Lampu lalu lintas' },
          { de: 'der Führerschein', id: 'SIM' }, { de: 'das Benzin', id: 'Bensin' }
        ]
      },
      travel: {
        title: 'Perjalanan', icon: '✈️',
        vocab: [
          { de: 'der Urlaub', id: 'Liburan' }, { de: 'die Reise', id: 'Perjalanan' },
          { de: 'das Hotel', id: 'Hotel' }, { de: 'die Unterkunft', id: 'Akomodasi' },
          { de: 'der Pass', id: 'Paspor' }, { de: 'der Koffer', id: 'Koper' },
          { de: 'die Fahrkarte', id: 'Tiket' }, { de: 'die Reservierung', id: 'Reservasi' },
          { de: 'der Reisepass', id: 'Paspor' }, { de: 'die Touristeninformation', id: 'Pariwisata' },
          { de: 'der Souvenir', id: 'Oleh-oleh' }, { de: 'die Sehenswürdigkeit', id: 'Tempat wisata' },
          { de: 'die Strand', id: 'Pantai' }, { de: 'die Berge', id: 'Gunung' }
        ]
      }
    },
    achievements: [
      { id: 'first_quiz', title: 'Kuis Pertama', description: 'Selesaikan kuis pertama', icon: '🎯', condition: (stats) => stats.quizzesCompleted >= 1 },
      { id: 'quiz_master', title: 'Ahli Kuis', description: 'Selesaikan 10 kuis', icon: '🏆', condition: (stats) => stats.quizzesCompleted >= 10 },
      { id: 'quiz_champion', title: 'Juara Kuis', description: 'Selesaikan 50 kuis', icon: '👑', condition: (stats) => stats.quizzesCompleted >= 50 },
      { id: 'perfect_score', title: 'Skor Sempurna', description: 'Dapat skor 100% dalam kuis', icon: '💯', condition: (stats) => stats.perfectScores >= 1 },
      { id: 'perfect_10', title: 'Sempurna 10x', description: 'Dapat skor 100% sebanyak 10 kali', icon: '⭐', condition: (stats) => stats.perfectScores >= 10 },
      { id: 'flashcard_beginner', title: 'Pemula Flashcard', description: 'Lihat 10 kartu flashcard', icon: '🃏', condition: (stats) => stats.flashcardsViewed >= 10 },
      { id: 'flashcard_master', title: 'Ahli Flashcard', description: 'Lihat 100 kartu flashcard', icon: '🎰', condition: (stats) => stats.flashcardsViewed >= 100 },
      { id: 'flashcard_expert', title: 'Pakar Flashcard', description: 'Lihat 500 kartu flashcard', icon: '📚', condition: (stats) => stats.flashcardsViewed >= 500 },
      { id: 'vocabulary_100', title: 'Kolektor Kata', description: 'Pelajari 100 kata', icon: '📝', condition: (stats) => stats.wordsLearned >= 100 },
      { id: 'vocabulary_500', title: 'Master Kosakata', description: 'Pelajari 500 kata', icon: '📖', condition: (stats) => stats.wordsLearned >= 500 },
      { id: 'vocabulary_1000', title: 'Koleksi Besar', description: 'Pelajari 1000 kata', icon: '🎓', condition: (stats) => stats.wordsLearned >= 1000 },
      { id: 'xp_100', title: 'Pengalaman 100', description: 'Kumpulkan 100 XP', icon: '✨', condition: (stats) => stats.totalXP >= 100 },
      { id: 'xp_500', title: 'Pengalaman 500', description: 'Kumpulkan 500 XP', icon: '🌟', condition: (stats) => stats.totalXP >= 500 },
      { id: 'xp_1000', title: 'Pengalaman 1000', description: 'Kumpulkan 1000 XP', icon: '💫', condition: (stats) => stats.totalXP >= 1000 },
      { id: 'xp_5000', title: 'Pengalaman 5000', description: 'Kumpulkan 5000 XP', icon: '🔥', condition: (stats) => stats.totalXP >= 5000 },
      { id: 'level_5', title: 'Level 5', description: 'Capai level 5', icon: '🏅', condition: (stats) => stats.level >= 5 },
      { id: 'level_10', title: 'Level 10', description: 'Capai level 10', icon: '🥇', condition: (stats) => stats.level >= 10 },
      { id: 'level_20', title: 'Level 20', description: 'Capai level 20', icon: '🎖️', condition: (stats) => stats.level >= 20 },
      { id: 'streak_3', title: 'Streak 3 Hari', description: 'Belajar 3 hari berturut-turut', icon: '📅', condition: (stats) => stats.streak >= 3 },
      { id: 'streak_7', title: 'Streak 7 Hari', description: 'Belajar 7 hari berturut-turut', icon: '📆', condition: (stats) => stats.streak >= 7 },
      { id: 'streak_30', title: 'Streak 30 Hari', description: 'Belajar 30 hari berturut-turut', icon: '🗓️', condition: (stats) => stats.streak >= 30 },
      { id: 'all_categories', title: 'Semua Kategori', description: 'Coba semua kategori kuis', icon: '🗂️', condition: (stats) => stats.categoriesTried >= 16 },
      { id: 'speed_demon', title: 'Iblis Kecepatan', description: 'Selesaikan kuis dalam waktu kurang dari 30 detik', icon: '⚡', condition: (stats) => stats.fastestQuiz <= 30 },
      { id: 'consistent', title: 'Konsisten', description: 'Selesaikan 10 kuis tanpa salah', icon: '🎯', condition: (stats) => stats.perfectStreak >= 10 },
      { id: 'night_owl', title: 'Burung Hantu', description: 'Belajar setelah jam 10 malam', icon: '🦉', condition: (stats) => stats.nightStudy >= 1 },
      { id: 'early_bird', title: 'Burung Pagi', description: 'Belajar sebelum jam 6 pagi', icon: '🐦', condition: (stats) => stats.earlyStudy >= 1 },
      { id: 'explorer', title: 'Penjelajah', description: 'Gunakan semua fitur aplikasi', icon: '🧭', condition: (stats) => stats.featuresUsed >= 8 },
      { id: 'social', title: 'Sosial', description: 'Ekspor data 1 kali', icon: '📤', condition: (stats) => stats.exports >= 1 },
      { id: 'collector', title: 'Kolektor', description: 'Impor data 1 kali', icon: '📥', condition: (stats) => stats.imports >= 1 },
      { id: 'perfectionist', title: 'Perfeksionis', description: 'Dapat 100% di 5 kuis berbeda', icon: '💎', condition: (stats) => stats.perfectScores >= 5 },
      { id: 'polyglot', title: 'Polyglot', description: 'Pelajari 3 bahasa berbeda', icon: '🌍', condition: (stats) => stats.languagesStudied >= 3 },
      { id: 'daily_quest', title: 'Kuis Harian', description: 'Selesaikan kuis harian', icon: '📋', condition: (stats) => stats.dailyQuests >= 1 },
      { id: 'weekend_warrior', title: 'Pejuang Akhir Pekan', description: 'Belajar di akhir pekan', icon: '⚔️', condition: (stats) => stats.weekendStudy >= 1 },
      { id: 'master_grammar', title: 'Pakar Tata Bahasa', description: 'Selesaikan kuis konjugasi 5 kali', icon: '📐', condition: (stats) => stats.grammarQuizzes >= 5 },
      { id: 'grammatik_professor', title: 'Profesor Grammatik', description: 'Selesaikan kuis konjugasi 20 kali', icon: '🎓', condition: (stats) => stats.grammarQuizzes >= 20 }
    ]
};
