const CONTENT_DATA = {
  vocabulary: {
    salam: [
      { es: 'Hola', id: 'Halo' }, { es: 'Buenos dias', id: 'Selamat pagi' },
      { es: 'Buenas tardes', id: 'Selamat siang' }, { es: 'Buenas noches', id: 'Selamat malam' },
      { es: 'Adios', id: 'Selamat tinggal' }, { es: 'Hasta luego', id: 'Sampai nanti' },
      { es: 'Hasta manana', id: 'Sampai besok' }, { es: 'Por favor', id: 'Tolong' },
      { es: 'Gracias', id: 'Terima kasih' }, { es: 'Muchas gracias', id: 'Terima kasih banyak' },
      { es: 'De nada', id: 'Sama-sama' }, { es: 'Perdon', id: 'Maaf' },
      { es: 'Lo siento', id: 'Saya minta maaf' }, { es: 'Buenas noches', id: 'Selamat malam' },
      { es: 'Como estas?', id: 'Apa kabar?' }, { es: 'Estoy bien', id: 'Saya baik-baik saja' },
      { es: 'Me llamo...', id: 'Nama saya...' }, { es: 'Mucho gusto', id: 'Senang bertemu Anda' },
      { es: 'Si', id: 'Ya' }, { es: 'No', id: 'Tidak' },
      { es: 'Disculpe', id: 'Permisi' }, { es: 'No entiendo', id: 'Saya tidak mengerti' },
      { es: 'Habla ingles?', id: 'Apakah Anda bicara bahasa Inggris?' },
      { es: 'Quisiera...', id: 'Saya ingin...' },
      { es: 'Que tal?', id: 'Bagaimana?' },
      { es: 'Muy bien', id: 'Sangat baik' },
      { es: 'Mas o menos', id: 'Lumayan' },
      { es: 'Mal', id: 'Buruk' },
      { es: 'Encantado', id: 'Senang bertemu Anda' },
      { es: 'Igualmente', id: 'Sama juga' }
    ],
    angka: [
      { es: 'uno', id: '1' }, { es: 'dos', id: '2' }, { es: 'tres', id: '3' },
      { es: 'cuatro', id: '4' }, { es: 'cinco', id: '5' }, { es: 'seis', id: '6' },
      { es: 'siete', id: '7' }, { es: 'ocho', id: '8' }, { es: 'nueve', id: '9' },
      { es: 'diez', id: '10' }, { es: 'once', id: '11' }, { es: 'doce', id: '12' },
      { es: 'trece', id: '13' }, { es: 'catorce', id: '14' }, { es: 'quince', id: '15' },
      { es: 'dieciseis', id: '16' }, { es: 'diecisiete', id: '17' },
      { es: 'dieciocho', id: '18' }, { es: 'diecinueve', id: '19' },
      { es: 'veinte', id: '20' }, { es: 'treinta', id: '30' },
      { es: 'cuarenta', id: '40' }, { es: 'cincuenta', id: '50' },
      { es: 'sesenta', id: '60' }, { es: 'setenta', id: '70' },
      { es: 'ochenta', id: '80' }, { es: 'noventa', id: '90' }, { es: 'cien', id: '100' }
    ],
    hari: [
      { es: 'Lunes', id: 'Senin' }, { es: 'Martes', id: 'Selasa' },
      { es: 'Miercoles', id: 'Rabu' }, { es: 'Jueves', id: 'Kamis' },
      { es: 'Viernes', id: 'Jumat' }, { es: 'Sabado', id: 'Sabtu' },
      { es: 'Domingo', id: 'Minggu' }
    ],
    warna: [
      { es: 'Rojo', id: 'Merah' }, { es: 'Azul', id: 'Biru' },
      { es: 'Verde', id: 'Hijau' }, { es: 'Amarillo', id: 'Kuning' },
      { es: 'Negro', id: 'Hitam' }, { es: 'Blanco', id: 'Putih' },
      { es: 'Gris', id: 'Abu-abu' }, { es: 'Naranja', id: 'Oranye' },
      { es: 'Rosa', id: 'Merah muda' }, { es: 'Marron', id: 'Cokelat' }
    ],
    ganti: [
      { es: 'Yo', id: 'Saya' }, { es: 'Tu', id: 'Kamu (informal)' },
      { es: 'El', id: 'Dia (lk)' }, { es: 'Ella', id: 'Dia (pr)' },
      { es: 'Nosotros', id: 'Kami/Kita' }, { es: 'Vosotros', id: 'Kalian' },
      { es: 'Ellos', id: 'Mereka (lk)' }, { es: 'Ellas', id: 'Mereka (pr)' }
    ],
    keluarga: [
      { es: 'la madre', id: 'Ibu' }, { es: 'el padre', id: 'Ayah' },
      { es: 'la hermana', id: 'Saudari' }, { es: 'el hermano', id: 'Saudara lk' },
      { es: 'la hija', id: 'Anak pr' }, { es: 'el hijo', id: 'Anak lk' },
      { es: 'los padres', id: 'Orang tua' }, { es: 'la familia', id: 'Keluarga' },
      { es: 'el abuelo', id: 'Kakek' }, { es: 'la abuela', id: 'Nenek' },
      { es: 'el primo', id: 'Sepupu lk' }, { es: 'la prima', id: 'Sepupu pr' },
      { es: 'el esposo', id: 'Suami' }, { es: 'la esposa', id: 'Istri' },
      { es: 'el bebe', id: 'Bayi' }
    ],
    makanan: [
      { es: 'el pan', id: 'Roti' }, { es: 'el agua', id: 'Air' },
      { es: 'el cafe', id: 'Kopi' }, { es: 'la leche', id: 'Susu' },
      { es: 'el queso', id: 'Keju' }, { es: 'la manzana', id: 'Apel' },
      { es: 'el pollo', id: 'Ayam' }, { es: 'el arroz', id: 'Nasi' },
      { es: 'el pescado', id: 'Ikan' }, { es: 'la carne', id: 'Daging' },
      { es: 'el azucar', id: 'Gula' }, { es: 'la sal', id: 'Garam' },
      { es: 'el vino', id: 'Anggur (minuman)' }, { es: 'la cerveza', id: 'Bir' },
      { es: 'el jugo', id: 'Jus' }, { es: 'el te', id: 'Teh' },
      { es: 'el chocolate', id: 'Cokelat' }, { es: 'el pastel', id: 'Kue' },
      { es: 'la ensalada', id: 'Salad' }, { es: 'la sopa', id: 'Sup' }
    ],
    tempat: [
      { es: 'la escuela', id: 'Sekolah' }, { es: 'la casa', id: 'Rumah' },
      { es: 'la tienda', id: 'Toko' }, { es: 'la calle', id: 'Jalan' },
      { es: 'a la derecha', id: 'Ke kanan' }, { es: 'a la izquierda', id: 'Ke kiri' },
      { es: 'el hospital', id: 'Rumah sakit' }, { es: 'la biblioteca', id: 'Perpustakaan' },
      { es: 'el restaurante', id: 'Restoran' }, { es: 'la estacion', id: 'Stasiun' },
      { es: 'el hotel', id: 'Hotel' }, { es: 'el banco', id: 'Bank' },
      { es: 'el parque', id: 'Taman' }, { es: 'el mercado', id: 'Pasar' },
      { es: 'la iglesia', id: 'Gereja' }, { es: 'el cine', id: 'Bioskop' },
      { es: 'la farmacia', id: 'Apotek' }, { es: 'la oficina de correos', id: 'Kantor pos' },
      { es: 'el supermercado', id: 'Supermarket' }, { es: 'la playa', id: 'Pantai' }
    ],
    profesi: [
      { es: 'el medico', id: 'Dokter' }, { es: 'el profesor', id: 'Guru' },
      { es: 'el ingeniero', id: 'Insinyur' }, { es: 'el estudiante', id: 'Mahasiswa' },
      { es: 'el policia', id: 'Polisi' }, { es: 'el cocinero', id: 'Koki' },
      { es: 'el artista', id: 'Seniman' }, { es: 'el periodista', id: 'Jurnalis' },
      { es: 'el chofer', id: 'Sopir' }, { es: 'el vendedor', id: 'Penjual' },
      { es: 'el mesero', id: 'Pelayan' }, { es: 'el cartero', id: 'Tukang pos' },
      { es: 'el soldado', id: 'Tentara' }, { es: 'el bombero', id: 'Pemadam kebakaran' },
      { es: 'el abogado', id: 'Pengacara' }, { es: 'el granjero', id: 'Petani' },
      { es: 'el musico', id: 'Musisi' }, { es: 'el actor', id: 'Aktor' },
      { es: 'el director', id: 'Sutradara' }, { es: 'el traductor', id: 'Penerjemah' }
    ],
    emosi: [
      { es: 'feliz', id: 'Senang' }, { es: 'triste', id: 'Sedih' },
      { es: 'cansado', id: 'Lelah' }, { es: 'enojado', id: 'Marah' },
      { es: 'asustado', id: 'Takut' }, { es: 'sorprendido', id: 'Terkejut' },
      { es: 'tranquilo', id: 'Tenang' }, { es: 'emocionado', id: 'Antusias' },
      { es: 'enamorado', id: 'Jatuh cinta' }, { es: 'celoso', id: 'Cemburu' },
      { es: 'orgulloso', id: 'Bangga' }, { es: 'timido', id: 'Pemalu' },
      { es: 'avergonzado', id: 'Memalukan' }, { es: 'confiado', id: 'Percaya diri' },
      { es: 'decepcionado', id: 'Kecewa' }, { es: 'preocupado', id: 'Khawatir' },
      { es: 'solo', id: 'Kesepian' }, { es: 'entusiasmado', id: 'Antusias' },
      { es: 'calmado', id: 'Tenang' }, { es: 'nervioso', id: 'Gugup' }
    ],
    verbes: [
      { es: 'ser', id: 'Adalah/menjadi' }, { es: 'tener', id: 'Memiliki' },
      { es: 'ir', id: 'Pergi' }, { es: 'hacer', id: 'Melakukan' },
      { es: 'poder', id: 'Bisa' }, { es: 'querer', id: 'Mau' },
      { es: 'deber', id: 'Harus' }, { es: 'decir', id: 'Berkata' },
      { es: 'ver', id: 'Melihat' }, { es: 'venir', id: 'Datang' },
      { es: 'salir', id: 'Keluar' }, { es: 'llegar', id: 'Tiba' },
      { es: 'entrar', id: 'Masuk' }, { es: 'subir', id: 'Naik' },
      { es: 'bajar', id: 'Turun' }, { es: 'abrir', id: 'Membuka' },
      { es: 'cerrar', id: 'Menutup' }, { es: 'dar', id: 'Memberi' },
      { es: 'tomar', id: 'Mengambil' }, { es: 'saber', id: 'Tahu' }
    ]
  },
    bodyParts: [
      { es: 'la cabeza', id: 'Kepala' }, { es: 'el cabello', id: 'Rambut' },
      { es: 'la frente', id: 'Dahi' }, { es: 'las cejas', id: 'Alis' },
      { es: 'los ojos', id: 'Mata' }, { es: 'la nariz', id: 'Hidung' },
      { es: 'las orejas', id: 'Telinga' }, { es: 'la boca', id: 'Mulut' },
      { es: 'los labios', id: 'Bibir' }, { es: 'los dientes', id: 'Gigi' },
      { es: 'la lengua', id: 'Lidah' }, { es: 'la barbilla', id: 'Dagu' },
      { es: 'la mejilla', id: 'Pipi' }, { es: 'el cuello', id: 'Leher' },
      { es: 'los hombros', id: 'Bahu' }, { es: 'el brazo', id: 'Lengan' },
      { es: 'el codo', id: 'Siku' }, { es: 'la muneca', id: 'Pergelangan tangan' },
      { es: 'la mano', id: 'Tangan' }, { es: 'los dedos', id: 'Jari-jari' },
      { es: 'el pecho', id: 'Dada' }, { es: 'el estomago', id: 'Perut' },
      { es: 'la espalda', id: 'Punggung' }, { es: 'la cintura', id: 'Pinggang' },
      { es: 'las caderas', id: 'Pinggul' }, { es: 'el muslo', id: 'Paha' },
      { es: 'la rodilla', id: 'Lutut' }, { es: 'la pantorrilla', id: 'Betis' },
      { es: 'el tobillo', id: 'Pergelangan kaki' }, { es: 'el pie', id: 'Kaki' },
      { es: 'los talones', id: 'Tumit' }, { es: 'los dedos del pie', id: 'Jari kaki' },
      { es: 'el corazon', id: 'Jantung' }, { es: 'los pulmones', id: 'Paru-paru' },
      { es: 'el higado', id: 'Hati' }
    ],
    clothing: [
      { es: 'el pantalon', id: 'Celana panjang' }, { es: 'la falda', id: 'Rok' },
      { es: 'la camisa', id: 'Kemeja' }, { es: 'la blusa', id: 'Blus' },
      { es: 'la camiseta', id: 'Kaos' }, { es: 'el vestido', id: 'Gaun/Baju' },
      { es: 'el sueter', id: 'Sweater' }, { es: 'la chaqueta', id: 'Jaket' },
      { es: 'el abrigo', id: 'Mantel' }, { es: 'el traje', id: 'Setelan' },
      { es: 'la corbata', id: 'Dasi' }, { es: 'el cinturon', id: 'Ikat pinggang' },
      { es: 'los zapatos', id: 'Sepatu' }, { es: 'las botas', id: 'Boots' },
      { es: 'las sandalias', id: 'Sandal' }, { es: 'los calcetines', id: 'Kaos kaki' },
      { es: 'el sombrero', id: 'Topi' }, { es: 'las gafas', id: 'Kacamata' },
      { es: 'la bufanda', id: 'Syal' }, { es: 'los guantes', id: 'Sarung tangan' },
      { es: 'la gorra', id: 'Topi baseball' }, { es: 'la playera', id: 'Kaos olahraga' },
      { es: 'los pantalones cortos', id: 'Celana pendek' },
      { es: 'el bikini', id: 'Bikini' },
      { es: 'el pijama', id: 'Piama' },
      { es: 'la ropa interior', id: 'Celana dalam' },
      { es: 'el corpiño', id: 'Bra' },
      { es: 'el uniforme', id: 'Seragam' },
      { es: 'la ropa deportiva', id: 'Pakaian olahraga' },
      { es: 'el traje de bano', id: 'Baju renang' },
      { es: 'los tenis', id: 'Sneakers' },
      { es: 'los zapatos de tacón', id: 'High heels' },
      { es: 'los mocasines', id: 'Moccasins' },
      { es: 'los vaqueros', id: 'Jeans' },
      { es: 'el cardigan', id: 'Cardigan' },
      { es: 'el blazer', id: 'Blazer' },
      { es: 'el chaleco', id: 'Rompi' },
      { es: 'los aretes', id: 'Anting-anting' },
      { es: 'el collar', id: 'Kalung' },
      { es: 'el anillo', id: 'Cincin' },
      { es: 'la pulsera', id: 'Gelang' },
      { es: 'el reloj', id: 'Jam tangan' }
    ],
    house: [
      { es: 'el cuarto', id: 'Kamar tidur' }, { es: 'el bano', id: 'Kamar mandi' },
      { es: 'la cocina', id: 'Dapur' }, { es: 'la sala', id: 'Ruang tamu' },
      { es: 'la entrada', id: 'Pintu masuk' }, { es: 'el pasillo', id: 'Koridor' },
      { es: 'el sotano', id: 'Ruang bawah tanah' }, { es: 'el atico', id: 'Loteng' },
      { es: 'el garaje', id: 'Garasi' }, { es: 'el jardin', id: 'Taman' },
      { es: 'la terraza', id: 'Teras' }, { es: 'el balcon', id: 'Balkon' },
      { es: 'la puerta', id: 'Pintu' }, { es: 'la ventana', id: 'Jendela' },
      { es: 'la pared', id: 'Dinding' }, { es: 'el techo', id: 'Langit-langit' },
      { es: 'el suelo', id: 'Lantai' }, { es: 'la escalera', id: 'Tangga' },
      { es: 'la barandilla', id: 'Pegangan tangga' }, { es: 'el ladrillo', id: 'Bata' },
      { es: 'la chimenea', id: 'Perapian' }, { es: 'la valla', id: 'Pagar' },
      { es: 'el edificio', id: 'Gedung apartemen' },
      { es: 'el apartamento', id: 'Apartemen' },
      { es: 'la bodega', id: 'Ruang penyimpanan anggur' },
      { es: 'el cuarto de lavado', id: 'Ruang cuci' },
      { es: 'la sala de estar', id: 'Ruang keluarga' },
      { es: 'el comedor', id: 'Ruang makan' },
      { es: 'la sala de juegos', id: 'Ruang bermain' },
      { es: 'la piscina', id: 'Kolam renang' },
      { es: 'el huerto', id: 'Kebun sayur' },
      { es: 'la cortina', id: 'Gorden' },
      { es: 'la alfombra', id: 'Karpet' },
      { es: 'el mueble', id: 'Furniture' },
      { es: 'el armario', id: 'Lemari' },
      { es: 'el sofa', id: 'Sofa' },
      { es: 'la mesa', id: 'Meja' },
      { es: 'la silla', id: 'Kursi' },
      { es: 'la cama', id: 'Tempat tidur' },
      { es: 'el colchon', id: 'Matras' },
      { es: 'la almohada', id: 'Bantal' },
      { es: 'la cobija', id: 'Selimut' },
      { es: 'la sabana', id: 'Sprei' },
      { es: 'el espejo', id: 'Cermin' },
      { es: 'la estanteria', id: 'Rak' },
      { es: 'el cajon', id: 'Laci' }
    ],
    nature: [
      { es: 'el sol', id: 'Matahari' }, { es: 'la luna', id: 'Bulan' },
      { es: 'las estrellas', id: 'Bintang' }, { es: 'el cielo', id: 'Langit' },
      { es: 'el mar', id: 'Laut' }, { es: 'el oceano', id: 'Samudra' },
      { es: 'el rio', id: 'Sungai' }, { es: 'el lago', id: 'Danau' },
      { es: 'la montaña', id: 'Gunung' }, { es: 'la colina', id: 'Bukit' },
      { es: 'el valle', id: 'Lembah' }, { es: 'el desierto', id: 'Gurun' },
      { es: 'el bosque', id: 'Hutan' }, { es: 'la llanura', id: 'Dataran' },
      { es: 'el arroyo', id: 'Aliran sungai' }, { es: 'la isla', id: 'Pulau' },
      { es: 'la playa', id: 'Pantai' }, { es: 'las olas', id: 'Ombak' },
      { es: 'la arena', id: 'Pasir' }, { es: 'las rocas', id: 'Batu karang' },
      { es: 'el viento', id: 'Angin' }, { es: 'la lluvia', id: 'Hujan' },
      { es: 'la nieve', id: 'Salju' }, { es: 'el granizo', id: 'Hujan es' },
      { es: 'el arcoiris', id: 'Pelangi' }, { es: 'la nube', id: 'Awan' },
      { es: 'la tormenta', id: 'Badai' }, { es: 'la niebla', id: 'Kabut' },
      { es: 'la helada', id: 'Embun beku' }, { es: 'el hielo', id: 'Es' },
      { es: 'la tierra', id: 'Tanah' }, { es: 'el polvo', id: 'Debu' },
      { es: 'la hierba', id: 'Rumput' }, { es: 'las hojas', id: 'Daun' },
      { es: 'el musgo', id: 'Lumut' }
    ],
    animalsDomestic: [
      { es: 'el perro', id: 'Anjing' }, { es: 'el gato', id: 'Kucing' },
      { es: 'el conejo', id: 'Kelinci' }, { es: 'el pajaro', id: 'Burung' },
      { es: 'el pez', id: 'Ikan' }, { es: 'el hamster', id: 'Hamster' },
      { es: 'la tortuga', id: 'Kura-kura' }, { es: 'el caballo', id: 'Kuda' },
      { es: 'la gallina', id: 'Ayam betina' }, { es: 'el gallo', id: 'Ayam jantan' },
      { es: 'el pato', id: 'Bebek' }, { es: 'la cabra', id: 'Kambing' },
      { es: 'la oveja', id: 'Domba' }, { es: 'el cerdo', id: 'Babi' },
      { es: 'el burro', id: 'Keledai' }
    ],
    animalsWild: [
      { es: 'el leon', id: 'Singa' }, { es: 'el tigre', id: 'Harimau' },
      { es: 'el elefante', id: 'Gajah' }, { es: 'la jirafa', id: 'Jerapah' },
      { es: 'la cebra', id: 'Zebra' }, { es: 'el gorila', id: 'Gorila' },
      { es: 'el oso', id: 'Beruang' }, { es: 'el lobo', id: 'Serigala' },
      { es: 'el zorro', id: 'Rubah' }, { es: 'el ciervo', id: 'Rusa' },
      { es: 'la serpiente', id: 'Ular' }, { es: 'el cocodrilo', id: 'Buaya' },
      { es: 'el hipopotamo', id: 'Kudanil' }, { es: 'el rinoceronte', id: 'Badak' },
      { es: 'el mono', id: 'Monyet' }, { es: 'el canguro', id: 'Kanguru' },
      { es: 'el koala', id: 'Koala' }, { es: 'la hiena', id: 'Hiena' },
      { es: 'la pantera', id: 'Macan tutul' }, { es: 'el guepardo', id: 'Cheetah' },
      { es: 'el chacal', id: 'Jakal' }, { es: 'el buitre', id: 'Burung nasar' },
      { es: 'el ave de presa', id: 'Burung pemangsa' },
      { es: 'el mapache', id: 'Rakun' },
      { es: 'el puerco espin', id: 'Babi tanah' }
    ],
    animalsSea: [
      { es: 'la ballena', id: 'Paus' }, { es: 'el delfin', id: 'Lumba-lumba' },
      { es: 'el tiburon', id: 'Hiu' }, { es: 'la tortuga marina', id: 'Penyu' },
      { es: 'la foca', id: 'Anjing laut' }, { es: 'el lobo marino', id: 'Singa laut' },
      { es: 'el cangrejo', id: 'Kepiting' }, { es: 'el camaron', id: 'Udang' },
      { es: 'la ostra', id: 'Tiram' }, { es: 'el mejillon', id: 'Kerang' }
    ],
    insects: [
      { es: 'la abeja', id: 'Lebah' }, { es: 'la hormiga', id: 'Semut' },
      { es: 'la mariposa', id: 'Kupu-kupu' }, { es: 'la oruga', id: 'Ulat' },
      { es: 'la mariquita', id: 'Kepik' }, { es: 'el escarabajo', id: 'Kumbang' },
      { es: 'la mosca', id: 'Lalat' }, { es: 'el mosquito', id: 'Nyamuk' },
      { es: 'la polilla', id: 'Ngengat' }, { es: 'la langosta', id: 'Belalang' },
      { es: 'el grillo', id: 'Jangkrik' }, { es: 'la arana', id: 'Laba-laba' },
      { es: 'el escorpion', id: 'Kalajengking' }, { es: 'la chinche', id: 'Kutu busuk' },
      { es: 'la libelula', id: 'Capung' }
    ],
    foodExtended: [
      { es: 'el croissant', id: 'Croissant' }, { es: 'el baguette', id: 'Roti baguette' },
      { es: 'la brioche', id: 'Brioche' },
      { es: 'el pan con chocolate', id: 'Roti cokelat' },
      { es: 'la crepa', id: 'Kue dadar' }, { es: 'el waffle', id: 'Waffle' },
      { es: 'la quiche', id: 'Kue pai asin' },
      { es: 'el queso de cabra', id: 'Keju kambing' },
      { es: 'el camembert', id: 'Keju Camembert' },
      { es: 'el brie', id: 'Keju Brie' },
      { es: 'la ratatouille', id: 'Ratatouille' },
      { es: 'la paella', id: 'Paella' },
      { es: 'el gazpacho', id: 'Gazpacho' },
      { es: 'el churro', id: 'Churros' },
      { es: 'la tortilla', id: 'Tortilla' },
      { es: 'el jamon', id: 'Sapi masak Burgundy' },
      { es: 'el pollo asado', id: 'Ayam panggang' },
      { es: 'el pato asado', id: 'Bebek panggang' },
      { es: 'la sopa de cebolla', id: 'Sup bawang' },
      { es: 'la ensalada mixta', id: 'Salad campuran' },
      { es: 'el chorizo', id: 'Chorizo' },
      { es: 'la fabada', id: 'Fabada' },
      { es: 'el cocido', id: 'Cocido' },
      { es: 'el arroz con leche', id: 'Susu beras' },
      { es: 'el flan', id: 'Flan' },
      { es: 'la tarta de Santiago', id: 'Kue Santiago' },
      { es: 'el polvoron', id: 'Polvoron' },
      { es: 'el turrón', id: 'Turrón' },
      { es: 'el mazapan', id: 'Marzipan' },
      { es: 'la leche frita', id: 'Susu goreng' },
      { es: 'la manzana', id: 'Apel' },
      { es: 'la pera', id: 'Pir' },
      { es: 'el melocoton', id: 'Persik' },
      { es: 'la cereza', id: 'Ceri' },
      { es: 'la fresa', id: 'Stroberi' },
      { es: 'el arandano', id: 'Blueberry' },
      { es: 'la frambuesa', id: 'Raspberry' },
      { es: 'la uva', id: 'Anggur buah' },
      { es: 'el melon', id: 'Melon' },
      { es: 'la naranja', id: 'Jeruk' },
      { es: 'el limon', id: 'Lemon' },
      { es: 'la piña', id: 'Nanas' },
      { es: 'el mango', id: 'Mangga' },
      { es: 'el kiwi', id: 'Kiwi' },
      { es: 'la ciruela', id: 'Plum' },
      { es: 'la almendra', id: 'Almond' },
      { es: 'la nuez', id: 'Kenari' },
      { es: 'el avellana', id: 'Hazelnut' },
      { es: 'el cacahuete', id: 'Kacang tanah' },
      { es: 'el pistacho', id: 'Kacang pistachio' },
      { es: 'el anacardo', id: 'Kacang mete' },
      { es: 'la mermelada', id: 'Selai' },
      { es: 'la miel', id: 'Madu' },
      { es: 'la mantequilla', id: 'Mentega' },
      { es: 'la harina', id: 'Tepung' },
      { es: 'el aceite de oliva', id: 'Minyak zaitun' },
      { es: 'el vinagre', id: 'Cuka' },
      { es: 'la mostaza', id: 'Mustard' },
      { es: 'el ketchup', id: 'Kecap' },
      { es: 'la mayonesa', id: 'Mayones' },
      { es: 'la nata', id: 'Krim asam' }
    ],
    transportation: [
      { es: 'el coche', id: 'Mobil' }, { es: 'el camion', id: 'Truk' },
      { es: 'el autobus', id: 'Bus' }, { es: 'el metro', id: 'Kereta bawah tanah' },
      { es: 'el tren', id: 'Kereta api' }, { es: 'el tranvia', id: 'Trem' },
      { es: 'el taxi', id: 'Taksi' }, { es: 'el avion', id: 'Pesawat' },
      { es: 'el barco', id: 'Kapal' }, { es: 'la bicicleta', id: 'Sepeda' },
      { es: 'la moto', id: 'Motor' }, { es: 'la scooter', id: 'Skuter' },
      { es: 'el ferry', id: 'Kapal feri' }, { es: 'el yate', id: 'Kapal pesiar' },
      { es: 'la teleferica', id: 'Kereta gantung' },
      { es: 'el tren de alta velocidad', id: 'Kereta cepat' },
      { es: 'el helicoptero', id: 'Helikopter' },
      { es: 'el dirigible', id: 'Balon udara' },
      { es: 'el submarino', id: 'Kapal selam' },
      { es: 'el carguero', id: 'Kapal kargo' },
      { es: 'el transatlantico', id: 'Kapal pesiar besar' },
      { es: 'la ambulancia', id: 'Ambulans' },
      { es: 'el camion de bomberos', id: 'Truk pemadam' },
      { es: 'el camion de basura', id: 'Truk sampah' },
      { es: 'el tractor', id: 'Traktor' },
      { es: 'el vehiculo', id: 'Kendaraan' },
      { es: 'la autopista', id: 'Jalan tol' },
      { es: 'la carretera', id: 'Jalan raya' },
      { es: 'la calle', id: 'Jalan kota' },
      { es: 'la interseccion', id: 'Perempatan' },
      { es: 'la rotonda', id: 'Bundaran' },
      { es: 'el estacionamiento', id: 'Parkir' },
      { es: 'el paso de peatones', id: 'Penyeberangan pejalan kaki' },
      { es: 'el semaforo en rojo', id: 'Lampu merah' },
      { es: 'el semaforo en verde', id: 'Lampu hijau' },
      { es: 'la señal de transito', id: 'Rambu lalu lintas' },
      { es: 'el cinturon de seguridad', id: 'Sabuk pengaman' },
      { es: 'la licencia de conducir', id: 'Surat izin mengemudi' },
      { es: 'la gasolina', id: 'Bensin' },
      { es: 'el tanque lleno', id: 'Isi penuh' },
      { es: 'el motor', id: 'Mesin' },
      { es: 'la rueda', id: 'Roda' }
    ],
    technology: [
      { es: 'el ordenador', id: 'Komputer' }, { es: 'la pantalla', id: 'Layar' },
      { es: 'el teclado', id: 'Keyboard' }, { es: 'el raton', id: 'Mouse' },
      { es: 'la impresora', id: 'Printer' }, { es: 'el telefono', id: 'Telepon' },
      { es: 'el movil', id: 'HP' }, { es: 'la tableta', id: 'Tablet' },
      { es: 'el internet', id: 'Internet' }, { es: 'la red', id: 'Jaringan' },
      { es: 'la conexion', id: 'Koneksi' }, { es: 'el wifi', id: 'Wifi' },
      { es: 'la aplicacion', id: 'Aplikasi' }, { es: 'el software', id: 'Perangkat lunak' },
      { es: 'el hardware', id: 'Perangkat keras' },
      { es: 'la pantalla tactil', id: 'Layar sentuh' },
      { es: 'el procesador', id: 'Prosesor' },
      { es: 'la memoria', id: 'Memori' },
      { es: 'el disco duro', id: 'Hard disk' },
      { es: 'el pendrive', id: 'Flashdisk' },
      { es: 'la camara', id: 'Kamera' },
      { es: 'el video', id: 'Video' },
      { es: 'la foto', id: 'Foto' },
      { es: 'los auriculares', id: 'Headset' },
      { es: 'los cascos', id: 'Earphone' },
      { es: 'los altavoces', id: 'Speaker' },
      { es: 'el cargador', id: 'Charger' },
      { es: 'la bateria', id: 'Baterai' },
      { es: 'la pantalla de inicio', id: 'Home screen' },
      { es: 'la contrasena', id: 'Password' },
      { es: 'la direccion de correo', id: 'Alamat email' },
      { es: 'el navegador', id: 'Browser' },
      { es: 'la pagina web', id: 'Halaman web' },
      { es: 'el sitio web', id: 'Situs web' },
      { es: 'el blog', id: 'Blog' },
      { es: 'la red social', id: 'Jejaring sosial' },
      { es: 'el mensaje', id: 'Pesan' },
      { es: 'el correo electronico', id: 'Email' },
      { es: 'el archivo adjunto', id: 'Lampiran' },
      { es: 'descargar', id: 'Mengunduh' },
      { es: 'actualizar', id: 'Memperbarui' },
      { es: 'guardar', id: 'Menyimpan' },
      { es: 'enviar', id: 'Mengirim' },
      { es: 'eliminar', id: 'Menghapus' },
      { es: 'imprimir', id: 'Mencetak' }
    ],
    schoolEducation: [
      { es: 'la escuela', id: 'Sekolah' }, { es: 'la universidad', id: 'Universitas' },
      { es: 'el aula', id: 'Kelas' }, { es: 'la pizarra', id: 'Papan tulis' },
      { es: 'el escritorio', id: 'Meja guru' }, { es: 'la silla', id: 'Kursi' },
      { es: 'el libro', id: 'Buku' }, { es: 'el cuaderno', id: 'Buku tulis' },
      { es: 'el boligrafo', id: 'Pena' }, { es: 'el lapiz', id: 'Pensil' },
      { es: 'el borrador', id: 'Penghapus' }, { es: 'la regla', id: 'Penggaris' },
      { es: 'la mochila', id: 'Tas punggung' },
      { es: 'el estuche', id: 'Tempat pensil' },
      { es: 'la geometria', id: 'Alat gambar' },
      { es: 'el compas', id: 'Jangka' },
      { es: 'la ecuacion', id: 'Persamaan matematika' },
      { es: 'la fraccion', id: 'Pecahan' },
      { es: 'el resultado', id: 'Hasil' },
      { es: 'la media', id: 'Nilai rata-rata' },
      { es: 'la nota', id: 'Nilai' },
      { es: 'el deber', id: 'PR' },
      { es: 'el examen', id: 'Ujian' },
      { es: 'el curso', id: 'Kursus' },
      { es: 'la materia', id: 'Mata pelajaran' },
      { es: 'el espanol', id: 'Bahasa Spanyol' },
      { es: 'las matematicas', id: 'Matematika' },
      { es: 'la fisica', id: 'Fisika' },
      { es: 'la quimica', id: 'Kimia' },
      { es: 'la biologia', id: 'Biologi' },
      { es: 'la historia', id: 'Sejarah' },
      { es: 'la geografia', id: 'Geografi' },
      { es: 'el ingles', id: 'Bahasa Inggris' },
      { es: 'el arte', id: 'Seni' },
      { es: 'la musica', id: 'Musik' },
      { es: 'la educacion fisica', id: 'Pendidikan jasmani' },
      { es: 'la filosofia', id: 'Filsafat' },
      { es: 'la economia', id: 'Ekonomi' },
      { es: 'el semestre', id: 'Semester' },
      { es: 'el campus', id: 'Kampus' },
      { es: 'la biblioteca', id: 'Perpustakaan' },
      { es: 'la cafeteria', id: 'Kantin' },
      { es: 'la inscription', id: 'Pendaftaran' },
      { es: 'el titulo', id: 'Gelar' },
      { es: 'la tesis', id: 'Tesis' },
      { es: 'la practica', id: 'Magang' },
      { es: 'el profesor', id: 'Guru besar' },
      { es: 'el rector', id: 'Rektor' },
      { es: 'el alumno', id: 'Siswa' },
      { es: 'el compañero', id: 'Teman sekelas' }
    ],
    workOffice: [
      { es: 'la oficina', id: 'Kantor' }, { es: 'la reunion', id: 'Rapat' },
      { es: 'el jefe', id: 'Atasan' }, { es: 'el compañero de trabajo', id: 'Rekan kerja' },
      { es: 'el salario', id: 'Gaji' }, { es: 'el empleo', id: 'Pekerjaan' },
      { es: 'el contrato', id: 'Kontrak' }, { es: 'las vacaciones', id: 'Liburan' },
      { es: 'el permiso', id: 'Cuti' }, { es: 'el horario', id: 'Jam kerja' },
      { es: 'el descanso', id: 'Istirahat' },
      { es: 'la pausa para el cafe', id: 'Istirahat kopi' },
      { es: 'la entrevista', id: 'Wawancara kerja' },
      { es: 'la solicitud', id: 'Lamaran kerja' },
      { es: 'el curriculum', id: 'Curriculum vitae' },
      { es: 'la carta de motivacion', id: 'Surat motivasi' },
      { es: 'la promocion', id: 'Promosi' },
      { es: 'el despido', id: 'PHK' },
      { es: 'la dimision', id: 'Mengundurkan diri' },
      { es: 'el departamento', id: 'Departemen' },
      { es: 'el proyecto', id: 'Proyek' },
      { es: 'el fracaso', id: 'Kegagalan' },
      { es: 'el exito', id: 'Keberhasilan' },
      { es: 'la evaluacion', id: 'Penilaian' },
      { es: 'el rendimiento', id: 'Pencapaian' },
      { es: 'la ambicion', id: 'Ambisi' },
      { es: 'el triunfo', id: 'Kesuksesan' },
      { es: 'el pago', id: 'Bayaran' },
      { es: 'el impuesto', id: 'Pajak' },
      { es: 'el seguro medico', id: 'Asuransi kesehatan' },
      { es: 'el bono', id: 'Bonus' },
      { es: 'el fin de ano', id: 'Akhir tahun' },
      { es: 'la caja', id: 'Meja kasir' },
      { es: 'el armario', id: 'Lemari arsip' },
      { es: 'el archivador', id: 'Map' }
    ],
    sportsActivities: [
      { es: 'el futbol', id: 'Sepak bola' }, { es: 'el baloncesto', id: 'Basket' },
      { es: 'el tenis', id: 'Tenis' }, { es: 'el voleibol', id: 'Voli' },
      { es: 'el atletismo', id: 'Atletik' }, { es: 'la natacion', id: 'Renang' },
      { es: 'el rugby', id: 'Ragbi' }, { es: 'el balonmano', id: 'Bola tangan' },
      { es: 'la esgrima', id: 'Anggar' }, { es: 'la equitacion', id: 'Berkuda' },
      { es: 'el golf', id: 'Golf' }, { es: 'el esqui', id: 'Ski' },
      { es: 'el snowboard', id: 'Snowboard' }, { es: 'el surf', id: 'Selancar' },
      { es: 'el judo', id: 'Judo' }, { es: 'el karate', id: 'Karate' },
      { es: 'el boxeo', id: 'Tinju' }, { es: 'la lucha libre', id: 'Gulat' },
      { es: 'la gimnasia', id: 'Senam' }, { es: 'el yoga', id: 'Yoga' },
      { es: 'el ciclismo', id: 'Bersepeda' }, { es: 'el halterofilia', id: 'Angkat besi' },
      { es: 'la carrera', id: 'Lari' }, { es: 'la caminata', id: 'Jalan kaki' },
      { es: 'el alpinismo', id: 'Mendaki' }, { es: 'la escalada', id: 'Panjat tebing' },
      { es: 'el buceo', id: 'Selam' }, { es: 'la vela', id: 'Layar' },
      { es: 'el remo', id: 'Mendayung' }, { es: 'el piragüismo', id: 'Kano' },
      { es: 'el kayak', id: 'Kajak' }, { es: 'el tiro con arco', id: 'Panahan' },
      { es: 'el tiro', id: 'Menembak' }, { es: 'el patinaje', id: 'Seluncur es' },
      { es: 'el hockey', id: 'Hoki' }, { es: 'el beisbol', id: 'Baseball' },
      { es: 'el cricket', id: 'Kriket' }, { es: 'el bádminton', id: 'Bulutangkis' },
      { es: 'el ping pong', id: 'Pingpong' },
      { es: 'el billar', id: 'Bilyar' },
      { es: 'el bowling', id: 'Boling' },
      { es: 'el baile', id: 'Tari' },
      { es: 'el skateboard', id: 'Skateboard' },
      { es: 'el patinaje sobre ruedas', id: 'Inline skate' },
      { es: 'el ultimate frisbee', id: 'Frisbee' }
    ],
    hobbiesLeisure: [
      { es: 'la lectura', id: 'Membaca' }, { es: 'la escritura', id: 'Menulis' },
      { es: 'la pintura', id: 'Melukis' }, { es: 'el dibujo', id: 'Menggambar' },
      { es: 'el cine', id: 'Nonton film' }, { es: 'la musica', id: 'Dengar musik' },
      { es: 'los videojuegos', id: 'Main game' }, { es: 'la fotografia', id: 'Fotografi' },
      { es: 'la jardineria', id: 'Berkebun' }, { es: 'la costura', id: 'Menjahit' },
      { es: 'el tejido', id: 'Merajut' }, { es: 'el bordado', id: 'Menyulam' },
      { es: 'el bricolaje', id: 'DIY/perbaikan' },
      { es: 'la coleccion', id: 'Koleksi' },
      { es: 'el modelismo', id: 'Model kit' },
      { es: 'la filatelia', id: 'Filateli (perangko)' },
      { es: 'la acuariofilia', id: 'Hobi ikan' },
      { es: 'la petanca', id: 'Petanque' },
      { es: 'los ajedrez', id: 'Catur' },
      { es: 'las cartas', id: 'Main kartu' },
      { es: 'la meditacion', id: 'Meditasi' },
      { es: 'el aire libre', id: 'Alam terbuka' },
      { es: 'la excursion', id: 'Hiking' },
      { es: 'el picnic', id: 'Piknik' },
      { es: 'el camping', id: 'Berkemah' },
      { es: 'la pesca', id: 'Memancing' },
      { es: 'la caza', id: 'Berburu' },
      { es: 'el baile', id: 'Menari' },
      { es: 'el yoga', id: 'Yoga' },
      { es: 'la ceramica', id: 'Keramik' }
    ],
    healthMedical: [
      { es: 'la salud', id: 'Kesehatan' }, { es: 'la enfermedad', id: 'Penyakit' },
      { es: 'el resfriado', id: 'Pilek' }, { es: 'la gripe', id: 'Flu' },
      { es: 'la fiebre', id: 'Demam' }, { es: 'la tos', id: 'Batuk' },
      { es: 'el dolor de cabeza', id: 'Sakit kepala' },
      { es: 'el dolor de espalda', id: 'Sakit punggung' },
      { es: 'el dolor de estomago', id: 'Sakit perut' },
      { es: 'la nausea', id: 'Mual' },
      { es: 'el vomito', id: 'Muntah' },
      { es: 'la diarrea', id: 'Diare' },
      { es: 'el estrenimiento', id: 'Sembelit' },
      { es: 'la alergia', id: 'Alergi' },
      { es: 'el asma', id: 'Asma' },
      { es: 'la diabetes', id: 'Diabetes' },
      { es: 'la hipertension', id: 'Hipertensi' },
      { es: 'la infeccion', id: 'Infeksi' },
      { es: 'la herida', id: 'Luka' },
      { es: 'la cicatriz', id: 'Bekas luka' },
      { es: 'el raspón', id: 'Luka lecet' },
      { es: 'el corte', id: 'Goresan' },
      { es: 'la ampolla', id: 'Gelembung' },
      { es: 'el moreton', id: 'Memar' },
      { es: 'la hinchazon', id: 'Bengkak' },
      { es: 'el mareo', id: 'Pusing' },
      { es: 'el insomnio', id: 'Insomnia' },
      { es: 'el cansancio', id: 'Kelelahan' },
      { es: 'el estres', id: 'Stres' },
      { es: 'la depresion', id: 'Depresi' },
      { es: 'la ansiedad', id: 'Kecemasan' },
      { es: 'el tratamiento', id: 'Perawatan' },
      { es: 'la receta', id: 'Resep' },
      { es: 'el antibiotico', id: 'Antibiotik' },
      { es: 'la aspirina', id: 'Aspirin' },
      { es: 'el paracetamol', id: 'Parasetamol' },
      { es: 'la pomada', id: 'Salep' },
      { es: 'la vendaja', id: 'Perban' },
      { es: 'la inyeccion', id: 'Suntikan' },
      { es: 'la perfusion', id: 'Infus' },
      { es: 'el analisis', id: 'Pemeriksaan' },
      { es: 'la radiografia', id: 'Rontgen' },
      { es: 'el ecograma', id: 'USG' },
      { es: 'la resonancia', id: 'MRI' },
      { es: 'la cirugia', id: 'Operasi' },
      { es: 'la anestesia', id: 'Anestesi' },
      { es: 'la curacion', id: 'Penyembuhan' },
      { es: 'la convalecencia', id: 'Masa pemulihan' },
      { es: 'la vacuna', id: 'Vaksin' }
    ],
    professionsExtended: [
      { es: 'el enfermero/enfermera', id: 'Perawat' },
      { es: 'el arquitecto', id: 'Arsitek' },
      { es: 'el farmaceutico', id: 'Apoteker' },
      { es: 'el dentista', id: 'Dokter gigi' },
      { es: 'el veterinario', id: 'Dokter hewan' },
      { es: 'el optico', id: 'Ahli kacamata' },
      { es: 'el contable', id: 'Akuntan' },
      { es: 'el agente inmobiliario', id: 'Agen properti' },
      { es: 'el banquero', id: 'Bankir' },
      { es: 'el asegurador', id: 'Agen asuransi' },
      { es: 'el empresario', id: 'Pengusaha' },
      { es: 'el gerente', id: 'Manajer' },
      { es: 'el asistente', id: 'Asisten' },
      { es: 'el secretario', id: 'Sekretaris' },
      { es: 'el comercial', id: 'Sales' },
      { es: 'el desarrollador', id: 'Developer' },
      { es: 'el disenador', id: 'Desainer' },
      { es: 'el disenador grafico', id: 'Desainer grafis' },
      { es: 'el fotografo', id: 'Fotografer' },
      { es: 'el videgrafo', id: 'Videografer' },
      { es: 'el influencer', id: 'Influencer' },
      { es: 'el youtuber', id: 'YouTuber' },
      { es: 'el barista', id: 'Barista' },
      { es: 'el electricista', id: 'Tukang listrik' },
      { es: 'el fontanero', id: 'Tukang ledeng' },
      { es: 'el carpintero', id: 'Tukang kayu' },
      { es: 'el albañil', id: 'Tukang batu' },
      { es: 'el pintor', id: 'Tukang cat' },
      { es: 'el costurero', id: 'Penjahit' },
      { es: 'el peluquero', id: 'Tukang potong rambut' },
      { es: 'el joyero', id: 'Perhiasan' },
      { es: 'el relojero', id: 'Ahli jam' },
      { es: 'el mecanico', id: 'Montir mobil' },
      { es: 'el obrero', id: 'Pekerja' },
      { es: 'el tecnico', id: 'Teknisi' },
      { es: 'el operador', id: 'Operator' },
      { es: 'el inspector', id: 'Petugas' },
      { es: 'el capataz', id: 'Mandor' },
      { es: 'el supervisor', id: 'Supervisor' },
      { es: 'el subdirector', id: 'Wakil direktur' }
    ],
    cityPlaces: [
      { es: 'la ciudad', id: 'Kota' }, { es: 'el pueblo', id: 'Desa' },
      { es: 'la plaza', id: 'Alun-alun' },
      { es: 'la avenida', id: 'Jalan utama' },
      { es: 'el bulevar', id: 'Boulevard' },
      { es: 'el paseo', id: 'Jalan setapak' },
      { es: 'el parque', id: 'Taman kota' },
      { es: 'la fuente', id: 'Air mancur' },
      { es: 'la estatua', id: 'Patung' },
      { es: 'el monumento', id: 'Monumen' },
      { es: 'la catedral', id: 'Katedral' },
      { es: 'la mezquita', id: 'Masjid' },
      { es: 'la sinagoga', id: 'Sinagoge' },
      { es: 'el ayuntamiento', id: 'Balai kota' },
      { es: 'el tribunal', id: 'Pengadilan' },
      { es: 'el cuartel', id: 'K barak' },
      { es: 'el estadio', id: 'Stadion' },
      { es: 'el gimnasio', id: 'Pusat kebugaran' },
      { es: 'el centro comercial', id: 'Mall' },
      { es: 'la tienda de moda', id: 'Butik' },
      { es: 'la galeria', id: 'Galeri' },
      { es: 'la exposicion', id: 'Pameran' },
      { es: 'el teatro', id: 'Teater' },
      { es: 'la opera', id: 'Opera' },
      { es: 'la sala de conciertos', id: 'Gedung konser' },
      { es: 'el circo', id: 'Sirkus' },
      { es: 'el zoologico', id: 'Kebun binatang' },
      { es: 'el acuario', id: 'Akuarium' },
      { es: 'el planetario', id: 'Planetarium' },
      { es: 'el museo', id: 'Museum' }
    ],
    weatherClimate: [
      { es: 'el tiempo', id: 'Cuaca' }, { es: 'el clima', id: 'Iklim' },
      { es: 'el calor', id: 'Panas' }, { es: 'el frio', id: 'Dingin' },
      { es: 'la sequedad', id: 'Kering' }, { es: 'la humedad', id: 'Kelembaban' },
      { es: 'la primavera', id: 'Musim semi' },
      { es: 'el verano', id: 'Musim panas' },
      { es: 'el otoño', id: 'Musim gugur' },
      { es: 'el invierno', id: 'Musim dingin' },
      { es: 'la temperatura', id: 'Suhu' },
      { es: 'los grados', id: 'Derajat' },
      { es: 'las nubes', id: 'Awan' },
      { es: 'la llovizna', id: 'Gerimis' },
      { es: 'la tormenta', id: 'Badai petir' },
      { es: 'el rayo', id: 'Petir' },
      { es: 'el trueno', id: 'Guntur' },
      { es: 'la nieve derretida', id: 'Salju mencair' },
      { es: 'el hielo', id: 'Es jalan' },
      { es: 'la escarcha', id: 'Embun beku' },
      { es: 'la helada', id: 'Es' },
      { es: 'la ola de calor', id: 'Gelombang panas' },
      { es: 'el frio polar', id: 'Dingin ekstrem' },
      { es: 'el monzon', id: 'Monsoon' },
      { es: 'la sequia', id: 'Kekeringan' },
      { es: 'la inundacion', id: 'Banjir' },
      { es: 'el tornado', id: 'Tornado' },
      { es: 'el huracan', id: 'Badai' },
      { es: 'el tsunami', id: 'Tsunami' },
      { es: 'el terremoto', id: 'Gempa bumi' }
    ],
    timeExtended: [
      { es: 'el segundo', id: 'Detik' }, { es: 'el minuto', id: 'Menit' },
      { es: 'la hora', id: 'Jam' }, { es: 'el dia', id: 'Hari' },
      { es: 'la semana', id: 'Minggu' }, { es: 'el mes', id: 'Bulan' },
      { es: 'el ano', id: 'Tahun' }, { es: 'el siglo', id: 'Abad' },
      { es: 'la manana', id: 'Pagi' }, { es: 'la tarde', id: 'Siang' },
      { es: 'la noche', id: 'Sore/Malam' },
      { es: 'hoy', id: 'Hari ini' }, { es: 'ayer', id: 'Kemarin' },
      { es: 'manana', id: 'Besok' }, { es: 'la proxima semana', id: 'Minggu depan' },
      { es: 'el proximo mes', id: 'Bulan depan' },
      { es: 'el proximo ano', id: 'Tahun depan' },
      { es: 'el fin de semana', id: 'Akhir pekan' },
      { es: 'las vacaciones', id: 'Liburan' },
      { es: 'el comienzo', id: 'Awal' },
      { es: 'el fin', id: 'Akhir' },
      { es: 'el medio', id: 'Tengah' },
      { es: 'temprano', id: 'Pagi-pagi' },
      { es: 'tarde', id: 'Larut malam' },
      { es: 'pronto', id: 'Lebih awal' },
      { es: 'atrasado', id: 'Terlambat' },
      { es: 'a tiempo', id: 'Tepat waktu' },
      { es: 'hace', id: 'Yang lalu' },
      { es: 'en', id: 'Dalam waktu' },
      { es: 'siempre', id: 'Selalu' }
    ],
    directionsPositions: [
      { es: 'arriba', id: 'Di atas' }, { es: 'abajo', id: 'Di bawah' },
      { es: 'al lado', id: 'Di sebelah' }, { es: 'enfrente', id: 'Di depan' },
      { es: 'detras', id: 'Di belakang' }, { es: 'en el medio', id: 'Di tengah' },
      { es: 'a la izquierda', id: 'Di kiri' }, { es: 'a la derecha', id: 'Di kanan' },
      { es: 'cerca', id: 'Dekat' }, { es: 'lejos', id: 'Jauh' },
      { es: 'dentro', id: 'Di dalam' }, { es: 'fuera', id: 'Di luar' },
      { es: 'alrededor', id: 'Di sekitar' }, { es: 'a traves de', id: 'Menembus' },
      { es: 'hacia', id: 'Ke arah' },
      { es: 'frente a', id: 'Seberang' },
      { es: 'en opuesto a', id: 'Bertentangan dengan' },
      { es: 'en proximidad a', id: 'Di dekat' },
      { es: 'a distancia', id: 'Di kejauhan' },
      { es: 'en el borde de', id: 'Di tepi' },
      { es: 'en la esquina de', id: 'Di sudut' },
      { es: 'en el centro de', id: 'Di pusat' },
      { es: 'en el interior', id: 'Di dalam ruangan' },
      { es: 'en el exterior', id: 'Di luar ruangan' },
      { es: 'entre', id: 'Di antara' }
    ],
    quantitiesMeasurements: [
      { es: 'mucho', id: 'Banyak' }, { es: 'poco', id: 'Sedikit' },
      { es: 'demasiado', id: 'Terlalu banyak' },
      { es: 'suficiente', id: 'Cukup' },
      { es: 'un poco', id: 'Sedikit' },
      { es: 'la mitad', id: 'Setengah' },
      { es: 'un cuarto', id: 'Seperempat' },
      { es: 'un tercio', id: 'Seperiga' },
      { es: 'un decimo', id: 'Sepersepuluh' },
      { es: 'un centesimo', id: 'Perseratus' },
      { es: 'un millon', id: 'Sejuta' },
      { es: 'un mil millones', id: 'Sejuta juta' },
      { es: 'el doble', id: 'Dua kali lipat' },
      { es: 'la mitad menos', id: 'Setengahnya' },
      { es: 'un kilo', id: 'Se-kilo' },
      { es: 'un litro', id: 'Se-liter' },
      { es: 'un metro', id: 'Se-meter' },
      { es: 'un centimetro', id: 'Se-sentimeter' },
      { es: 'un kilometro', id: 'Se-kilometer' },
      { es: 'un gramo', id: 'Se-gram' },
      { es: 'una tonelada', id: 'Se-ton' },
      { es: 'un punado', id: 'Segenggam' },
      { es: 'un monton', id: 'Segunungan' },
      { es: 'una docena', id: 'Kira-kira dua belas' },
      { es: 'una veintena', id: 'Kira-kira dua puluh' }
    ],
    adjectivesDescriptions: [
      { es: 'grande', id: 'Besar/Tinggi' }, { es: 'pequeño', id: 'Kecil' },
      { es: 'largo', id: 'Panjang' }, { es: 'corto', id: 'Pendek' },
      { es: 'ancho', id: 'Lebar' }, { es: 'estrecho', id: 'Sempit' },
      { es: 'grueso', id: 'Tebal' }, { es: 'delgado', id: 'Tipis' },
      { es: 'pesado', id: 'Berat' }, { es: 'ligero', id: 'Ringan' },
      { es: 'caro', id: 'Mahal' }, { es: 'barato', id: 'Murah' },
      { es: 'bueno', id: 'Bagus/Baik' }, { es: 'malo', id: 'Buruk/Jahat' },
      { es: 'nuevo', id: 'Baru' }, { es: 'viejo', id: 'Tua/Lama' },
      { es: 'joven', id: 'Muda' }, { es: 'rapido', id: 'Cepat' },
      { es: 'lento', id: 'Lambat' }, { es: 'facil', id: 'Mudah' },
      { es: 'dificil', id: 'Sulit' }, { es: 'importante', id: 'Penting' },
      { es: 'interesante', id: 'Menarik' }, { es: 'aburrido', id: 'Membosankan' },
      { es: 'completo', id: 'Lengkap' }, { es: 'simple', id: 'Sederhana' },
      { es: 'complicado', id: 'Sulit/Kompleks' }, { es: 'rico', id: 'Kaya' },
      { es: 'pobre', id: 'Miskin' }, { es: 'sucio', id: 'Kotor' },
      { es: 'limpio', id: 'Bersih' }, { es: 'calmado', id: 'Tenang' },
      { es: 'ruidoso', id: 'Berisik' }, { es: 'fuerte', id: 'Kuat' },
      { es: 'debil', id: 'Lemah' }, { es: 'magnifico', id: 'Menakjubkan' },
      { es: 'guapo', id: 'Tampan' }, { es: 'bonito', id: 'Cantik' },
      { es: 'feo', id: 'Jelek' }, { es: 'promedio', id: 'Sedang/Rata-rata' },
      { es: 'redondo', id: 'Bulat' }, { es: 'cuadrado', id: 'Persegi' },
      { es: 'plano', id: 'Datar' }, { es: 'duro', id: 'Keras' },
      { es: 'blando', id: 'Lunak' }, { es: 'seco', id: 'Kering' },
      { es: 'mojado', id: 'Basah' }, { es: 'caliente', id: 'Panas' },
      { es: 'frio', id: 'Dingin' }, { es: 'fresco', id: 'Sejuk' }
    ],
    verbsExtended: [
      { es: 'querer', id: 'Menyukai' }, { es: 'adorar', id: 'Sangat menyukai' },
      { es: 'preferir', id: 'Lebih suka' }, { es: 'odiar', id: 'Membenci' },
      { es: 'pensar', id: 'Berpikir' }, { es: 'creer', id: 'Percaya' },
      { es: 'conocer', id: 'Mengenal' }, { es: 'aprender', id: 'Belajar' },
      { es: 'ensenar', id: 'Mengajar' }, { es: 'explicar', id: 'Menjelaskan' },
      { es: 'hablar', id: 'Bicara' }, { es: 'escuchar', id: 'Mendengarkan' },
      { es: 'oír', id: 'Mendengar' }, { es: 'leer', id: 'Membaca' },
      { es: 'escribir', id: 'Menulis' }, { es: 'describir', id: 'Mendeskripsikan' },
      { es: 'buscar', id: 'Mencari' }, { es: 'encontrar', id: 'Menemukan' },
      { es: 'perder', id: 'Kehilangan' }, { es: 'guardar', id: 'Menjaga' },
      { es: 'tirar', id: 'Membuang' }, { es: 'limpiar', id: 'Membersihkan' },
      { es: 'romper', id: 'Memecahkan' }, { es: 'reparar', id: 'Memperbaiki' },
      { es: 'construir', id: 'Membangun' }, { es: 'destruir', id: 'Menghancurkan' },
      { es: 'crear', id: 'Menciptakan' }, { es: 'inventar', id: 'Menciptakan' },
      { es: 'elegir', id: 'Memilih' }, { es: 'decidir', id: 'Memutuskan' },
      { es: 'intentar', id: 'Mencoba' }, { es: 'lograr', id: 'Berhasil' },
      { es: 'fracasar', id: 'Gagal' }, { es: 'comenzar', id: 'Memulai' },
      { es: 'terminar', id: 'Selesai' }, { es: 'continuar', id: 'Melanjutkan' },
      { es: 'parar', id: 'Berhenti' }, { es: 'esperar', id: 'Menunggu' },
      { es: 'apresurarse', id: 'Terburu-buru' },
      { es: 'volver', id: 'Kembali' },
      { es: 'viajar', id: 'Bepergian' }, { es: 'visitar', id: 'Mengunjungi' },
      { es: 'vivir', id: 'Tinggal' }, { es: 'mudarse', id: 'Pindah' },
      { es: 'nadar', id: 'Berenang' }, { es: 'correr', id: 'Berlari' },
      { es: 'caminar', id: 'Berjalan' }, { es: 'saltar', id: 'Melompat' },
      { es: 'caer', id: 'Jatuh' }, { es: 'levantarse', id: 'Bangun' },
      { es: 'sentarse', id: 'Duduk' }, { es: 'dormir', id: 'Tidur' },
      { es: 'despertarse', id: 'Bangun tidur' }, { es: 'comer', id: 'Makan' },
      { es: 'beber', id: 'Minum' }, { es: 'cocinar', id: 'Memasak' },
      { es: 'comprar', id: 'Membeli' }, { es: 'vender', id: 'Menjual' },
      { es: 'pagar', id: 'Membayar' }, { es: 'depositar', id: 'Menyetor' },
      { es: 'retirar', id: 'Menarik tunai' }, { es: 'transferir', id: 'Transfer' },
      { es: 'enviar', id: 'Mengirim' }, { es: 'recibir', id: 'Menerima' },
      { es: 'ofrecer', id: 'Memberikan hadiah' }, { es: 'compartir', id: 'Berbagi' },
      { es: 'ayudar', id: 'Membantu' }, { es: 'apoyar', id: 'Mendukung' },
      { es: 'animar', id: 'Mendorong' }, { es: 'castigar', id: 'Menghukum' },
      { es: 'recompensar', id: 'Memberi penghargaan' },
      { es: 'comparar', id: 'Membandingkan' },
      { es: 'evaluar', id: 'Mengevaluasi' },
      { es: 'medir', id: 'Mengukur' }
    ],
    abstractConcepts: [
      { es: 'la libertad', id: 'Kebebasan' }, { es: 'la igualdad', id: 'Kesetaraan' },
      { es: 'la fraternidad', id: 'Persaudaraan' }, { es: 'la justicia', id: 'Keadilan' },
      { es: 'la verdad', id: 'Kebenaran' }, { es: 'la mentira', id: 'Kebohongan' },
      { es: 'la paz', id: 'Perdamaian' }, { es: 'la guerra', id: 'Perang' },
      { es: 'la esperanza', id: 'Harapan' }, { es: 'el coraje', id: 'Keberanian' },
      { es: 'el miedo', id: 'Ketakutan' }, { es: 'la felicidad', id: 'Kebahagiaan' },
      { es: 'la desgracia', id: 'Kesengsaraan' }, { es: 'el amor', id: 'Cinta' },
      { es: 'el odio', id: 'Kebencian' }, { es: 'los celos', id: 'Kecemburuan' },
      { es: 'el orgullo', id: 'Kesombongan' }, { es: 'la humildad', id: 'Kerendahan hati' },
      { es: 'la paciencia', id: 'Kesabaran' }, { es: 'la ira', id: 'Kemarahan' },
      { es: 'el respeto', id: 'Penghormatan' }, { es: 'la confianza', id: 'Kepercayaan' },
      { es: 'la lealtad', id: 'Kesetiaan' }, { es: 'la generosidad', id: 'Kedermawanan' },
      { es: 'la integridad', id: 'Integritas' }, { es: 'la compasion', id: 'Belas kasih' },
      { es: 'la determinacion', id: 'Determinasi' }, { es: 'la imaginacion', id: 'Imajinasi' },
      { es: 'la creatividad', id: 'Kreativitas' }, { es: 'la sabiduria', id: 'Kebijaksanaan' }
    ],
  quizzes: {
    colors: {
      title: 'Warna dalam Bahasa Spanyol',
      icon: '🎨',
      questions: [
        { q: 'Merah dalam bahasa Spanyol adalah?', options: ['Azul', 'Rojo', 'Verde', 'Negro'], answer: 1 },
        { q: 'Biru dalam bahasa Spanyol adalah?', options: ['Rojo', 'Amarillo', 'Azul', 'Rosa'], answer: 2 },
        { q: 'Hijau dalam bahasa Spanyol adalah?', options: ['Verde', 'Negro', 'Blanco', 'Naranja'], answer: 0 },
        { q: 'Kuning dalam bahasa Spanyol adalah?', options: ['Gris', 'Amarillo', 'Rosa', 'Marron'], answer: 1 },
        { q: 'Hitam dalam bahasa Spanyol adalah?', options: ['Blanco', 'Negro', 'Gris', 'Naranja'], answer: 1 },
        { q: 'Putih dalam bahasa Spanyol adalah?', options: ['Rosa', 'Marron', 'Blanco', 'Rojo'], answer: 2 },
        { q: 'Abu-abu dalam bahasa Spanyol adalah?', options: ['Gris', 'Verde', 'Azul', 'Negro'], answer: 0 },
        { q: 'Oranye dalam bahasa Spanyol adalah?', options: ['Amarillo', 'Naranja', 'Rosa', 'Marron'], answer: 1 },
        { q: 'Merah muda dalam bahasa Spanyol adalah?', options: ['Rojo', 'Rosa', 'Blanco', 'Gris'], answer: 1 },
        { q: 'Cokelat dalam bahasa Spanyol adalah?', options: ['Negro', 'Marron', 'Naranja', 'Gris'], answer: 1 }
      ]
    },
    numbers: {
      title: 'Angka dalam Bahasa Spanyol',
      icon: '🔢',
      questions: [
        { q: 'Angka 1 dalam bahasa Spanyol adalah?', options: ['Dos', 'Uno', 'Tres', 'Cuatro'], answer: 1 },
        { q: 'Angka 5 dalam bahasa Spanyol adalah?', options: ['Tres', 'Cuatro', 'Cinco', 'Seis'], answer: 2 },
        { q: 'Angka 10 dalam bahasa Spanyol adalah?', options: ['Ocho', 'Nueve', 'Once', 'Diez'], answer: 3 },
        { q: 'Angka 20 dalam bahasa Spanyol adalah?', options: ['Veinte', 'Diez', 'Treinta', 'Cuarenta'], answer: 0 },
        { q: 'Angka 30 dalam bahasa Spanyol adalah?', options: ['Veinte', 'Treinta', 'Cuarenta', 'Cincuenta'], answer: 1 },
        { q: 'Angka 50 dalam bahasa Spanyol adalah?', options: ['Sesenta', 'Cincuenta', 'Cuarenta', 'Treinta'], answer: 1 },
        { q: 'Angka 100 dalam bahasa Spanyol adalah?', options: ['Mil', 'Cien', 'Diez', 'Veinte'], answer: 1 },
        { q: 'Angka 8 dalam bahasa Spanyol adalah?', options: ['Seis', 'Siete', 'Ocho', 'Nueve'], answer: 2 },
        { q: 'Angka 15 dalam bahasa Spanyol adalah?', options: ['Catorce', 'Quince', 'Dieciseis', 'Trece'], answer: 1 },
        { q: 'Angka 40 dalam bahasa Spanyol adalah?', options: ['Treinta', 'Cincuenta', 'Cuarenta', 'Sesenta'], answer: 2 }
      ]
    },
    greetings: {
      title: 'Salam & Perkenalan',
      icon: '👋',
      questions: [
        { q: 'Cara menyapa di pagi hari dalam bahasa Spanyol adalah?', options: ['Buenas noches', 'Buenos dias', 'Buenas tardes', 'Hola'], answer: 1 },
        { q: 'Terima kasih dalam bahasa Spanyol adalah?', options: ['Perdon', 'De nada', 'Gracias', 'Por favor'], answer: 2 },
        { q: 'Sampai jumpa dalam bahasa Spanyol adalah?', options: ['Buenos dias', 'Adios', 'Hola', 'Hasta luego'], answer: 1 },
        { q: 'Maaf dalam bahasa Spanyol adalah?', options: ['Perdon', 'Gracias', 'Buenos dias', 'De nada'], answer: 0 },
        { q: 'Halo dalam bahasa Spanyol adalah?', options: ['Buenos dias', 'Buenas noches', 'Hola', 'Adios'], answer: 2 },
        { q: 'Nama saya... dalam bahasa Spanyol adalah?', options: ['Quisiera...', 'Como estas?', 'Me llamo...', 'Habla ingles?'], answer: 2 },
        { q: 'Ya dalam bahasa Spanyol adalah?', options: ['No', 'Tal vez', 'Si', 'Muy bien'], answer: 2 },
        { q: 'Tidak dalam bahasa Spanyol adalah?', options: ['Si', 'No', 'Tal vez', 'Nunca'], answer: 1 },
        { q: 'Tolong dalam bahasa Spanyol adalah?', options: ['Gracias', 'Perdon', 'Por favor', 'De nada'], answer: 2 },
        { q: 'Sama-sama dalam bahasa Spanyol adalah?', options: ['Gracias', 'Perdon', 'Buenos dias', 'De nada'], answer: 3 }
      ]
    },
    family: {
      title: 'Keluarga',
      icon: '👨‍👩‍👧‍👦',
      questions: [
        { q: 'Ibu dalam bahasa Spanyol adalah?', options: ['El padre', 'La madre', 'La hermana', 'El hermano'], answer: 1 },
        { q: 'Ayah dalam bahasa Spanyol adalah?', options: ['La madre', 'El padre', 'El hijo', 'La hija'], answer: 1 },
        { q: 'Saudari dalam bahasa Spanyol adalah?', options: ['El hermano', 'La hermana', 'El hijo', 'La hija'], answer: 1 },
        { q: 'Anak perempuan dalam bahasa Spanyol adalah?', options: ['El hijo', 'La hija', 'El bebe', 'La madre'], answer: 1 },
        { q: 'Kakek dalam bahasa Spanyol adalah?', options: ['El hermano', 'La abuela', 'El abuelo', 'El padre'], answer: 2 },
        { q: 'Keluarga dalam bahasa Spanyol adalah?', options: ['Los padres', 'La familia', 'El hermano', 'La hermana'], answer: 1 },
        { q: 'Suami dalam bahasa Spanyol adalah?', options: ['La esposa', 'El esposo', 'El hijo', 'El hermano'], answer: 1 },
        { q: 'Bayi dalam bahasa Spanyol adalah?', options: ['La hija', 'El hijo', 'El bebe', 'El abuelo'], answer: 2 },
        { q: 'Sepupu (laki-laki) dalam bahasa Spanyol adalah?', options: ['La prima', 'El primo', 'El hermano', 'El sobrino'], answer: 1 },
        { q: 'Orang tua dalam bahasa Spanyol adalah?', options: ['Los padres', 'Los abuelos', 'Los hermanos', 'La familia'], answer: 0 }
      ]
    },
    food: {
      title: 'Makanan & Minuman',
      icon: '🍽️',
      questions: [
        { q: 'Roti dalam bahasa Spanyol adalah?', options: ['El arroz', 'El pan', 'El pollo', 'El pescado'], answer: 1 },
        { q: 'Air dalam bahasa Spanyol adalah?', options: ['El cafe', 'El vino', 'El agua', 'La leche'], answer: 2 },
        { q: 'Nasi dalam bahasa Spanyol adalah?', options: ['El pan', 'El arroz', 'El azucar', 'La sal'], answer: 1 },
        { q: 'Keju dalam bahasa Spanyol adalah?', options: ['El queso', 'El pollo', 'La carne', 'El pescado'], answer: 0 },
        { q: 'Daging dalam bahasa Spanyol adalah?', options: ['El pollo', 'El pescado', 'La carne', 'El arroz'], answer: 2 },
        { q: 'Kopi dalam bahasa Spanyol adalah?', options: ['El te', 'El cafe', 'El jugo', 'El agua'], answer: 1 },
        { q: 'Apel dalam bahasa Spanyol adalah?', options: ['La manzana', 'La ensalada', 'La sopa', 'El pastel'], answer: 0 },
        { q: 'Susu dalam bahasa Spanyol adalah?', options: ['El cafe', 'El vino', 'La leche', 'El jugo'], answer: 2 },
        { q: 'Sup dalam bahasa Spanyol adalah?', options: ['La ensalada', 'La sopa', 'El pan', 'El arroz'], answer: 1 },
        { q: 'Cokelat dalam bahasa Spanyol adalah?', options: ['El azucar', 'El pastel', 'El chocolate', 'El te'], answer: 2 }
      ]
    },
    places: {
      title: 'Tempat & Lokasi',
      icon: '📍',
      questions: [
        { q: 'Sekolah dalam bahasa Spanyol adalah?', options: ['La casa', 'La escuela', 'La tienda', 'La calle'], answer: 1 },
        { q: 'Rumah dalam bahasa Spanyol adalah?', options: ['La escuela', 'La casa', 'La calle', 'La tienda'], answer: 1 },
        { q: 'Toko dalam bahasa Spanyol adalah?', options: ['La casa', 'La tienda', 'La calle', 'La escuela'], answer: 1 },
        { q: 'Rumah sakit dalam bahasa Spanyol adalah?', options: ['La farmacia', 'El restaurante', 'El hospital', 'La biblioteca'], answer: 2 },
        { q: 'Restoran dalam bahasa Spanyol adalah?', options: ['La tienda', 'El restaurante', 'El parque', 'La estacion'], answer: 1 },
        { q: 'Taman dalam bahasa Spanyol adalah?', options: ['La calle', 'El parque', 'El banco', 'El cine'], answer: 1 },
        { q: 'Stasiun dalam bahasa Spanyol adalah?', options: ['La estacion', 'El hotel', 'La farmacia', 'El restaurante'], answer: 0 },
        { q: 'Apotek dalam bahasa Spanyol adalah?', options: ['El hospital', 'La farmacia', 'La tienda', 'El cine'], answer: 1 },
        { q: 'Bank dalam bahasa Spanyol adalah?', options: ['El banco', 'El parque', 'La calle', 'La escuela'], answer: 0 },
        { q: 'Pantai dalam bahasa Spanyol adalah?', options: ['El parque', 'La playa', 'La tienda', 'El restaurante'], answer: 1 }
      ]
    },
    professions: {
      title: 'Profesi & Pekerjaan',
      icon: '👨‍⚕️',
      questions: [
        { q: 'Dokter dalam bahasa Spanyol adalah?', options: ['El policia', 'El medico', 'El cocinero', 'El chofer'], answer: 1 },
        { q: 'Guru dalam bahasa Spanyol adalah?', options: ['El ingeniero', 'El profesor', 'El estudiante', 'El artista'], answer: 1 },
        { q: 'Polisi dalam bahasa Spanyol adalah?', options: ['El medico', 'El policia', 'El vendedor', 'El cartero'], answer: 1 },
        { q: 'Koki dalam bahasa Spanyol adalah?', options: ['El chofer', 'El mesero', 'El cocinero', 'El vendedor'], answer: 2 },
        { q: 'Pengacara dalam bahasa Spanyol adalah?', options: ['El abogado', 'El periodista', 'El medico', 'El profesor'], answer: 0 },
        { q: 'Jurnalis dalam bahasa Spanyol adalah?', options: ['El director', 'El periodista', 'El musico', 'El actor'], answer: 1 },
        { q: 'Tukang pos dalam bahasa Spanyol adalah?', options: ['El cartero', 'El chofer', 'El policia', 'El bombero'], answer: 0 },
        { q: 'Pemadam kebakaran dalam bahasa Spanyol adalah?', options: ['El policia', 'El bombero', 'El medico', 'El soldado'], answer: 1 },
        { q: 'Seniman dalam bahasa Spanyol adalah?', options: ['El ingeniero', 'El estudiante', 'El artista', 'El granjero'], answer: 2 },
        { q: 'Penerjemah dalam bahasa Spanyol adalah?', options: ['El traductor', 'El periodista', 'El director', 'El vendedor'], answer: 0 }
      ]
    },
    emotions: {
      title: 'Emosi & Perasaan',
      icon: '😊',
      questions: [
        { q: 'Senang dalam bahasa Spanyol adalah?', options: ['Triste', 'Feliz', 'Cansado', 'Sorprendido'], answer: 1 },
        { q: 'Sedih dalam bahasa Spanyol adalah?', options: ['Feliz', 'Triste', 'Emocionado', 'Calmado'], answer: 1 },
        { q: 'Lelah dalam bahasa Spanyol adalah?', options: ['Enojado', 'Asustado', 'Cansado', 'Timido'], answer: 2 },
        { q: 'Marah dalam bahasa Spanyol adalah?', options: ['Calmado', 'Triste', 'Enojado', 'Feliz'], answer: 2 },
        { q: 'Takut dalam bahasa Spanyol adalah?', options: ['Sorprendido', 'Asustado', 'Orgulloso', 'Timido'], answer: 1 },
        { q: 'Terkejut dalam bahasa Spanyol adalah?', options: ['Cansado', 'Sorprendido', 'Enamorado', 'Enojado'], answer: 1 },
        { q: 'Pemalu dalam bahasa Spanyol adalah?', options: ['Timido', 'Confiado', 'Orgulloso', 'Preocupado'], answer: 0 },
        { q: 'Bangga dalam bahasa Spanyol adalah?', options: ['Decepcionado', 'Celoso', 'Orgulloso', 'Solo'], answer: 2 },
        { q: 'Kecewa dalam bahasa Spanyol adalah?', options: ['Feliz', 'Entusiasmado', 'Decepcionado', 'Nervioso'], answer: 2 },
        { q: 'Khawatir dalam bahasa Spanyol adalah?', options: ['Calmado', 'Preocupado', 'Enamorado', 'Triste'], answer: 1 }
      ]
    },
    verbConjugations: {
      title: 'Kata Kerja Dasar',
      icon: '🏃',
      questions: [
        { q: '"Pergi" dalam bahasa Spanyol adalah?', options: ['Venir', 'Ir', 'Salir', 'Llegar'], answer: 1 },
        { q: '"Memiliki" dalam bahasa Spanyol adalah?', options: ['Ser', 'Tener', 'Poder', 'Querer'], answer: 1 },
        { q: '"Bisa" dalam bahasa Spanyol adalah?', options: ['Querer', 'Deber', 'Poder', 'Saber'], answer: 2 },
        { q: '"Mau" dalam bahasa Spanyol adalah?', options: ['Poder', 'Querer', 'Deber', 'Hacer'], answer: 1 },
        { q: '"Harus" dalam bahasa Spanyol adalah?', options: ['Poder', 'Querer', 'Deber', 'Hacer'], answer: 2 },
        { q: '"Melakukan" dalam bahasa Spanyol adalah?', options: ['Decir', 'Ver', 'Venir', 'Hacer'], answer: 3 },
        { q: '"Berkata" dalam bahasa Spanyol adalah?', options: ['Decir', 'Ver', 'Venir', 'Hacer'], answer: 0 },
        { q: '"Melihat" dalam bahasa Spanyol adalah?', options: ['Decir', 'Ver', 'Venir', 'Tomar'], answer: 1 },
        { q: '"Datang" dalam bahasa Spanyol adalah?', options: ['Salir', 'Llegar', 'Venir', 'Entrar'], answer: 2 },
        { q: '"Masuk" dalam bahasa Spanyol adalah?', options: ['Salir', 'Subir', 'Bajar', 'Entrar'], answer: 3 }
      ]
    },
    bodyParts: {
      title: 'Bagian Tubuh',
      icon: '🦵',
      questions: [
        { q: 'Kepala dalam bahasa Spanyol adalah?', options: ['El cuello', 'La cabeza', 'El brazo', 'El estomago'], answer: 1 },
        { q: 'Mata dalam bahasa Spanyol adalah?', options: ['Las orejas', 'La nariz', 'Los ojos', 'La boca'], answer: 2 },
        { q: 'Tangan dalam bahasa Spanyol adalah?', options: ['El pie', 'La mano', 'El brazo', 'La pierna'], answer: 1 },
        { q: 'Kaki dalam bahasa Spanyol adalah?', options: ['La mano', 'La rodilla', 'El pie', 'El muslo'], answer: 2 },
        { q: 'Perut dalam bahasa Spanyol adalah?', options: ['El pecho', 'La espalda', 'La cintura', 'El estomago'], answer: 3 },
        { q: 'Leher dalam bahasa Spanyol adalah?', options: ['El hombro', 'El cuello', 'El codo', 'La muneca'], answer: 1 },
        { q: 'Jari-jari dalam bahasa Spanyol adalah?', options: ['Los dientes', 'Los dedos', 'Los labios', 'El cabello'], answer: 1 },
        { q: 'Hidung dalam bahasa Spanyol adalah?', options: ['Los ojos', 'La boca', 'La nariz', 'Las orejas'], answer: 2 },
        { q: 'Mulut dalam bahasa Spanyol adalah?', options: ['La nariz', 'La boca', 'Los dientes', 'La lengua'], answer: 1 },
        { q: 'Jantung dalam bahasa Spanyol adalah?', options: ['El corazon', 'La espalda', 'El estomago', 'El pecho'], answer: 0 }
      ]
    },
    clothing: {
      title: 'Pakaian & Aksesori',
      icon: '👕',
      questions: [
        { q: 'Sepatu dalam bahasa Spanyol adalah?', options: ['El sombrero', 'Los zapatos', 'Los guantes', 'Las gafas'], answer: 1 },
        { q: 'Topi dalam bahasa Spanyol adalah?', options: ['Los zapatos', 'La corbata', 'El sombrero', 'Los guantes'], answer: 2 },
        { q: 'Gaun/baju dalam bahasa Spanyol adalah?', options: ['El pantalon', 'La falda', 'El vestido', 'El sueter'], answer: 2 },
        { q: 'Jaket dalam bahasa Spanyol adalah?', options: ['El abrigo', 'La chaqueta', 'La camiseta', 'La camisa'], answer: 1 },
        { q: 'Kemeja dalam bahasa Spanyol adalah?', options: ['La camiseta', 'La camisa', 'La blusa', 'El traje'], answer: 1 },
        { q: 'Rok dalam bahasa Spanyol adalah?', options: ['El pantalon', 'La falda', 'Los pantalones cortos', 'El vestido'], answer: 1 },
        { q: 'Sandal dalam bahasa Spanyol adalah?', options: ['Las botas', 'Los tenis', 'Las sandalias', 'Los calcetines'], answer: 2 },
        { q: 'Dasi dalam bahasa Spanyol adalah?', options: ['El cinturon', 'La gorra', 'La bufanda', 'La corbata'], answer: 3 },
        { q: 'Kaos dalam bahasa Spanyol adalah?', options: ['El sueter', 'La camiseta', 'La blusa', 'El traje'], answer: 1 },
        { q: 'Jam tangan dalam bahasa Spanyol adalah?', options: ['Las gafas', 'El anillo', 'El reloj', 'La pulsera'], answer: 2 }
      ]
    },
    house: {
      title: 'Rumah & Ruangan',
      icon: '🏠',
      questions: [
        { q: 'Kamar tidur dalam bahasa Spanyol adalah?', options: ['La cocina', 'La sala', 'El cuarto', 'El bano'], answer: 2 },
        { q: 'Dapur dalam bahasa Spanyol adalah?', options: ['El cuarto', 'La cocina', 'La sala', 'El jardin'], answer: 1 },
        { q: 'Ruang tamu dalam bahasa Spanyol adalah?', options: ['La sala', 'El jardin', 'El cuarto', 'El sotano'], answer: 0 },
        { q: 'Taman dalam bahasa Spanyol adalah?', options: ['El balcon', 'La terraza', 'El jardin', 'El garaje'], answer: 2 },
        { q: 'Pintu dalam bahasa Spanyol adalah?', options: ['La ventana', 'La pared', 'La puerta', 'El suelo'], answer: 2 },
        { q: 'Jendela dalam bahasa Spanyol adalah?', options: ['La puerta', 'La ventana', 'El techo', 'La pared'], answer: 1 },
        { q: 'Tangga dalam bahasa Spanyol adalah?', options: ['El balcon', 'La escalera', 'La terraza', 'El sotano'], answer: 1 },
        { q: 'Garasi dalam bahasa Spanyol adalah?', options: ['El sotano', 'El atico', 'El garaje', 'El jardin'], answer: 2 },
        { q: 'Apartemen dalam bahasa Spanyol adalah?', options: ['El edificio', 'La casa', 'El apartamento', 'La oficina'], answer: 2 },
        { q: 'Loteng dalam bahasa Spanyol adalah?', options: ['El sotano', 'El atico', 'La bodega', 'El bano'], answer: 1 }
      ]
    },
    foodExtended: {
      title: 'Makanan Spanyol Lanjutan',
      icon: '🥐',
      questions: [
        { q: 'Paella dalam bahasa Spanyol adalah?', options: ['El gazpacho', 'La crepa', 'La paella', 'El churro'], answer: 2 },
        { q: 'Churros dalam bahasa Spanyol adalah?', options: ['El waffle', 'La crepa', 'El churro', 'La quiche'], answer: 2 },
        { q: 'Gazpacho dalam bahasa Spanyol adalah?', options: ['El brie', 'El gazpacho', 'El camembert', 'El chorizo'], answer: 1 },
        { q: 'Sapi masak Burgundy dalam bahasa Spanyol adalah?', options: ['El pollo asado', 'El jamon', 'La paella', 'El gazpacho'], answer: 1 },
        { q: 'Sup bawang dalam bahasa Spanyol adalah?', options: ['El cocido', 'La sopa de cebolla', 'La ensalada mixta', 'La fabada'], answer: 1 },
        { q: 'Flan dalam bahasa Spanyol adalah?', options: ['El arroz con leche', 'El flan', 'El turrón', 'La leche frita'], answer: 1 },
        { q: 'Tortilla dalam bahasa Spanyol adalah?', options: ['La crepa', 'La tortilla', 'El pan con chocolate', 'La brioche'], answer: 1 },
        { q: 'Stroberi dalam bahasa Spanyol adalah?', options: ['La cereza', 'La fresa', 'La frambuesa', 'El arandano'], answer: 1 },
        { q: 'Madu dalam bahasa Spanyol adalah?', options: ['La mantequilla', 'La mermelada', 'La miel', 'El vinagre'], answer: 2 },
        { q: 'Mentega dalam bahasa Spanyol adalah?', options: ['La mantequilla', 'La harina', 'El aceite de oliva', 'La miel'], answer: 0 }
      ]
    },
    technology: {
      title: 'Teknologi & Komputer',
      icon: '💻',
      questions: [
        { q: 'Komputer dalam bahasa Spanyol adalah?', options: ['La impresora', 'El ordenador', 'La pantalla', 'El teclado'], answer: 1 },
        { q: 'HP/portable dalam bahasa Spanyol adalah?', options: ['La tableta', 'El telefono', 'El movil', 'El internet'], answer: 2 },
        { q: 'Printer dalam bahasa Spanyol adalah?', options: ['El ordenador', 'La impresora', 'El teclado', 'El raton'], answer: 1 },
        { q: 'Internet dalam bahasa Spanyol adalah?', options: ['El wifi', 'La conexion', 'El internet', 'La red'], answer: 2 },
        { q: 'Layar dalam bahasa Spanyol adalah?', options: ['El teclado', 'El raton', 'La pantalla', 'El ordenador'], answer: 2 },
        { q: 'Keyboard dalam bahasa Spanyol adalah?', options: ['El raton', 'El teclado', 'La pantalla', 'La impresora'], answer: 1 },
        { q: 'Mouse dalam bahasa Spanyol adalah?', options: ['El teclado', 'El raton', 'La pantalla', 'El telefono'], answer: 1 },
        { q: 'Wifi dalam bahasa Spanyol adalah?', options: ['El internet', 'La conexion', 'La red', 'El wifi'], answer: 3 },
        { q: 'Aplikasi dalam bahasa Spanyol adalah?', options: ['El software', 'La aplicacion', 'El hardware', 'La memoria'], answer: 1 },
        { q: 'Password dalam bahasa Spanyol adalah?', options: ['La direccion de correo', 'La contrasena', 'El navegador', 'La pagina web'], answer: 1 }
      ]
    },
    transportation: {
      title: 'Kendaraan & Transportasi',
      icon: '🚗',
      questions: [
        { q: 'Mobil dalam bahasa Spanyol adalah?', options: ['El autobus', 'El coche', 'El tren', 'El avion'], answer: 1 },
        { q: 'Pesawat dalam bahasa Spanyol adalah?', options: ['El barco', 'El tren', 'El avion', 'El taxi'], answer: 2 },
        { q: 'Kereta api dalam bahasa Spanyol adalah?', options: ['El autobus', 'El metro', 'El tren', 'El tranvia'], answer: 2 },
        { q: 'Bus dalam bahasa Spanyol adalah?', options: ['El autobus', 'El coche', 'El taxi', 'El metro'], answer: 0 },
        { q: 'Sepeda dalam bahasa Spanyol adalah?', options: ['La moto', 'La bicicleta', 'La scooter', 'El coche'], answer: 1 },
        { q: 'Kapal dalam bahasa Spanyol adalah?', options: ['El avion', 'El barco', 'El ferry', 'El yate'], answer: 1 },
        { q: 'Motor dalam bahasa Spanyol adalah?', options: ['La moto', 'La bicicleta', 'La scooter', 'El camion'], answer: 0 },
        { q: 'Taksi dalam bahasa Spanyol adalah?', options: ['El autobus', 'El tren', 'El taxi', 'El metro'], answer: 2 },
        { q: 'Helikopter dalam bahasa Spanyol adalah?', options: ['El avion', 'El barco', 'El helicoptero', 'El dirigible'], answer: 2 },
        { q: 'Kereta bawah tanah dalam bahasa Spanyol adalah?', options: ['El tren', 'El tranvia', 'El metro', 'El autobus'], answer: 2 }
      ]
    },
    travel: {
      title: 'Perjalanan & Liburan',
      icon: '✈️',
      questions: [
        { q: 'Hotel dalam bahasa Spanyol adalah?', options: ['El edificio', 'El apartamento', 'El hotel', 'El restaurante'], answer: 2 },
        { q: 'Bandara dalam bahasa Spanyol adalah?', options: ['La estacion', 'El aeropuerto', 'El puerto', 'La parada'], answer: 1 },
        { q: 'Paspor dalam bahasa Spanyol adalah?', options: ['El visado', 'El pasaporte', 'La cedula', 'El billete'], answer: 1 },
        { q: 'Tiket dalam bahasa Spanyol adalah?', options: ['El pasaporte', 'El billete', 'El visado', 'La reserva'], answer: 1 },
        { q: 'Koper dalam bahasa Spanyol adalah?', options: ['La bolsa', 'La maleta', 'La mochila', 'La cartera'], answer: 1 },
        { q: 'Pemandu wisata dalam bahasa Spanyol adalah?', options: ['El guia', 'El chofer', 'El piloto', 'El viajero'], answer: 0 },
        { q: 'Wisatawan dalam bahasa Spanyol adalah?', options: ['El turista', 'El guia', 'El viajero', 'El explorador'], answer: 2 },
        { q: 'Pemandangan dalam bahasa Spanyol adalah?', options: ['La vista', 'El paisaje', 'El panoramico', 'El horizonte'], answer: 1 },
        { q: 'Pantai dalam bahasa Spanyol adalah?', options: ['La montaña', 'La playa', 'El bosque', 'El desierto'], answer: 1 },
        { q: 'Museum dalam bahasa Spanyol adalah?', options: ['El teatro', 'El cine', 'El museo', 'La exposicion'], answer: 2 }
      ]
    }
  },
  achievements: [
    { id: 'first_quiz', title: 'Pertama Kali!', description: 'Selesaikan kuis pertama Anda', icon: '🎯', requirement: 'Selesaikan 1 kuis' },
    { id: 'quiz_5', title: 'Pemula', description: 'Selesaikan 5 kuis', icon: '📚', requirement: 'Selesaikan 5 kuis' },
    { id: 'quiz_10', title: 'Siswa Rajin', description: 'Selesaikan 10 kuis', icon: '🏆', requirement: 'Selesaikan 10 kuis' },
    { id: 'quiz_25', title: 'Penggemar Kuis', description: 'Selesaikan 25 kuis', icon: '⭐', requirement: 'Selesaikan 25 kuis' },
    { id: 'quiz_50', title: 'Master Kuis', description: 'Selesaikan 50 kuis', icon: '👑', requirement: 'Selesaikan 50 kuis' },
    { id: 'quiz_100', title: 'Legenda Kuis', description: 'Selesaikan 100 kuis', icon: '🌟', requirement: 'Selesaikan 100 kuis' },
    { id: 'flashcard_10', title: 'Penjelajah Kata', description: 'Lihat 10 kartu flashcard', icon: '🃏', requirement: 'Lihat 10 kartu' },
    { id: 'flashcard_50', title: 'Kolektor Kata', description: 'Lihat 50 kartu flashcard', icon: '📦', requirement: 'Lihat 50 kartu' },
    { id: 'flashcard_100', title: 'Ahli Kosakata', description: 'Lihat 100 kartu flashcard', icon: '🎓', requirement: 'Lihat 100 kartu' },
    { id: 'flashcard_500', title: 'Penguasa Kosakata', description: 'Lihat 500 kartu flashcard', icon: '🧠', requirement: 'Lihat 500 kartu' },
    { id: 'streak_3', title: '3 Hari Berturut', description: 'Belajar 3 hari berturut-turut', icon: '🔥', requirement: '3 hari streak' },
    { id: 'streak_7', title: 'Seminggu Penuh', description: 'Belajar 7 hari berturut-turut', icon: '💪', requirement: '7 hari streak' },
    { id: 'streak_30', title: 'Sebulan Penuh', description: 'Belajar 30 hari berturut-turut', icon: '🏆', requirement: '30 hari streak' },
    { id: 'perfect_score', title: 'Sempurna!', description: 'Dapatkan skor 100% di kuis', icon: '💯', requirement: 'Skor 100% di kuis' },
    { id: 'perfect_5', title: 'Sangat Sempurna', description: 'Dapatkan 5 skor sempurna', icon: '🎯', requirement: '5 skor 100%' },
    { id: 'perfect_10', title: 'Master Sempurna', description: 'Dapatkan 10 skor sempurna', icon: '🏅', requirement: '10 skor 100%' },
    { id: 'xp_100', title: '100 XP', description: 'Kumpulkan 100 XP', icon: '⭐', requirement: '100 XP' },
    { id: 'xp_500', title: '500 XP', description: 'Kumpulkan 500 XP', icon: '🌟', requirement: '500 XP' },
    { id: 'xp_1000', title: '1000 XP', description: 'Kumpulkan 1000 XP', icon: '👑', requirement: '1000 XP' },
    { id: 'xp_5000', title: '5000 XP', description: 'Kumpulkan 5000 XP', icon: '🏆', requirement: '5000 XP' },
    { id: 'word_explorer', title: 'Penjelajah Kata', description: 'Pelajari 100 kata unik', icon: '🔤', requirement: '100 kata unik' },
    { id: 'vocabulary_champion', title: 'Juara Kosakata', description: 'Pelajari 500 kata unik', icon: '📚', requirement: '500 kata unik' },
    { id: 'fashionista', title: 'Fashionista', description: 'Kuasai kategori pakaian', icon: '👗', requirement: 'Kuis pakaian 100%' },
    { id: 'chef_de_cuisine', title: 'Chef de Cuisine', description: 'Kuasai kategori makanan', icon: '👨‍🍳', requirement: 'Kuis makanan 100%' },
    { id: 'tech_savvy', title: 'Tech Savvy', description: 'Kuasai kategori teknologi', icon: '💻', requirement: 'Kuis teknologi 100%' },
    { id: 'body_master', title: 'Body Master', description: 'Kuasai kategori bagian tubuh', icon: '🦵', requirement: 'Kuis tubuh 100%' },
    { id: 'house_expert', title: 'House Expert', description: 'Kuasai kategori rumah', icon: '🏠', requirement: 'Kuis rumah 100%' },
    { id: 'travel_guru', title: 'Travel Guru', description: 'Kuasai kategori perjalanan', icon: '✈️', requirement: 'Kuis perjalanan 100%' },
    { id: 'emotion_reader', title: 'Emotion Reader', description: 'Kuasai kategori emosi', icon: '😊', requirement: 'Kuis emosi 100%' },
    { id: 'verb_master', title: 'Verb Master', description: 'Kuasai kategori kata kerja', icon: '🏃', requirement: 'Kuis kata kerja 100%' },
    { id: 'transport_king', title: 'Transport King', description: 'Kuasai kategori transportasi', icon: '🚗', requirement: 'Kuis transportasi 100%' },
    { id: 'animal_lover', title: 'Animal Lover', description: 'Pelajari semua nama hewan', icon: '🐾', requirement: 'Semua hewan' },
    { id: 'color_master', title: 'Color Master', description: 'Kuasai kategori warna', icon: '🎨', requirement: 'Kuis warna 100%' },
    { id: 'number_wizard', title: 'Number Wizard', description: 'Kuasai kategori angka', icon: '🔢', requirement: 'Kuis angka 100%' },
    { id: 'full_spectrum', title: 'Full Spectrum', description: 'Selesaikan semua kategori kuis', icon: '🌈', requirement: 'Semua 15 kategori' }
  ]
};
