const CONTENT_DATA = {
  vocabulary: {
    salam: [
      { it: 'Ciao', id: 'Halo', note: 'informal' },
      { it: 'Buongiorno', id: 'Selamat pagi' },
      { it: 'Buonasera', id: 'Selamat sore' },
      { it: 'Buonanotte', id: 'Selamat malam' },
      { it: 'Arrivederci', id: 'Selamat tinggal' },
      { it: 'A presto', id: 'Sampai nanti' },
      { it: 'Per favore', id: 'Tolong' },
      { it: 'Grazie', id: 'Terima kasih' },
      { it: 'Grazie mille', id: 'Terima kasih banyak' },
      { it: 'Prego', id: 'Sama-sama' },
      { it: 'Mi scusi', id: 'Maaf (formal)' },
      { it: 'Scusa', id: 'Maaf (informal)' },
      { it: 'Come sta?', id: 'Apa kabar? (formal)' },
      { it: 'Come stai?', id: 'Apa kabar? (informal)' },
      { it: 'Sto bene', id: 'Saya baik-baik saja' },
      { it: 'Mi chiamo...', id: 'Nama saya...' },
      { it: 'Piacere di conoscerti', id: 'Senang berkenalan' },
      { it: 'Sì', id: 'Ya' },
      { it: 'No', id: 'Tidak' },
      { it: 'Come ti chiami?', id: 'Siapa nama Anda?' },
      { it: 'Quanti anni hai?', id: 'Berapa umur Anda?' },
      { it: 'Di dove sei?', id: 'Anda dari mana?' },
      { it: 'Non capisco', id: 'Saya tidak mengerti' },
      { it: 'Parla inglese?', id: 'Apakah Anda bicara bahasa Inggris?' },
      { it: 'Aiuto!', id: 'Tolong!' },
      { it: 'Felice', id: 'Senang' },
      { it: 'Triste', id: 'Sedih' },
      { it: 'Arrabbiato', id: 'Marah' },
      { it: 'Stanco', id: 'Lelah' },
      { it: 'Affamato', id: 'Lapar' }
    ],
    angka: [
      { it: 'zero', id: 'Nol' },
      { it: 'uno', id: 'Satu' },
      { it: 'due', id: 'Dua' },
      { it: 'tre', id: 'Tiga' },
      { it: 'quattro', id: 'Empat' },
      { it: 'cinque', id: 'Lima' },
      { it: 'sei', id: 'Enam' },
      { it: 'sette', id: 'Tujuh' },
      { it: 'otto', id: 'Delapan' },
      { it: 'nove', id: 'Sembilan' },
      { it: 'dieci', id: 'Sepuluh' },
      { it: 'undici', id: 'Sebelas' },
      { it: 'dodici', id: 'Dua belas' },
      { it: 'venti', id: 'Dua puluh' },
      { it: 'trenta', id: 'Tiga puluh' },
      { it: 'quaranta', id: 'Empat puluh' },
      { it: 'cinquanta', id: 'Lima puluh' },
      { it: 'cento', id: 'Seratus' },
      { it: 'mille', id: 'Seribu' },
      { it: 'primo', id: 'Pertama' },
      { it: 'secondo', id: 'Kedua' },
      { it: 'terzo', id: 'Ketiga' },
      { it: 'decimo', id: 'Kesepuluh' },
      { it: 'ultimo', id: 'Terakhir' },
      { it: 'numero', id: 'Angka' }
    ],
    hari: [
      { it: 'lunedì', id: 'Senin' },
      { it: 'martedì', id: 'Selasa' },
      { it: 'mercoledì', id: 'Rabu' },
      { it: 'giovedì', id: 'Kamis' },
      { it: 'venerdì', id: 'Jumat' },
      { it: 'sabato', id: 'Sabtu' },
      { it: 'domenica', id: 'Minggu' },
      { it: 'giorno feriale', id: 'Hari kerja' },
      { it: 'giorno festivo', id: 'Hari libur' },
      { it: 'oggi', id: 'Hari ini' },
      { it: 'ieri', id: 'Kemarin' },
      { it: 'domani', id: 'Besok' },
      { it: 'settimana', id: 'Minggu (satuan waktu)' },
      { it: 'mese', id: 'Bulan' },
      { it: 'anno', id: 'Tahun' },
      { it: 'gennaio', id: 'Januari' },
      { it: 'febbraio', id: 'Februari' },
      { it: 'marzo', id: 'Maret' },
      { it: 'aprile', id: 'April' },
      { it: 'maggio', id: 'Mei' },
      { it: 'giugno', id: 'Juni' },
      { it: 'luglio', id: 'Juli' },
      { it: 'agosto', id: 'Agustus' },
      { it: 'settembre', id: 'September' },
      { it: 'ottobre', id: 'Oktober' },
      { it: 'novembre', id: 'November' },
      { it: 'dicembre', id: 'Desember' },
      { it: 'stagione', id: 'Musim' },
      { it: 'primavera', id: 'Musim semi' },
      { it: 'estate', id: 'Musim panas' },
      { it: 'autunno', id: 'Musim gugur' },
      { it: 'inverno', id: 'Musim dingin' }
    ],
    warna: [
      { it: 'rosso', id: 'Merah' },
      { it: 'blu', id: 'Biru' },
      { it: 'verde', id: 'Hijau' },
      { it: 'giallo', id: 'Kuning' },
      { it: 'arancione', id: 'Oranye' },
      { it: 'viola', id: 'Ungu' },
      { it: 'rosa', id: 'Merah muda' },
      { it: 'nero', id: 'Hitam' },
      { it: 'bianco', id: 'Putih' },
      { it: 'grigio', id: 'Abu-abu' },
      { it: 'marrone', id: 'Cokelat' },
      { it: 'dorato', id: 'Emas' },
      { it: 'argenteo', id: 'Perak' },
      { it: 'beige', id: 'Krem' },
      { it: 'azzurro', id: 'Biru muda' },
      { it: 'color crema', id: 'Warna krem' }
    ],
    ganti: [
      { it: 'io', id: 'Saya' },
      { it: 'tu', id: 'Kamu (informal)' },
      { it: 'Lei', id: 'Anda (formal)' },
      { it: 'lui', id: 'Dia (laki-laki)' },
      { it: 'lei', id: 'Dia (perempuan)' },
      { it: 'noi', id: 'Kami/Kita' },
      { it: 'voi', id: 'Kalian' },
      { it: 'loro', id: 'Mereka' },
      { it: 'mio', id: 'Saya (milik)' },
      { it: 'tuo', id: 'Kamu (milik)' },
      { it: 'suo', id: 'Dia (milik)' },
      { it: 'nostro', id: 'Kita (milik)' },
      { it: 'vostro', id: 'Kalian (milik)' },
      { it: 'loro', id: 'Mereka (milik)' },
      { it: 'questo', id: 'Ini' },
      { it: 'quello', id: 'Itu' },
      { it: 'chi', id: 'Siapa' },
      { it: 'cosa', id: 'Apa' },
      { it: 'dove', id: 'Di mana' },
      { it: 'quando', id: 'Kapan' },
      { it: 'perché', id: 'Mengapa' },
      { it: 'come', id: 'Bagaimana' },
      { it: 'quanto', id: 'Berapa' }
    ],
    keluarga: [
      { it: 'la madre', id: 'Ibu', note: 'feminin' },
      { it: 'il padre', id: 'Ayah', note: 'maskulin' },
      { it: 'la nonna', id: 'Nenek', note: 'feminin' },
      { it: 'il nonno', id: 'Kakek', note: 'maskulin' },
      { it: 'la sorella', id: 'Saudara perempuan', note: 'feminin' },
      { it: 'il fratello', id: 'Saudara laki-laki', note: 'maskulin' },
      { it: 'la figlia', id: 'Anak perempuan', note: 'feminin' },
      { it: 'il figlio', id: 'Anak laki-laki', note: 'maskulin' },
      { it: 'la zia', id: 'Bibi', note: 'feminin' },
      { it: 'lo zio', id: 'Paman', note: 'maskulin' },
      { it: 'la cugina', id: 'Sepupu (wanita)', note: 'feminin' },
      { it: 'il cugino', id: 'Sepupu (pria)', note: 'maskulin' },
      { it: 'la nipote', id: 'Cucu/Keponakan', note: 'feminin' },
      { it: 'la famiglia', id: 'Keluarga', note: 'feminin' },
      { it: 'la moglie', id: 'Istri', note: 'feminin' },
      { it: 'il marito', id: 'Suami', note: 'maskulin' },
      { it: 'i genitori', id: 'Orang tua' },
      { it: 'i figli', id: 'Anak-anak' },
      { it: 'il suocero', id: 'Mertua (pria)', note: 'maskulin' },
      { it: 'la suocera', id: 'Mertua (wanita)', note: 'feminin' },
      { it: 'il genero', id: 'Menantu laki-laki', note: 'maskulin' },
      { it: 'la nuora', id: 'Menantu perempuan', note: 'feminin' },
      { it: 'il cognato', id: 'Ipar (pria)', note: 'maskulin' },
      { it: 'la cognata', id: 'Ipar (wanita)', note: 'feminin' },
      { it: 'il bambino', id: 'Anak kecil', note: 'maskulin' }
    ],
    makanan: [
      { it: 'la colazione', id: 'Sarapan' },
      { it: 'il pranzo', id: 'Makan siang' },
      { it: 'la cena', id: 'Makan malam' },
      { it: 'il pane', id: 'Roti', note: 'maskulin' },
      { it: 'il burro', id: 'Mentega', note: 'maskulin' },
      { it: 'il formaggio', id: 'Keju', note: 'maskulin' },
      { it: 'la salsiccia', id: 'Sosis', note: 'feminin' },
      { it: "l'uovo", id: 'Telur', note: 'netral' },
      { it: 'il riso', id: 'Nasi', note: 'maskulin' },
      { it: 'la patata', id: 'Kentang', note: 'feminin' },
      { it: 'la zuppa', id: 'Sup', note: 'feminin' },
      { it: "l'insalata", id: 'Salad', note: 'feminin' },
      { it: 'la carne', id: 'Daging', note: 'feminin' },
      { it: 'il pesce', id: 'Ikan', note: 'maskulin' },
      { it: 'il latte', id: 'Susu', note: 'maskulin' },
      { it: 'il caffè', id: 'Kopi', note: 'maskulin' },
      { it: 'il tè', id: 'Teh', note: 'maskulin' },
      { it: 'il succo', id: 'Jus', note: 'maskulin' },
      { it: "l'acqua", id: 'Air', note: 'feminin' },
      { it: 'la birra', id: 'Bir', note: 'feminin' },
      { it: 'il vino', id: 'Anggur', note: 'maskulin' },
      { it: 'lo zucchero', id: 'Gula', note: 'maskulin' },
      { it: 'il sale', id: 'Garam', note: 'maskulin' },
      { it: 'il pepe', id: 'Merica', note: 'maskulin' },
      { it: "l'olio", id: 'Minyak', note: 'netral' },
      { it: 'la farina', id: 'Tepung', note: 'feminin' },
      { it: 'la torta', id: 'Kue', note: 'feminin' },
      { it: 'il gelato', id: 'Es krim', note: 'maskulin' },
      { it: 'il cioccolato', id: 'Cokelat', note: 'maskulin' },
      { it: 'le caramelle', id: 'Permen' },
      { it: 'la pizza', id: 'Pizza', note: 'feminin' },
      { it: "l'insalata mista", id: 'Salad campur', note: 'feminin' },
      { it: 'la pasta', id: 'Pasta', note: 'feminin' },
      { it: 'il sandwich', id: 'Roti lapis', note: 'maskulin' },
      { it: 'lo yogurt', id: 'Yogurt', note: 'maskulin' }
    ],
    tempat: [
      { it: 'la scuola', id: 'Sekolah', note: 'feminin' },
      { it: "l'università", id: 'Universitas', note: 'feminin' },
      { it: "l'ospedale", id: 'Rumah sakit', note: 'netral' },
      { it: 'la chiesa', id: 'Gereja', note: 'feminin' },
      { it: 'il museo', id: 'Museum', note: 'maskulin' },
      { it: "l'albergo", id: 'Hotel', note: 'netral' },
      { it: 'il ristorante', id: 'Restoran', note: 'maskulin' },
      { it: "l'ufficio postale", id: 'Kantor pos', note: 'netral' },
      { it: 'la banca', id: 'Bank', note: 'feminin' },
      { it: 'il supermercato', id: 'Supermarket', note: 'maskulin' },
      { it: 'la biblioteca', id: 'Perpustakaan', note: 'feminin' },
      { it: 'il cinema', id: 'Bioskop', note: 'maskulin' },
      { it: 'il teatro', id: 'Teater', note: 'maskulin' },
      { it: "l'opera", id: 'Opera', note: 'feminin' },
      { it: 'il parco', id: 'Taman', note: 'maskulin' },
      { it: 'la stazione', id: 'Stasiun kereta', note: 'feminin' },
      { it: "l'aeroporto", id: 'Bandara', note: 'netral' },
      { it: 'la farmacia', id: 'Apotek', note: 'feminin' },
      { it: 'il cimitero', id: 'Kuburan', note: 'maskulin' },
      { it: 'la fabbrica', id: 'Pabrik', note: 'feminin' },
      { it: 'il municipio', id: 'Balai kota', note: 'maskulin' },
      { it: 'la stazione di polizia', id: 'Kantor polisi', note: 'feminin' },
      { it: 'la caserma dei pompieri', id: 'Kantor pemadam', note: 'feminin' },
      { it: 'il mercato', id: 'Pasar', note: 'maskulin' },
      { it: 'il centro commerciale', id: 'Pusat perbelanjaan', note: 'maskulin' },
      { it: 'lo stadio', id: 'Stadion', note: 'maskulin' },
      { it: 'lo zoo', id: 'Kebun binatang', note: 'maskulin' },
      { it: "l'acquario", id: 'Akuarium', note: 'netral' },
      { it: 'il bar', id: 'Kafe', note: 'maskulin' },
      { it: 'la palestra', id: 'Gym', note: 'feminin' }
    ],
    profesi: [
      { it: 'il medico', id: 'Dokter', note: 'maskulin' },
      { it: "l'insegnante", id: 'Guru', note: 'maskulin' },
      { it: "l'ingegnere", id: 'Insinyur', note: 'maskulin' },
      { it: "l'avvocato", id: 'Pengacara', note: 'maskulin' },
      { it: 'il poliziotto', id: 'Polisi', note: 'maskulin' },
      { it: 'il pompiere', id: 'Pemadam kebakaran', note: 'maskulin' },
      { it: "l'infermiere", id: 'Perawat', note: 'maskulin' },
      { it: 'il cuoco', id: 'Koki', note: 'maskulin' },
      { it: 'il panettiere', id: 'Tukang roti', note: 'maskulin' },
      { it: 'il macellaio', id: 'Tukang daging', note: 'maskulin' },
      { it: 'il parrucchiere', id: 'Tukang cukur', note: 'maskulin' },
      { it: 'il venditore', id: 'Penjual', note: 'maskulin' },
      { it: 'il cameriere', id: 'Pelayan', note: 'maskulin' },
      { it: 'il pilota', id: 'Pilot', note: 'maskulin' },
      { it: "l'architetto", id: 'Arsitek', note: 'maskulin' },
      { it: 'il giornalista', id: 'Jurnalis', note: 'maskulin' },
      { it: 'lo scrittore', id: 'Penulis', note: 'maskulin' },
      { it: "l'artista", id: 'Seniman', note: 'maskulin' },
      { it: 'il musicista', id: 'Musisi', note: 'maskulin' },
      { it: "l'attore", id: 'Aktor', note: 'maskulin' },
      { it: "l'attrice", id: 'Aktris', note: 'feminin' },
      { it: 'il regista', id: 'Sutradara', note: 'maskulin' },
      { it: 'il programmatore', id: 'Programmer', note: 'maskulin' },
      { it: "l'autista", id: 'Sopir', note: 'maskulin' },
      { it: 'il contadino', id: 'Petani', note: 'maskulin' }
    ],
    emosi: [
      { it: 'felice', id: 'Bahagia' },
      { it: 'triste', id: 'Sedih' },
      { it: 'arrabbiato', id: 'Marah' },
      { it: 'irritato', id: 'Jengkel' },
      { it: 'sorpreso', id: 'Terkejut' },
      { it: 'deluso', id: 'Kecewa' },
      { it: 'orgoglioso', id: 'Bangga' },
      { it: 'timido', id: 'Malu' },
      { it: 'curioso', id: 'Penasaran' },
      { it: 'soddisfatto', id: 'Puas' },
      { it: 'preoccupato', id: 'Khawatir' },
      { it: 'nervoso', id: 'Gugup' },
      { it: 'confuso', id: 'Bingung' },
      { it: 'coraggioso', id: 'Pemberani' },
      { it: 'pauroso', id: 'Penakut' },
      { it: 'geloso', id: 'Cemburu' },
      { it: 'colpevole', id: 'Bersalah' },
      { it: 'solo', id: 'Kesepian' },
      { it: 'calmo', id: 'Tenang' },
      { it: 'ansioso', id: 'Gelisah' },
      { it: 'stanco', id: 'Lelah' },
      { it: 'annoiato', id: 'Bosan' },
      { it: 'grato', id: 'Bersyukur' },
      { it: 'invidioso', id: 'Iri' },
      { it: 'innamorato', id: 'Jatuh cinta' },
      { it: 'entusiasta', id: 'Antusias' },
      { it: 'panico', id: 'Panik' },
      { it: 'fiducioso', id: 'Percaya diri' }
    ],
    verbes: [
      { it: 'essere', id: 'Adalah' },
      { it: 'avere', id: 'Memiliki' },
      { it: 'potere', id: 'Bisa' },
      { it: 'volere', id: 'Mau' },
      { it: 'dovere', id: 'Harus' },
      { it: 'andare', id: 'Pergi' },
      { it: 'venire', id: 'Datang' },
      { it: 'fare', id: 'Membuat' },
      { it: 'dire', id: 'Berkata' },
      { it: 'dare', id: 'Memberi' },
      { it: 'prendere', id: 'Mengambil' },
      { it: 'vedere', id: 'Melihat' },
      { it: 'sapere', id: 'Tahu' },
      { it: 'capire', id: 'Mengerti' },
      { it: 'pensare', id: 'Berpikir' },
      { it: 'credere', id: 'Percaya' },
      { it: 'amare', id: 'Mencintai' },
      { it: 'odiare', id: 'Membenci' },
      { it: 'comprare', id: 'Membeli' },
      { it: 'vendere', id: 'Menjual' },
      { it: 'lavorare', id: 'Bekerja' },
      { it: 'studiare', id: 'Belajar' },
      { it: 'leggere', id: 'Membaca' },
      { it: 'scrivere', id: 'Menulis' },
      { it: 'ascoltare', id: 'Mendengarkan' },
      { it: 'rispondere', id: 'Menjawab' },
      { it: 'chiedere', id: 'Bertanya' },
      { it: 'spiegare', id: 'Menjelaskan' },
      { it: 'mostrare', id: 'Menunjukkan' },
      { it: 'cercare', id: 'Mencari' },
      { it: 'trovare', id: 'Menemukan' },
      { it: 'perdere', id: 'Kehilangan' },
      { it: 'vincere', id: 'Menang' },
      { it: 'aprire', id: 'Membuka' },
      { it: 'chiudere', id: 'Menutup' },
      { it: 'iniziare', id: 'Memulai' },
      { it: 'finire', id: 'Mengakhiri' },
      { it: 'mangiare', id: 'Makan' },
      { it: 'bere', id: 'Minum' },
      { it: 'dormire', id: 'Tidur' },
      { it: 'vivere', id: 'Hidup' },
      { it: 'morire', id: 'Mati' },
      { it: 'nascere', id: 'Lahir' },
      { it: 'aiutare', id: 'Membantu' },
      { it: 'aspettare', id: 'Menunggu' },
      { it: 'portare', id: 'Membawa' },
      { it: 'ricevere', id: 'Menerima' },
      { it: 'inviare', id: 'Mengirim' },
      { it: 'pagare', id: 'Membayar' },
      { it: 'camminare', id: 'Berjalan-jalan' }
    ],
    bodyParts: [
      { it: 'la testa', id: 'Kepala', note: 'feminin' },
      { it: 'il viso', id: 'Wajah', note: 'maskulin' },
      { it: 'la fronte', id: 'Dahi', note: 'feminin' },
      { it: 'il sopracciglio', id: 'Alis', note: 'maskulin' },
      { it: "l'occhio", id: 'Mata', note: 'netral' },
      { it: 'le ciglia', id: 'Bulu mata' },
      { it: 'il naso', id: 'Hidung', note: 'maskulin' },
      { it: 'la guancia', id: 'Pipi', note: 'feminin' },
      { it: 'la bocca', id: 'Mulut', note: 'feminin' },
      { it: 'il labbro', id: 'Bibir', note: 'maskulin' },
      { it: 'il dente', id: 'Gigi', note: 'maskulin' },
      { it: 'la lingua', id: 'Lidah', note: 'feminin' },
      { it: 'il mento', id: 'Dagu', note: 'maskulin' },
      { it: 'la mascella', id: 'Rahang', note: 'feminin' },
      { it: "l'orecchio", id: 'Telinga', note: 'netral' },
      { it: 'il collo', id: 'Leher', note: 'maskulin' },
      { it: 'la spalla', id: 'Bahu', note: 'feminin' },
      { it: 'il braccio', id: 'Lengan', note: 'maskulin' },
      { it: 'il gomito', id: 'Siku', note: 'maskulin' },
      { it: 'la mano', id: 'Tangan', note: 'feminin' },
      { it: 'il dito', id: 'Jari', note: 'maskulin' },
      { it: 'il pollice', id: 'Ibu jari', note: 'maskulin' },
      { it: 'il palmo', id: 'Telapak tangan', note: 'maskulin' },
      { it: 'il petto', id: 'Dada', note: 'maskulin' },
      { it: 'la costola', id: 'Tulang rusuk', note: 'feminin' },
      { it: "l'addome", id: 'Perut', note: 'netral' },
      { it: 'la schiena', id: 'Punggung', note: 'feminin' },
      { it: 'la vita', id: 'Pinggang', note: 'feminin' },
      { it: "l'anca", id: 'Pinggul', note: 'feminin' },
      { it: 'la coscia', id: 'Paha', note: 'feminin' },
      { it: 'il ginocchio', id: 'Lutut', note: 'netral' },
      { it: 'la gamba', id: 'Tungkai', note: 'feminin' },
      { it: 'il polpaccio', id: 'Betis', note: 'maskulin' },
      { it: 'la caviglia', id: 'Pergelangan kaki', note: 'feminin' },
      { it: 'il piede', id: 'Kaki', note: 'maskulin' },
      { it: 'la pelle', id: 'Kulit', note: 'feminin' },
      { it: 'i capelli', id: 'Rambut' },
      { it: 'la barba', id: 'Janggut', note: 'feminin' },
      { it: 'il cuore', id: 'Jantung', note: 'maskulin' },
      { it: 'il polmone', id: 'Paru-paru', note: 'maskulin' },
      { it: 'il fegato', id: 'Hati', note: 'maskulin' },
      { it: 'il rene', id: 'Ginjal', note: 'maskulin' },
      { it: 'lo stomaco', id: 'Lambung', note: 'maskulin' },
      { it: "l'intestino", id: 'Usus', note: 'netral' },
      { it: 'il cervello', id: 'Otak', note: 'maskulin' },
      { it: 'il sangue', id: 'Darah', note: 'maskulin' },
      { it: "l'osso", id: 'Tulang', note: 'netral' },
      { it: 'il muscolo', id: 'Otot', note: 'maskulin' },
      { it: 'il nervo', id: 'Saraf', note: 'maskulin' }
    ],
    clothing: [
      { it: 'il vestito', id: 'Gaun', note: 'maskulin' },
      { it: 'la gonna', id: 'Rok', note: 'feminin' },
      { it: 'i pantaloni', id: 'Celana' },
      { it: 'i jeans', id: 'Jeans' },
      { it: 'la maglietta', id: 'Kaos', note: 'feminin' },
      { it: 'la camicetta', id: 'Blus', note: 'feminin' },
      { it: 'il maglione', id: 'Sweter', note: 'maskulin' },
      { it: 'la giacca', id: 'Jaket', note: 'feminin' },
      { it: 'il cappotto', id: 'Mantel', note: 'maskulin' },
      { it: "l'abito", id: 'Jas', note: 'netral' },
      { it: 'la camicia', id: 'Kemeja', note: 'feminin' },
      { it: 'la cravatta', id: 'Dasi', note: 'feminin' },
      { it: 'la cintura', id: 'Ikat pinggang', note: 'feminin' },
      { it: 'le scarpe', id: 'Sepatu' },
      { it: 'gli stivali', id: 'Bot' },
      { it: 'i calzini', id: 'Kaus kaki' },
      { it: 'il cappello', id: 'Topi', note: 'maskulin' },
      { it: 'il berretto', id: 'Topi hangat', note: 'maskulin' },
      { it: 'la sciarpa', id: 'Syal', note: 'feminin' },
      { it: 'i guanti', id: 'Sarung tangan' },
      { it: 'gli occhiali', id: 'Kacamata' },
      { it: 'il gioiello', id: 'Perhiasan', note: 'maskulin' },
      { it: 'la collana', id: 'Kalung', note: 'feminin' },
      { it: "l'anello", id: 'Cincin', note: 'netral' },
      { it: 'il braccialetto', id: 'Gelang', note: 'maskulin' },
      { it: 'gli orecchini', id: 'Anting' },
      { it: 'il costume da bagno', id: 'Baju renang', note: 'maskulin' },
      { it: 'il pigiama', id: 'Baju tidur', note: 'maskulin' },
      { it: 'la biancheria intima', id: 'Pakaian dalam', note: 'feminin' },
      { it: 'le calze', id: 'Stoking' },
      { it: 'la tuta sportiva', id: 'Pakaian olahraga', note: 'feminin' },
      { it: "l'uniforme", id: 'Seragam', note: 'netral' },
      { it: 'il camice', id: 'Jas lab', note: 'maskulin' },
      { it: 'la tutina', id: 'Wangsu', note: 'feminin' }
    ],
    house: [
      { it: 'la casa', id: 'Rumah', note: 'feminin' },
      { it: "l'appartamento", id: 'Apartemen', note: 'netral' },
      { it: 'la stanza', id: 'Kamar', note: 'feminin' },
      { it: 'la camera da letto', id: 'Kamar tidur', note: 'feminin' },
      { it: 'il soggiorno', id: 'Ruang tamu', note: 'maskulin' },
      { it: 'la cucina', id: 'Dapur', note: 'feminin' },
      { it: 'il bagno', id: 'Kamar mandi', note: 'maskulin' },
      { it: 'la sala da pranzo', id: 'Ruang makan', note: 'feminin' },
      { it: 'lo studio', id: 'Ruang kerja', note: 'maskulin' },
      { it: 'la cameretta', id: 'Kamar anak', note: 'feminin' },
      { it: 'il corridoio', id: 'Koridor', note: 'maskulin' },
      { it: "l'ingresso", id: 'Ruang depan', note: 'netral' },
      { it: 'il balcone', id: 'Balkon', note: 'maskulin' },
      { it: 'la terrazza', id: 'Teras', note: 'feminin' },
      { it: 'il giardino', id: 'Kebun', note: 'maskulin' },
      { it: 'la cantina', id: 'Gudang bawah tanah', note: 'feminin' },
      { it: 'la soffitta', id: 'Loteng', note: 'feminin' },
      { it: 'il garage', id: 'Garasi', note: 'maskulin' },
      { it: 'il tetto', id: 'Atap', note: 'maskulin' },
      { it: 'il camino', id: 'Cerobong asap', note: 'maskulin' },
      { it: 'la finestra', id: 'Jendela', note: 'feminin' },
      { it: 'la porta', id: 'Pintu', note: 'feminin' },
      { it: 'il cancello', id: 'Gerbang', note: 'maskulin' },
      { it: 'il muro', id: 'Tembok', note: 'maskulin' },
      { it: 'il pavimento', id: 'Lantai', note: 'maskulin' },
      { it: 'il soffitto', id: 'Langit-langit', note: 'maskulin' },
      { it: 'la scala', id: 'Tangga', note: 'feminin' },
      { it: 'il corrimano', id: 'Pegangan', note: 'maskulin' },
      { it: 'la chiave', id: 'Kunci', note: 'feminin' },
      { it: 'la serratura', id: 'Kunci pintu', note: 'feminin' },
      { it: 'la maniglia', id: 'Gagang pintu', note: 'feminin' },
      { it: 'il campanello', id: 'Bel pintu', note: 'maskulin' },
      { it: 'il riscaldamento', id: 'Pemanas', note: 'maskulin' },
      { it: "l'aria condizionata", id: 'AC', note: 'feminin' },
      { it: 'la presa', id: 'Stop kontak', note: 'feminin' },
      { it: "l'interruttore", id: 'Sakelar', note: 'netral' },
      { it: 'la lavatrice', id: 'Mesin cuci', note: 'feminin' },
      { it: 'il frigorifero', id: 'Kulkas', note: 'maskulin' },
      { it: 'il forno', id: 'Oven', note: 'maskulin' },
      { it: 'il fornello', id: 'Kompor', note: 'maskulin' },
      { it: 'la lavastoviglie', id: 'Mesin pencuci piring', note: 'feminin' },
      { it: "l'aspirapolvere", id: 'Penyedot debu', note: 'netral' },
      { it: 'il secchio della spazzatura', id: 'Tempat sampah', note: 'maskulin' },
      { it: 'lo specchio', id: 'Cermin', note: 'maskulin' },
      { it: 'il divano', id: 'Sofa', note: 'maskulin' },
      { it: "l'armadio", id: 'Lemari', note: 'netral' },
      { it: 'la mensola', id: 'Rak', note: 'feminin' },
      { it: 'il tavolo', id: 'Meja', note: 'maskulin' },
      { it: 'la sedia', id: 'Kursi', note: 'feminin' },
      { it: 'il letto', id: 'Tempat tidur', note: 'maskulin' },
      { it: 'il materasso', id: 'Kasur', note: 'maskulin' },
      { it: 'il cuscino', id: 'Bantal', note: 'maskulin' },
      { it: 'la coperta', id: 'Selimut', note: 'feminin' },
      { it: 'il lenzuolo', id: 'Sprei', note: 'maskulin' },
      { it: 'la lampada', id: 'Lampu', note: 'feminin' },
      { it: 'il tappeto', id: 'Karpet', note: 'maskulin' },
      { it: 'la tenda', id: 'Gorden', note: 'feminin' },
      { it: 'il quadro', id: 'Lukisan', note: 'maskulin' },
      { it: "l'orologio", id: 'Jam', note: 'netral' },
      { it: 'il vaso', id: 'Vas', note: 'maskulin' }
    ],
    nature: [
      { it: 'il sole', id: 'Matahari', note: 'maskulin' },
      { it: 'la luna', id: 'Bulan', note: 'feminin' },
      { it: 'la stella', id: 'Bintang', note: 'feminin' },
      { it: 'il cielo', id: 'Langit', note: 'maskulin' },
      { it: 'il mare', id: 'Laut', note: 'maskulin' },
      { it: "l'oceano", id: 'Samudra', note: 'netral' },
      { it: 'il fiume', id: 'Sungai', note: 'maskulin' },
      { it: 'il lago', id: 'Danau', note: 'maskulin' },
      { it: 'la montagna', id: 'Gunung', note: 'feminin' },
      { it: 'la collina', id: 'Bukit', note: 'feminin' },
      { it: 'la foresta', id: 'Hutan', note: 'feminin' },
      { it: "l'albero", id: 'Pohon', note: 'netral' },
      { it: 'il fiore', id: 'Bunga', note: 'maskulin' },
      { it: "l'erba", id: 'Rumput', note: 'feminin' },
      { it: 'la pietra', id: 'Batu', note: 'feminin' },
      { it: 'la sabbia', id: 'Pasir', note: 'feminin' },
      { it: 'la nuvola', id: 'Awan', note: 'feminin' },
      { it: 'la pioggia', id: 'Hujan', note: 'feminin' },
      { it: 'la neve', id: 'Salju', note: 'feminin' },
      { it: 'il vento', id: 'Angin', note: 'maskulin' },
      { it: "l'aria", id: 'Udara', note: 'feminin' },
      { it: 'la terra', id: 'Tanah/Bumi', note: 'feminin' },
      { it: "l'acqua", id: 'Air', note: 'feminin' },
      { it: 'il fuoco', id: 'Api', note: 'maskulin' },
      { it: "l'arcobaleno", id: 'Pelangi', note: 'netral' },
      { it: 'il lampo', id: 'Petir', note: "maskulin'" },
      { it: 'il tuono', id: 'Guntur', note: 'maskulin' },
      { it: "l'alba", id: 'Fajar', note: 'feminin' },
      { it: 'il tramonto', id: 'Senja', note: 'maskulin' },
      { it: "l'isola", id: 'Pulau', note: 'feminin' },
      { it: 'la spiaggia', id: 'Pantai', note: 'feminin' },
      { it: 'il deserto', id: 'Gurun', note: 'maskulin' },
      { it: 'la valle', id: 'Lembah', note: 'feminin' },
      { it: 'la cascata', id: 'Air terjun', note: 'feminin' },
      { it: 'la grotta', id: 'Gua', note: 'feminin' },
      { it: 'il vulcano', id: 'Gunung berapi', note: 'maskulin' },
      { it: 'il terremoto', id: 'Gempa bumi', note: 'maskulin' },
      { it: "l'alluvione", id: 'Banjir', note: 'feminin' },
      { it: 'la siccità', id: 'Kekeringan', note: 'feminin' }
    ],
    animalsDomestic: [
      { it: 'il cane', id: 'Anjing', note: 'maskulin' },
      { it: 'il gatto', id: 'Kucing', note: 'maskulin' },
      { it: 'il coniglio', id: 'Kelinci', note: 'maskulin' },
      { it: "l'uccello", id: 'Burung', note: 'netral' },
      { it: 'il pesce rosso', id: 'Ikan mas', note: 'maskulin' },
      { it: 'il criceto', id: 'Hamster', note: 'maskulin' },
      { it: 'la tartaruga', id: 'Kura-kura', note: 'feminin' },
      { it: 'il cavallo', id: 'Kuda', note: 'maskulin' },
      { it: 'la gallina', id: 'Ayam betina', note: 'feminin' },
      { it: 'il gallo', id: 'Ayam jantan', note: 'maskulin' },
      { it: "l'anatra", id: 'Bebek', note: 'feminin' },
      { it: 'la capra', id: 'Kambing', note: 'feminin' },
      { it: 'la pecora', id: 'Domba', note: 'feminin' },
      { it: 'il maiale', id: 'Babi', note: 'maskulin' },
      { it: "l'asino", id: 'Keledai', note: 'netral' },
      { it: 'la mucca', id: 'Sapi', note: 'feminin' },
      { it: 'il toro', id: 'Banteng', note: 'maskulin' },
      { it: 'il tacchino', id: 'Kalkun', note: 'maskulin' },
      { it: 'il piccione', id: 'Merpati', note: 'maskulin' },
      { it: 'il pappagallo', id: 'Burung beo', note: 'maskulin' }
    ],
    animalsWild: [
      { it: 'il leone', id: 'Singa', note: 'maskulin' },
      { it: 'la tigre', id: 'Harimau', note: 'feminin' },
      { it: "l'elefante", id: 'Gajah', note: 'maskulin' },
      { it: 'la giraffa', id: 'Jerapah', note: 'feminin' },
      { it: 'la zebra', id: 'Zebra', note: 'feminin' },
      { it: 'il gorilla', id: 'Gorila', note: 'maskulin' },
      { it: "l'orso", id: 'Beruang', note: 'netral' },
      { it: 'il lupo', id: 'Serigala', note: 'maskulin' },
      { it: 'la volpe', id: 'Rubah', note: 'feminin' },
      { it: 'il cervo', id: 'Rusa', note: 'maskulin' },
      { it: 'il serpente', id: 'Ular', note: 'maskulin' },
      { it: 'il coccodrillo', id: 'Buaya', note: 'maskulin' },
      { it: "l'ippopotamo", id: 'Kuda nil', note: 'netral' },
      { it: 'il rinoceronte', id: 'Badak', note: 'maskulin' },
      { it: 'la scimmia', id: 'Monyet', note: 'feminin' },
      { it: 'il canguro', id: 'Kanguru', note: 'maskulin' },
      { it: 'il koala', id: 'Koala', note: 'maskulin' },
      { it: 'la iena', id: 'Hiena', note: 'feminin' },
      { it: 'il leopardo', id: 'Macan tutul', note: 'maskulin' },
      { it: 'il ghepardo', id: 'Cheetah', note: 'maskulin' },
      { it: 'lo sciacallo', id: 'Jakal', note: 'maskulin' },
      { it: "l'avvoltoio", id: 'Burung nasar', note: 'netral' },
      { it: 'il cinghiale', id: 'Babi hutan', note: 'maskulin' },
      { it: 'il procione', id: 'Rakun', note: 'maskulin' },
      { it: 'il riccio', id: 'Landak', note: 'maskulin' },
      { it: 'il castoro', id: 'Berang-berang', note: 'maskulin' },
      { it: 'lo scoiattolo', id: 'Tupai', note: 'maskulin' },
      { it: 'la talpa', id: 'Tikus tanah', note: 'feminin' },
      { it: 'il pipistrello', id: 'Kelelawar', note: 'maskulin' }
    ],
    animalsSea: [
      { it: 'la balena', id: 'Paus', note: 'feminin' },
      { it: 'il delfino', id: 'Lumba-lumba', note: 'maskulin' },
      { it: 'lo squalo', id: 'Hiu', note: 'maskulin' },
      { it: 'la tartaruga marina', id: 'Penyu', note: 'feminin' },
      { it: 'la foca', id: 'Anjing laut', note: 'feminin' },
      { it: "l'otaria", id: 'Singa laut', note: 'feminin' },
      { it: 'il granchio', id: 'Kepiting', note: 'maskulin' },
      { it: 'il gambero', id: 'Udang', note: 'maskulin' },
      { it: "l'ostrica", id: 'Tiram', note: 'feminin' },
      { it: 'il mollusco', id: 'Kerang', note: 'maskulin' },
      { it: 'il polpo', id: 'Gurita', note: 'maskulin' },
      { it: 'il calamaro', id: 'Cumi-cumi', note: 'maskulin' },
      { it: 'la medusa', id: 'Ubur-ubur', note: 'feminin' },
      { it: 'la stella marina', id: 'Bintang laut', note: 'feminin' },
      { it: 'il cavalluccio marino', id: 'Kuda laut', note: 'maskulin' }
    ],
    insects: [
      { it: "l'ape", id: 'Lebah', note: 'feminin' },
      { it: 'la formica', id: 'Semut', note: 'feminin' },
      { it: 'la farfalla', id: 'Kupu-kupu', note: 'feminin' },
      { it: 'il bruco', id: 'Ulat', note: 'maskulin' },
      { it: 'la coccinella', id: 'Kepik', note: 'feminin' },
      { it: 'lo scarafaggio', id: 'Kecoak', note: 'maskulin' },
      { it: 'la mosca', id: 'Lalat', note: 'feminin' },
      { it: 'la zanzara', id: 'Nyamuk', note: 'feminin' },
      { it: 'la falena', id: 'Ngengat', note: 'feminin' },
      { it: 'la cavalletta', id: 'Belalang', note: 'feminin' },
      { it: 'il grillo', id: 'Jangkrik', note: 'maskulin' },
      { it: 'il ragno', id: 'Laba-laba', note: 'maskulin' },
      { it: 'lo scorpione', id: 'Kalajengking', note: 'maskulin' },
      { it: 'la cimice', id: 'Kutu busuk', note: 'feminin' },
      { it: 'la libellula', id: 'Capung', note: 'feminin' },
      { it: 'la mantide religiosa', id: 'Belalang sembah', note: 'feminin' }
    ],
    foodExtended: [
      { it: 'il cornetto', id: 'Croissant', note: 'maskulin' },
      { it: 'il pretzel', id: 'Pretzel', note: 'maskulin' },
      { it: 'la torta', id: 'Kue', note: 'feminin' },
      { it: 'la crêpe', id: 'Kue dadar', note: 'feminin' },
      { it: 'il waffle', id: 'Waffle', note: 'maskulin' },
      { it: 'il quiche', id: 'Kue pai asin', note: 'maskulin' },
      { it: 'il formaggio di capra', id: 'Keju kambing', note: 'maskulin' },
      { it: 'il camembert', id: 'Keju Camembert', note: 'maskulin' },
      { it: 'la salsiccia', id: 'Sosis', note: 'feminin' },
      { it: 'i crauti', id: 'Kubis asam' },
      { it: "l'insalata russa", id: 'Salad Rusia', note: 'feminin' },
      { it: 'la cotoletta', id: 'Schnitzel', note: 'feminin' },
      { it: 'lo strudel di mele', id: 'Strudel apel', note: 'maskulin' },
      { it: 'il pane', id: 'Roti', note: 'maskulin' },
      { it: 'il panino', id: 'Roti kecil', note: 'maskulin' },
      { it: 'la pasta', id: 'Pasta', note: 'feminin' },
      { it: 'la zuppa di pomodoro', id: 'Sup tomat', note: 'feminin' },
      { it: "l'insalata di frutta", id: 'Salad buah', note: 'feminin' },
      { it: "l'insalata mista", id: 'Salad sayuran', note: 'feminin' },
      { it: 'la mela', id: 'Apel', note: 'feminin' },
      { it: 'la pera', id: 'Pir', note: 'feminin' },
      { it: 'la pesca', id: 'Persik', note: 'feminin' },
      { it: 'la ciliegia', id: 'Ceri', note: 'feminin' },
      { it: 'la fragola', id: 'Stroberi', note: "feminin'" },
      { it: 'il mirtillo', id: 'Blueberry', note: 'maskulin' },
      { it: 'il lampone', id: 'Raspberry', note: 'maskulin' },
      { it: "l'uva", id: 'Anggur buah', note: 'feminin' },
      { it: 'il melone', id: 'Melon', note: 'maskulin' },
      { it: "l'arancia", id: 'Jeruk', note: 'feminin' },
      { it: 'il limone', id: 'Lemon', note: 'maskulin' },
      { it: "l'ananas", id: 'Nanas', note: 'maskulin' },
      { it: 'il mango', id: 'Mangga', note: 'maskulin' },
      { it: 'il kiwi', id: 'Kiwi', note: 'maskulin' },
      { it: 'la prugna', id: 'Plum', note: 'feminin' },
      { it: 'la mandorla', id: 'Almond', note: 'feminin' },
      { it: 'la noce', id: 'Kenari', note: 'feminin' },
      { it: 'la nocciola', id: 'Hazelnut', note: 'feminin' },
      { it: "l'arachide", id: 'Kacang tanah', note: 'feminin' },
      { it: 'il pistacchio', id: 'Kacang pistachio', note: 'maskulin' },
      { it: "l'anacardio", id: 'Kacang mete', note: 'maskulin' },
      { it: 'la marmellata', id: 'Selai', note: 'feminin' },
      { it: 'il miele', id: 'Madu', note: 'maskulin' },
      { it: 'il burro', id: 'Mentega', note: 'maskulin' },
      { it: 'la farina', id: 'Tepung', note: 'feminin' },
      { it: "l'olio d'oliva", id: 'Minyak zaitun', note: 'netral' },
      { it: "l'aceto", id: 'Cuka', note: 'netral' },
      { it: 'la senape', id: 'Mustard', note: 'feminin' },
      { it: 'il ketchup', id: 'Kecap', note: 'maskulin' },
      { it: 'la maionese', id: 'Mayones', note: 'feminin' },
      { it: 'la panna', id: 'Krim', note: 'feminin' },
      { it: 'lo yogurt', id: 'Yogurt', note: 'maskulin' }
    ],
    transportation: [
      { it: "l'automobile", id: 'Mobil', note: 'feminin' },
      { it: 'il camion', id: 'Truk', note: 'maskulin' },
      { it: "l'autobus", id: 'Bus', note: 'maskulin' },
      { it: 'la metropolitana', id: 'Kereta bawah tanah', note: 'feminin' },
      { it: 'il treno', id: 'Kereta api', note: 'maskulin' },
      { it: 'il tram', id: 'Trem', note: 'maskulin' },
      { it: 'il taxi', id: 'Taksi', note: 'maskulin' },
      { it: "l'aereo", id: 'Pesawat', note: 'netral' },
      { it: 'la nave', id: 'Kapal', note: 'feminin' },
      { it: 'la bicicletta', id: 'Sepeda', note: 'feminin' },
      { it: 'la motocicletta', id: 'Motor', note: 'feminin' },
      { it: 'lo scooter', id: 'Skuter', note: 'maskulin' },
      { it: 'il traghetto', id: 'Kapal feri', note: 'maskulin' },
      { it: 'lo yacht', id: 'Kapal pesiar', note: 'maskulin' },
      { it: 'la funivia', id: 'Kereta gantung', note: 'feminin' },
      { it: 'il treno ad alta velocità', id: 'Kereta cepat', note: 'maskulin' },
      { it: "l'elicottero", id: 'Helikopter', note: 'netral' },
      { it: 'il dirigibile', id: 'Balon udara', note: 'maskulin' },
      { it: 'il sottomarino', id: 'Kapal selam', note: 'maskulin' },
      { it: 'la nave cargo', id: 'Kapal kargo', note: 'feminin' },
      { it: "l'ambulanza", id: 'Ambulans', note: 'feminin' },
      { it: 'il camion dei pompieri', id: 'Truk pemadam', note: 'maskulin' },
      { it: 'il camion della spazzatura', id: 'Truk sampah', note: 'maskulin' },
      { it: 'il trattore', id: 'Traktor', note: 'maskulin' },
      { it: 'il veicolo', id: 'Kendaraan', note: 'maskulin' },
      { it: "l'autostrada", id: 'Jalan tol', note: 'feminin' },
      { it: 'la strada', id: 'Jalan raya', note: 'feminin' },
      { it: 'l incrocio', id: 'Perempatan', note: 'maskulin' },
      { it: 'la rotatoria', id: 'Bundaran', note: 'feminin' },
      { it: 'il parcheggio', id: 'Parkir', note: 'maskulin' },
      { it: 'il passaggio pedonale', id: 'Penyeberangan', note: 'maskulin' },
      { it: 'il semaforo', id: 'Lampu lalu lintas', note: 'maskulin' },
      { it: 'il segnale stradale', id: 'Rambu lalu lintas', note: 'maskulin' },
      { it: 'la cintura di sicurezza', id: 'Sabuk pengaman', note: 'feminin' },
      { it: 'la patente', id: 'SIM', note: 'feminin' },
      { it: 'la benzina', id: 'Bensin', note: 'feminin' },
      { it: 'il serbatoio', id: 'Tangki', note: 'maskulin' },
      { it: 'il motore', id: 'Mesin', note: 'maskulin' },
      { it: 'la ruota', id: 'Roda', note: 'feminin' }
    ],
    technology: [
      { it: 'il computer', id: 'Komputer', note: 'maskulin' },
      { it: 'lo schermo', id: 'Layar', note: 'maskulin' },
      { it: 'la tastiera', id: 'Keyboard', note: 'feminin' },
      { it: 'il mouse', id: 'Mouse', note: 'maskulin' },
      { it: 'la stampante', id: 'Printer', note: 'feminin' },
      { it: 'il telefono', id: 'Telepon', note: 'maskulin' },
      { it: 'il cellulare', id: 'HP', note: 'maskulin' },
      { it: 'il tablet', id: 'Tablet', note: 'maskulin' },
      { it: 'internet', id: 'Internet', note: 'maskulin' },
      { it: 'la rete', id: 'Jaringan', note: 'feminin' },
      { it: 'la connessione', id: 'Koneksi', note: 'feminin' },
      { it: 'il Wi-Fi', id: 'Wifi', note: 'maskulin' },
      { it: "l'applicazione", id: 'Aplikasi', note: 'feminin' },
      { it: 'il software', id: 'Perangkat lunak', note: 'maskulin' },
      { it: "l'hardware", id: 'Perangkat keras', note: 'maskulin' },
      { it: 'il touchscreen', id: 'Layar sentuh', note: 'maskulin' },
      { it: 'il processore', id: 'Prosesor', note: 'maskulin' },
      { it: 'la memoria', id: 'Memori', note: 'feminin' },
      { it: 'il disco rigido', id: 'Hard disk', note: 'maskulin' },
      { it: 'la chiavetta USB', id: 'Flashdisk', note: 'feminin' },
      { it: 'la macchina fotografica', id: 'Kamera', note: 'feminin' },
      { it: 'il video', id: 'Video', note: 'maskulin' },
      { it: 'la foto', id: 'Foto', note: 'feminin' },
      { it: 'le cuffie', id: 'Headset' },
      { it: 'le casse', id: 'Speaker' },
      { it: 'il caricabatterie', id: 'Charger', note: 'maskulin' },
      { it: 'la batteria', id: 'Baterai', note: 'feminin' },
      { it: 'la schermata home', id: 'Home screen', note: 'feminin' },
      { it: 'la password', id: 'Password', note: 'feminin' },
      { it: "l'e-mail", id: 'Email', note: 'feminin' },
      { it: 'il browser', id: 'Browser', note: 'maskulin' },
      { it: 'la pagina web', id: 'Halaman web', note: 'feminin' },
      { it: 'il sito web', id: 'Situs web', note: 'maskulin' },
      { it: 'il blog', id: 'Blog', note: 'maskulin' },
      { it: 'il social network', id: 'Jejaring sosial', note: 'maskulin' },
      { it: 'il messaggio', id: 'Pesan', note: 'maskulin' },
      { it: "l'allegato", id: 'Lampiran', note: 'netral' },
      { it: 'scaricare', id: 'Mengunduh' },
      { it: 'aggiornare', id: 'Memperbarui' },
      { it: 'salvare', id: 'Menyimpan' },
      { it: 'inviare', id: 'Mengirim' },
      { it: 'eliminare', id: 'Menghapus' },
      { it: 'stampare', id: 'Mencetak' }
    ],
    schoolEducation: [
      { it: 'la scuola', id: 'Sekolah', note: 'feminin' },
      { it: "l'università", id: 'Universitas', note: 'feminin' },
      { it: 'la classe', id: 'Kelas', note: 'feminin' },
      { it: 'la lavagna', id: 'Papan tulis', note: 'feminin' },
      { it: 'la cattedra', id: 'Meja guru', note: 'feminin' },
      { it: 'il libro', id: 'Buku', note: 'maskulin' },
      { it: 'il quaderno', id: 'Buku tulis', note: 'maskulin' },
      { it: 'la penna', id: 'Pena', note: 'feminin' },
      { it: 'la matita', id: 'Pensil', note: 'feminin' },
      { it: 'la gomma', id: 'Penghapus', note: 'feminin' },
      { it: 'il righello', id: 'Penggaris', note: 'maskulin' },
      { it: 'lo zaino', id: 'Tas punggung', note: 'maskulin' },
      { it: 'il pennarello', id: 'Spidol', note: 'maskulin' },
      { it: 'il gesso', id: 'Kapur tulis', note: 'maskulin' },
      { it: "l'equazione", id: 'Persamaan', note: 'feminin' },
      { it: 'la frazione', id: 'Pecahan', note: 'feminin' },
      { it: 'il risultato', id: 'Hasil', note: 'maskulin' },
      { it: 'la media', id: 'Nilai rata-rata', note: 'feminin' },
      { it: 'il voto', id: 'Nilai', note: 'maskulin' },
      { it: 'i compiti', id: 'PR' },
      { it: "l'esame", id: 'Ujian', note: 'netral' },
      { it: 'il corso', id: 'Kursus', note: 'maskulin' },
      { it: 'la materia', id: 'Mata pelajaran', note: 'feminin' },
      { it: "l'italiano", id: 'Bahasa Italia', note: 'maskulin' },
      { it: 'la matematica', id: 'Matematika', note: 'feminin' },
      { it: 'la fisica', id: 'Fisika', note: 'feminin' },
      { it: 'la chimica', id: 'Kimia', note: 'feminin' },
      { it: 'la biologia', id: 'Biologi', note: 'feminin' },
      { it: 'la storia', id: 'Sejarah', note: 'feminin' },
      { it: 'la geografia', id: 'Geografi', note: 'feminin' },
      { it: "l'inglese", id: 'Bahasa Inggris', note: 'maskulin' },
      { it: "l'arte", id: 'Seni', note: 'feminin' },
      { it: 'la musica', id: 'Musik', note: 'feminin' },
      { it: 'educazione fisica', id: 'Olahraga', note: 'feminin' },
      { it: 'la filosofia', id: 'Filsafat', note: 'feminin' },
      { it: "l'economia", id: 'Ekonomi', note: 'feminin' },
      { it: 'il semestre', id: 'Semester', note: 'maskulin' },
      { it: 'il campus', id: 'Kampus', note: 'maskulin' },
      { it: 'la biblioteca', id: 'Perpustakaan', note: 'feminin' },
      { it: 'la mensa', id: 'Kantin', note: 'feminin' },
      { it: "l'iscrizione", id: 'Pendaftaran', note: 'feminin' },
      { it: 'la laurea', id: 'Gelar', note: 'feminin' },
      { it: 'la tesi', id: 'Tesis', note: 'feminin' },
      { it: 'il tirocinio', id: 'Magang', note: 'maskulin' },
      { it: 'il professore', id: 'Profesor', note: 'maskulin' },
      { it: 'il rettore', id: 'Rektor', note: 'maskulin' },
      { it: 'lo studente', id: 'Siswa', note: 'maskulin' },
      { it: 'il compagno di classe', id: 'Teman sekelas', note: 'maskulin' }
    ],
    workOffice: [
      { it: "l'ufficio", id: 'Kantor', note: 'netral' },
      { it: 'la riunione', id: 'Rapat', note: 'feminin' },
      { it: 'il capo', id: 'Atasan', note: 'maskulin' },
      { it: 'il collega', id: 'Rekan kerja', note: 'maskulin' },
      { it: 'lo stipendio', id: 'Gaji', note: 'maskulin' },
      { it: 'il lavoro', id: 'Pekerjaan', note: 'maskulin' },
      { it: 'il contratto', id: 'Kontrak', note: 'maskulin' },
      { it: 'le vacanze', id: 'Liburan' },
      { it: 'la pausa', id: 'Istirahat', note: 'feminin' },
      { it: 'la fine della giornata lavorativa', id: 'Akhir hari kerja', note: 'feminin' },
      { it: 'il colloquio', id: 'Wawancara kerja', note: 'maskulin' },
      { it: 'la candidatura', id: 'Lamaran kerja', note: 'feminin' },
      { it: 'il curriculum vitae', id: 'CV', note: 'maskulin' },
      { it: 'la lettera di presentazione', id: 'Surat motivasi', note: 'feminin' },
      { it: 'la promozione', id: 'Promosi', note: 'feminin' },
      { it: 'il licenziamento', id: 'PHK', note: 'maskulin' },
      { it: 'la pensione', id: 'Pensiun', note: 'feminin' },
      { it: 'il dipartimento', id: 'Departemen', note: 'maskulin' },
      { it: 'il progetto', id: 'Proyek', note: 'maskulin' },
      { it: 'il successo', id: 'Keberhasilan', note: 'maskulin' },
      { it: 'il risultato', id: 'Pencapaian', note: 'maskulin' },
      { it: "l'ambizione", id: 'Ambisi', note: 'feminin' },
      { it: 'la valutazione', id: 'Penilaian', note: 'feminin' },
      { it: 'il bonus', id: 'Bonus', note: 'maskulin' },
      { it: 'la tassa', id: 'Pajak', note: 'feminin' },
      { it: 'la cassa', id: 'Kasir', note: 'feminin' },
      { it: "l'archivio", id: 'Lemari arsip', note: 'netral' },
      { it: 'la cartella', id: 'Map', note: 'feminin' }
    ],
    sportsActivities: [
      { it: 'il calcio', id: 'Sepak bola', note: 'maskulin' },
      { it: 'la pallacanestro', id: 'Basket', note: 'feminin' },
      { it: 'il tennis', id: 'Tenis', note: 'maskulin' },
      { it: 'la pallavolo', id: 'Voli', note: 'feminin' },
      { it: "l'atletica", id: 'Atletik', note: 'feminin' },
      { it: 'il nuoto', id: 'Renang', note: 'maskulin' },
      { it: 'il rugby', id: 'Ragbi', note: 'maskulin' },
      { it: 'la pallamano', id: 'Bola tangan', note: 'feminin' },
      { it: 'la scherma', id: 'Anggar', note: 'feminin' },
      { it: "l'equitazione", id: 'Berkuda', note: 'feminin' },
      { it: 'il golf', id: 'Golf', note: 'maskulin' },
      { it: 'lo sci', id: 'Ski', note: 'maskulin' },
      { it: 'il snowboard', id: 'Snowboard', note: 'maskulin' },
      { it: 'il surf', id: 'Selancar', note: 'maskulin' },
      { it: 'il judo', id: 'Judo', note: 'maskulin' },
      { it: 'il karate', id: 'Karate', note: 'maskulin' },
      { it: 'la boxe', id: 'Tinju', note: 'feminin' },
      { it: 'la lotta', id: 'Gulat', note: 'feminin' },
      { it: 'la ginnastica', id: 'Senam', note: 'feminin' },
      { it: 'lo yoga', id: 'Yoga', note: 'maskulin' },
      { it: 'il ciclismo', id: 'Bersepeda', note: 'maskulin' },
      { it: 'il sollevamento pesi', id: 'Angkat besi', note: 'maskulin' },
      { it: 'la corsa', id: 'Lari', note: 'feminin' },
      { it: "l'escursionismo", id: 'Jalan kaki', note: 'maskulin' },
      { it: "l'arrampicata", id: 'Panjat tebing', note: 'feminin' },
      { it: 'le immersioni', id: 'Selam' },
      { it: 'la vela', id: 'Layar', note: 'feminin' },
      { it: 'il canottaggio', id: 'Mendayung', note: 'maskulin' },
      { it: 'il kayak', id: 'Kajak', note: 'maskulin' },
      { it: "il tiro con l'arco", id: 'Panahan', note: 'maskulin' },
      { it: 'il tiro a segno', id: 'Menembak', note: 'maskulin' },
      { it: 'il pattinaggio sul ghiaccio', id: 'Seluncur es', note: 'maskulin' },
      { it: "l'hockey su ghiaccio", id: 'Hoki es', note: 'maskulin' },
      { it: 'il baseball', id: 'Baseball', note: 'maskulin' },
      { it: 'il cricket', id: 'Kriket', note: 'maskulin' },
      { it: 'il badminton', id: 'Bulutangkis', note: 'maskulin' },
      { it: 'il tennis tavolo', id: 'Pingpong', note: 'maskulin' },
      { it: 'il bowling', id: 'Boling', note: 'maskulin' },
      { it: 'la danza', id: 'Tari', note: 'feminin' },
      { it: 'lo skateboard', id: 'Skateboard', note: 'maskulin' },
      { it: 'il pattinaggio in linea', id: 'Inline skate', note: 'maskulin' }
    ],
    hobbiesLeisure: [
      { it: 'la lettura', id: 'Membaca', note: 'feminin' },
      { it: 'la scrittura', id: 'Menulis', note: 'feminin' },
      { it: 'la pittura', id: 'Melukis', note: 'feminin' },
      { it: 'il disegno', id: 'Menggambar', note: 'maskulin' },
      { it: 'il cinema', id: 'Nonton film', note: 'maskulin' },
      { it: 'la musica', id: 'Dengar musik', note: 'feminin' },
      { it: 'i videogiochi', id: 'Main game' },
      { it: 'la fotografia', id: 'Fotografi', note: 'feminin' },
      { it: 'il giardinaggio', id: 'Berkebun', note: 'maskulin' },
      { it: 'il cucito', id: 'Menjahit', note: 'maskulin' },
      { it: 'il lavoro a maglia', id: 'Merajut', note: 'maskulin' },
      { it: 'il ricamo', id: 'Menyulam', note: 'maskulin' },
      { it: 'il fai da te', id: 'DIY/perbaikan', note: 'maskulin' },
      { it: 'il collezionismo', id: 'Koleksi', note: 'maskulin' },
      { it: 'il modellismo', id: 'Model kit', note: 'maskulin' },
      { it: 'la filatelia', id: 'Filateli', note: 'feminin' },
      { it: "l'acquariofilia", id: 'Hobi ikan', note: 'feminin' },
      { it: 'la petanque', id: 'Petanque', note: 'feminin' },
      { it: 'gli scacchi', id: 'Catur' },
      { it: 'le carte', id: 'Main kartu' },
      { it: 'la meditazione', id: 'Meditasi', note: 'feminin' },
      { it: 'la natura', id: 'Alam terbuka', note: "feminin'" },
      { it: "l'escursione", id: 'Hiking', note: 'feminin' },
      { it: 'il picnic', id: 'Piknik', note: 'maskulin' },
      { it: 'il campeggio', id: 'Berkemah', note: 'maskulin' },
      { it: 'la pesca', id: 'Memancing', note: 'feminin' },
      { it: 'la caccia', id: 'Berburu', note: 'feminin' },
      { it: 'la danza', id: 'Menari', note: 'feminin' },
      { it: 'la ceramica', id: 'Keramik', note: 'feminin' }
    ],
    healthMedical: [
      { it: 'la salute', id: 'Kesehatan', note: 'feminin' },
      { it: 'la malattia', id: 'Penyakit', note: 'feminin' },
      { it: 'il raffreddore', id: 'Pilek', note: 'maskulin' },
      { it: "l'influenza", id: 'Flu', note: 'feminin' },
      { it: 'la febbre', id: 'Demam', note: 'feminin' },
      { it: 'la tosse', id: 'Batuk', note: 'feminin' },
      { it: 'il mal di testa', id: 'Sakit kepala', note: 'maskulin' },
      { it: 'il mal di schiena', id: 'Sakit punggung', note: 'maskulin' },
      { it: 'il mal di stomaco', id: 'Sakit perut', note: 'maskulin' },
      { it: 'la nausea', id: 'Mual', note: 'feminin' },
      { it: 'il vomito', id: 'Muntah', note: 'maskulin' },
      { it: 'la diarrea', id: 'Diare', note: 'feminin' },
      { it: 'la stitichezza', id: 'Sembelit', note: 'feminin' },
      { it: "l'allergia", id: 'Alergi', note: 'feminin' },
      { it: "l'asma", id: 'Asma', note: 'feminin' },
      { it: 'il diabete', id: 'Diabetes', note: 'maskulin' },
      { it: "l'ipertensione", id: 'Hipertensi', note: 'feminin' },
      { it: "l'infezione", id: 'Infeksi', note: 'feminin' },
      { it: 'la ferita', id: 'Luka', note: 'feminin' },
      { it: 'la cicatrice', id: 'Bekas luka', note: 'feminin' },
      { it: "l'escoriazione", id: 'Luka lecet', note: 'feminin' },
      { it: 'il taglio', id: 'Goresan', note: 'maskulin' },
      { it: 'il livido', id: 'Memar', note: 'maskulin' },
      { it: 'il gonfiore', id: 'Bengkak', note: 'maskulin' },
      { it: 'la vertigine', id: 'Pusing', note: 'feminin' },
      { it: "l'insonnia", id: 'Insomnia', note: 'feminin' },
      { it: 'la stanchezza', id: 'Kelelahan', note: 'feminin' },
      { it: 'lo stress', id: 'Stres', note: 'maskulin' },
      { it: 'la depressione', id: 'Depresi', note: 'feminin' },
      { it: "l'ansia", id: 'Kecemasan', note: 'feminin' },
      { it: 'il trattamento', id: 'Perawatan', note: 'maskulin' },
      { it: 'la ricetta', id: 'Resep', note: 'feminin' },
      { it: "l'antibiotico", id: 'Antibiotik', note: 'netral' },
      { it: "l'aspirina", id: 'Aspirin', note: 'feminin' },
      { it: "l'unguento", id: 'Salep', note: 'netral' },
      { it: 'la benda', id: 'Perban', note: 'feminin' },
      { it: "l'iniezione", id: 'Suntikan', note: 'feminin' },
      { it: 'la visita', id: 'Pemeriksaan', note: 'feminin' },
      { it: 'la radiografia', id: 'Rontgen', note: 'feminin' },
      { it: "l'operazione", id: 'Operasi', note: 'feminin' },
      { it: "l'anestesia", id: 'Anestesi', note: 'feminin' },
      { it: 'la guarigione', id: 'Penyembuhan', note: 'feminin' },
      { it: 'il vaccino', id: 'Vaksin', note: 'maskulin' }
    ],
    professionsExtended: [
      { it: 'il medico', id: 'Dokter', note: 'maskulin' },
      { it: 'la dottoressa', id: 'Dokter (wanita)', note: 'feminin' },
      { it: "l'avvocato", id: 'Pengacara', note: 'maskulin' },
      { it: "l'avvocatessa", id: 'Pengacara (wanita)', note: 'feminin' },
      { it: "l'ingegnere", id: 'Insinyur', note: 'maskulin' },
      { it: "l'ingegnera", id: 'Insinyur (wanita)', note: 'feminin' },
      { it: "l'architetto", id: 'Arsitek', note: 'maskulin' },
      { it: "l'architetta", id: 'Arsitek (wanita)', note: 'feminin' },
      { it: "l'insegnante", id: 'Guru', note: 'maskulin' },
      { it: "l'insegnante", id: 'Guru (wanita)', note: 'feminin' },
      { it: 'il professore', id: 'Profesor', note: 'maskulin' },
      { it: 'la professoressa', id: 'Profesor (wanita)', note: 'feminin' },
      { it: 'il pilota', id: 'Pilot', note: 'maskulin' },
      { it: 'la pilota', id: 'Pilot (wanita)', note: 'feminin' },
      { it: 'il poliziotto', id: 'Polisi', note: 'maskulin' },
      { it: 'la poliziotta', id: 'Polisi (wanita)', note: 'feminin' },
      { it: 'il pompiere', id: 'Pemadam kebakaran', note: 'maskulin' },
      { it: 'la pompiere', id: 'Pemadam (wanita)', note: 'feminin' },
      { it: "l'infermiere", id: 'Perawat (pria)', note: 'maskulin' },
      { it: "l'infermiera", id: 'Perawat', note: 'feminin' },
      { it: 'il dentista', id: 'Dokter gigi', note: 'maskulin' },
      { it: 'la dentista', id: 'Dokter gigi (wanita)', note: 'feminin' },
      { it: 'il farmacista', id: 'Apoteker', note: 'maskulin' },
      { it: 'la farmacista', id: 'Apoteker (wanita)', note: 'feminin' },
      { it: 'il giornalista', id: 'Jurnalis', note: 'maskulin' },
      { it: 'la giornalista', id: 'Jurnalis (wanita)', note: 'feminin' },
      { it: 'lo scrittore', id: 'Penulis', note: 'maskulin' },
      { it: 'la scrittrice', id: 'Penulis (wanita)', note: 'feminin' },
      { it: "l'artista", id: 'Seniman', note: 'maskulin' },
      { it: "l'artista", id: 'Seniwati', note: 'feminin' },
      { it: 'il musicista', id: 'Musisi', note: 'maskulin' },
      { it: 'la musicista', id: 'Musisi (wanita)', note: 'feminin' },
      { it: "l'attore", id: 'Aktor', note: 'maskulin' },
      { it: "l'attrice", id: 'Aktris', note: 'feminin' },
      { it: 'il regista', id: 'Sutradara', note: 'maskulin' },
      { it: 'la regista', id: 'Sutradara (wanita)', note: 'feminin' },
      { it: 'il cuoco', id: 'Koki', note: 'maskulin' },
      { it: 'la cuoca', id: 'Koki (wanita)', note: 'feminin' },
      { it: 'il panettiere', id: 'Tukang roti', note: 'maskulin' },
      { it: 'la panettiera', id: 'Tukang roti (wanita)', note: 'feminin' },
      { it: 'il macellaio', id: 'Tukang daging', note: 'maskulin' },
      { it: 'la macellaia', id: 'Tukang daging (wanita)', note: 'feminin' },
      { it: 'il parrucchiere', id: 'Tukang cukur', note: 'maskulin' },
      { it: 'la parrucchiera', id: 'Tukang cukur (wanita)', note: 'feminin' },
      { it: 'il venditore', id: 'Penjual', note: 'maskulin' },
      { it: 'la venditrice', id: 'Penjual (wanita)', note: 'feminin' },
      { it: 'il cameriere', id: 'Pelayan', note: 'maskulin' },
      { it: 'la cameriera', id: 'Pelayan (wanita)', note: 'feminin' },
      { it: 'il direttore', id: 'Manajer', note: 'maskulin' },
      { it: 'la direttrice', id: 'Manajer (wanita)', note: 'feminin' },
      { it: 'il segretario', id: 'Sekretaris', note: 'maskulin' },
      { it: 'la segretaria', id: 'Sekretaris (wanita)', note: 'feminin' },
      { it: 'il programmatore', id: 'Programmer', note: 'maskulin' },
      { it: 'la programmatrice', id: 'Programmer (wanita)', note: 'feminin' }
    ],
    cityPlaces: [
      { it: 'la città', id: 'Kota', note: 'feminin' },
      { it: 'la capitale', id: 'Ibukota', note: 'feminin' },
      { it: 'il villaggio', id: 'Desa', note: 'maskulin' },
      { it: 'la periferia', id: 'Pinggiran kota', note: 'feminin' },
      { it: 'il quartiere', id: 'Distrik kota', note: 'maskulin' },
      { it: 'il municipio', id: 'Balai kota', note: 'maskulin' },
      { it: 'la chiesa', id: 'Gereja', note: 'feminin' },
      { it: 'il duomo', id: 'Katedral', note: 'maskulin' },
      { it: 'la cappella', id: 'Kapel', note: 'feminin' },
      { it: 'il museo', id: 'Museum', note: 'maskulin' },
      { it: 'la galleria', id: 'Galeri', note: 'feminin' },
      { it: 'il palazzo', id: 'Istana', note: 'maskulin' },
      { it: 'la fortezza', id: 'Benteng', note: 'feminin' },
      { it: 'il parco', id: 'Taman', note: 'maskulin' },
      { it: 'il giardino', id: 'Kebun', note: 'maskulin' },
      { it: 'il parco giochi', id: 'Taman bermain', note: 'maskulin' },
      { it: 'la scuola', id: 'Sekolah', note: 'feminin' },
      { it: "l'ospedale", id: 'Rumah sakit', note: 'netral' },
      { it: 'la farmacia', id: 'Apotek', note: 'feminin' },
      { it: "l'ufficio postale", id: 'Kantor pos', note: 'netral' },
      { it: 'la banca', id: 'Bank', note: 'feminin' },
      { it: "l'hotel", id: 'Hotel', note: 'maskulin' },
      { it: 'il ristorante', id: 'Restoran', note: 'maskulin' },
      { it: 'il bar', id: 'Bar', note: 'maskulin' },
      { it: 'il caffè', id: 'Kafe', note: 'maskulin' },
      { it: 'la panetteria', id: 'Toko roti', note: 'feminin' },
      { it: 'la pasticceria', id: 'Toko kue', note: 'feminin' },
      { it: 'la macelleria', id: 'Toko daging', note: 'feminin' },
      { it: 'il supermercato', id: 'Supermarket', note: 'maskulin' },
      { it: 'il mercato', id: 'Pasar', note: 'maskulin' },
      { it: 'il grande magazzino', id: 'Toko serba ada', note: 'maskulin' },
      { it: 'la biblioteca', id: 'Perpustakaan', note: 'feminin' },
      { it: 'il teatro', id: 'Teater', note: 'maskulin' },
      { it: "l'opera", id: 'Opera', note: 'feminin' },
      { it: 'il cinema', id: 'Bioskop', note: 'maskulin' },
      { it: 'la stazione', id: 'Stasiun kereta', note: 'feminin' },
      { it: 'la fermata', id: 'Halte bus', note: 'feminin' },
      { it: "l'aeroporto", id: 'Bandara', note: 'netral' },
      { it: 'il ponte', id: 'Jembatan', note: 'maskulin' },
      { it: 'la torre', id: 'Menara', note: 'feminin' },
      { it: 'il monumento', id: 'Monumen', note: 'maskulin' },
      { it: 'la fontana', id: 'Air mancur', note: 'feminin' },
      { it: 'il pozzo', id: 'Sumur', note: 'maskulin' },
      { it: 'la scala', id: 'Tangga', note: 'feminin' },
      { it: "l'ascensore", id: 'Lift', note: 'netral' },
      { it: 'la strada', id: 'Jalan', note: 'feminin' },
      { it: 'la via', id: 'Jalur', note: 'feminin' },
      { it: 'il cartello', id: 'Rambu', note: 'maskulin' },
      { it: 'la pubblicità', id: 'Reklame', note: 'feminin' },
      { it: 'la fabbrica', id: 'Pabrik', note: 'feminin' }
    ],
    weatherClimate: [
      { it: 'il tempo', id: 'Cuaca', note: 'maskulin' },
      { it: 'il clima', id: 'Iklim', note: 'maskulin' },
      { it: 'il sole', id: 'Matahari', note: 'maskulin' },
      { it: 'la pioggia', id: 'Hujan', note: 'feminin' },
      { it: 'la neve', id: 'Salju', note: 'feminin' },
      { it: 'il vento', id: 'Angin', note: 'maskulin' },
      { it: 'la nuvola', id: 'Awan', note: 'feminin' },
      { it: 'la nebbia', id: 'Kabut', note: 'feminin' },
      { it: 'il temporale', id: 'Badai petir', note: 'maskulin' },
      { it: 'il fulmine', id: 'Petir', note: 'maskulin' },
      { it: 'il tuono', id: 'Guntur', note: 'maskulin' },
      { it: "l'arcobaleno", id: 'Pelangi', note: 'netral' },
      { it: 'la brina', id: 'Embun beku', note: 'feminin' },
      { it: 'il ghiaccio', id: 'Es', note: 'maskulin' },
      { it: 'il caldo', id: 'Panas', note: 'maskulin' },
      { it: 'il freddo', id: 'Dingin', note: 'maskulin' },
      { it: 'la siccità', id: 'Kekeringan', note: 'feminin' },
      { it: "l'umidità", id: 'Kelembapan', note: 'feminin' },
      { it: 'la tempesta', id: 'Badai', note: 'feminin' },
      { it: "l'alluvione", id: 'Banjir', note: 'feminin' },
      { it: 'la luce del sole', id: 'Sinar matahari', note: 'feminin' },
      { it: 'la temperatura', id: 'Suhu', note: 'feminin' },
      { it: 'il grado', id: 'Derajat', note: 'maskulin' },
      { it: "l'estate", id: 'Musim panas', note: 'feminin' },
      { it: "l'inverno", id: 'Musim dingin', note: 'netral' },
      { it: 'la primavera', id: 'Musim semi', note: 'feminin' },
      { it: "l'autunno", id: 'Musim gugur', note: 'netral' }
    ],
    timeExtended: [
      { it: 'il tempo', id: 'Waktu', note: 'maskulin' },
      { it: 'il secondo', id: 'Detik', note: 'maskulin' },
      { it: 'il minuto', id: 'Menit', note: 'maskulin' },
      { it: "l'ora", id: 'Jam', note: 'feminin' },
      { it: 'la mattina', id: 'Pagi', note: 'feminin' },
      { it: 'il pomeriggio', id: 'Siang', note: 'maskulin' },
      { it: 'la sera', id: 'Sore', note: 'feminin' },
      { it: 'la notte', id: 'Malam', note: 'feminin' },
      { it: 'il giorno', id: 'Hari', note: 'maskulin' },
      { it: 'la settimana', id: 'Minggu', note: 'feminin' },
      { it: 'il mese', id: 'Bulan', note: 'maskulin' },
      { it: "l'anno", id: 'Tahun', note: 'netral' },
      { it: 'il decennio', id: 'Dekade', note: 'maskulin' },
      { it: 'il secolo', id: 'Abad', note: 'maskulin' },
      { it: 'il millennio', id: 'Milenium', note: 'maskulin' },
      { it: 'il passato', id: 'Masa lalu', note: 'maskulin' },
      { it: 'il presente', id: 'Masa kini', note: 'maskulin' },
      { it: 'il futuro', id: 'Masa depan', note: 'maskulin' },
      { it: "l'alba", id: 'Subuh', note: 'feminin' },
      { it: 'la fretta', id: 'Terburu-buru', note: 'feminin' },
      { it: 'la pazienza', id: 'Kesabaran', note: 'feminin' },
      { it: 'il silenzio', id: 'Keheningan', note: 'maskulin' },
      { it: 'la quiete', id: 'Ketenangan', note: 'feminin' },
      { it: "l'età", id: 'Usia', note: 'feminin' },
      { it: 'la gioventù', id: 'Masa muda', note: 'feminin' },
      { it: "l'infanzia", id: 'Masa kecil', note: 'feminin' },
      { it: "l'inizio", id: 'Awal', note: 'netral' },
      { it: 'la fine', id: 'Akhir', note: 'feminin' },
      { it: 'la pausa', id: 'Jeda', note: 'feminin' },
      { it: 'la festa', id: 'Pesta', note: 'feminin' },
      { it: 'le vacanze', id: 'Liburan' },
      { it: 'i giorni feriali', id: 'Hari biasa' }
    ],
    directionsPositions: [
      { it: 'a sinistra', id: 'Kiri' },
      { it: 'a destra', id: 'Kanan' },
      { it: 'dritto', id: 'Lurus' },
      { it: 'su', id: 'Atas' },
      { it: 'giù', id: 'Bawah' },
      { it: 'avanti', id: 'Depan' },
      { it: 'indietro', id: 'Belakang' },
      { it: 'accanto', id: 'Di sebelah' },
      { it: 'di fronte', id: 'Seberang' },
      { it: 'tra', id: 'Di antara' },
      { it: 'vicino', id: 'Dekat' },
      { it: 'lontano', id: 'Jauh' },
      { it: 'dentro', id: 'Di dalam' },
      { it: 'fuori', id: 'Di luar' },
      { it: 'sopra', id: 'Di atas' },
      { it: 'sotto', id: 'Di bawah' },
      { it: 'davanti', id: 'Di depan' },
      { it: 'dietro', id: 'Di belakang' },
      { it: 'verso', id: 'Ke arah' },
      { it: 'da', id: 'Dari' },
      { it: 'a', id: 'Ke' },
      { it: 'con', id: 'Bersama' },
      { it: 'senza', id: 'Tanpa' },
      { it: 'contro', id: 'Melawan' },
      { it: 'per', id: 'Untuk' },
      { it: 'intorno', id: 'Di sekitar' },
      { it: 'attraverso', id: 'Melalui' }
    ],
    quantitiesMeasurements: [
      { it: 'il metro', id: 'Meter', note: 'maskulin' },
      { it: 'il chilometro', id: 'Kilometer', note: 'maskulin' },
      { it: 'il centimetro', id: 'Sentimeter', note: 'maskulin' },
      { it: 'il chilogrammo', id: 'Kilogram', note: 'maskulin' },
      { it: 'il grammo', id: 'Gram', note: 'maskulin' },
      { it: 'la tonnellata', id: 'Ton', note: 'feminin' },
      { it: 'il litro', id: 'Liter', note: 'maskulin' },
      { it: 'la bottiglia', id: 'Botol', note: 'feminin' },
      { it: 'il bicchiere', id: 'Gelas', note: 'maskulin' },
      { it: 'la tazza', id: 'Cangkir', note: 'feminin' },
      { it: 'il cucchiaio', id: 'Sendok', note: 'maskulin' },
      { it: 'la forchetta', id: 'Garpu', note: 'feminin' },
      { it: 'il coltello', id: 'Pisau', note: 'maskulin' },
      { it: 'la ciotola', id: 'Mangkuk', note: 'feminin' },
      { it: 'il piatto', id: 'Piring', note: 'maskulin' },
      { it: 'il vassoio', id: 'Nampan', note: 'maskulin' },
      { it: 'la pentola', id: 'Panci', note: 'feminin' },
      { it: 'la padella', id: 'Wajan', note: 'feminin' },
      { it: 'il bollitore', id: 'Ketel', note: 'maskulin' },
      { it: 'il secchio', id: 'Ember', note: 'maskulin' },
      { it: 'la pala', id: 'Cangkul', note: 'feminin' },
      { it: 'la scopa', id: 'Sapu', note: 'feminin' },
      { it: 'il manico', id: 'Tangkai', note: 'maskulin' },
      { it: 'il cestino', id: 'Keranjang', note: 'maskulin' },
      { it: 'la scatola', id: 'Kotak', note: 'feminin' },
      { it: 'il cartone', id: 'Kardus', note: 'maskulin' },
      { it: 'la lattina', id: 'Kaleng', note: 'feminin' },
      { it: 'il coperchio', id: 'Tutup', note: 'maskulin' },
      { it: 'la borsa', id: 'Tas belanja', note: 'feminin' },
      { it: 'la confezione', id: 'Kemasan', note: 'feminin' },
      { it: 'il prezzo', id: 'Harga', note: 'maskulin' },
      { it: 'il conto', id: 'Tagihan', note: 'maskulin' },
      { it: 'lo sconto', id: 'Diskon', note: 'maskulin' },
      { it: "l'IVA", id: 'PPN', note: 'feminin' },
      { it: 'la mancia', id: 'Tip', note: 'feminin' },
      { it: 'il prezzo totale', id: 'Total harga', note: 'maskulin' },
      { it: 'il prezzo unitario', id: 'Harga satuan', note: 'maskulin' }
    ],
    adjectivesDescriptions: [
      { it: 'grande', id: 'Besar' },
      { it: 'piccolo', id: 'Kecil' },
      { it: 'lungo', id: 'Panjang' },
      { it: 'corto', id: 'Pendek' },
      { it: 'largo', id: 'Lebar' },
      { it: 'stretto', id: 'Sempit' },
      { it: 'spesso', id: 'Tebal' },
      { it: 'sottile', id: 'Tipis' },
      { it: 'pesante', id: 'Berat' },
      { it: 'leggero', id: 'Ringan' },
      { it: 'forte', id: 'Kuat' },
      { it: 'debole', id: 'Lemah' },
      { it: 'veloce', id: 'Cepat' },
      { it: 'lento', id: 'Lambat' },
      { it: 'vecchio', id: 'Tua/Lama' },
      { it: 'giovane', id: 'Muda' },
      { it: 'nuovo', id: 'Baru' },
      { it: 'buono', id: 'Baik' },
      { it: 'cattivo', id: 'Buruk' },
      { it: 'bello', id: 'Cantik/Indah' },
      { it: 'brutto', id: 'Jelek' },
      { it: 'pulito', id: 'Bersih' },
      { it: 'sporco', id: 'Kotor' },
      { it: 'secco', id: 'Kering' },
      { it: 'bagnato', id: 'Basah' },
      { it: 'freddo', id: 'Dingin' },
      { it: 'caldo', id: 'Panas' },
      { it: 'fresco', id: 'Segar' },
      { it: 'stanco', id: 'Lelah' },
      { it: 'affamato', id: 'Lapar' },
      { it: 'assetato', id: 'Haus' },
      { it: 'malato', id: 'Sakit' },
      { it: 'sano', id: 'Sehat' },
      { it: 'felice', id: 'Bahagia' },
      { it: 'triste', id: 'Sedih' },
      { it: 'divertente', id: 'Lucu' },
      { it: 'serio', id: 'Serius' },
      { it: 'amichevole', id: 'Ramah' },
      { it: 'cattivo', id: 'Jahat' },
      { it: 'piacevole', id: 'Menyenangkan' },
      { it: 'comodo', id: 'Nyaman' },
      { it: 'semplice', id: 'Sederhana' },
      { it: 'difficile', id: 'Sulit' },
      { it: 'pronto', id: 'Siap' },
      { it: 'giusto', id: 'Benar' },
      { it: 'sbagliato', id: 'Salah' },
      { it: 'importante', id: 'Penting' },
      { it: 'interessante', id: 'Menarik' },
      { it: 'noioso', id: 'Membosankan' },
      { it: 'famoso', id: 'Terkenal' },
      { it: 'speciale', id: 'Istimewa' },
      { it: 'normale', id: 'Normal' },
      { it: 'tipico', id: 'Tipikal' },
      { it: 'moderno', id: 'Modern' },
      { it: 'antico', id: 'Kuno' },
      { it: 'classico', id: 'Klasik' },
      { it: 'internazionale', id: 'Internasional' },
      { it: 'nazionale', id: 'Nasional' },
      { it: 'locale', id: 'Lokal' },
      { it: 'globale', id: 'Global' },
      { it: 'personale', id: 'Pribadi' },
      { it: 'privato', id: 'Privat' },
      { it: 'pubblico', id: 'Publik' },
      { it: 'caro', id: 'Mahal' },
      { it: 'economico', id: 'Murah' },
      { it: 'ricco', id: 'Kaya' },
      { it: 'povero', id: 'Miskin' }
    ],
    verbsExtended: [
      { it: 'dormire', id: 'Tidur' },
      { it: 'svegliarsi', id: 'Bangun' },
      { it: 'fare colazione', id: 'Makan pagi' },
      { it: 'fare la doccia', id: 'Mandi' },
      { it: 'vestirsi', id: 'Berpakaian' },
      { it: 'spogliarsi', id: 'Membuka pakaian' },
      { it: 'cucinare', id: 'Memasak' },
      { it: 'cuocere al forno', id: 'Memanggang' },
      { it: 'friggere', id: 'Menggoreng' },
      { it: 'lavare', id: 'Mencuci' },
      { it: 'pulire', id: 'Membersihkan' },
      { it: 'aspirare', id: 'Menyedot debu' },
      { it: 'stirare', id: 'Menggosok' },
      { it: 'spazzare', id: 'Menyapu' },
      { it: 'lavare il pavimento', id: 'Mengepel' },
      { it: 'fare la spesa', id: 'Berbelanja' },
      { it: 'pagare', id: 'Membayar' },
      { it: 'risparmiare', id: 'Menabung' },
      { it: 'spendere', id: 'Menghabiskan' },
      { it: 'guadagnare', id: 'Menghasilkan' },
      { it: 'lavorare', id: 'Bekerja' },
      { it: 'studiare', id: 'Belajar' },
      { it: 'leggere', id: 'Membaca' },
      { it: 'scrivere', id: 'Menulis' },
      { it: 'parlare', id: 'Berbicara' },
      { it: 'ascoltare', id: 'Mendengarkan' },
      { it: 'rispondere', id: 'Menjawab' },
      { it: 'chiedere', id: 'Bertanya' },
      { it: 'raccontare', id: 'Menceritakan' },
      { it: 'spiegare', id: 'Menjelaskan' },
      { it: 'mostrare', id: 'Menunjukkan' },
      { it: 'cercare', id: 'Mencari' },
      { it: 'trovare', id: 'Menemukan' },
      { it: 'perdere', id: 'Kehilangan' },
      { it: 'vincere', id: 'Menang' },
      { it: 'comprare', id: 'Membeli' },
      { it: 'vendere', id: 'Menjual' },
      { it: 'scambiare', id: 'Menukar' },
      { it: 'consegnare', id: 'Mengirim' },
      { it: 'arrivare', id: 'Tiba' },
      { it: 'partire', id: 'Berangkat' },
      { it: 'tornare', id: 'Kembali' },
      { it: 'viaggiare', id: 'Bepergian' },
      { it: 'volare', id: 'Terbang' },
      { it: 'guidare', id: 'Mengendarai' },
      { it: 'correre', id: 'Berlari' },
      { it: 'camminare', id: 'Berjalan' },
      { it: 'venire', id: 'Datang' },
      { it: 'portare', id: 'Membawa' },
      { it: 'prendere', id: 'Mengambil' },
      { it: 'dare', id: 'Memberi' },
      { it: 'tenere', id: 'Memegang' },
      { it: 'posare', id: 'Meletakkan' },
      { it: 'mettere', id: 'Menempatkan' },
      { it: 'gettare', id: 'Melempar' },
      { it: 'prendere', id: 'Menangkap' },
      { it: 'aprire', id: 'Membuka' },
      { it: 'chiudere', id: 'Menutup' },
      { it: 'iniziare', id: 'Memulai' },
      { it: 'finire', id: 'Mengakhiri' },
      { it: 'bere', id: 'Minum' },
      { it: 'mangiare', id: 'Makan' },
      { it: 'sentire', id: 'Merasa' },
      { it: 'pensare', id: 'Berpikir' },
      { it: 'credere', id: 'Percaya' },
      { it: 'sapere', id: 'Tahu' },
      { it: 'conoscere', id: 'Mengenal' },
      { it: 'capire', id: 'Mengerti' },
      { it: 'dimenticare', id: 'Lupa' },
      { it: 'ricordare', id: 'Ingat' },
      { it: 'sognare', id: 'Bermimpi' },
      { it: 'sperare', id: 'Berharap' },
      { it: 'desiderare', id: 'Menginginkan' },
      { it: 'amare', id: 'Mencintai' },
      { it: 'odiare', id: 'Membenci' },
      { it: 'rispettare', id: 'Menghormati' },
      { it: 'aiutare', id: 'Membantu' },
      { it: 'sostenere', id: 'Mendukung' },
      { it: 'aver bisogno', id: 'Membutuhkan' },
      { it: 'usare', id: 'Menggunakan' },
      { it: 'vietare', id: 'Melarang' },
      { it: 'permettere', id: 'Memperbolehkan' },
      { it: 'decidere', id: 'Memutuskan' },
      { it: 'scegliere', id: 'Memilih' },
      { it: 'cambiare', id: 'Mengubah' },
      { it: 'sviluppare', id: 'Mengembangkan' },
      { it: 'migliorare', id: 'Memperbaiki' },
      { it: 'peggiorare', id: 'Memperburuk' },
      { it: 'confrontare', id: 'Membandingkan' },
      { it: 'distinguere', id: 'Membedakan' },
      { it: 'misurare', id: 'Mengukur' },
      { it: 'contare', id: 'Menghitung' },
      { it: 'verificare', id: 'Memeriksa' },
      { it: 'controllare', id: 'Mengontrol' },
      { it: 'testare', id: 'Menguji' },
      { it: 'mescolare', id: 'Mencampur' },
      { it: 'separare', id: 'Memisahkan' },
      { it: 'collegare', id: 'Menyambungkan' },
      { it: 'distruggere', id: 'Menghancurkan' },
      { it: 'riparare', id: 'Memperbaiki' },
      { it: 'costruire', id: 'Membangun' },
      { it: 'dipingere', id: 'Menggambar' },
      { it: 'fotografare', id: 'Memotret' },
      { it: 'registrare', id: 'Merekam' },
      { it: 'tagliare', id: 'Memotong' },
      { it: 'suonare', id: 'Berbunyi' },
      { it: 'sussurrare', id: 'Berbisik' },
      { it: 'gridare', id: 'Berteriak' },
      { it: 'piangere', id: 'Menangis' },
      { it: 'ridere', id: 'Tertawa' },
      { it: 'sorridere', id: 'Senyum' },
      { it: 'starnutire', id: 'Bersin' },
      { it: 'tossire', id: 'Batuk' },
      { it: 'deglutire', id: 'Menelan' },
      { it: 'masticare', id: 'Mengunyah' },
      { it: 'russare', id: 'Mendengkur' },
      { it: 'respirare', id: 'Bernapas' }
    ],
    abstractConcepts: [
      { it: 'la vita', id: 'Kehidupan', note: 'feminin' },
      { it: 'la morte', id: 'Kematian', note: 'feminin' },
      { it: "l'amore", id: 'Cinta', note: 'netral' },
      { it: "l'odio", id: 'Kebencian', note: 'netral' },
      { it: "l'amicizia", id: 'Persahabatan', note: 'feminin' },
      { it: 'la famiglia', id: 'Keluarga', note: 'feminin' },
      { it: 'la società', id: 'Masyarakat', note: 'feminin' },
      { it: 'la politica', id: 'Politik', note: 'feminin' },
      { it: "l'economia", id: 'Ekonomi', note: 'feminin' },
      { it: 'la cultura', id: 'Budaya', note: 'feminin' },
      { it: "l'arte", id: 'Seni', note: 'feminin' },
      { it: 'la musica', id: 'Musik', note: 'feminin' },
      { it: 'la religione', id: 'Agama', note: 'feminin' },
      { it: 'la fede', id: 'Keyakinan', note: 'feminin' },
      { it: 'la speranza', id: 'Harapan', note: 'feminin' },
      { it: 'il sogno', id: 'Mimpi', note: 'maskulin' },
      { it: 'la paura', id: 'Ketakutan', note: 'feminin' },
      { it: 'la libertà', id: 'Kebebasan', note: 'feminin' },
      { it: 'la giustizia', id: 'Keadilan', note: 'feminin' },
      { it: 'la verità', id: 'Kebenaran', note: 'feminin' },
      { it: 'la bugia', id: 'Kebohongan', note: 'feminin' },
      { it: 'la felicità', id: 'Kebahagiaan', note: 'feminin' },
      { it: 'la sofferenza', id: 'Penderitaan', note: 'feminin' },
      { it: 'il successo', id: 'Keberhasilan', note: 'maskulin' },
      { it: 'il fallimento', id: 'Kegagalan', note: 'maskulin' },
      { it: 'la delusione', id: 'Kekecewaan', note: 'feminin' },
      { it: 'la sorpresa', id: 'Keterkejutan', note: 'feminin' },
      { it: "l'entusiasmo", id: 'Antusiasme', note: 'netral' },
      { it: 'la noia', id: 'Kebosanan', note: 'feminin' },
      { it: 'la curiosità', id: 'Keingintahuan', note: 'feminin' },
      { it: 'il dubbio', id: 'Keraguan', note: 'maskulin' },
      { it: 'la sicurezza', id: 'Keamanan', note: 'feminin' },
      { it: 'il pericolo', id: 'Bahaya', note: 'maskulin' },
      { it: 'il rischio', id: 'Risiko', note: 'maskulin' },
      { it: 'la sfida', id: 'Tantangan', note: 'feminin' },
      { it: "l'opportunità", id: 'Kesempatan', note: 'feminin' },
      { it: 'la possibilità', id: 'Kemungkinan', note: 'feminin' },
      { it: 'la necessità', id: 'Kebutuhan', note: 'feminin' },
      { it: 'il dovere', id: 'Kewajiban', note: 'maskulin' },
      { it: 'la responsabilità', id: 'Tanggung jawab', note: 'feminin' },
      { it: 'la decisione', id: 'Keputusan', note: 'feminin' },
      { it: "l'opinione", id: 'Pendapat', note: 'feminin' },
      { it: "l'idea", id: 'Ide', note: 'feminin' },
      { it: 'il piano', id: 'Rencana', note: 'maskulin' },
      { it: "l'obiettivo", id: 'Tujuan', note: 'netral' },
      { it: 'il significato', id: 'Arti', note: 'maskulin' },
      { it: 'il ricordo', id: 'Kenangan', note: 'maskulin' },
      { it: "l'esperienza", id: 'Pengalaman', note: 'feminin' },
      { it: 'la tradizione', id: 'Tradisi', note: 'feminin' },
      { it: 'la storia', id: 'Sejarah', note: 'feminin' },
      { it: 'la natura', id: 'Alam', note: 'feminin' },
      { it: "l'ambiente", id: 'Lingkungan', note: 'netral' },
      { it: 'la terra', id: 'Bumi', note: 'feminin' },
      { it: 'il cielo', id: 'Langit', note: 'maskulin' },
      { it: 'il sole', id: 'Matahari', note: 'maskulin' },
      { it: 'la luna', id: 'Bulan', note: 'feminin' },
      { it: 'la stella', id: 'Bintang', note: 'feminin' },
      { it: 'il mare', id: 'Laut', note: 'maskulin' },
      { it: 'il fiume', id: 'Sungai', note: 'maskulin' },
      { it: 'il lago', id: 'Danau', note: 'maskulin' },
      { it: 'la montagna', id: 'Gunung', note: 'feminin' },
      { it: 'la valle', id: 'Lembah', note: 'feminin' },
      { it: "l'isola", id: 'Pulau', note: 'feminin' },
      { it: 'la foresta', id: 'Hutan', note: 'feminin' },
      { it: 'il deserto', id: 'Gurun', note: 'maskulin' },
      { it: 'la lingua', id: 'Bahasa', note: 'feminin' },
      { it: 'la parola', id: 'Kata', note: 'feminin' },
      { it: 'la frase', id: 'Kalimat', note: 'feminin' },
      { it: 'la grammatica', id: 'Tata bahasa', note: 'feminin' },
      { it: 'la traduzione', id: 'Terjemahan', note: 'feminin' },
      { it: 'la pronuncia', id: 'Pengucapan', note: 'feminin' },
      { it: "l'accento", id: 'Aksen', note: 'netral' },
      { it: 'la scrittura', id: 'Tulisan', note: 'feminin' },
      { it: "l'alfabeto", id: 'Alfabet', note: 'netral' }
    ]
  },
  quizzes: {
      colors: {
        title: 'Warna', icon: '🎨',
        vocab: [
          { it: 'rosso', id: 'Merah' }, { it: 'blu', id: 'Biru' }, { it: 'verde', id: 'Hijau' },
          { it: 'giallo', id: 'Kuning' }, { it: 'viola', id: 'Ungu' }, { it: 'rosa', id: 'Merah muda' },
          { it: 'nero', id: 'Hitam' }, { it: 'bianco', id: 'Putih' }, { it: 'grigio', id: 'Abu-abu' },
          { it: 'marrone', id: 'Cokelat' }, { it: 'dorato', id: 'Emas' }, { it: 'argenteo', id: 'Perak' }
        ]
      },
      numbers: {
        title: 'Angka', icon: '🔢',
        vocab: [
          { it: 'zero', id: 'Nol' }, { it: 'uno', id: 'Satu' }, { it: 'due', id: 'Dua' },
          { it: 'tre', id: 'Tiga' }, { it: 'quattro', id: 'Empat' }, { it: 'cinque', id: 'Lima' },
          { it: 'sei', id: 'Enam' }, { it: 'sette', id: 'Tujuh' }, { it: 'otto', id: 'Delapan' },
          { it: 'nove', id: 'Sembilan' }, { it: 'dieci', id: 'Sepuluh' }, { it: 'venti', id: 'Dua puluh' },
          { it: 'cento', id: 'Seratus' }, { it: 'mille', id: 'Seribu' }
        ]
      },
      greetings: {
        title: 'Salam', icon: '👋',
        vocab: [
          { it: 'Ciao', id: 'Halo' }, { it: 'Buongiorno', id: 'Selamat pagi' },
          { it: 'Buonasera', id: 'Selamat sore' }, { it: 'Buonanotte', id: 'Selamat malam' },
          { it: 'Arrivederci', id: 'Sampai jumpa' }, { it: 'Grazie', id: 'Terima kasih' },
          { it: 'Prego', id: 'Sama-sama' }, { it: 'Mi scusi', id: 'Maaf' },
          { it: 'Sì', id: 'Ya' }, { it: 'No', id: 'Tidak' }
        ]
      },
      family: {
        title: 'Keluarga', icon: '👨‍👩‍👧‍👦',
        vocab: [
          { it: 'la madre', id: 'Ibu' }, { it: 'il padre', id: 'Ayah' },
          { it: 'la nonna', id: 'Nenek' }, { it: 'il nonno', id: 'Kakek' },
          { it: 'la sorella', id: 'Saudara perempuan' }, { it: 'il fratello', id: 'Saudara laki-laki' },
          { it: 'la figlia', id: 'Anak perempuan' }, { it: 'il figlio', id: 'Anak laki-laki' },
          { it: 'la famiglia', id: 'Keluarga' }, { it: 'la moglie', id: 'Istri' },
          { it: 'il marito', id: 'Suami' }, { it: 'il bambino', id: 'Anak' }
        ]
      },
      food: {
        title: 'Makanan & Minuman', icon: '🍽️',
        vocab: [
          { it: 'il pane', id: 'Roti' }, { it: 'il burro', id: 'Mentega' },
          { it: 'il formaggio', id: 'Keju' }, { it: 'la salsiccia', id: 'Sosis' },
          { it: "l'uovo", id: 'Telur' }, { it: 'il riso', id: 'Nasi' },
          { it: 'la patata', id: 'Kentang' }, { it: 'la zuppa', id: 'Sup' },
          { it: 'la carne', id: 'Daging' }, { it: 'il pesce', id: 'Ikan' },
          { it: 'il latte', id: 'Susu' }, { it: 'il caffè', id: 'Kopi' },
          { it: 'il tè', id: 'Teh' }, { it: "l'acqua", id: 'Air' },
          { it: 'la pasta', id: 'Pasta' }, { it: 'la pizza', id: 'Pizza' }
        ]
      },
      places: {
        title: 'Tempat', icon: '📍',
        vocab: [
          { it: 'la scuola', id: 'Sekolah' }, { it: "l'università", id: 'Universitas' },
          { it: "l'ospedale", id: 'Rumah sakit' }, { it: 'la chiesa', id: 'Gereja' },
          { it: 'il museo', id: 'Museum' }, { it: "l'albergo", id: 'Hotel' },
          { it: 'il ristorante', id: 'Restoran' }, { it: 'la banca', id: 'Bank' },
          { it: 'il supermercato', id: 'Supermarket' }, { it: 'la biblioteca', id: 'Perpustakaan' },
          { it: 'il cinema', id: 'Bioskop' }, { it: 'il parco', id: 'Taman' },
          { it: 'la stazione', id: 'Stasiun kereta' }, { it: "l'aeroporto", id: 'Bandara' }
        ]
      },
      professions: {
        title: 'Profesi', icon: '💼',
        vocab: [
          { it: 'il medico', id: 'Dokter' }, { it: 'la dottoressa', id: 'Dokter (wanita)' },
          { it: "l'insegnante", id: 'Guru' }, { it: 'la professoressa', id: 'Guru (wanita)' },
          { it: "l'ingegnere", id: 'Insinyur' }, { it: "l'ingegnera", id: 'Insinyur (wanita)' },
          { it: "l'avvocato", id: 'Pengacara' }, { it: 'il poliziotto', id: 'Polisi' },
          { it: 'la poliziotta', id: 'Polisi (wanita)' }, { it: 'il cuoco', id: 'Koki' },
          { it: 'la cuoca', id: 'Koki (wanita)' }, { it: 'il pilota', id: 'Pilot' },
          { it: 'la pilota', id: 'Pilot (wanita)' }, { it: 'il giornalista', id: 'Jurnalis' },
          { it: "l'infermiera", id: 'Perawat' }, { it: "l'architetto", id: 'Arsitek' }
        ]
      },
      emotions: {
        title: 'Emosi', icon: '😊',
        vocab: [
          { it: 'felice', id: 'Bahagia' }, { it: 'triste', id: 'Sedih' },
          { it: 'arrabbiato', id: 'Marah' }, { it: 'sorpreso', id: 'Terkejut' },
          { it: 'deluso', id: 'Kecewa' }, { it: 'orgoglioso', id: 'Bangga' },
          { it: 'curioso', id: 'Penasaran' }, { it: 'soddisfatto', id: 'Puas' },
          { it: 'preoccupato', id: 'Khawatir' }, { it: 'nervoso', id: 'Gugup' },
          { it: 'confuso', id: 'Bingung' }, { it: 'coraggioso', id: 'Pemberani' },
          { it: 'pauroso', id: 'Penakut' }, { it: 'innamorato', id: 'Jatuh cinta' },
          { it: 'geloso', id: 'Cemburu' }, { it: 'colpevole', id: 'Bersalah' }
        ]
      },
      verbConjugations: {
        title: 'Konjugasi Verba', icon: '📝',
        vocab: [
          { it: 'io sono', id: 'Saya adalah' }, { it: 'tu sei', id: 'Kamu adalah' },
          { it: 'lui/lei è', id: 'Dia adalah' }, { it: 'noi siamo', id: 'Kami adalah' },
          { it: 'io ho', id: 'Saya memiliki' }, { it: 'tu hai', id: 'Kamu memiliki' },
          { it: 'lui/lei ha', id: 'Dia memiliki' }, { it: 'io vado', id: 'Saya pergi' },
          { it: 'tu vai', id: 'Kamu pergi' }, { it: 'io posso', id: 'Saya bisa' },
          { it: 'tu puoi', id: 'Kamu bisa' }, { it: 'io devo', id: 'Saya harus' },
          { it: 'io voglio', id: 'Saya mau' }, { it: 'io faccio', id: 'Saya membuat' },
          { it: 'io dico', id: 'Saya berkata' }, { it: 'io do', id: 'Saya memberi' },
          { it: 'io prendo', id: 'Saya mengambil' }, { it: 'io vedo', id: 'Saya melihat' },
          { it: 'io so', id: 'Saya tahu' }, { it: 'io credo', id: 'Saya percaya' },
          { it: 'io lavoro', id: 'Saya bekerja' }, { it: 'io studio', id: 'Saya belajar' },
          { it: 'io leggo', id: 'Saya membaca' }, { it: 'io scrivo', id: 'Saya menulis' },
          { it: 'io parlo', id: 'Saya bicara' }, { it: 'io ascolto', id: 'Saya mendengarkan' }
        ]
      },
      bodyParts: {
        title: 'Bagian Tubuh', icon: '🫁',
        vocab: [
          { it: 'la testa', id: 'Kepala' }, { it: 'il viso', id: 'Wajah' },
          { it: "l'occhio", id: 'Mata' }, { it: 'il naso', id: 'Hidung' },
          { it: 'la bocca', id: 'Mulut' }, { it: 'il labbro', id: 'Bibir' },
          { it: 'il dente', id: 'Gigi' }, { it: 'la lingua', id: 'Lidah' },
          { it: "l'orecchio", id: 'Telinga' }, { it: 'il collo', id: 'Leher' },
          { it: 'la spalla', id: 'Bahu' }, { it: 'la mano', id: 'Tangan' },
          { it: 'il dito', id: 'Jari' }, { it: 'il petto', id: 'Dada' },
          { it: "l'addome", id: 'Perut' }, { it: 'la schiena', id: 'Punggung' },
          { it: 'il ginocchio', id: 'Lutut' }, { it: 'il piede', id: 'Kaki' },
          { it: 'il cuore', id: 'Jantung' }, { it: 'il cervello', id: 'Otak' }
        ]
      },
      clothing: {
        title: 'Pakaian', icon: '👕',
        vocab: [
          { it: 'il vestito', id: 'Gaun' }, { it: 'i pantaloni', id: 'Celana' },
          { it: 'la camicia', id: 'Kemeja' }, { it: 'la giacca', id: 'Jaket' },
          { it: 'le scarpe', id: 'Sepatu' }, { it: 'i calzini', id: 'Kaus kaki' },
          { it: 'il cappello', id: 'Topi' }, { it: 'gli occhiali', id: 'Kacamata' },
          { it: 'la cintura', id: 'Ikat pinggang' }, { it: 'la cravatta', id: 'Dasi' },
          { it: 'il maglione', id: 'Sweter' }, { it: 'il cappotto', id: 'Mantel' },
          { it: 'i guanti', id: 'Sarung tangan' }, { it: 'la sciarpa', id: 'Syal' }
        ]
      },
      house: {
        title: 'Rumah', icon: '🏠',
        vocab: [
          { it: 'la casa', id: 'Rumah' }, { it: 'la stanza', id: 'Kamar' },
          { it: 'la cucina', id: 'Dapur' }, { it: 'il bagno', id: 'Kamar mandi' },
          { it: 'la porta', id: 'Pintu' }, { it: 'la finestra', id: 'Jendela' },
          { it: 'il tavolo', id: 'Meja' }, { it: 'la sedia', id: 'Kursi' },
          { it: 'il letto', id: 'Tempat tidur' }, { it: 'il divano', id: 'Sofa' },
          { it: "l'armadio", id: 'Lemari' }, { it: 'la mensola', id: 'Rak' },
          { it: 'la chiave', id: 'Kunci' }, { it: 'lo specchio', id: 'Cermin' },
          { it: 'la scala', id: 'Tangga' }, { it: 'il giardino', id: 'Kebun' }
        ]
      },
      foodExtended: {
        title: 'Makanan Lanjutan', icon: '🍷',
        vocab: [
          { it: 'la mela', id: 'Apel' }, { it: 'la pera', id: 'Pir' },
          { it: 'la ciliegia', id: 'Ceri' }, { it: 'la fragola', id: 'Stroberi' },
          { it: "l'uva", id: 'Anggur' }, { it: "l'arancia", id: 'Jeruk' },
          { it: 'il limone', id: 'Lemon' }, { it: "l'ananas", id: 'Nanas' },
          { it: 'il mango', id: 'Mangga' }, { it: 'il miele', id: 'Madu' },
          { it: 'la marmellata', id: 'Selai' }, { it: 'la senape', id: 'Mustard' },
          { it: "l'aceto", id: 'Cuka' }, { it: 'la farina', id: 'Tepung' },
          { it: "l'olio d'oliva", id: 'Minyak zaitun' }, { it: 'la panna', id: 'Krim' }
        ]
      },
      technology: {
        title: 'Teknologi', icon: '💻',
        vocab: [
          { it: 'il computer', id: 'Komputer' }, { it: 'il cellulare', id: 'HP' },
          { it: 'il tablet', id: 'Tablet' }, { it: 'internet', id: 'Internet' },
          { it: 'il Wi-Fi', id: 'Wifi' }, { it: 'il software', id: 'Perangkat lunak' },
          { it: "l'hardware", id: 'Perangkat keras' }, { it: 'lo schermo', id: 'Layar' },
          { it: 'la tastiera', id: 'Keyboard' }, { it: 'il mouse', id: 'Mouse' },
          { it: 'la stampante', id: 'Printer' }, { it: 'la macchina fotografica', id: 'Kamera' },
          { it: 'la password', id: 'Password' }, { it: 'il browser', id: 'Browser' },
          { it: "l'e-mail", id: 'Email' }, { it: "l'applicazione", id: 'Aplikasi' }
        ]
      },
      transportation: {
        title: 'Transportasi', icon: '🚗',
        vocab: [
          { it: "l'automobile", id: 'Mobil' }, { it: "l'autobus", id: 'Bus' },
          { it: 'il treno', id: 'Kereta api' }, { it: 'il taxi', id: 'Taksi' },
          { it: "l'aereo", id: 'Pesawat' }, { it: 'la nave', id: 'Kapal' },
          { it: 'la bicicletta', id: 'Sepeda' }, { it: 'la motocicletta', id: 'Motor' },
          { it: "l'autostrada", id: 'Jalan tol' }, { it: 'la stazione', id: 'Stasiun' },
          { it: "l'aeroporto", id: 'Bandara' }, { it: 'il semaforo', id: 'Lampu lalu lintas' },
          { it: 'la patente', id: 'SIM' }, { it: 'la benzina', id: 'Bensin' }
        ]
      },
      travel: {
        title: 'Perjalanan', icon: '✈️',
        vocab: [
          { it: 'le vacanze', id: 'Liburan' }, { it: 'il viaggio', id: 'Perjalanan' },
          { it: "l'albergo", id: 'Hotel' }, { it: "l'alloggio", id: 'Akomodasi' },
          { it: 'il passaporto', id: 'Paspor' }, { it: 'la valigia', id: 'Koper' },
          { it: 'il biglietto', id: 'Tiket' }, { it: 'la prenotazione', id: 'Reservasi' },
          { it: "l'ufficio turistico", id: 'Pariwisata' }, { it: 'il souvenir', id: 'Oleh-oleh' },
          { it: "l'attrazione turistica", id: 'Tempat wisata' }, { it: 'la spiaggia', id: 'Pantai' },
          { it: 'le montagne', id: 'Gunung' }, { it: 'il visto', id: 'Visa' }
        ]
      }
    },
    achievements: [
      { id: 'first_quiz', title: 'Primo Quiz!', description: 'Completa il primo quiz', icon: '🎯', condition: (stats) => stats.quizzesCompleted >= 1 },
      { id: 'quiz_5', title: 'Principiante', description: 'Completa 5 quiz', icon: '🏆', condition: (stats) => stats.quizzesCompleted >= 5 },
      { id: 'quiz_10', title: 'Studente', description: 'Completa 10 quiz', icon: '📚', condition: (stats) => stats.quizzesCompleted >= 10 },
      { id: 'quiz_25', title: 'Esperto', description: 'Completa 25 quiz', icon: '🎓', condition: (stats) => stats.quizzesCompleted >= 25 },
      { id: 'quiz_50', title: 'Maestro', description: 'Completa 50 quiz', icon: '👑', condition: (stats) => stats.quizzesCompleted >= 50 },
      { id: 'perfect_score', title: 'Punteggio Perfetto', description: 'Ottieni il 100% in un quiz', icon: '💯', condition: (stats) => stats.perfectScores >= 1 },
      { id: 'perfect_5', title: 'Perfetto 5 Volte', description: 'Ottieni il 100% in 5 quiz', icon: '⭐', condition: (stats) => stats.perfectScores >= 5 },
      { id: 'perfect_10', title: 'Perfetto 10 Volte', description: 'Ottieni il 100% in 10 quiz', icon: '✨', condition: (stats) => stats.perfectScores >= 10 },
      { id: 'flashcard_10', title: 'Esploratore', description: 'Guarda 10 flashcard', icon: '🃏', condition: (stats) => stats.flashcardsViewed >= 10 },
      { id: 'flashcard_50', title: 'Collezionista', description: 'Guarda 50 flashcard', icon: '📇', condition: (stats) => stats.flashcardsViewed >= 50 },
      { id: 'flashcard_100', title: 'Esperto Flashcard', description: 'Guarda 100 flashcard', icon: '🎴', condition: (stats) => stats.flashcardsViewed >= 100 },
      { id: 'flashcard_500', title: 'Maestro Flashcard', description: 'Guarda 500 flashcard', icon: '🃏', condition: (stats) => stats.flashcardsViewed >= 500 },
      { id: 'vocabulary_100', title: '100 Parole', description: 'Impara 100 parole', icon: '📝', condition: (stats) => stats.wordsLearned >= 100 },
      { id: 'vocabulary_500', title: '500 Parole', description: 'Impara 500 parole', icon: '📖', condition: (stats) => stats.wordsLearned >= 500 },
      { id: 'vocabulary_1000', title: '1000 Parole', description: 'Impara 1000 parole', icon: '📚', condition: (stats) => stats.wordsLearned >= 1000 },
      { id: 'xp_100', title: '100 XP', description: 'Guadagna 100 XP', icon: '✨', condition: (stats) => stats.totalXP >= 100 },
      { id: 'xp_500', title: '500 XP', description: 'Guadagna 500 XP', icon: '🌟', condition: (stats) => stats.totalXP >= 500 },
      { id: 'xp_1000', title: '1000 XP', description: 'Guadagna 1000 XP', icon: '💫', condition: (stats) => stats.totalXP >= 1000 },
      { id: 'xp_5000', title: '5000 XP', description: 'Guadagna 5000 XP', icon: '🔥', condition: (stats) => stats.totalXP >= 5000 },
      { id: 'level_5', title: 'Livello 5', description: 'Raggiungi il livello 5', icon: '🏅', condition: (stats) => stats.level >= 5 },
      { id: 'level_10', title: 'Livello 10', description: 'Raggiungi il livello 10', icon: '🥇', condition: (stats) => stats.level >= 10 },
      { id: 'level_20', title: 'Livello 20', description: 'Raggiungi il livello 20', icon: '🎖️', condition: (stats) => stats.level >= 20 },
      { id: 'streak_3', title: '3 Giorni', description: 'Studia per 3 giorni consecutivi', icon: '📅', condition: (stats) => stats.streak >= 3 },
      { id: 'streak_7', title: '7 Giorni', description: 'Studia per 7 giorni consecutivi', icon: '📆', condition: (stats) => stats.streak >= 7 },
      { id: 'streak_30', title: '30 Giorni', description: 'Studia per 30 giorni consecutivi', icon: '🗓️', condition: (stats) => stats.streak >= 30 },
      { id: 'all_categories', title: 'Tutte le Categorie', description: 'Prova tutte le categorie di quiz', icon: '🗂️', condition: (stats) => stats.categoriesTried >= 16 },
      { id: 'speed_demon', title: 'Veloce', description: 'Completa un quiz in meno di 30 secondi', icon: '⚡', condition: (stats) => stats.fastestQuiz <= 30 },
      { id: 'consistent', title: 'Costante', description: 'Completa 10 quiz senza errori', icon: '🎯', condition: (stats) => stats.perfectStreak >= 10 },
      { id: 'night_owl', title: 'Gufo Notturno', description: 'Studia dopo le 22:00', icon: '🦉', condition: (stats) => stats.nightStudy >= 1 },
      { id: 'early_bird', title: 'Mattiniero', description: 'Studia prima delle 6:00', icon: '🐦', condition: (stats) => stats.earlyStudy >= 1 },
      { id: 'explorer', title: 'Esploratore', description: 'Usa tutte le funzionalità', icon: '🧭', condition: (stats) => stats.featuresUsed >= 8 },
      { id: 'social', title: 'Sociale', description: 'Esporta i dati 1 volta', icon: '📤', condition: (stats) => stats.exports >= 1 },
      { id: 'collector', title: 'Collezionista', description: 'Importa i dati 1 volta', icon: '📥', condition: (stats) => stats.imports >= 1 },
      { id: 'grammar_master', title: 'Maestro di Grammatica', description: 'Completa 5 quiz di coniugazione', icon: '📐', condition: (stats) => stats.grammarQuizzes >= 5 },
      { id: 'verb_master', title: 'Maestro dei Verbi', description: 'Completa 20 quiz di coniugazione', icon: '🎓', condition: (stats) => stats.grammarQuizzes >= 20 }
    ]
  };


