const CONTENT_DATA = {
  vocabulary: {
    salam: [
      { it: 'Ciao', id: 'Halo' }, { it: 'Buongiorno', id: 'Selamat pagi' },
      { it: 'Buonasera', id: 'Selamat siang' }, { it: 'Buonanotte', id: 'Selamat malam' },
      { it: 'Arrivederci', id: 'Selamat tinggal' }, { it: 'A presto', id: 'Sampai nanti' },
      { it: 'A domani', id: 'Sampai besok' }, { it: 'Per favore', id: 'Tolong' },
      { it: 'Grazie', id: 'Terima kasih' }, { it: 'Grazie mille', id: 'Terima kasih banyak' },
      { it: 'Prego', id: 'Sama-sama' }, { it: 'Scusi', id: 'Maaf' },
      { it: 'Mi dispiace', id: 'Saya minta maaf' },
      { it: 'Come stai?', id: 'Apa kabar?' }, { it: 'Sto bene', id: 'Saya baik-baik saja' },
      { it: 'Mi chiamo...', id: 'Nama saya...' }, { it: 'Piacere di conoscerti', id: 'Senang bertemu Anda' },
      { it: 'Si', id: 'Ya' }, { it: 'No', id: 'Tidak' },
      { it: 'Mi scusi', id: 'Permisi' }, { it: 'Non capisco', id: 'Saya tidak mengerti' },
      { it: 'Parla inglese?', id: 'Apakah Anda bicara bahasa Inggris?' },
      { it: 'Vorrei...', id: 'Saya ingin...' },
      { it: 'Come va?', id: 'Bagaimana?' },
      { it: 'Molto bene', id: 'Sangat baik' },
      { it: 'Così così', id: 'Lumayan' },
      { it: 'Male', id: 'Buruk' },
      { it: 'Incantato', id: 'Senang bertemu Anda' },
      { it: 'Allo stesso modo', id: 'Sama juga' },
      { it: 'Benissimo', id: 'Sangat baik' }
    ],
    angka: [
      { it: 'uno', id: '1' }, { it: 'due', id: '2' }, { it: 'tre', id: '3' },
      { it: 'quattro', id: '4' }, { it: 'cinque', id: '5' }, { it: 'sei', id: '6' },
      { it: 'sette', id: '7' }, { it: 'otto', id: '8' }, { it: 'nove', id: '9' },
      { it: 'dieci', id: '10' }, { it: 'undici', id: '11' }, { it: 'dodici', id: '12' },
      { it: 'tredici', id: '13' }, { it: 'quattordici', id: '14' }, { it: 'quindici', id: '15' },
      { it: 'sedici', id: '16' }, { it: 'diciassette', id: '17' },
      { it: 'diciotto', id: '18' }, { it: 'diciannove', id: '19' },
      { it: 'venti', id: '20' }, { it: 'trenta', id: '30' },
      { it: 'quaranta', id: '40' }, { it: 'cinquanta', id: '50' },
      { it: 'sessanta', id: '60' }, { it: 'settanta', id: '70' },
      { it: 'ottanta', id: '80' }, { it: 'novanta', id: '90' }, { it: 'cento', id: '100' }
    ],
    hari: [
      { it: 'Lunedi', id: 'Senin' }, { it: 'Martedi', id: 'Selasa' },
      { it: 'Mercoledi', id: 'Rabu' }, { it: 'Giovedi', id: 'Kamis' },
      { it: 'Venerdi', id: 'Jumat' }, { it: 'Sabato', id: 'Sabtu' },
      { it: 'Domenica', id: 'Minggu' }
    ],
    warna: [
      { it: 'Rosso', id: 'Merah' }, { it: 'Blu', id: 'Biru' },
      { it: 'Verde', id: 'Hijau' }, { it: 'Giallo', id: 'Kuning' },
      { it: 'Nero', id: 'Hitam' }, { it: 'Bianco', id: 'Putih' },
      { it: 'Grigio', id: 'Abu-abu' }, { it: 'Arancione', id: 'Oranye' },
      { it: 'Rosa', id: 'Merah muda' }, { it: 'Marrone', id: 'Cokelat' }
    ],
    ganti: [
      { it: 'Io', id: 'Saya' }, { it: 'Tu', id: 'Kamu (informal)' },
      { it: 'Lui', id: 'Dia (lk)' }, { it: 'Lei', id: 'Dia (pr)' },
      { it: 'Noi', id: 'Kami/Kita' }, { it: 'Voi', id: 'Kalian' },
      { it: 'Loro', id: 'Mereka' }
    ],
    keluarga: [
      { it: 'la madre', id: 'Ibu' }, { it: 'il padre', id: 'Ayah' },
      { it: 'la sorella', id: 'Saudari' }, { it: 'il fratello', id: 'Saudara lk' },
      { it: 'la figlia', id: 'Anak pr' }, { it: 'il figlio', id: 'Anak lk' },
      { it: 'i genitori', id: 'Orang tua' }, { it: 'la famiglia', id: 'Keluarga' },
      { it: 'il nonno', id: 'Kakek' }, { it: 'la nonna', id: 'Nenek' },
      { it: 'il cugino', id: 'Sepupu lk' }, { it: 'la cugina', id: 'Sepupu pr' },
      { it: 'il marito', id: 'Suami' }, { it: 'la moglie', id: 'Istri' },
      { it: 'il bambino', id: 'Bayi' }
    ],
    makanan: [
      { it: 'il pane', id: 'Roti' }, { it: "l'acqua", id: 'Air' },
      { it: 'il caffè', id: 'Kopi' }, { it: 'il latte', id: 'Susu' },
      { it: 'il formaggio', id: 'Keju' }, { it: "la mela", id: 'Apel' },
      { it: 'il pollo', id: 'Ayam' }, { it: 'il riso', id: 'Nasi' },
      { it: 'il pesce', id: 'Ikan' }, { it: 'la carne', id: 'Daging' },
      { it: 'lo zucchero', id: 'Gula' }, { it: 'il sale', id: 'Garam' },
      { it: 'il vino', id: 'Anggur (minuman)' }, { it: 'la birra', id: 'Bir' },
      { it: 'il succo', id: 'Jus' }, { it: 'il tè', id: 'Teh' },
      { it: 'il cioccolato', id: 'Cokelat' }, { it: 'la torta', id: 'Kue' },
      { it: "l'insalata", id: 'Salad' }, { it: 'la minestra', id: 'Sup' }
    ],
    tempat: [
      { it: 'la scuola', id: 'Sekolah' }, { it: 'la casa', id: 'Rumah' },
      { it: 'il negozio', id: 'Toko' }, { it: 'la strada', id: 'Jalan' },
      { it: 'a destra', id: 'Ke kanan' }, { it: 'a sinistra', id: 'Ke kiri' },
      { it: "l'ospedale", id: 'Rumah sakit' }, { it: 'la biblioteca', id: 'Perpustakaan' },
      { it: 'il ristorante', id: 'Restoran' }, { it: 'la stazione', id: 'Stasiun' },
      { it: "l'albergo", id: 'Hotel' }, { it: 'la banca', id: 'Bank' },
      { it: 'il parco', id: 'Taman' }, { it: 'il mercato', id: 'Pasar' },
      { it: 'la chiesa', id: 'Gereja' }, { it: 'il cinema', id: 'Bioskop' },
      { it: 'la farmacia', id: 'Apotek' }, { it: "l'ufficio postale", id: 'Kantor pos' },
      { it: 'il supermercato', id: 'Supermarket' }, { it: 'la spiaggia', id: 'Pantai' }
    ],
    profesi: [
      { it: 'il medico', id: 'Dokter' }, { it: 'il professore', id: 'Guru' },
      { it: "l'ingegnere", id: 'Insinyur' }, { it: "lo studente", id: 'Mahasiswa' },
      { it: 'il poliziotto', id: 'Polisi' }, { it: 'il cuoco', id: 'Koki' },
      { it: "l'artista", id: 'Seniman' }, { it: 'il giornalista', id: 'Jurnalis' },
      { it: 'ilautista', id: 'Sopir' }, { it: 'il venditore', id: 'Penjual' },
      { it: 'il cameriere', id: 'Pelayan' }, { it: 'il postino', id: 'Tukang pos' },
      { it: 'il soldato', id: 'Tentara' }, { it: 'il pompiere', id: 'Pemadam kebakaran' },
      { it: "l'avvocato", id: 'Pengacara' }, { it: 'il contadino', id: 'Petani' },
      { it: 'il musicista', id: 'Musisi' }, { it: 'l'attore', id: 'Aktor' },
      { it: 'il regista', id: 'Sutradara' }, { it: 'il traduttore', id: 'Penerjemah' }
    ],
    emosi: [
      { it: 'felice', id: 'Senang' }, { it: 'triste', id: 'Sedih' },
      { it: 'stanco', id: 'Lelah' }, { it: 'arrabbiato', id: 'Marah' },
      { it: 'spaventato', id: 'Takut' }, { it: 'sorpreso', id: 'Terkejut' },
      { it: 'calmo', id: 'Tenang' }, { it: 'eccitato', id: 'Antusias' },
      { it: 'innamorato', id: 'Jatuh cinta' }, { it: 'geloso', id: 'Cemburu' },
      { it: 'orgoglioso', id: 'Bangga' }, { it: 'timido', id: 'Pemalu' },
      { it: 'imbarazzato', id: 'Memalukan' }, { it: 'sicuro', id: 'Percaya diri' },
      { it: 'deluso', id: 'Kecewa' }, { it: 'preoccupato', id: 'Khawatir' },
      { it: 'solo', id: 'Kesepian' }, { it: 'entusiasta', id: 'Antusias' },
      { it: 'tranquillo', id: 'Tenang' }, { it: 'nervoso', id: 'Gugup' }
    ],
    verbes: [
      { it: 'essere', id: 'Adalah/menjadi' }, { it: 'avere', id: 'Memiliki' },
      { it: 'andare', id: 'Pergi' }, { it: 'fare', id: 'Melakukan' },
      { it: 'potere', id: 'Bisa' }, { it: 'volere', id: 'Mau' },
      { it: 'dovere', id: 'Harus' }, { it: 'dire', id: 'Berkata' },
      { it: 'vedere', id: 'Melihat' }, { it: 'venire', id: 'Datang' },
      { it: 'uscire', id: 'Keluar' }, { it: 'arrivare', id: 'Tiba' },
      { it: 'entrare', id: 'Masuk' }, { it: 'salire', id: 'Naik' },
      { it: 'scendere', id: 'Turun' }, { it: 'aprire', id: 'Membuka' },
      { it: 'chiudere', id: 'Menutup' }, { it: 'dare', id: 'Memberi' },
      { it: 'prendere', id: 'Mengambil' }, { it: 'sapere', id: 'Tahu' }
    ]
  },
    bodyParts: [
      { it: 'la testa', id: 'Kepala' }, { it: 'i capelli', id: 'Rambut' },
      { it: 'la fronte', id: 'Dahi' }, { it: 'le sopracciglia', id: 'Alis' },
      { it: 'gli occhi', id: 'Mata' }, { it: 'il naso', id: 'Hidung' },
      { it: 'le orecchie', id: 'Telinga' }, { it: 'la bocca', id: 'Mulut' },
      { it: 'le labbra', id: 'Bibir' }, { it: 'i denti', id: 'Gigi' },
      { it: 'la lingua', id: 'Lidah' }, { it: 'il mento', id: 'Dagu' },
      { it: 'la guancia', id: 'Pipi' }, { it: 'il collo', id: 'Leher' },
      { it: 'le spalle', id: 'Bahu' }, { it: 'il braccio', id: 'Lengan' },
      { it: 'il gomito', id: 'Siku' }, { it: 'il polso', id: 'Pergelangan tangan' },
      { it: 'la mano', id: 'Tangan' }, { it: 'le dita', id: 'Jari-jari' },
      { it: 'il petto', id: 'Dada' }, { it: "l'addome", id: 'Perut' },
      { it: 'la schiena', id: 'Punggung' }, { it: 'la vita', id: 'Pinggang' },
      { it: 'le anche', id: 'Pinggul' }, { it: 'la coscia', id: 'Paha' },
      { it: 'il ginocchio', id: 'Lutut' }, { it: 'la polpaccio', id: 'Betis' },
      { it: 'la caviglia', id: 'Pergelangan kaki' }, { it: 'il piede', id: 'Kaki' },
      { it: 'i talloni', id: 'Tumit' }, { it: 'le dita dei piedi', id: 'Jari kaki' },
      { it: 'il cuore', id: 'Jantung' }, { it: 'i polmoni', id: 'Paru-paru' },
      { it: 'il fegato', id: 'Hati' }
    ],
    clothing: [
      { it: 'il pantalone', id: 'Celana panjang' }, { it: 'la gonna', id: 'Rok' },
      { it: 'la camicia', id: 'Kemeja' }, { it: 'la blusa', id: 'Blus' },
      { it: 'la maglietta', id: 'Kaos' }, { it: "l'abito", id: 'Gaun/Baju' },
      { it: 'il maglione', id: 'Sweater' }, { it: 'la giacca', id: 'Jaket' },
      { it: 'il cappotto', id: 'Mantel' }, { it: "l'abito completo", id: 'Setelan' },
      { it: 'la cravatta', id: 'Dasi' }, { it: 'la cintura', id: 'Ikat pinggang' },
      { it: 'le scarpe', id: 'Sepatu' }, { it: 'gli stivali', id: 'Boots' },
      { it: 'le sandali', id: 'Sandal' }, { it: 'i calzini', id: 'Kaos kaki' },
      { it: 'il cappello', id: 'Topi' }, { it: 'gli occhiali', id: 'Kacamata' },
      { it: 'la sciarpa', id: 'Syal' }, { it: 'i guanti', id: 'Sarung tangan' },
      { it: 'la berretta', id: 'Topi baseball' }, { it: 'la maglietta sportiva', id: 'Kaos olahraga' },
      { it: 'i pantaloncini', id: 'Celana pendek' },
      { it: 'il bikini', id: 'Bikini' },
      { it: 'il pigiama', id: 'Piama' },
      { it: "l'intimo", id: 'Celana dalam' },
      { it: 'il reggiseno', id: 'Bra' },
      { it: "l'uniforme", id: 'Seragam' },
      { it: "l'abbigliamento sportivo", id: 'Pakaian olahraga' },
      { it: 'il costume da bagno', id: 'Baju renang' },
      { it: 'le scarpe da ginnastica', id: 'Sneakers' },
      { it: 'le scarpe col tacco', id: 'High heels' },
      { it: 'i mocassini', id: 'Moccasins' },
      { it: 'i jeans', id: 'Jeans' },
      { it: 'il cardigan', id: 'Cardigan' },
      { it: 'il blazer', id: 'Blazer' },
      { it: 'il gilet', id: 'Rompi' },
      { it: "gli orecchini", id: 'Anting-anting' },
      { it: 'il collana', id: 'Kalung' },
      { it: "l'anello", id: 'Cincin' },
      { it: 'il braccialetto', id: 'Gelang' },
      { it: "l'orologio", id: 'Jam tangan' }
    ],
    house: [
      { it: 'la camera', id: 'Kamar tidur' }, { it: 'il bagno', id: 'Kamar mandi' },
      { it: 'la cucina', id: 'Dapur' }, { it: 'il soggiorno', id: 'Ruang tamu' },
      { it: "l'ingresso", id: 'Pintu masuk' }, { it: 'il corridoio', id: 'Koridor' },
      { it: 'la cantina', id: 'Ruang bawah tanah' }, { it: 'la soffitta', id: 'Loteng' },
      { it: 'il garage', id: 'Garasi' }, { it: 'il giardino', id: 'Taman' },
      { it: 'la terrazza', id: 'Teras' }, { it: 'il balcone', id: 'Balkon' },
      { it: 'la porta', id: 'Pintu' }, { it: 'la finestra', id: 'Jendela' },
      { it: 'il muro', id: 'Dinding' }, { it: 'il soffitto', id: 'Langit-langit' },
      { it: 'il pavimento', id: 'Lantai' }, { it: 'la scala', id: 'Tangga' },
      { it: 'la ringhiera', id: 'Pegangan tangga' }, { it: 'il mattone', id: 'Bata' },
      { it: 'il camino', id: 'Perapian' }, { it: 'la recinzione', id: 'Pagar' },
      { it: "l'edificio", id: 'Gedung apartemen' },
      { it: "l'appartamento", id: 'Apartemen' },
      { it: 'la dispensa', id: 'Ruang penyimpanan anggur' },
      { it: 'la lavanderia', id: 'Ruang cuci' },
      { it: 'il salotto', id: 'Ruang keluarga' },
      { it: 'la sala da pranzo', id: 'Ruang makan' },
      { it: 'la sala giochi', id: 'Ruang bermain' },
      { it: 'la piscina', id: 'Kolam renang' },
      { it: "l'orto", id: 'Kebun sayur' },
      { it: 'la tenda', id: 'Gorden' },
      { it: 'il tappeto', id: 'Karpet' },
      { it: "l'arredamento", id: 'Furniture' },
      { it: "l'armadio", id: 'Lemari' },
      { it: 'il divano', id: 'Sofa' },
      { it: 'il tavolo', id: 'Meja' },
      { it: 'la sedia', id: 'Kursi' },
      { it: 'il letto', id: 'Tempat tidur' },
      { it: 'il materasso', id: 'Matras' },
      { it: 'il cuscino', id: 'Bantal' },
      { it: 'la coperta', id: 'Selimut' },
      { it: 'le lenzuola', id: 'Sprei' },
      { it: 'lo specchio', id: 'Cermin' },
      { it: 'lo scaffale', id: 'Rak' },
      { it: 'il cassetto', id: 'Laci' }
    ],
    nature: [
      { it: 'il sole', id: 'Matahari' }, { it: 'la luna', id: 'Bulan' },
      { it: 'le stelle', id: 'Bintang' }, { it: 'il cielo', id: 'Langit' },
      { it: 'il mare', id: 'Laut' }, { it: "l'oceano", id: 'Samudra' },
      { it: 'il fiume', id: 'Sungai' }, { it: 'il lago', id: 'Danau' },
      { it: 'la montagna', id: 'Gunung' }, { it: 'la collina', id: 'Bukit' },
      { it: 'la valle', id: 'Lembah' }, { it: 'il deserto', id: 'Gurun' },
      { it: 'la foresta', id: 'Hutan' }, { it: 'la pianura', id: 'Dataran' },
      { it: 'il ruscello', id: "Aliran sungai" }, { it: "l'isola", id: 'Pulau' },
      { it: 'la spiaggia', id: 'Pantai' }, { it: 'le onde', id: 'Ombak' },
      { it: 'la sabbia', id: 'Pasir' }, { it: 'le rocce', id: 'Batu karang' },
      { it: 'il vento', id: 'Angin' }, { it: 'la pioggia', id: 'Hujan' },
      { it: 'la neve', id: 'Salju' }, { it: 'la grandine', id: 'Hujan es' },
      { it: "l'arcobaleno", id: 'Pelangi' }, { it: 'la nuvola', id: 'Awan' },
      { it: 'il temporale', id: 'Badai petir' }, { it: 'la nebbia', id: 'Kabut' },
      { it: 'la brina', id: 'Embun beku' }, { it: 'il ghiaccio', id: 'Es' },
      { it: 'la terra', id: 'Tanah' }, { it: 'la polvere', id: 'Debu' },
      { it: "l'erba", id: 'Rumput' }, { it: 'le foglie', id: 'Daun' },
      { it: 'il muschio', id: 'Lumut' }
    ],
    animalsDomestic: [
      { it: 'il cane', id: 'Anjing' }, { it: 'il gatto', id: 'Kucing' },
      { it: 'il coniglio', id: 'Kelinci' }, { it: "l'uccello", id: 'Burung' },
      { it: 'il pesce rosso', id: 'Ikan mas' }, { it: 'il criceto', id: 'Hamster' },
      { it: 'la tartaruga', id: 'Kura-kura' }, { it: 'il cavallo', id: 'Kuda' },
      { it: 'la gallina', id: 'Ayam betina' }, { it: 'il gallo', id: 'Ayam jantan' },
      { it: 'l'anatra', id: 'Bebek' }, { it: 'la capra', id: 'Kambing' },
      { it: 'la pecora', id: 'Domba' }, { it: 'il maiale', id: 'Babi' },
      { it: "l'asino", id: 'Keledai' }
    ],
    animalsWild: [
      { it: 'il leone', id: 'Singa' }, { it: 'la tigre', id: 'Harimau' },
      { it: "l'elefante", id: 'Gajah' }, { it: 'la giraffa', id: 'Jerapah' },
      { it: 'la zebra', id: 'Zebra' }, { it: 'il gorilla', id: 'Gorila' },
      { it: "l'orso", id: 'Beruang' }, { it: 'il lupo', id: 'Serigala' },
      { it: 'la volpe', id: 'Rubah' }, { it: 'il cervo', id: 'Rusa' },
      { it: 'il serpente', id: 'Ular' }, { it: 'il coccodrillo', id: 'Buaya' },
      { it: "l'ippopotamo", id: 'Kudanil' }, { it: 'il rinoceronte', id: 'Badak' },
      { it: 'la scimmia', id: 'Monyet' }, { it: 'il canguro', id: 'Kanguru' },
      { it: 'il koala', id: 'Koala' }, { it: 'la iena', id: 'Hiena' },
      { it: 'la pantera', id: 'Macan tutul' }, { it: 'il ghepardo', id: 'Cheetah' },
      { it: 'lo sciacallo', id: 'Jakal' }, { it: 'l'avvoltoio', id: 'Burung nasar' },
      { it: 'il rapace', id: 'Burung pemangsa' },
      { it: 'il procione', id: 'Rakun' },
      { it: 'il porcospino', id: 'Babi tanah' }
    ],
    animalsSea: [
      { it: 'la balena', id: 'Paus' }, { it: 'il delfino', id: 'Lumba-lumba' },
      { it: 'lo squalo', id: 'Hiu' }, { it: 'la tartaruga marina', id: 'Penyu' },
      { it: 'la foca', id: 'Anjing laut' }, { it: "l'otaria", id: 'Singa laut' },
      { it: 'il granchio', id: 'Kepiting' }, { it: 'il gambero', id: 'Udang' },
      { it: "l'ostrica", id: 'Tiram' }, { it: 'le cozze', id: 'Kerang' }
    ],
    insects: [
      { it: "l'ape", id: 'Lebah' }, { it: 'la formica', id: 'Semut' },
      { it: 'la farfalla', id: 'Kupu-kupu' }, { it: 'il bruco', id: 'Ulat' },
      { it: 'la coccinella', id: 'Kepik' }, { it: 'lo scarabeo', id: 'Kumbang' },
      { it: 'la mosca', id: 'Lalat' }, { it: 'la zanzara', id: 'Nyamuk' },
      { it: 'la falena', id: 'Ngengat' }, { it: 'la cavalletta', id: 'Belalang' },
      { it: 'il grillo', id: 'Jangkrik' }, { it: "l'aragno", id: 'Laba-laba' },
      { it: 'lo scorpione', id: 'Kalajengking' }, { it: 'la cimice', id: 'Kutu busuk' },
      { it: 'la libellula', id: 'Capung' }
    ],
    foodExtended: [
      { it: 'il croissant', id: 'Croissant' }, { it: 'la baguette', id: 'Roti baguette' },
      { it: 'la brioche', id: 'Brioche' },
      { it: 'il panino al cioccolato', id: 'Roti cokelat' },
      { it: 'la crêpe', id: 'Kue dadar' }, { it: 'il waffle', id: 'Waffle' },
      { it: 'la quiche', id: 'Kue pai asin' },
      { it: 'il formaggio di capra', id: 'Keju kambing' },
      { it: 'il camembert', id: 'Keju Camembert' },
      { it: 'il brie', id: 'Keju Brie' },
      { it: 'la ratatouille', id: 'Ratatouille' },
      { it: 'la pasta alla carbonara', id: 'Pasta carbonara' },
      { it: 'la pizza margherita', id: 'Pizza margherita' },
      { it: 'il tiramisù', id: 'Tiramisu' },
      { it: 'la bruschetta', id: 'Bruschetta' },
      { it: 'il prosciutto', id: 'Sapi masak Burgundy' },
      { it: 'il pollo arrosto', id: 'Ayam panggang' },
      { it: 'l'anatra arrosto', id: 'Bebek panggang' },
      { it: "l'estratto di carne", id: 'Sup bawang' },
      { it: "l'insalata mista", id: 'Salad campuran' },
      { it: 'la mozzarella', id: 'Mozzarella' },
      { it: 'il risotto', id: 'Risotto' },
      { it: 'la bolognese', id: 'Bolognese' },
      { it: 'il riso al latte', id: 'Susu beras' },
      { it: 'il panacotta', id: 'Panna cotta' },
      { it: 'la torta di mele', id: 'Kue apel' },
      { it: 'i biscotti', id: 'Kue kering' },
      { it: 'il gelato', id: 'Es krim' },
      { it: 'la panna', id: 'Krim' },
      { it: 'la frutta fresca', id: 'Buah segar' },
      { it: "la mela", id: 'Apel' },
      { it: 'la pera', id: 'Pir' },
      { it: 'la pesca', id: 'Persik' },
      { it: 'la ciliegia', id: 'Ceri' },
      { it: 'la fragola', id: 'Stroberi' },
      { it: 'il mirtillo', id: 'Blueberry' },
      { it: 'il lampone', id: 'Raspberry' },
      { it: "l'uva", id: 'Anggur buah' },
      { it: 'il melone', id: 'Melon' },
      { it: "l'arancia", id: 'Jeruk' },
      { it: 'il limone', id: 'Lemon' },
      { it: "l'ananas", id: 'Nanas' },
      { it: 'la mango', id: 'Mangga' },
      { it: 'il kiwi', id: 'Kiwi' },
      { it: 'la prugna', id: 'Plum' },
      { it: "l'amanda", id: 'Almond' },
      { it: 'la noce', id: 'Kenari' },
      { it: "l'avellana", id: 'Hazelnut' },
      { it: "l'arachide", id: 'Kacang tanah' },
      { it: 'il pistacchio', id: 'Kacang pistachio' },
      { it: 'la anacardo', id: 'Kacang mete' },
      { it: 'la marmellata', id: 'Selai' },
      { it: 'il miele', id: 'Madu' },
      { it: 'il burro', id: 'Mentega' },
      { it: 'la farina', id: 'Tepung' },
      { it: "l'olio d'oliva", id: 'Minyak zaitun' },
      { it: "l'aceto", id: 'Cuka' },
      { it: 'la senape', id: 'Mustard' },
      { it: 'il ketchup', id: 'Kecap' },
      { it: 'la maionese', id: 'Mayones' },
      { it: 'la panna acida', id: 'Krim asam' }
    ],
    transportation: [
      { it: "l'auto", id: 'Mobil' }, { it: 'il camion', id: 'Truk' },
      { it: "l'autobus", id: 'Bus' }, { it: 'la metropolitana', id: 'Kereta bawah tanah' },
      { it: 'il treno', id: 'Kereta api' }, { it: 'il tram', id: 'Trem' },
      { it: 'il taxi', id: 'Taksi' }, { it: "l'aereo", id: 'Pesawat' },
      { it: 'la barca', id: 'Kapal' }, { it: 'la bicicletta', id: 'Sepeda' },
      { it: 'la moto', id: 'Motor' }, { it: 'lo scooter', id: 'Skuter' },
      { it: 'il traghetto', id: 'Kapal feri' }, { it: 'lo yacht', id: 'Kapal pesiar' },
      { it: "la funivia", id: 'Kereta gantung' },
      { it: "l'alta velocità", id: 'Kereta cepat' },
      { it: "l'elicottero", id: 'Helikopter' },
      { it: "l'aerostato", id: 'Balon udara' },
      { it: 'il sottomarino', id: 'Kapal selam' },
      { it: 'il cargo', id: 'Kapal kargo' },
      { it: 'il transatlantico', id: 'Kapal pesiar besar' },
      { it: "l'ambulanza", id: 'Ambulans' },
      { it: 'il camion dei pompieri', id: 'Truk pemadam' },
      { it: 'il camion della spazzatura', id: 'Truk sampah' },
      { it: 'il trattore', id: 'Traktor' },
      { it: "il veicolo", id: 'Kendaraan' },
      { it: "l'autostrada", id: 'Jalan tol' },
      { it: 'la strada', id: 'Jalan raya' },
      { it: 'la via', id: 'Jalan kota' },
      { it: "l'incrocio", id: 'Perempatan' },
      { it: 'la rotatoria', id: 'Bundaran' },
      { it: 'il parcheggio', id: 'Parkir' },
      { it: 'il passaggio pedonale', id: 'Penyeberangan pejalan kaki' },
      { it: 'il semaforo rosso', id: 'Lampu merah' },
      { it: 'il semaforo verde', id: 'Lampu hijau' },
      { it: "il segnale stradale", id: 'Rambu lalu lintas' },
      { it: 'la cintura di sicurezza', id: 'Sabuk pengaman' },
      { it: "la patente", id: 'Surat izin mengemudi' },
      { it: 'la benzina', id: 'Bensin' },
      { it: 'il serbatoio pieno', id: 'Isi penuh' },
      { it: 'il motore', id: 'Mesin' },
      { it: 'la ruota', id: 'Roda' }
    ],
    technology: [
      { it: 'il computer', id: 'Komputer' }, { it: 'lo schermo', id: 'Layar' },
      { it: 'la tastiera', id: 'Keyboard' }, { it: 'il mouse', id: 'Mouse' },
      { it: 'la stampante', id: 'Printer' }, { it: 'il telefono', id: 'Telepon' },
      { it: 'il cellulare', id: 'HP' }, { it: 'il tablet', id: 'Tablet' },
      { it: 'internet', id: 'Internet' }, { it: 'la rete', id: 'Jaringan' },
      { it: 'la connessione', id: 'Koneksi' }, { it: 'il wifi', id: 'Wifi' },
      { it: "l'applicazione", id: 'Aplikasi' }, { it: 'il software', id: 'Perangkat lunak' },
      { it: 'il hardware', id: 'Perangkat keras' },
      { it: 'lo schermo tattile', id: 'Layar sentuh' },
      { it: 'il processore', id: 'Prosesor' },
      { it: 'la memoria', id: 'Memori' },
      { it: 'il disco rigido', id: 'Hard disk' },
      { it: 'la chiavetta USB', id: 'Flashdisk' },
      { it: 'la fotocamera', id: 'Kamera' },
      { it: 'il video', id: 'Video' },
      { it: 'la foto', id: 'Foto' },
      { it: 'le cuffie', id: 'Headset' },
      { it: 'gli auricolari', id: 'Earphone' },
      { it: 'le casse', id: 'Speaker' },
      { it: 'il caricatore', id: 'Charger' },
      { it: 'la batteria', id: 'Baterai' },
      { it: "la schermata iniziale", id: 'Home screen' },
      { it: 'la password', id: 'Password' },
      { it: "l'indirizzo email", id: 'Alamat email' },
      { it: 'il browser', id: 'Browser' },
      { it: 'la pagina web', id: 'Halaman web' },
      { it: 'il sito web', id: 'Situs web' },
      { it: 'il blog', id: 'Blog' },
      { it: 'il social network', id: 'Jejaring sosial' },
      { it: 'il messaggio', id: 'Pesan' },
      { it: "l'email", id: 'Email' },
      { it: 'l allegato', id: 'Lampiran' },
      { it: 'scaricare', id: 'Mengunduh' },
      { it: 'aggiornare', id: 'Memperbarui' },
      { it: 'salvare', id: 'Menyimpan' },
      { it: 'inviare', id: 'Mengirim' },
      { it: 'eliminare', id: 'Menghapus' },
      { it: 'stampare', id: 'Mencetak' }
    ],
    schoolEducation: [
      { it: 'la scuola', id: 'Sekolah' }, { it: "l'università", id: 'Universitas' },
      { it: 'la classe', id: 'Kelas' }, { it: 'la lavagna', id: 'Papan tulis' },
      { it: 'la scrivania', id: 'Meja guru' }, { it: 'la sedia', id: 'Kursi' },
      { it: 'il libro', id: 'Buku' }, { it: 'il quaderno', id: 'Buku tulis' },
      { it: 'la penna', id: 'Pena' }, { it: 'la matita', id: 'Pensil' },
      { it: 'la gomma', id: 'Penghapus' }, { it: 'il righello', id: 'Penggaris' },
      { it: 'lo zaino', id: 'Tas punggung' },
      { it: 'la pennerla', id: 'Tempat pensil' },
      { it: 'la geometria', id: 'Alat gambar' },
      { it: 'il compasso', id: 'Jangka' },
      { it: "l'equazione", id: 'Persamaan matematika' },
      { it: 'la frazione', id: 'Pecahan' },
      { it: 'il risultato', id: 'Hasil' },
      { it: 'la media', id: 'Nilai rata-rata' },
      { it: 'il voto', id: 'Nilai' },
      { it: 'il compito', id: 'PR' },
      { it: "l'esame", id: 'Ujian' },
      { it: 'il corso', id: 'Kursus' },
      { it: 'la materia', id: 'Mata pelajaran' },
      { it: "l'italiano", id: 'Bahasa Italia' },
      { it: 'la matematica', id: 'Matematika' },
      { it: 'la fisica', id: 'Fisika' },
      { it: 'la chimica', id: 'Kimia' },
      { it: 'la biologia', id: 'Biologi' },
      { it: 'la storia', id: 'Sejarah' },
      { it: 'la geografia', id: 'Geografi' },
      { it: "l'inglese", id: 'Bahasa Inggris' },
      { it: "l'arte", id: 'Seni' },
      { it: 'la musica', id: 'Musik' },
      { it: "l'educazione fisica", id: 'Pendidikan jasmani' },
      { it: 'la filosofia', id: 'Filsafat' },
      { it: "l'economia", id: 'Ekonomi' },
      { it: 'il semestre', id: 'Semester' },
      { it: 'il campus', id: 'Kampus' },
      { it: 'la biblioteca', id: 'Perpustakaan' },
      { it: 'la mensa', id: 'Kantin' },
      { it: "l'iscrizione", id: 'Pendaftaran' },
      { it: 'la laurea', id: 'Gelar' },
      { it: 'la tesi', id: 'Tesis' },
      { it: "l'stage", id: 'Magang' },
      { it: 'il professore universitario', id: 'Guru besar' },
      { it: 'il rettore', id: 'Rektor' },
      { it: "l'alunno", id: 'Siswa' },
      { it: 'il compagno di classe', id: 'Teman sekelas' }
    ],
    workOffice: [
      { it: "l'ufficio", id: 'Kantor' }, { it: 'la riunione', id: 'Rapat' },
      { it: 'il capo', id: 'Atasan' }, { it: 'il collega', id: 'Rekan kerja' },
      { it: 'lo stipendio', id: 'Gaji' }, { it: 'il lavoro', id: 'Pekerjaan' },
      { it: 'il contratto', id: 'Kontrak' }, { it: 'le vacanze', id: 'Liburan' },
      { it: 'il permesso', id: 'Cuti' }, { it: 'l'orario', id: 'Jam kerja' },
      { it: 'la pausa', id: 'Istirahat' },
      { it: 'la pausa caffè', id: 'Istirahat kopi' },
      { it: "l' colloquio", id: 'Wawancara kerja' },
      { it: "la candidatura", id: 'Lamaran kerja' },
      { it: 'il curriculum vitae', id: 'Curriculum vitae' },
      { it: 'la lettera di motivazione', id: 'Surat motivasi' },
      { it: 'la promozione', id: 'Promosi' },
      { it: 'il licenziamento', id: 'PHK' },
      { it: 'le dimissioni', id: 'Mengundurkan diri' },
      { it: 'il reparto', id: 'Departemen' },
      { it: 'il progetto', id: 'Proyek' },
      { it: "l'insuccesso", id: 'Kegagalan' },
      { it: 'il successo', id: 'Keberhasilan' },
      { it: "la valutazione", id: 'Penilaian' },
      { it: 'le prestazioni', id: 'Pencapaian' },
      { it: "l'ambizione", id: 'Ambisi' },
      { it: 'il trionfo', id: 'Kesuksesan' },
      { it: 'il pagamento', id: 'Bayaran' },
      { it: "le imposte", id: 'Pajak' },
      { it: "l'assicurazione sanitaria", id: 'Asuransi kesehatan' },
      { it: 'il bonus', id: 'Bonus' },
      { it: "la fine dell'anno", id: 'Akhir tahun' },
      { it: 'la cassa', id: 'Meja kasir' },
      { it: "l'armadio", id: 'Lemari arsip' },
      { it: 'la cartella', id: 'Map' }
    ],
    sportsActivities: [
      { it: 'il calcio', id: 'Sepak bola' }, { it: 'la pallacanestro', id: 'Basket' },
      { it: 'il tennis', id: 'Tenis' }, { it: 'la pallavolo', id: 'Voli' },
      { it: "l'atletica", id: 'Atletik' }, { it: 'il nuoto', id: 'Renang' },
      { it: 'il rugby', id: 'Ragbi' }, { it: 'la pallamano', id: 'Bola tangan' },
      { it: "la scherma", id: 'Anggar' }, { it: "l'equitazione", id: 'Berkuda' },
      { it: 'il golf', id: 'Golf' }, { it: 'lo sci', id: 'Ski' },
      { it: 'il snowboard', id: 'Snowboard' }, { it: 'il surf', id: 'Selancar' },
      { it: 'il judo', id: 'Judo' }, { it: 'il karate', id: 'Karate' },
      { it: 'la boxe', id: 'Tinju' }, { it: 'la lotta', id: 'Gulat' },
      { it: 'la ginnastica', id: 'Senam' }, { it: 'lo yoga', id: 'Yoga' },
      { it: 'il ciclismo', id: 'Bersepeda' }, { it: "l'isolamento", id: 'Angkat besi' },
      { it: 'la corsa', id: 'Lari' }, { it: 'la camminata', id: 'Jalan kaki' },
      { it: "l'alpinismo", id: 'Mendaki' }, { it: "l'arrampicata", id: 'Panjat tebing' },
      { it: 'il tuffo', id: 'Selam' }, { it: 'la vela', id: 'Layar' },
      { it: 'il canottaggio', id: 'Mendayung' }, { it: 'il canoa', id: 'Kano' },
      { it: 'il kayak', id: 'Kajak' }, { it: 'il tiro con l'arco', id: 'Panahan' },
      { it: 'il tiro a segno', id: 'Menembak' }, { it: 'il pattinaggio', id: 'Seluncur es' },
      { it: "l'hockey", id: 'Hoki' }, { it: 'la baseball', id: 'Baseball' },
      { it: 'il cricket', id: 'Kriket' }, { it: 'il badminton', id: 'Bulutangkis' },
      { it: 'il ping pong', id: 'Pingpong' },
      { it: 'il biliardo', id: 'Bilyar' },
      { it: 'il bowling', id: 'Boling' },
      { it: 'la danza', id: 'Tari' },
      { it: 'lo skateboard', id: 'Skateboard' },
      { it: 'il pattinaggio a rotelle', id: 'Inline skate' },
      { it: "l'ultimate frisbee", id: 'Frisbee' }
    ],
    hobbiesLeisure: [
      { it: 'la lettura', id: 'Membaca' }, { it: 'la scrittura', id: 'Menulis' },
      { it: 'la pittura', id: 'Melukis' }, { it: 'il disegno', id: 'Menggambar' },
      { it: 'il cinema', id: 'Nonton film' }, { it: 'la musica', id: 'Dengar musik' },
      { it: 'i videogiochi', id: 'Main game' }, { it: 'la fotografia', id: 'Fotografi' },
      { it: 'il giardinaggio', id: 'Berkebun' }, { it: 'la cucito', id: 'Menjahit' },
      { it: 'il tricotto', id: 'Merajut' }, { it: 'il ricamo', id: 'Menyulam' },
      { it: 'il fai da te', id: 'DIY/perbaikan' },
      { it: 'la collezione', id: 'Koleksi' },
      { it: 'il modellismo', id: 'Model kit' },
      { it: 'la filatelia', id: 'Filateli (perangko)' },
      { it: "l'acquariofilia", id: 'Hobi ikan' },
      { it: 'la petanque', id: 'Petanque' },
      { it: 'gli scacchi', id: 'Catur' },
      { it: 'le carte', id: 'Main kartu' },
      { it: 'la meditazione', id: 'Meditasi' },
      { it: "l'aria aperta", id: 'Alam terbuka' },
      { it: 'l'escursione', id: 'Hiking' },
      { it: 'il picnic', id: 'Piknik' },
      { it: 'il campeggio', id: 'Berkemah' },
      { it: 'la pesca', id: 'Memancing' },
      { it: 'la caccia', id: 'Berburu' },
      { it: 'la danza', id: 'Menari' },
      { it: 'lo yoga', id: 'Yoga' },
      { it: 'la ceramica', id: 'Keramik' }
    ],
    healthMedical: [
      { it: 'la salute', id: 'Kesehatan' }, { it: 'la malattia', id: 'Penyakit' },
      { it: 'il raffreddore', id: 'Pilek' }, { it: "l'influenza", id: 'Flu' },
      { it: 'la febbre', id: 'Demam' }, { it: 'la tosse', id: 'Batuk' },
      { it: 'il mal di testa', id: 'Sakit kepala' },
      { it: 'il mal di schiena', id: 'Sakit punggung' },
      { it: 'il mal di stomaco', id: 'Sakit perut' },
      { it: 'la nausea', id: 'Mual' },
      { it: 'il vomito', id: 'Muntah' },
      { it: 'la diarrea', id: 'Diare' },
      { it: 'la stipsi', id: 'Sembelit' },
      { it: "l'allergia", id: 'Alergi' },
      { it: "l'asma", id: 'Asma' },
      { it: 'il diabete', id: 'Diabetes' },
      { it: "l'ipertensione", id: 'Hipertensi' },
      { it: "l'infezione", id: 'Infeksi' },
      { it: 'la ferita', id: 'Luka' },
      { it: 'la cicatrice', id: 'Bekas luka' },
      { it: "l'escoriazione", id: 'Luka lecet' },
      { it: 'il taglio', id: 'Goresan' },
      { it: 'la vescica', id: 'Gelembung' },
      { it: 'il livido', id: 'Memar' },
      { it: "l' gonfiore", id: 'Bengkak' },
      { it: 'il mal di testa', id: 'Pusing' },
      { it: "l'insonnia", id: 'Insomnia' },
      { it: 'la stanchezza', id: 'Kelelahan' },
      { it: 'lo stress', id: 'Stres' },
      { it: 'la depressione', id: 'Depresi' },
      { it: "l'ansia", id: 'Kecemasan' },
      { it: 'il trattamento', id: 'Perawatan' },
      { it: 'la ricetta', id: 'Resep' },
      { it: "l'antibiotico", id: 'Antibiotik' },
      { it: "l'aspirina", id: 'Aspirin' },
      { it: 'il paracetamolo', id: 'Parasetamol' },
      { it: 'la pomata', id: 'Salep' },
      { it: "la benda", id: 'Perban' },
      { it: "l'iniezione", id: 'Suntikan' },
      { it: 'la flebo', id: 'Infus' },
      { it: "l'esame", id: 'Pemeriksaan' },
      { it: 'la radiografia', id: 'Rontgen' },
      { it: "l'ecografia", id: 'USG' },
      { it: "la risonanza magnetica", id: 'MRI' },
      { it: 'la chirurgia', id: 'Operasi' },
      { it: "l'anestesia", id: 'Anestesi' },
      { it: 'la guarigione', id: 'Penyembuhan' },
      { it: 'la convalescenza', id: 'Masa pemulihan' },
      { it: 'il vaccino', id: 'Vaksin' }
    ],
    professionsExtended: [
      { it: "l'infermiere/infermiera", id: 'Perawat' },
      { it: "l'architetto", id: 'Arsitek' },
      { it: 'il farmacista', id: 'Apoteker' },
      { it: 'il dentista', id: 'Dokter gigi' },
      { it: 'il veterinario', id: 'Dokter hewan' },
      { it: "l'ottico", id: 'Ahli kacamata' },
      { it: 'il contabile', id: 'Akuntan' },
      { it: "l'agente immobiliare", id: 'Agen properti' },
      { it: 'il banchiere', id: 'Bankir' },
      { it: "l'assicuratore", id: 'Agen asuransi' },
      { it: "l'imprenditore", id: 'Pengusaha' },
      { it: 'il direttore', id: 'Manajer' },
      { it: "l'assistente", id: 'Asisten' },
      { it: 'il segretario', id: 'Sekretaris' },
      { it: 'il venditore', id: 'Sales' },
      { it: 'lo sviluppatore', id: 'Developer' },
      { it: 'il designer', id: 'Desainer' },
      { it: 'il grafico', id: 'Desainer grafis' },
      { it: 'il fotografo', id: 'Fotografer' },
      { it: 'il videomaker', id: 'Videografer' },
      { it: "l'influencer", id: 'Influencer' },
      { it: 'lo youtuber', id: 'YouTuber' },
      { it: 'il barista', id: 'Barista' },
      { it: "l'elettricista", id: 'Tukang listrik' },
      { it: 'l'idraulico', id: 'Tukang ledeng' },
      { it: 'il falegname', id: 'Tukang kayu' },
      { it: 'il muratore', id: 'Tukang batu' },
      { it: 'il pitore', id: 'Tukang cat' },
      { it: 'il sarto', id: 'Penjahit' },
      { it: 'il parrucchiere', id: 'Tukang potong rambut' },
      { it: 'il gioielliere', id: 'Perhiasan' },
      { it: "l'orologio", id: 'Ahli jam' },
      { it: "l'autorista", id: 'Montir mobil' },
      { it: "l'operaio", id: 'Pekerja' },
      { it: 'il tecnico', id: 'Teknisi' },
      { it: "l'operatore", id: 'Operator' },
      { it: 'il controllore', id: 'Petugas' },
      { it: 'il caposquadra', id: 'Mandor' },
      { it: 'il supervisore', id: 'Supervisor' },
      { it: 'il vice direttore', id: 'Wakil direktur' }
    ],
    cityPlaces: [
      { it: 'la città', id: 'Kota' }, { it: 'il paese', id: 'Desa' },
      { it: 'la piazza', id: 'Alun-alun' },
      { it: "l'via', id: 'Jalan utama' },
      { it: 'il viale', id: 'Boulevard' },
      { it: 'il percorso pedonale', id: 'Jalan setapak' },
      { it: 'il parco', id: 'Taman kota' },
      { it: 'la fontana', id: 'Air mancur' },
      { it: 'la statua', id: 'Patung' },
      { it: 'il monumento', id: 'Monumen' },
      { it: 'la cattedrale', id: 'Katedral' },
      { it: 'la moschea', id: 'Masjid' },
      { it: 'la sinagoga', id: 'Sinagoge' },
      { it: 'il municipio', id: 'Balai kota' },
      { it: 'il tribunale', id: 'Pengadilan' },
      { it: 'la caserma', id: 'K barak' },
      { it: 'lo stadio', id: 'Stadion' },
      { it: "la palestra", id: 'Pusat kebugaran' },
      { it: 'il centro commerciale', id: 'Mall' },
      { it: 'il negozio di moda', id: 'Butik' },
      { it: "la galleria", id: 'Galeri' },
      { it: "la mostra", id: 'Pameran' },
      { it: 'il teatro', id: 'Teater' },
      { it: "l'opera", id: 'Opera' },
      { it: 'la sala concerti', id: 'Gedung konser' },
      { it: 'il circo', id: 'Sirkus' },
      { it: 'lo zoo', id: 'Kebun binatang' },
      { it: "l'acquario", id: 'Akuarium' },
      { it: 'il planetario', id: 'Planetarium' },
      { it: 'il museo', id: 'Museum' }
    ],
    weatherClimate: [
      { it: 'il tempo', id: 'Cuaca' }, { it: 'il clima', id: 'Iklim' },
      { it: 'il caldo', id: 'Panas' }, { it: 'il freddo', id: 'Dingin' },
      { it: "l'aridità", id: 'Kering' }, { it: "l'umidità", id: 'Kelembaban' },
      { it: 'la primavera', id: 'Musim semi' },
      { it: "l'estate", id: 'Musim panas' },
      { it: "l'autunno", id: 'Musim gugur' },
      { it: "l'inverno", id: 'Musim dingin' },
      { it: 'la temperatura', id: 'Suhu' },
      { it: 'i gradi', id: 'Derajat' },
      { it: 'le nuvole', id: 'Awan' },
      { it: 'la pioggia leggera', id: 'Gerimis' },
      { it: 'il temporale', id: 'Badai petir' },
      { it: 'il fulmine', id: 'Petir' },
      { it: 'il tuono', id: 'Guntur' },
      { it: 'la neve sciolta', id: 'Salju mencair' },
      { it: 'il ghiaccio', id: 'Es jalan' },
      { it: 'la brina', id: 'Embun beku' },
      { it: "l'gelata", id: 'Es' },
      { it: "l'ondata di caldo", id: 'Gelombang panas' },
      { it: 'il freddo polare', id: 'Dingin ekstrem' },
      { it: "il monsone", id: 'Monsoon' },
      { it: 'la siccità', id: 'Kekeringan' },
      { it: "l'alluvione", id: 'Banjir' },
      { it: 'il tornado', id: 'Tornado' },
      { it: "l'uragano", id: 'Badai' },
      { it: 'lo tsunami', id: 'Tsunami' },
      { it: "il terremoto", id: 'Gempa bumi' }
    ],
    timeExtended: [
      { it: 'il secondo', id: 'Detik' }, { it: 'il minuto', id: 'Menit' },
      { it: "l'ora", id: 'Jam' }, { it: 'il giorno', id: 'Hari' },
      { it: 'la settimana', id: 'Minggu' }, { it: 'il mese', id: 'Bulan' },
      { it: "l'anno", id: 'Tahun' }, { it: 'il secolo', id: 'Abad' },
      { it: 'la mattina', id: 'Pagi' }, { it: 'il pomeriggio', id: 'Siang' },
      { it: 'la sera', id: 'Sore/Malam' },
      { it: 'oggi', id: 'Hari ini' }, { it: 'ieri', id: 'Kemarin' },
      { it: 'domani', id: 'Besok' }, { it: 'la prossima settimana', id: 'Minggu depan' },
      { it: 'il prossimo mese', id: 'Bulan depan' },
      { it: "l'prossimo anno", id: 'Tahun depan' },
      { it: 'il weekend', id: 'Akhir pekan' },
      { it: 'le vacanze', id: "Liburan" },
      { it: "l'inizio", id: 'Awal' },
      { it: 'la fine', id: 'Akhir' },
      { it: 'il mezzo', id: 'Tengah' },
      { it: 'di mattina presto', id: 'Pagi-pagi' },
      { it: 'tardi', id: 'Larut malam' },
      { it: 'presto', id: 'Lebih awal' },
      { it: 'in ritardo', id: 'Terlambat' },
      { it: 'in tempo', id: 'Tepat waktu' },
      { it: 'fa', id: 'Yang lalu' },
      { it: 'tra', id: 'Dalam waktu' },
      { it: 'sempre', id: 'Selalu' }
    ],
    directionsPositions: [
      { it: "l'alto", id: 'Di atas' }, { it: 'il basso', id: 'Di bawah' },
      { it: 'accanto', id: 'Di sebelah' }, { it: 'di fronte', id: 'Di depan' },
      { it: 'dietro', id: 'Di belakang' }, { it: 'al centro', id: 'Di tengah' },
      { it: 'a sinistra', id: 'Di kiri' }, { it: 'a destra', id: 'Di kanan' },
      { it: 'vicino', id: 'Dekat' }, { it: 'lontano', id: 'Jauh' },
      { it: 'dentro', id: 'Di dalam' }, { it: 'fuori', id: 'Di luar' },
      { it: 'intorno', id: 'Di sekitar' }, { it: 'attraverso', id: 'Menembus' },
      { it: 'verso', id: 'Ke arah' },
      { it: 'di fronte a', id: 'Seberang' },
      { it: "all'opposto di", id: 'Bertentangan dengan' },
      { it: 'vicino a', id: 'Di dekat' },
      { it: 'a distanza', id: 'Di kejauhan' },
      { it: 'sul bordo di', id: 'Di tepi' },
      { it: "all'angolo di", id: 'Di sudut' },
      { it: 'al centro di', id: 'Di pusat' },
      { it: "all'interno", id: 'Di dalam ruangan' },
      { it: "all'esterno", id: 'Di luar ruangan' },
      { it: 'tra', id: 'Di antara' }
    ],
    quantitiesMeasurements: [
      { it: 'molto', id: 'Banyak' }, { it: 'poco', id: 'Sedikit' },
      { it: 'troppo', id: 'Terlalu banyak' },
      { it: 'abbastanza', id: 'Cukup' },
      { it: 'un po"', id: 'Sedikit' },
      { it: 'la meta"', id: 'Setengah' },
      { it: 'un quarto', id: 'Seperempat' },
      { it: 'un terzo', id: 'Seperiga' },
      { it: 'un decimo', id: 'Sepersepuluh' },
      { it: 'un centesimo', id: 'Perseratus' },
      { it: 'un milione', id: 'Sejuta' },
      { it: 'un miliardo', id: 'Sejuta juta' },
      { it: 'il doppio', id: 'Dua kali lipat' },
      { it: 'la meta" meno', id: 'Setengahnya' },
      { it: 'un chilo', id: 'Se-kilo' },
      { it: 'un litro', id: 'Se-liter' },
      { it: 'un metro', id: 'Se-meter' },
      { it: 'un centimetro', id: 'Se-sentimeter' },
      { it: 'un chilometro', id: 'Se-kilometer' },
      { it: 'un grammo', id: 'Se-gram' },
      { it: 'una tonnellata', id: 'Se-ton' },
      { it: 'una manciata', id: 'Segenggam' },
      { it: 'un mucchio', id: 'Segunungan' },
      { it: 'una dozzina', id: 'Kira-kira dua belas' },
      { it: 'una ventina', id: 'Kira-kira dua puluh' }
    ],
    adjectivesDescriptions: [
      { it: 'grande', id: 'Besar/Tinggi' }, { it: 'piccolo', id: 'Kecil' },
      { it: 'lungo', id: 'Panjang' }, { it: 'corto', id: 'Pendek' },
      { it: 'largo', id: 'Lebar' }, { it: 'stretto', id: 'Sempit' },
      { it: 'spesso', id: 'Tebal' }, { it: 'sottile', id: 'Tipis' },
      { it: 'pesante', id: 'Berat' }, { it: 'leggero', id: 'Ringan' },
      { it: 'caro', id: 'Mahal' }, { it: 'economico', id: 'Murah' },
      { it: 'buono', id: 'Bagus/Baik' }, { it: 'cattivo', id: 'Buruk/Jahat' },
      { it: 'nuovo', id: 'Baru' }, { it: 'vecchio', id: 'Tua/Lama' },
      { it: 'giovane', id: 'Muda' }, { it: 'veloce', id: 'Cepat' },
      { it: 'lento', id: 'Lambat' }, { it: 'facile', id: 'Mudah' },
      { it: 'difficile', id: 'Sulit' }, { it: 'importante', id: 'Penting' },
      { it: 'interessante', id: 'Menarik' }, { it: 'noioso', id: 'Membosankan' },
      { it: 'completo', id: 'Lengkap' }, { it: 'semplice', id: 'Sederhana' },
      { it: 'complicato', id: 'Sulit/Kompleks' }, { it: 'ricco', id: 'Kaya' },
      { it: 'povero', id: 'Miskin' }, { it: 'sporco', id: 'Kotor' },
      { it: 'pulito', id: 'Bersih' }, { it: 'calmo', id: 'Tenang' },
      { it: 'rumoroso', id: 'Berisik' }, { it: 'forte', id: 'Kuat' },
      { it: 'debole', id: 'Lemah' }, { it: 'magnifico', id: 'Menakjubkan' },
      { it: 'bello', id: 'Cantik/Tampan' }, { it: 'brutto', id: 'Jelek' },
      { it: 'medio', id: 'Sedang/Rata-rata' }, { it: 'rotondo', id: 'Bulat' },
      { it: 'quadrato', id: 'Persegi' }, { it: 'piatto', id: 'Datar' },
      { it: 'duro', id: 'Keras' }, { it: 'morbido', id: 'Lunak' },
      { it: 'asciutto', id: 'Kering' }, { it: 'bagnato', id: 'Basah' },
      { it: 'caldo', id: 'Panas' }, { it: 'freddo', id: 'Dingin' },
      { it: 'fresco', id: 'Sejuk' }, { it: 'pieno', id: 'Penuh' }
    ],
    verbsExtended: [
      { it: 'amare', id: 'Menyukai' }, { it: 'adorare', id: 'Sangat menyukai' },
      { it: 'preferire', id: 'Lebih suka' }, { it: 'odiare', id: 'Membenci' },
      { it: 'pensare', id: 'Berpikir' }, { it: 'credere', id: 'Percaya' },
      { it: 'conoscere', id: 'Mengenal' }, { it: 'imparare', id: 'Belajar' },
      { it: 'insegnare', id: 'Mengajar' }, { it: 'spiegare', id: 'Menjelaskan' },
      { it: 'parlare', id: 'Bicara' }, { it: 'ascoltare', id: 'Mendengarkan' },
      { it: 'sentire', id: 'Mendengar' }, { it: 'leggere', id: 'Membaca' },
      { it: 'scrivere', id: 'Menulis' }, { it: 'descrivere', id: 'Mendeskripsikan' },
      { it: 'cercare', id: 'Mencari' }, { it: 'trovare', id: 'Menemukan' },
      { it: 'perdere', id: 'Kehilangan' }, { it: 'tenere', id: 'Menjaga' },
      { it: 'gettare', id: 'Membuang' }, { it: 'pulire', id: 'Membersihkan' },
      { it: 'rompere', id: 'Memecahkan' }, { it: 'riparare', id: 'Memperbaiki' },
      { it: 'costruire', id: 'Membangun' }, { it: 'distruggere', id: 'Menghancurkan' },
      { it: 'creare', id: 'Menciptakan' }, { it: 'inventare', id: 'Menciptakan' },
      { it: 'scegliere', id: 'Memilih' }, { it: 'decidere', id: 'Memutuskan' },
      { it: 'provare', id: 'Mencoba' }, { it: 'riuscire', id: 'Berhasil' },
      { it: 'fallire', id: 'Gagal' }, { it: 'iniziare', id: 'Memulai' },
      { it: 'finire', id: 'Selesai' }, { it: 'continuare', id: 'Melanjutkan' },
      { it: 'fermare', id: 'Berhenti' }, { it: 'aspettare', id: 'Menunggu' },
      { it: 'affrettarsi', id: 'Terburu-buru' },
      { it: 'tornare', id: 'Kembali' },
      { it: 'viaggiare', id: 'Bepergian' }, { it: 'visitare', id: 'Mengunjungi' },
      { it: 'vivere', id: 'Tinggal' }, { it: 'trasferirsi', id: 'Pindah' },
      { it: 'nuotare', id: 'Berenang' }, { it: 'correre', id: 'Berlari' },
      { it: 'camminare', id: 'Berjalan' }, { it: 'saltare', id: 'Melompat' },
      { it: 'cadere', id: 'Jatuh' }, { it: 'alzarsi', id: 'Bangun' },
      { it: 'sedersi', id: 'Duduk' }, { it: 'dormire', id: 'Tidur' },
      { it: 'svegliarsi', id: 'Bangun tidur' }, { it: 'mangiare', id: 'Makan' },
      { it: 'bere', id: 'Minum' }, { it: 'cucinare', id: 'Memasak' },
      { it: 'comprare', id: 'Membeli' }, { it: 'vendere', id: 'Menjual' },
      { it: 'pagare', id: 'Membayar' }, { it: 'versare', id: 'Menyetor' },
      { it: 'prelevare', id: 'Menarik tunai' }, { it: 'trasferire', id: 'Transfer' },
      { it: 'inviare', id: 'Mengirim' }, { it: 'ricevere', id: 'Menerima' },
      { it: 'offrire', id: 'Memberikan hadiah' }, { it: 'condividere', id: 'Berbagi' },
      { it: 'aiutare', id: 'Membantu' }, { it: 'sostenere', id: 'Mendukung' },
      { it: 'incoraggiare', id: 'Mendorong' }, { it: 'punire', id: 'Menghukum' },
      { it: 'premiare', id: 'Memberi penghargaan' },
      { it: 'confrontare', id: 'Membandingkan' },
      { it: 'valutare', id: 'Mengevaluasi' },
      { it: 'misurare', id: 'Mengukur' }
    ],
    abstractConcepts: [
      { it: 'la libertà', id: 'Kebebasan' }, { it: "l'uguaglianza", id: 'Kesetaraan' },
      { it: 'la fratellanza', id: 'Persaudaraan' }, { it: 'la giustizia', id: 'Keadilan' },
      { it: 'la verità', id: 'Kebenaran' }, { it: 'la menzogna', id: 'Kebohongan' },
      { it: 'la pace', id: 'Perdamaian' }, { it: 'la guerra', id: 'Perang' },
      { it: 'la speranza', id: 'Harapan' }, { it: 'il coraggio', id: 'Keberanian' },
      { it: 'la paura', id: 'Ketakutan' }, { it: 'la felicità', id: 'Kebahagiaan' },
      { it: 'la sfortuna', id: 'Kesengsaraan' }, { it: "l'amore", id: 'Cinta' },
      { it: "l'odio", id: 'Kebencian' }, { it: 'la gelosia', id: 'Kecemburuan' },
      { it: "l'orgoglio", id: 'Kesombongan' }, { it: "l'umiltà", id: 'Kerendahan hati' },
      { it: 'la pazienza', id: 'Kesabaran' }, { it: 'la rabbia', id: 'Kemarahan' },
      { it: 'il rispetto', id: 'Penghormatan' }, { it: 'la fiducia', id: 'Kepercayaan' },
      { it: 'la lealtà', id: 'Kesetiaan' }, { it: 'la generosità', id: 'Kedermawanan' },
      { it: "l'integrità", id: 'Integritas' }, { it: 'la compassione', id: 'Belas kasih' },
      { it: 'la determinazione', id: 'Determinasi' }, { it: "l'immaginazione", id: 'Imajinasi' },
      { it: 'la creatività', id: 'Kreativitas' }, { it: 'la saggezza', id: 'Kebijaksanaan' }
    ]
  },
  quizzes: {
    colors: {
      title: 'Warna dalam Bahasa Italia',
      icon: '🎨',
      questions: [
        { q: 'Merah dalam bahasa Italia adalah?', options: ['Blu', 'Rosso', 'Verde', 'Nero'], answer: 1 },
        { q: 'Biru dalam bahasa Italia adalah?', options: ['Rosso', 'Giallo', 'Blu', 'Rosa'], answer: 2 },
        { q: 'Hijau dalam bahasa Italia adalah?', options: ['Verde', 'Nero', 'Bianco', 'Arancione'], answer: 0 },
        { q: 'Kuning dalam bahasa Italia adalah?', options: ['Grigio', 'Giallo', 'Rosa', 'Marrone'], answer: 1 },
        { q: 'Hitam dalam bahasa Italia adalah?', options: ['Bianco', 'Nero', 'Grigio', 'Arancione'], answer: 1 },
        { q: 'Putih dalam bahasa Italia adalah?', options: ['Rosa', 'Marrone', 'Bianco', 'Rosso'], answer: 2 },
        { q: 'Abu-abu dalam bahasa Italia adalah?', options: ['Grigio', 'Verde', 'Blu', 'Nero'], answer: 0 },
        { q: 'Oranye dalam bahasa Italia adalah?', options: ['Giallo', 'Arancione', 'Rosa', 'Marrone'], answer: 1 },
        { q: 'Merah muda dalam bahasa Italia adalah?', options: ['Rosso', 'Rosa', 'Bianco', 'Grigio'], answer: 1 },
        { q: 'Cokelat dalam bahasa Italia adalah?', options: ['Nero', 'Marrone', 'Arancione', 'Grigio'], answer: 1 }
      ]
    },
    numbers: {
      title: 'Angka dalam Bahasa Italia',
      icon: '🔢',
      questions: [
        { q: 'Angka 1 dalam bahasa Italia adalah?', options: ['Due', 'Uno', 'Tre', 'Quattro'], answer: 1 },
        { q: 'Angka 5 dalam bahasa Italia adalah?', options: ['Tre', 'Quattro', 'Cinque', 'Sei'], answer: 2 },
        { q: 'Angka 10 dalam bahasa Italia adalah?', options: ['Otto', 'Nove', 'Undici', 'Dieci'], answer: 3 },
        { q: 'Angka 20 dalam bahasa Italia adalah?', options: ['Venti', 'Dieci', 'Trenta', 'Quaranta'], answer: 0 },
        { q: 'Angka 30 dalam bahasa Italia adalah?', options: ['Venti', 'Trenta', 'Quaranta', 'Cinquanta'], answer: 1 },
        { q: 'Angka 50 dalam bahasa Italia adalah?', options: ['Sessanta', 'Cinquanta', 'Quaranta', 'Trenta'], answer: 1 },
        { q: 'Angka 100 dalam bahasa Italia adalah?', options: ['Mille', 'Cento', 'Dieci', 'Venti'], answer: 1 },
        { q: 'Angka 8 dalam bahasa Italia adalah?', options: ['Sei', 'Sette', 'Otto', 'Nove'], answer: 2 },
        { q: 'Angka 15 dalam bahasa Italia adalah?', options: ['Quattordici', 'Quindici', 'Sedici', 'Tredici'], answer: 1 },
        { q: 'Angka 40 dalam bahasa Italia adalah?', options: ['Trenta', 'Cinquanta', 'Quaranta', 'Sessanta'], answer: 2 }
      ]
    },
    greetings: {
      title: 'Salam & Perkenalan',
      icon: '👋',
      questions: [
        { q: 'Cara menyapa di pagi hari dalam bahasa Italia adalah?', options: ['Buonanotte', 'Buongiorno', 'Buonasera', 'Ciao'], answer: 1 },
        { q: 'Terima kasih dalam bahasa Italia adalah?', options: ['Scusi', 'Prego', 'Grazie', 'Per favore'], answer: 2 },
        { q: 'Sampai jumpa dalam bahasa Italia adalah?', options: ['Buongiorno', 'Arrivederci', 'Ciao', 'A presto'], answer: 1 },
        { q: 'Maaf dalam bahasa Italia adalah?', options: ['Scusi', 'Grazie', 'Buongiorno', 'Prego'], answer: 0 },
        { q: 'Halo dalam bahasa Italia adalah?', options: ['Buongiorno', 'Buonanotte', 'Ciao', 'Arrivederci'], answer: 2 },
        { q: 'Nama saya... dalam bahasa Italia adalah?', options: ['Vorrei...', 'Come va?', 'Mi chiamo...', 'Parla inglese?'], answer: 2 },
        { q: 'Ya dalam bahasa Italia adalah?', options: ['No', 'Forse', 'Si', 'Molto bene'], answer: 2 },
        { q: 'Tidak dalam bahasa Italia adalah?', options: ['Si', 'No', 'Forse', 'Mai'], answer: 1 },
        { q: 'Tolong dalam bahasa Italia adalah?', options: ['Grazie', 'Scusi', 'Per favore', 'Prego'], answer: 2 },
        { q: 'Sama-sama dalam bahasa Italia adalah?', options: ['Grazie', 'Scusi', 'Buongiorno', 'Prego'], answer: 3 }
      ]
    },
    family: {
      title: 'Keluarga',
      icon: '👨‍👩‍👧‍👦',
      questions: [
        { q: 'Ibu dalam bahasa Italia adalah?', options: ['Il padre', 'La madre', 'La sorella', 'Il fratello'], answer: 1 },
        { q: 'Ayah dalam bahasa Italia adalah?', options: ['La madre', 'Il padre', 'Il figlio', 'La figlia'], answer: 1 },
        { q: 'Saudari dalam bahasa Italia adalah?', options: ['Il fratello', 'La sorella', 'Il figlio', 'La figlia'], answer: 1 },
        { q: 'Anak perempuan dalam bahasa Italia adalah?', options: ['Il figlio', 'La figlia', 'Il bambino', 'La madre'], answer: 1 },
        { q: 'Kakek dalam bahasa Italia adalah?', options: ['Il fratello', 'La nonna', 'Il nonno', 'Il padre'], answer: 2 },
        { q: 'Keluarga dalam bahasa Italia adalah?', options: ['I genitori', 'La famiglia', 'Il fratello', 'La sorella'], answer: 1 },
        { q: 'Suami dalam bahasa Italia adalah?', options: ['La moglie', 'Il marito', 'Il figlio', 'Il fratello'], answer: 1 },
        { q: 'Bayi dalam bahasa Italia adalah?', options: ['La figlia', 'Il figlio', 'Il bambino', 'Il nonno'], answer: 2 },
        { q: 'Sepupu (laki-laki) dalam bahasa Italia adalah?', options: ['La cugina', 'Il cugino', 'Il fratello', 'Il nipote'], answer: 1 },
        { q: 'Orang tua dalam bahasa Italia adalah?', options: ['I genitori', 'I nonni', 'I fratelli', 'La famiglia'], answer: 0 }
      ]
    },
    food: {
      title: 'Makanan & Minuman',
      icon: '🍽️',
      questions: [
        { q: 'Roti dalam bahasa Italia adalah?', options: ['Il riso', 'Il pane', 'Il pollo', 'Il pesce'], answer: 1 },
        { q: 'Air dalam bahasa Italia adalah?', options: ['Il caffe', 'Il vino', "l'acqua", 'Il latte'], answer: 2 },
        { q: 'Nasi dalam bahasa Italia adalah?', options: ['Il pane', 'Il riso', 'Lo zucchero', 'Il sale'], answer: 1 },
        { q: 'Keju dalam bahasa Italia adalah?', options: ['Il formaggio', 'Il pollo', 'La carne', 'Il pesce'], answer: 0 },
        { q: 'Daging dalam bahasa Italia adalah?', options: ['Il pollo', 'Il pesce', 'La carne', 'Il riso'], answer: 2 },
        { q: 'Kopi dalam bahasa Italia adalah?', options: ['Il te', 'Il caffe', 'Il succo', "l'acqua"], answer: 1 },
        { q: 'Apel dalam bahasa Italia adalah?', options: ["la mela", "l'insalata", 'la minestra', 'la torta'], answer: 0 },
        { q: 'Susu dalam bahasa Italia adalah?', options: ['Il caffe', 'Il vino', 'Il latte', 'Il succo'], answer: 2 },
        { q: 'Sup dalam bahasa Italia adalah?', options: ["l'insalata", 'la minestra', 'Il pane', 'Il riso'], answer: 1 },
        { q: 'Cokelat dalam bahasa Italia adalah?', options: ['Lo zucchero', 'la torta', 'il cioccolato', 'Il te'], answer: 2 }
      ]
    },
    places: {
      title: 'Tempat & Lokasi',
      icon: '📍',
      questions: [
        { q: 'Sekolah dalam bahasa Italia adalah?', options: ['la casa', 'la scuola', 'il negozio', 'la strada'], answer: 1 },
        { q: 'Rumah dalam bahasa Italia adalah?', options: ['la scuola', 'la casa', 'la strada', 'il negozio'], answer: 1 },
        { q: 'Toko dalam bahasa Italia adalah?', options: ['la casa', 'il negozio', 'la strada', 'la scuola'], answer: 1 },
        { q: 'Rumah sakit dalam bahasa Italia adalah?', options: ['la farmacia', 'il ristorante', "l'ospedale", 'la biblioteca'], answer: 2 },
        { q: 'Restoran dalam bahasa Italia adalah?', options: ['il negozio', 'il ristorante', 'il parco', 'la stazione'], answer: 1 },
        { q: 'Taman dalam bahasa Italia adalah?', options: ['la strada', 'il parco', 'la banca', 'il cinema'], answer: 1 },
        { q: 'Stasiun dalam bahasa Italia adalah?', options: ['la stazione', "l'albergo", 'la farmacia', 'il ristorante'], answer: 0 },
        { q: 'Apotek dalam bahasa Italia adalah?', options: ["l'ospedale", 'la farmacia', 'il negozio', 'il cinema'], answer: 1 },
        { q: 'Bank dalam bahasa Italia adalah?', options: ['la banca', 'il parco', 'la strada', 'la scuola'], answer: 0 },
        { q: 'Pantai dalam bahasa Italia adalah?', options: ['il parco', 'la spiaggia', 'il negozio', 'il ristorante'], answer: 1 }
      ]
    },
    professions: {
      title: 'Profesi & Pekerjaan',
      icon: '👨‍⚕️',
      questions: [
        { q: 'Dokter dalam bahasa Italia adalah?', options: ['il poliziotto', 'il medico', 'il cuoco', 'l'autista'], answer: 1 },
        { q: 'Guru dalam bahasa Italia adalah?', options: ["l'ingegnere", 'il professore', 'lo studente', "l'artista"], answer: 1 },
        { q: 'Polisi dalam bahasa Italia adalah?', options: ['il medico', 'il poliziotto', 'il venditore', 'il postino'], answer: 1 },
        { q: 'Koki dalam bahasa Italia adalah?', options: ['l'autista', 'il cameriere', 'il cuoco', 'il venditore'], answer: 2 },
        { q: 'Pengacara dalam bahasa Italia adalah?', options: ["l'avvocato", 'il giornalista', 'il medico', 'il professore'], answer: 0 },
        { q: 'Jurnalis dalam bahasa Italia adalah?', options: ['il regista', 'il giornalista', 'il musicista', "l'attore"], answer: 1 },
        { q: 'Tukang pos dalam bahasa Italia adalah?', options: ['il postino', 'l'autista', 'il poliziotto', 'il pompiere'], answer: 0 },
        { q: 'Pemadam kebakaran dalam bahasa Italia adalah?', options: ['il poliziotto', 'il pompiere', 'il medico', 'il soldato'], answer: 1 },
        { q: 'Seniman dalam bahasa Italia adalah?', options: ["l'ingegnere", 'lo studente', "l'artista", 'il contadino'], answer: 2 },
        { q: 'Penerjemah dalam bahasa Italia adalah?', options: ['il traduttore', 'il giornalista', 'il regista', 'il venditore'], answer: 0 }
      ]
    },
    emotions: {
      title: 'Emosi & Perasaan',
      icon: '😊',
      questions: [
        { q: 'Senang dalam bahasa Italia adalah?', options: ['triste', 'felice', 'stanco', 'sorpreso'], answer: 1 },
        { q: 'Sedih dalam bahasa Italia adalah?', options: ['felice', 'triste', 'eccitato', 'calmo'], answer: 1 },
        { q: 'Lelah dalam bahasa Italia adalah?', options: ['arrabbiato', 'spaventato', 'stanco', 'timido'], answer: 2 },
        { q: 'Marah dalam bahasa Italia adalah?', options: ['calmo', 'triste', 'arrabbiato', 'felice'], answer: 2 },
        { q: 'Takut dalam bahasa Italia adalah?', options: ['sorpreso', 'spaventato', 'orgoglioso', 'timido'], answer: 1 },
        { q: 'Terkejut dalam bahasa Italia adalah?', options: ['stanco', 'sorpreso', 'innamorato', 'arrabbiato'], answer: 1 },
        { q: 'Pemalu dalam bahasa Italia adalah?', options: ['timido', 'sicuro', 'orgoglioso', 'preoccupato'], answer: 0 },
        { q: 'Bangga dalam bahasa Italia adalah?', options: ['deluso', 'geloso', 'orgoglioso', 'solo'], answer: 2 },
        { q: 'Kecewa dalam bahasa Italia adalah?', options: ['felice', 'entusiasta', 'deluso', 'nervoso'], answer: 2 },
        { q: 'Khawatir dalam bahasa Italia adalah?', options: ['calmo', 'preoccupato', 'innamorato', 'triste'], answer: 1 }
      ]
    },
    verbConjugations: {
      title: 'Kata Kerja Dasar',
      icon: '🏃',
      questions: [
        { q: '"Pergi" dalam bahasa Italia adalah?', options: ['venire', 'andare', 'uscire', 'arrivare'], answer: 1 },
        { q: '"Memiliki" dalam bahasa Italia adalah?', options: ['essere', 'avere', 'potere', 'volere'], answer: 1 },
        { q: '"Bisa" dalam bahasa Italia adalah?', options: ['volere', 'dovere', 'potere', 'sapere'], answer: 2 },
        { q: '"Mau" dalam bahasa Italia adalah?', options: ['potere', 'volere', 'dovere', 'fare'], answer: 1 },
        { q: '"Harus" dalam bahasa Italia adalah?', options: ['potere', 'volere', 'dovere', 'fare'], answer: 2 },
        { q: '"Melakukan" dalam bahasa Italia adalah?', options: ['dire', 'vedere', 'venire', 'fare'], answer: 3 },
        { q: '"Berkata" dalam bahasa Italia adalah?', options: ['dire', 'vedere', 'venire', 'fare'], answer: 0 },
        { q: '"Melihat" dalam bahasa Italia adalah?', options: ['dire', 'vedere', 'venire', 'prendere'], answer: 1 },
        { q: '"Datang" dalam bahasa Italia adalah?', options: ['uscire', 'arrivare', 'venire', 'entrare'], answer: 2 },
        { q: '"Masuk" dalam bahasa Italia adalah?', options: ['uscire', 'salire', 'scendere', 'entrare'], answer: 3 }
      ]
    },
    bodyParts: {
      title: 'Bagian Tubuh',
      icon: '🦵',
      questions: [
        { q: 'Kepala dalam bahasa Italia adalah?', options: ['il collo', 'la testa', 'il braccio', "l'addome"], answer: 1 },
        { q: 'Mata dalam bahasa Italia adalah?', options: ['le orecchie', 'il naso', 'gli occhi', 'la bocca'], answer: 2 },
        { q: 'Tangan dalam bahasa Italia adalah?', options: ['il piede', 'la mano', 'il braccio', 'la gamba'], answer: 1 },
        { q: 'Kaki dalam bahasa Italia adalah?', options: ['la mano', 'il ginocchio', 'il piede', 'la coscia'], answer: 2 },
        { q: 'Perut dalam bahasa Italia adalah?', options: ['il petto', 'la schiena', 'la vita', "l'addome"], answer: 3 },
        { q: 'Leher dalam bahasa Italia adalah?', options: ['la spalla', 'il collo', 'il gomito', 'il polso'], answer: 1 },
        { q: 'Jari-jari dalam bahasa Italia adalah?', options: ['i denti', 'le dita', 'le labbra', 'i capelli'], answer: 1 },
        { q: 'Hidung dalam bahasa Italia adalah?', options: ['gli occhi', 'la bocca', 'il naso', 'le orecchie'], answer: 2 },
        { q: 'Mulut dalam bahasa Italia adalah?', options: ['il naso', 'la bocca', 'i denti', 'la lingua'], answer: 1 },
        { q: 'Jantung dalam bahasa Italia adalah?', options: ['il cuore', 'la schiena', "l'addome", 'il petto'], answer: 0 }
      ]
    },
    clothing: {
      title: 'Pakaian & Aksesori',
      icon: '👕',
      questions: [
        { q: 'Sepatu dalam bahasa Italia adalah?', options: ['il cappello', 'le scarpe', 'i guanti', 'gli occhiali'], answer: 1 },
        { q: 'Topi dalam bahasa Italia adalah?', options: ['le scarpe', 'la cravatta', 'il cappello', 'i guanti'], answer: 2 },
        { q: 'Gaun/baju dalam bahasa Italia adalah?', options: ['il pantalone', 'la gonna', "l'abito", 'il maglione'], answer: 2 },
        { q: 'Jaket dalam bahasa Italia adalah?', options: ['il cappotto', 'la giacca', 'la maglietta', 'la camicia'], answer: 1 },
        { q: 'Kemeja dalam bahasa Italia adalah?', options: ['la maglietta', 'la camicia', 'la blusa', "l'abito"], answer: 1 },
        { q: 'Rok dalam bahasa Italia adalah?', options: ['il pantalone', 'la gonna', 'i pantaloncini', "l'abito"], answer: 1 },
        { q: 'Sandal dalam bahasa Italia adalah?', options: ['gli stivali', 'le scarpe da ginnastica', 'le sandali', 'i calzini'], answer: 2 },
        { q: 'Dasi dalam bahasa Italia adalah?', options: ['la cintura', 'la berretta', 'la sciarpa', 'la cravatta'], answer: 3 },
        { q: 'Kaos dalam bahasa Italia adalah?', options: ['il maglione', 'la maglietta', 'la blusa', "l'abito"], answer: 1 },
        { q: 'Jam tangan dalam bahasa Italia adalah?', options: ['gli occhiali', "l'anello", "l'orologio", 'il braccialetto'], answer: 2 }
      ]
    },
    house: {
      title: 'Rumah & Ruangan',
      icon: '🏠',
      questions: [
        { q: 'Kamar tidur dalam bahasa Italia adalah?', options: ['la cucina', 'il soggiorno', 'la camera', 'il bagno'], answer: 2 },
        { q: 'Dapur dalam bahasa Italia adalah?', options: ['la camera', 'la cucina', 'il soggiorno', 'il giardino'], answer: 1 },
        { q: 'Ruang tamu dalam bahasa Italia adalah?', options: ['il soggiorno', 'il giardino', 'la camera', 'la cantina'], answer: 0 },
        { q: 'Taman dalam bahasa Italia adalah?', options: ['il balcone', 'la terrazza', 'il giardino', 'il garage'], answer: 2 },
        { q: 'Pintu dalam bahasa Italia adalah?', options: ['la finestra', 'il muro', 'la porta', 'il pavimento'], answer: 2 },
        { q: 'Jendela dalam bahasa Italia adalah?', options: ['la porta', 'la finestra', 'il soffitto', 'il muro'], answer: 1 },
        { q: 'Tangga dalam bahasa Italia adalah?', options: ['il balcone', 'la scala', 'la terrazza', 'la cantina'], answer: 1 },
        { q: 'Garasi dalam bahasa Italia adalah?', options: ['la cantina', 'la soffitta', 'il garage', 'il giardino'], answer: 2 },
        { q: 'Apartemen dalam bahasa Italia adalah?', options: ["l'edificio", 'la casa', "l'appartamento", "l'ufficio"], answer: 2 },
        { q: 'Loteng dalam bahasa Italia adalah?', options: ['la cantina', 'la soffitta', 'la dispensa', 'il bagno'], answer: 1 }
      ]
    },
    foodExtended: {
      title: 'Makanan Italia Lanjutan',
      icon: '🥐',
      questions: [
        { q: 'Pizza dalam bahasa Italia adalah?', options: ['la crêpe', 'la pizza', 'il tiramisù', 'la bruschetta'], answer: 1 },
        { q: 'Tiramisu dalam bahasa Italia adalah?', options: ['il waffle', 'la crêpe', 'il tiramisù', 'la quiche'], answer: 2 },
        { q: 'Bruschetta dalam bahasa Italia adalah?', options: ['il brie', 'la bruschetta', 'il camembert', 'il prosciutto'], answer: 1 },
        { q: 'Pasta carbonara dalam bahasa Italia adalah?', options: ['il pollo arrosto', 'la pasta alla carbonara', 'la pizza margherita', 'la bruschetta'], answer: 1 },
        { q: 'Panna cotta dalam bahasa Italia adalah?', options: ['il risotto', 'la bolognese', 'il panacotta', 'la mozzarella'], answer: 2 },
        { q: 'Gelato dalam bahasa Italia adalah?', options: ['il riso al latte', 'il gelato', 'i biscotti', 'la panna'], answer: 1 },
        { q: 'Mozzarella dalam bahasa Italia adalah?', options: ['la crêpe', 'la mozzarella', 'il panino al cioccolato', 'la brioche'], answer: 1 },
        { q: 'Stroberi dalam bahasa Italia adalah?', options: ['la ciliegia', 'la fragola', 'il lampone', 'il mirtillo'], answer: 1 },
        { q: 'Madu dalam bahasa Italia adalah?', options: ['il burro', 'la marmellata', 'il miele', "l'aceto"], answer: 2 },
        { q: 'Mentega dalam bahasa Italia adalah?', options: ['il burro', 'la farina', "l'olio d'oliva", 'il miele'], answer: 0 }
      ]
    },
    technology: {
      title: 'Teknologi & Komputer',
      icon: '💻',
      questions: [
        { q: 'Komputer dalam bahasa Italia adalah?', options: ['la stampante', 'il computer', 'lo schermo', 'la tastiera'], answer: 1 },
        { q: 'HP/portable dalam bahasa Italia adalah?', options: ['il tablet', 'il telefono', 'il cellulare', 'internet'], answer: 2 },
        { q: 'Printer dalam bahasa Italia adalah?', options: ['il computer', 'la stampante', 'la tastiera', 'il mouse'], answer: 1 },
        { q: 'Internet dalam bahasa Italia adalah?', options: ['il wifi', 'la connessione', 'internet', 'la rete'], answer: 2 },
        { q: 'Layar dalam bahasa Italia adalah?', options: ['la tastiera', 'il mouse', 'lo schermo', 'il computer'], answer: 2 },
        { q: 'Keyboard dalam bahasa Italia adalah?', options: ['il mouse', 'la tastiera', 'lo schermo', 'la stampante'], answer: 1 },
        { q: 'Mouse dalam bahasa Italia adalah?', options: ['la tastiera', 'il mouse', 'lo schermo', 'il telefono'], answer: 1 },
        { q: 'Wifi dalam bahasa Italia adalah?', options: ['internet', 'la connessione', 'la rete', 'il wifi'], answer: 3 },
        { q: 'Aplikasi dalam bahasa Italia adalah?', options: ['il software', "l'applicazione", 'il hardware', 'la memoria'], answer: 1 },
        { q: 'Password dalam bahasa Italia adalah?', options: ["l'indirizzo email", 'la password', 'il browser', 'la pagina web'], answer: 1 }
      ]
    },
    transportation: {
      title: 'Kendaraan & Transportasi',
      icon: '🚗',
      questions: [
        { q: 'Mobil dalam bahasa Italia adalah?', options: ["l'autobus", "l'auto", 'il treno', "l'aereo"], answer: 1 },
        { q: 'Pesawat dalam bahasa Italia adalah?', options: ['la barca', 'il treno', "l'aereo", 'il taxi'], answer: 2 },
        { q: 'Kereta api dalam bahasa Italia adalah?', options: ["l'autobus", 'la metropolitana', 'il treno', 'il tram'], answer: 2 },
        { q: 'Bus dalam bahasa Italia adalah?', options: ["l'autobus", "l'auto", 'il taxi', 'la metropolitana'], answer: 0 },
        { q: 'Sepeda dalam bahasa Italia adalah?', options: ['la moto', 'la bicicletta', 'lo scooter', "l'auto"], answer: 1 },
        { q: 'Kapal dalam bahasa Italia adalah?', options: ["l'aereo", 'la barca', 'il traghetto', 'lo yacht'], answer: 1 },
        { q: 'Motor dalam bahasa Italia adalah?', options: ['la moto', 'la bicicletta', 'lo scooter', 'il camion'], answer: 0 },
        { q: 'Taksi dalam bahasa Italia adalah?', options: ["l'autobus", 'il treno', 'il taxi', 'la metropolitana'], answer: 2 },
        { q: 'Helikopter dalam bahasa Italia adalah?', options: ["l'aereo", 'la barca', "l'elicottero", "l'aerostato"], answer: 2 },
        { q: 'Kereta bawah tanah dalam bahasa Italia adalah?', options: ['il treno', 'il tram', 'la metropolitana', "l'autobus"], answer: 2 }
      ]
    },
    travel: {
      title: 'Perjalanan & Liburan',
      icon: '✈️',
      questions: [
        { q: 'Hotel dalam bahasa Italia adalah?', options: ["l'edificio", "l'appartamento", "l'albergo", 'il ristorante'], answer: 2 },
        { q: 'Bandara dalam bahasa Italia adalah?', options: ['la stazione', "l'aeroporto", 'il porto', 'la fermata'], answer: 1 },
        { q: 'Paspor dalam bahasa Italia adalah?', options: ['il visto', 'il passaporto', 'la carta d'identità', 'il biglietto'], answer: 1 },
        { q: 'Tiket dalam bahasa Italia adalah?', options: ['il passaporto', 'il biglietto', 'il visto', 'la prenotazione'], answer: 1 },
        { z: 'Koper dalam bahasa Italia adalah?', options: ['la borsa', 'la valigia', 'lo zaino', 'il borsone'], answer: 1 },
        { q: 'Pemandu wisata dalam bahasa Italia adalah?', options: ['la guida', 'l'autista', 'il pilota', 'il viaggiatore'], answer: 0 },
        { q: 'Wisatawan dalam bahasa Italia adalah?', options: ['il turista', 'la guida', 'il viaggiatore', "l'esploratore"], answer: 2 },
        { q: 'Pemandangan dalam bahasa Italia adalah?', options: ['la vista', 'il paesaggio', 'il panorama', "l'orizzonte"], answer: 1 },
        { q: 'Pantai dalam bahasa Italia adalah?', options: ['la montagna', 'la spiaggia', 'la foresta', 'il deserto'], answer: 1 },
        { q: 'Museum dalam bahasa Italia adalah?', options: ['il teatro', 'il cinema', 'il museo', 'la mostra'], answer: 2 }
      ]
    }
  },
  achievements: [
    { id: 'first_quiz', title: 'Pertama Kali!', description: 'Selesaikan kuis pertama Anda', icon: '🎯', requirement: 'Selesaikan 1 kuis' },
    { id: 'quiz_5', title: 'Pemula', description: 'Selesaikan 5 kuis', icon: '📚', requirement: 'Selesaikan 5 kuis' },
    { id: 'quiz_10', title: 'Siswa Rajin', description: 'Selesaikan 10 kuis', icon: '🏆', requirement: 'Selesaikan 10 kuis' },
    { id: 'quiz_25', title: 'Penggemar Kuis', description: 'Selesaikan 25 kuis', icon: '⭐', requirement: 'Selesaikan 25 kuis' },
    { id: 'quiz_50', title: 'Master Kuis', description: 'Selesaikan 50 kuis', icon: '👑', requirement: 'Selesaikan 50 kuis' },
    { id: 'quiz_100', title: 'Legenda Kuis', description: 'Selesaikan 100 kuis', icon: '🌟', requirement: 'Selesaikan 100 kuis' },
    { id: 'flashcard_10', title: 'Penjelajah Kata', description: 'Lihat 10 kartu flashcard', icon: '🃏', requirement: 'Lihat 10 kartu' },
    { id: 'flashcard_50', title: 'Kolektor Kata', description: 'Lihat 50 kartu flashcard', icon: '📦', requirement: 'Lihat 50 kartu' },
    { id: 'flashcard_100', title: 'Ahli Kosakata', description: 'Lihat 100 kartu flashcard', icon: '🎓', requirement: 'Lihat 100 kartu' },
    { id: 'flashcard_500', title: 'Penguasa Kosakata', description: 'Lihat 500 kartu flashcard', icon: '🧠', requirement: 'Lihat 500 kartu' },
    { id: 'streak_3', title: '3 Hari Berturut', description: 'Belajar 3 hari berturut-turut', icon: '🔥', requirement: '3 hari streak' },
    { id: 'streak_7', title: 'Seminggu Penuh', description: 'Belajar 7 hari berturut-turut', icon: '💪', requirement: '7 hari streak' },
    { id: 'streak_30', title: 'Sebulan Penuh', description: 'Belajar 30 hari berturut-turut', icon: '🏆', requirement: '30 hari streak' },
    { id: 'perfect_score', title: 'Sempurna!', description: 'Dapatkan skor 100% di kuis', icon: '💯', requirement: 'Skor 100% di kuis' },
    { id: 'perfect_5', title: 'Sangat Sempurna', description: 'Dapatkan 5 skor sempurna', icon: '🎯', requirement: '5 skor 100%' },
    { id: 'perfect_10', title: 'Master Sempurna', description: 'Dapatkan 10 skor sempurna', icon: '🏅', requirement: '10 skor 100%' },
    { id: 'xp_100', title: '100 XP', description: 'Kumpulkan 100 XP', icon: '⭐', requirement: '100 XP' },
    { id: 'xp_500', title: '500 XP', description: 'Kumpulkan 500 XP', icon: '🌟', requirement: '500 XP' },
    { id: 'xp_1000', title: '1000 XP', description: 'Kumpulkan 1000 XP', icon: '👑', requirement: '1000 XP' },
    { id: 'xp_5000', title: '5000 XP', description: 'Kumpulkan 5000 XP', icon: '🏆', requirement: '5000 XP' },
    { id: 'word_explorer', title: 'Penjelajah Kata', description: 'Pelajari 100 kata unik', icon: '🔤', requirement: '100 kata unik' },
    { id: 'vocabulary_champion', title: 'Juara Kosakata', description: 'Pelajari 500 kata unik', icon: '📚', requirement: '500 kata unik' },
    { id: 'fashionista', title: 'Fashionista', description: 'Kuasai kategori pakaian', icon: '👗', requirement: 'Kuis pakaian 100%' },
    { id: 'chef_de_cuisine', title: 'Chef de Cuisine', description: 'Kuasai kategori makanan', icon: '👨‍🍳', requirement: 'Kuis makanan 100%' },
    { id: 'tech_savvy', title: 'Tech Savvy', description: 'Kuasai kategori teknologi', icon: '💻', requirement: 'Kuis teknologi 100%' },
    { id: 'body_master', title: 'Body Master', description: 'Kuasai kategori bagian tubuh', icon: '🦵', requirement: 'Kuis tubuh 100%' },
    { id: 'house_expert', title: 'House Expert', description: 'Kuasai kategori rumah', icon: '🏠', requirement: 'Kuis rumah 100%' },
    { id: 'travel_guru', title: 'Travel Guru', description: 'Kuasai kategori perjalanan', icon: '✈️', requirement: 'Kuis perjalanan 100%' },
    { id: 'emotion_reader', title: 'Emotion Reader', description: 'Kuasai kategori emosi', icon: '😊', requirement: 'Kuis emosi 100%' },
    { id: 'verb_master', title: 'Verb Master', description: 'Kuasai kategori kata kerja', icon: '🏃', requirement: 'Kuis kata kerja 100%' },
    { id: 'transport_king', title: 'Transport King', description: 'Kuasai kategori transportasi', icon: '🚗', requirement: 'Kuis transportasi 100%' },
    { id: 'animal_lover', title: 'Animal Lover', description: 'Pelajari semua nama hewan', icon: '🐾', requirement: 'Semua hewan' },
    { id: 'color_master', title: 'Color Master', description: 'Kuasai kategori warna', icon: '🎨', requirement: 'Kuis warna 100%' },
    { id: 'number_wizard', title: 'Number Wizard', description: 'Kuasai kategori angka', icon: '🔢', requirement: 'Kuis angka 100%' },
    { id: 'full_spectrum', title: 'Full Spectrum', description: 'Selesaikan semua kategori kuis', icon: '🌈', requirement: 'Semua 15 kategori' }
  ]
};
